#|
#|  Copyright The Telepact Authors
#|
#|  Licensed under the Apache License, Version 2.0 (the "License");
#|  you may not use this file except in compliance with the License.
#|  You may obtain a copy of the License at
#|
#|  https://www.apache.org/licenses/LICENSE-2.0
#|
#|  Unless required by applicable law or agreed to in writing, software
#|  distributed under the License is distributed on an "AS IS" BASIS,
#|  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#|  See the License for the specific language governing permissions and
#|  limitations under the License.
#|

from typing import Any

from cases import get_values
from cases import additional_union_cases, additional_fn_cases, additional_integer_cases, additional_number_cases, additional_p2Union_cases, additional_p2Str_cases, additional_struct_cases


def generate_mock_cases(given_field: str, the_type, correct_values, additional_incorrect_values = []):
    for field, _, incorrect_values, base_path in get_values(given_field, the_type, correct_values, additional_incorrect_values):
        for incorrect_value, errors in incorrect_values:
            cases = [{'path': ['fn.createStub_', 'stub', 'fn.test', 'value!'] + base_path + path, 'reason': reason} for reason, path in errors if 'RequiredObjectKeyMissing' not in reason]
            if not cases:
                continue

            yield [[{}, {'fn.createStub_': {'stub': {'fn.test': {'value!': {field: incorrect_value}}, '->': {'Ok_': {}}}}}], [{}, {'ErrorInvalidRequestBody_': {'cases': cases}}]]

        for incorrect_value, errors in incorrect_values:
            cases = [{'path': ['fn.createStub_', 'stub', '->', 'Ok_', 'value!'] + base_path + path, 'reason': reason} for reason, path in errors if 'RequiredObjectKeyMissing' not in reason]
            if not cases:
                continue
            yield [[{}, {'fn.createStub_': {'stub': {'fn.test': {}, '->': {'Ok_': {'value!': {field: incorrect_value}}}}}}], [{}, {'ErrorInvalidRequestBody_': {'cases': cases}}]]



invalid_cases = {
    'boolean': [v for v in generate_mock_cases('bool!', bool, [False, True])],
    'integer': [v for v in generate_mock_cases('int!', int, [0, -1, 1, 9223372036854775807, -9223372036854775808], additional_integer_cases)],
    'number': [v for v in generate_mock_cases('num!', float, [0, -1, 1, -1.7976931348623157e+308, -2.2250738585072014e-308, 2.2250738585072014e-308, 1.7976931348623157e+308, -0.1, 0.1], additional_number_cases)],
    'string': [v for v in generate_mock_cases('str!', str, ['', 'abc'])],
    'array': [v for v in generate_mock_cases('arr!', list, [[], [False, 0, 0.1, '']])],
    'object': [v for v in generate_mock_cases('obj!', dict, [{}, {'a': False, 'b': 0, 'c': 0.1, 'd': ''}])],
    'any': [v for v in generate_mock_cases('any!', Any, [False, 0, 0.1, '', [], {}])],
    'struct': [v for v in generate_mock_cases('struct!', dict, [{'required': False}, {'optional!': False, 'required': False}], additional_struct_cases)],
    'union': [v for v in generate_mock_cases('union!', dict, [{'One': {}}, {'Two':{'required': False}}, {'Two':{'optional!': False, 'required': False}}], additional_union_cases)],
    'fn': [v for v in generate_mock_cases('fn!', dict, [{'fn.example': {'required': False}}, {'fn.example': {'optional!': False, 'required': False}}], additional_fn_cases)],
    'stub': [
        [[{}, {'fn.createStub_': {'stub': False}}], [{}, {'ErrorInvalidRequestBody_': {'cases': [{'path': ['fn.createStub_', 'stub'], 'reason': {'TypeUnexpected': {'actual': {'Boolean': {}}, 'expected': {'Object': {}}}}}]}}]],
        [[{}, {'fn.createStub_': {'stub': 0}}], [{}, {'ErrorInvalidRequestBody_': {'cases': [{'path': ['fn.createStub_', 'stub'], 'reason': {'TypeUnexpected': {'actual': {'Number': {}}, 'expected': {'Object': {}}}}}]}}]],
        [[{}, {'fn.createStub_': {'stub': ''}}], [{}, {'ErrorInvalidRequestBody_': {'cases': [{'path': ['fn.createStub_', 'stub'], 'reason': {'TypeUnexpected': {'actual': {'String': {}}, 'expected': {'Object': {}}}}}]}}]],
        [[{}, {'fn.createStub_': {'stub': []}}], [{}, {'ErrorInvalidRequestBody_': {'cases': [{'path': ['fn.createStub_', 'stub'], 'reason': {'TypeUnexpected': {'actual': {'Array': {}}, 'expected': {'Object': {}}}}}]}}]],
        [[{}, {'fn.createStub_': {'stub': {}}}], [{}, {'ErrorInvalidRequestBody_': {'cases': [{'path': ['fn.createStub_', 'stub'], 'reason': {'ObjectKeyRegexMatchCountUnexpected': {'regex': '^fn\\..*$', 'actual': 0, 'expected': 1, 'keys': []}}}]}}]],
        [[{}, {'fn.createStub_': {'stub': {'fn.test': {}}}}], [{}, {'ErrorInvalidRequestBody_': {'cases': [{'path': ['fn.createStub_', 'stub'], 'reason': {'RequiredObjectKeyMissing': {'key': '->'}}}]}}]],
        [[{}, {'fn.createStub_': {'stub': {'fn.test': {}, '->': {}}}}], [{}, {'ErrorInvalidRequestBody_': {'cases': [{'path': ['fn.createStub_', 'stub', '->'], 'reason': {'ObjectSizeUnexpected': {'actual': 0, 'expected': 1}}}]}}]],
        [[{}, {'fn.createStub_': {'stub': {'fn.testAnother': {}, 'fn.test': {}, '->': {'Ok_': {}}}}}], [{}, {'ErrorInvalidRequestBody_': {'cases': [{'path': ['fn.createStub_', 'stub'], 'reason': {'ObjectKeyRegexMatchCountUnexpected': {'regex': '^fn\\..*$', 'actual': 2, 'expected': 1, 'keys': ['->', 'fn.test', 'fn.testAnother']}}}]}}]],
        [[{}, {'fn.createStub_': {'stub': {'wrong': True, 'fn.test': {}, '->': {'Ok_': {}}}}}], [{}, {'ErrorInvalidRequestBody_': {'cases': [{'path': ['fn.createStub_', 'stub', 'wrong'], 'reason': {'ObjectKeyDisallowed': {}}}]}}]],
    ],
}

cases = {
    'emptyPartialMatchStub': [
        [[{}, {'fn.clearStubs_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.clearCalls_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.test': {}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.createStub_': {'stub': {'fn.test': {}, '->': {'Ok_': {}}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.test': {}}], [{}, {'Ok_': {}}]],
    ],
    'partialMatchStub': [
        [[{}, {'fn.clearStubs_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.clearCalls_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1, 'str!': 'a'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.createStub_': {'stub': {'fn.test': {'value!': {'int!': 1}}, '->': {'Ok_': {'value!': {'bool!': True}}}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.test': {}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 0}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1}}}], [{}, {'Ok_': {'value!': {'bool!': True}}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1, 'str!': 'a'}}}], [{}, {'Ok_': {'value!': {'bool!': True}}}]],
    ],
    'multiplePartialMatchStub': [
        [[{}, {'fn.clearStubs_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.clearCalls_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1, 'str!': 'a'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 0, 'str!': 'a'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1, 'str!': 'b'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'bool!': False, 'int!': 1, 'str!': 'a'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.createStub_': {'stub': {'fn.test': {'value!': {'int!': 1}}, '->': {'Ok_': {'value!': {'bool!': True}}}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.createStub_': {'stub': {'fn.test': {'value!': {'str!': 'a'}}, '->': {'Ok_': {'value!': {'bool!': False}}}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.createStub_': {'stub': {'fn.example': {}, '->': {'Ok_': {}}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.test': {}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 0}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1}}}], [{}, {'Ok_': {'value!': {'bool!': True}}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1, 'str!': 'a'}}}], [{}, {'Ok_': {'value!': {'bool!': False}}}]],
        [[{}, {'fn.test': {'value!': {'int!': 0, 'str!': 'a'}}}], [{}, {'Ok_': {'value!': {'bool!': False}}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1, 'str!': 'b'}}}], [{}, {'Ok_': {'value!': {'bool!': True}}}]],
        [[{}, {'fn.test': {'value!': {'bool!': False, 'int!': 1, 'str!': 'a'}}}], [{}, {'Ok_': {'value!': {'bool!': False}}}]],
    ],
    'multiplePartialMatchStubCount': [
        [[{}, {'fn.clearStubs_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.clearCalls_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1, 'str!': 'a'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 0, 'str!': 'a'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1, 'str!': 'b'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'bool!': False, 'int!': 1, 'str!': 'a'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.createStub_': {'count!': 2, 'stub': {'fn.test': {'value!': {'int!': 1}}, '->': {'Ok_': {'value!': {'bool!': True}}}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.createStub_': {'count!': 1, 'stub': {'fn.test': {'value!': {'str!': 'a'}}, '->': {'Ok_': {'value!': {'bool!': False}}}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.createStub_': {'stub': {'fn.example': {}, '->': {'Ok_': {}}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.test': {}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 0}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1}}}], [{}, {'Ok_': {'value!': {'bool!': True}}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1, 'str!': 'a'}}}], [{}, {'Ok_': {'value!': {'bool!': False}}}]],
        [[{}, {'fn.test': {'value!': {'int!': 0, 'str!': 'a'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1, 'str!': 'b'}}}], [{}, {'Ok_': {'value!': {'bool!': True}}}]],
        [[{}, {'fn.test': {'value!': {'bool!': False, 'int!': 1, 'str!': 'a'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
    ],    
    'multipleNestedPartialMatchStub': [
        [[{}, {'fn.clearStubs_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.clearCalls_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1, 'str!': 'a'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 0, 'str!': 'a'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1, 'str!': 'b'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'bool!': False, 'int!': 1, 'str!': 'a'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.createStub_': {'stub': {'fn.test': {'value!': {'struct!': {'optional!': True}}}, '->': {'Ok_': {'value!': {'bool!': True}}}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.createStub_': {'stub': {'fn.test': {'value!': {'struct!': {'required': True}}}, '->': {'Ok_': {'value!': {'bool!': False}}}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.createStub_': {'stub': {'fn.example': {}, '->': {'Ok_': {}}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.test': {}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'struct!': {'required': False}}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'struct!': {'optional!': False, 'required': False}}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'struct!': {'optional!': True, 'required': True}}}}], [{}, {'Ok_': {'value!': {'bool!': False}}}]],
        [[{}, {'fn.test': {'value!': {'struct!': {'optional!': True, 'required': False}}}}], [{}, {'Ok_': {'value!': {'bool!': True}}}]],
        [[{}, {'fn.test': {'value!': {'struct!': {'required': True}}}}], [{}, {'Ok_': {'value!': {'bool!': False}}}]],
        [[{}, {'fn.test': {'value!': {'struct!': {'optional!': False, 'required': True}}}}], [{}, {'Ok_': {'value!': {'bool!': False}}}]],
        [[{}, {'fn.test': {'value!': {'struct!': {'optional!': True, 'required': False}, 'str!': 'b'}}}], [{}, {'Ok_': {'value!': {'bool!': True}}}]],
    ],
    'multipleNestedPartialMatchStubCount': [
        [[{}, {'fn.clearStubs_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.clearCalls_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1, 'str!': 'a'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 0, 'str!': 'a'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1, 'str!': 'b'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'bool!': False, 'int!': 1, 'str!': 'a'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.createStub_': {'count!': 1, 'stub': {'fn.test': {'value!': {'struct!': {'optional!': True}}}, '->': {'Ok_': {'value!': {'bool!': True}}}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.createStub_': {'count!': 2, 'stub': {'fn.test': {'value!': {'struct!': {'required': True}}}, '->': {'Ok_': {'value!': {'bool!': False}}}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.createStub_': {'stub': {'fn.example': {}, '->': {'Ok_': {}}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.test': {}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'struct!': {'required': False}}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'struct!': {'optional!': False, 'required': False}}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'struct!': {'optional!': True, 'required': True}}}}], [{}, {'Ok_': {'value!': {'bool!': False}}}]],
        [[{}, {'fn.test': {'value!': {'struct!': {'optional!': True, 'required': False}}}}], [{}, {'Ok_': {'value!': {'bool!': True}}}]],
        [[{}, {'fn.test': {'value!': {'struct!': {'required': True}}}}], [{}, {'Ok_': {'value!': {'bool!': False}}}]],
        [[{}, {'fn.test': {'value!': {'struct!': {'optional!': False, 'required': True}}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'struct!': {'optional!': True, 'required': False}, 'str!': 'b'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
    ],    
    'multipleReallyNestedPartialMatchStub': [
        [[{}, {'fn.clearStubs_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.clearCalls_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1, 'str!': 'a'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 0, 'str!': 'a'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1, 'str!': 'b'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'bool!': False, 'int!': 1, 'str!': 'a'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.createStub_': {'stub': {'fn.test': {'value!': {'arrStruct!': [{'optional!': True}]}}, '->': {'Ok_': {'value!': {'bool!': True}}}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.createStub_': {'stub': {'fn.test': {'value!': {'arrStruct!': [{'required': True}]}}, '->': {'Ok_': {'value!': {'bool!': False}}}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.createStub_': {'stub': {'fn.example': {}, '->': {'Ok_': {}}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.test': {}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'arrStruct!': [{'required': False}, {'optional!': False, 'required': False}]}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'arrStruct!': [{'required': False}, {'optional!': True, 'required': True}]}}}], [{}, {'Ok_': {'value!': {'bool!': False}}}]],
        [[{}, {'fn.test': {'value!': {'arrStruct!': [{'required': False}, {'optional!': True, 'required': False}]}}}], [{}, {'Ok_': {'value!': {'bool!': True}}}]],
        [[{}, {'fn.test': {'value!': {'arrStruct!': [{'required': False}, {'optional!': False, 'required': True}]}}}], [{}, {'Ok_': {'value!': {'bool!': False}}}]],
        [[{}, {'fn.test': {'value!': {'arrStruct!': [{'required': False}, {'optional!': True, 'required': False}], 'str!': 'b'}}}], [{}, {'Ok_': {'value!': {'bool!': True}}}]],
    ],
    'multipleReallyNestedPartialMatchStubCount': [
        [[{}, {'fn.clearStubs_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.clearCalls_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1, 'str!': 'a'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 0, 'str!': 'a'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1, 'str!': 'b'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'bool!': False, 'int!': 1, 'str!': 'a'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.createStub_': {'count!': 1, 'stub': {'fn.test': {'value!': {'arrStruct!': [{'optional!': True}]}}, '->': {'Ok_': {'value!': {'bool!': True}}}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.createStub_': {'count!': 1, 'stub': {'fn.test': {'value!': {'arrStruct!': [{'required': True}]}}, '->': {'Ok_': {'value!': {'bool!': False}}}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.createStub_': {'stub': {'fn.example': {}, '->': {'Ok_': {}}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.test': {}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'arrStruct!': [{'required': False}, {'optional!': False, 'required': False}]}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'arrStruct!': [{'required': False}, {'optional!': True, 'required': True}]}}}], [{}, {'Ok_': {'value!': {'bool!': False}}}]],
        [[{}, {'fn.test': {'value!': {'arrStruct!': [{'required': False}, {'optional!': True, 'required': False}]}}}], [{}, {'Ok_': {'value!': {'bool!': True}}}]],
        [[{}, {'fn.test': {'value!': {'arrStruct!': [{'required': False}, {'optional!': False, 'required': True}]}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'arrStruct!': [{'required': False}, {'optional!': True, 'required': False}], 'str!': 'b'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
    ],    
    'strictMatchStub': [
        [[{}, {'fn.clearStubs_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.clearCalls_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.createStub_': {'stub': {'fn.test': {'value!': {'int!': 1}}, '->': {'Ok_': {'value!': {'bool!': True}}}}, 'strictMatch!': True}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.test': {}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 0}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1}}}], [{}, {'Ok_': {'value!': {'bool!': True}}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1, 'str!': 'a'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
    ],
    'multipleStrictMatchStub': [
        [[{}, {'fn.clearStubs_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.clearCalls_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'str!': 'a'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.createStub_': {'stub': {'fn.test': {'value!': {'int!': 1}}, '->': {'Ok_': {'value!': {'bool!': True}}}}, 'strictMatch!': True}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.createStub_': {'stub': {'fn.test': {'value!': {'str!': 'a'}}, '->': {'Ok_': {'value!': {'bool!': False}}}}, 'strictMatch!': True}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.test': {}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 0}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1}}}], [{}, {'Ok_': {'value!': {'bool!': True}}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1, 'str!': 'a'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'str!': 'a'}}}], [{}, {'Ok_': {'value!': {'bool!': False}}}]],
        [[{}, {'fn.test': {'value!': {'int!': 0, 'str!': 'a'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1, 'str!': 'b'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'bool!': False, 'int!': 1, 'str!': 'a'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
    ],
    'multipleStrictMatchStubCount': [
        [[{}, {'fn.clearStubs_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.clearCalls_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'str!': 'a'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.createStub_': {'count!': 1, 'stub': {'fn.test': {'value!': {'int!': 1}}, '->': {'Ok_': {'value!': {'bool!': True}}}}, 'strictMatch!': True}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.createStub_': {'count!': 1, 'stub': {'fn.test': {'value!': {'str!': 'a'}}, '->': {'Ok_': {'value!': {'bool!': False}}}}, 'strictMatch!': True}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.test': {}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 0}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1}}}], [{}, {'Ok_': {'value!': {'bool!': True}}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1, 'str!': 'a'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'str!': 'a'}}}], [{}, {'Ok_': {'value!': {'bool!': False}}}]],
        [[{}, {'fn.test': {'value!': {'str!': 'a'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 0, 'str!': 'a'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1, 'str!': 'b'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'bool!': False, 'int!': 1, 'str!': 'a'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
    ],    
    'mixedPartialStrictMatchStub': [
        [[{}, {'fn.clearStubs_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.clearCalls_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1, 'str!': 'a'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1, 'str!': 'b'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'bool!': False, 'int!': 1, 'str!': 'a'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.createStub_': {'stub': {'fn.test': {'value!': {'int!': 1}}, '->': {'Ok_': {'value!': {'bool!': True}}}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.createStub_': {'stub': {'fn.test': {'value!': {'int!': 1, 'str!': 'a'}}, '->': {'Ok_': {'value!': {'bool!': False}}}}, 'strictMatch!': True}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.test': {}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 0}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1}}}], [{}, {'Ok_': {'value!': {'bool!': True}}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1, 'str!': 'a'}}}], [{}, {'Ok_': {'value!': {'bool!': False}}}]],
        [[{}, {'fn.test': {'value!': {'int!': 0, 'str!': 'a'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1, 'str!': 'b'}}}], [{}, {'Ok_': {'value!': {'bool!': True}}}]],
        [[{}, {'fn.test': {'value!': {'bool!': False, 'int!': 1, 'str!': 'a'}}}], [{}, {'Ok_': {'value!': {'bool!': True}}}]],
    ],
    'mixedStrictPartialMatchStub': [
        [[{}, {'fn.clearStubs_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.clearCalls_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1, 'str!': 'a'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1, 'str!': 'b'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'bool!': False, 'int!': 1, 'str!': 'a'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.createStub_': {'stub': {'fn.test': {'value!': {'int!': 1, 'str!': 'a'}}, '->': {'Ok_': {'value!': {'bool!': False}}}}, 'strictMatch!': True}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.createStub_': {'stub': {'fn.test': {'value!': {'int!': 1}}, '->': {'Ok_': {'value!': {'bool!': True}}}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.test': {}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 0}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1}}}], [{}, {'Ok_': {'value!': {'bool!': True}}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1, 'str!': 'a'}}}], [{}, {'Ok_': {'value!': {'bool!': True}}}]],
        [[{}, {'fn.test': {'value!': {'int!': 0, 'str!': 'a'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1, 'str!': 'b'}}}], [{}, {'Ok_': {'value!': {'bool!': True}}}]],
        [[{}, {'fn.test': {'value!': {'bool!': False, 'int!': 1, 'str!': 'a'}}}], [{}, {'Ok_': {'value!': {'bool!': True}}}]],
    ],
    'clearStubs': [
        [[{}, {'fn.clearStubs_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.clearCalls_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.test': {}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.createStub_': {'stub': {'fn.test': {}, '->': {'Ok_': {}}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.test': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.clearStubs_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.test': {}}], [{}, {'ErrorNoMatchingStub_': {}}]],
    ],
    'generation': [
        [[{}, {'fn.setRandomSeed_': {'seed': 0}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.clearStubs_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.clearCalls_': {}}], [{}, {'Ok_': {}}]],
        [[{'@gen_': True}, {'fn.test': {}}], [{}, {'Ok_': {'value!': {'any!': True, 'arrBytes!': [], 'arrInt!': [1326349322], 'arrNullAny!': [772162768, None], 'arrNullBool!': [None], 'arrNullBytes!': ['IFcS0w=='], 'arrNullUnion!': [None], 'arrNum!': [0.2379846830097887], 'arrStr!': ['B8oYiw'], 'int!': 378133653, 'nullAny!': None, 'nullArr!': [False], 'nullBool!': False, 'nullBytes!': 'Mo6GPA==', 'nullObj!': {'MtBOhw': 1646991495}, 'nullStr!': 'B54/mA', 'nullStruct!': {'required': False}, 'nullUnion!': None, 'num!': 0.9951405059523604, 'objAny!': {'HyB1gg': 2038109007}, 'objBool!': {'HNHEPg': True}, 'objBytes!': {'KXpvWQ': 'Aq7NtA=='}, 'objInt!': {'PuKmug': 321788014, 'Y299zQ': 1251252674}, 'objNullAny!': {}, 'objNullBytes!': {'QYFAxA': None}, 'objNullFn!': {'CkST/g': {'fn.example': {'required': True}}}, 'objNullStr!': {'HwbrFw': 'SYjTAw', 'S5jNWQ': 'KGGV9w'}, 'objNullStruct!': {'WbEG3A': None}, 'objNullUnion!': {'IX7gOg': None, 'Hev3vQ': {'Two': {'optional!': False, 'required': True}}}, 'objNum!': {}, 'objStr!': {'MhZGwg': 'b4FVCg', 'avyIYA': 'MIul0Q'}, 'str!': 'cCFd9g'}}}]],
        [[{'@gen_': True}, {'fn.test': {}}], [{}, {'Ok_': {}}]],
        [[{'@gen_': True}, {'fn.test': {}}], [{}, {'Ok_': {}}]],
        [[{'@gen_': True}, {'fn.test': {}}], [{}, {'Ok_': {'value!': {'arr!': [False, True], 'arrAny!': [], 'arrArr!': [[], [90193426]], 'arrBool!': [], 'arrBytes!': [], 'arrInt!': [1395236724, 1193708583], 'arrNullAny!': ['LUbqGw', 1103378584], 'arrNullBool!': [None], 'arrNullBytes!': ['d+iQlw==', None], 'arrNullInt!': [393934695], 'arrNullNum!': [], 'arrNullObj!': [None, None], 'arrNum!': [], 'arrObj!': [], 'arrStruct!': [], 'arrUnion!': [{'One': {}}], 'fn!': {'fn.example': {'optional!': False, 'required': True}}, 'int!': 2040932635, 'nullAny!': True, 'nullArr!': None, 'nullInt!': 443159599, 'nullObj!': None, 'nullUnion!': {'Two': {'required': False}}, 'num!': 0.7561546036769424, 'objAny!': {'bGTuZA': 'dE7sdQ'}, 'objArr!': {'XYNwog': ['HskKDA', 'EwJctQ'], 'OZvhng': []}, 'objBool!': {'NkxP5A': True, 'FQNkyQ': True}, 'objBytes!': {'bgmaVw': 'flIhBA=='}, 'objFn!': {'WawLvg': {'fn.example': {'required': True}}, 'UeZmpw': {'fn.example': {'optional!': False, 'required': False}}}, 'objNullBool!': {'asXKjg': False}, 'objNullFn!': {}, 'objNullInt!': {'bPw3Cg': 1749771522, 'JFFJ7g': None}, 'objNullObj!': {'ZJr/Qw': None, 'OhA8nQ': None}, 'objNullStr!': {'IrLrtQ': None}, 'objNullUnion!': {'apSIVA': None, 'K72DXg': {'Two': {'optional!': True, 'required': False}}}, 'objNum!': {'FrtJcw': 0.3102339777677478}, 'objObj!': {'JauaEw': {'Lx6MeQ': 1835290038, 'OhyoHw': False}}}}}]],
        [[{'@gen_': True}, {'fn.test': {}}], [{}, {'Ok_': {}}]],
        [[{'@gen_': True}, {'fn.test': {}}], [{}, {'Ok_': {}}]],
        [[{'@gen_': True}, {'fn.test': {}}], [{}, {'Ok_': {'value!': {'arr!': [1409113263], 'arrAny!': [], 'arrArr!': [[False], [False, 194162462]], 'arrBool!': [True], 'arrInt!': [1659185989, 2089482048], 'arrNullAny!': [None, None], 'arrNullBytes!': [], 'arrNullFn!': [None, {'fn.example': {'optional!': False, 'required': False}}], 'arrNullInt!': [953201238, 1238691126], 'arrNullNum!': [], 'arrNullObj!': [], 'arrNullStr!': [None, 'TS/zhw'], 'arrNullUnion!': [], 'arrNum!': [0.7232969513737116], 'arrObj!': [{'Pyj1Fg': 106189909}, {}], 'bool!': False, 'fn!': {'fn.example': {'optional!': True, 'required': False}}, 'nullAny!': None, 'nullArr!': [], 'nullBool!': False, 'nullBytes!': 'DZFI6w==', 'nullFn!': {'fn.example': {'optional!': False, 'required': False}}, 'nullInt!': 1501133872, 'nullStr!': 'dNXNwQ', 'nullStruct!': {'optional2!': 959600189, 'required': False}, 'obj!': {}, 'objAny!': {}, 'objArr!': {}, 'objNullAny!': {'OP+5Eg': None}, 'objNullBytes!': {'QvKNRA': 'HPeXFA==', 'd7+Hpg': 'TQpw9A=='}, 'objNullObj!': {}, 'objNullStr!': {}, 'objNum!': {'PNpjDA': 0.29390355958319436}, 'objStr!': {}, 'objStruct!': {'TAiRHA': {'required': True}, 'MOaX9Q': {'optional2!': 281093312, 'required': False}}, 'objUnion!': {'CxLClQ': {'Two': {'required': False}}, 'YEq1yQ': {'Two': {'required': True}}}, 'str!': 'Pzcz+A'}}}]],
        [[{'@gen_': True}, {'fn.test': {}}], [{}, {'Ok_': {'value!': {'any!': 1884013111, 'arr!': [False], 'arrAny!': [], 'arrFn!': [], 'arrInt!': [2083348324], 'arrNullBytes!': [], 'arrNullFn!': [None], 'arrNullInt!': [], 'arrNullObj!': [{'AMbRzA': 'e+viCg'}], 'arrNullStr!': [None], 'arrNullStruct!': [{'optional2!': 324119899, 'required': False}], 'arrNum!': [], 'arrStruct!': [{'required': True}, {'optional2!': 93179805, 'required': False}], 'arrUnion!': [{'Two': {'optional!': True, 'required': False}}, {'Two': {'required': False}}], 'fn!': {'fn.example': {'required': False}}, 'nullAny!': None, 'nullArr!': [507679323], 'nullBool!': True, 'nullBytes!': None, 'nullFn!': {'fn.example': {'required': True}}, 'nullInt!': 218347264, 'nullStr!': None, 'nullStruct!': None, 'num!': 0.5941600881489739, 'obj!': {'FSxo7w': True, 'L7rrpg': False}, 'objAny!': {}, 'objArr!': {'d/LIKw': [True, 1702171516]}, 'objFn!': {'JRL8ag': {'fn.example': {'optional!': False, 'required': False}}, 'BWuWBw': {'fn.example': {'optional!': False, 'required': True}}}, 'objNullBool!': {'HETEDw': False, 'JGboDg': None}, 'objNullObj!': {'LcLwqg': {'LEmtMQ': 'cQo4vA'}, 'f67BGw': {'Oexq2Q': 'TFNNJA'}}, 'objNum!': {'ZoZuSQ': 0.13233985199236303}, 'objStr!': {}, 'objStruct!': {'SP+R6Q': {'optional2!': 1269064681, 'required': True}}, 'objUnion!': {'NExQ6g': {'One': {}}}, 'str!': 'RVVP0Q', 'union!': {'Two': {'optional!': True, 'required': True}}}}}]],
        [[{'@gen_': True}, {'fn.test': {}}], [{}, {'Ok_': {}}]],
    ],
    'emptyPartialMatchVerify': [
        [[{}, {'fn.clearStubs_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.clearCalls_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.createStub_': {'stub': {'fn.test': {}, '->': {'Ok_': {}}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {}}}}], [{}, {'ErrorVerificationFailure': {'reason': {'TooFewMatchingCalls': {'allCalls': [], 'found': 0, 'wanted': {'AtLeast': {'times': 1}}}}}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {}}, 'count!': {'Exact': {'times': 1}}}}], [{}, {'ErrorVerificationFailure': {'reason': {'TooFewMatchingCalls': {'allCalls': [], 'found': 0, 'wanted': {'Exact': {'times': 1}}}}}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {}}, 'count!': {'AtLeast': {'times': 1}}}}], [{}, {'ErrorVerificationFailure': {'reason': {'TooFewMatchingCalls': {'allCalls': [], 'wanted': {'AtLeast': {'times': 1}}, 'found': 0}}}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {}}, 'count!': {'AtMost': {'times': 0}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.test': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.verifyNoMoreInteractions_': {}}], [{}, {'ErrorVerificationFailure': {'additionalUnverifiedCalls': [{'fn.test': {}}]}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.verifyNoMoreInteractions_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {}}, 'count!': {'Exact': {'times': 1}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {}}, 'count!': {'AtLeast': {'times': 1}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {}}, 'count!': {'AtLeast': {'times': 2}}}}], [{}, {'ErrorVerificationFailure': {'reason': {'TooFewMatchingCalls': {'allCalls': [{'fn.test': {}}], 'found': 1, 'wanted': {'AtLeast': {'times': 2}}}}}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {}}, 'count!': {'AtMost': {'times': 1}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {}}, 'count!': {'AtMost': {'times': 0}}}}], [{}, {'ErrorVerificationFailure': {'reason': {'TooManyMatchingCalls': {'wanted': {'AtMost': {'times': 0}}, 'allCalls': [{'fn.test': {}}], 'found': 1}}}}]],
    ],
    'partialMatchVerify': [
        [[{}, {'fn.clearStubs_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.clearCalls_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.createStub_': {'stub': {'fn.test': {'value!': {'int!': 0}}, '->': {'Ok_': {'value!': {'bool!': True}}}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {'value!': {'int!': 0}}}}}], [{}, {'ErrorVerificationFailure': {'reason': {'TooFewMatchingCalls': {'found': 0, 'allCalls': [], 'wanted': {'AtLeast': {'times': 1}}}}}}]],
        [[{}, {'fn.test': {'value!': {'int!': 0, 'str!': 'a'}}}], [{}, {'Ok_': {'value!': {'bool!': True}}}]],
        [[{}, {'fn.verifyNoMoreInteractions_': {}}], [{}, {'ErrorVerificationFailure': {'additionalUnverifiedCalls': [{'fn.test': {'value!': {'int!': 0, 'str!': 'a'}}}]}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {'value!': {'int!': 0}}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.verifyNoMoreInteractions_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {'value!': {'int!': 0}}}, 'count!': {'Exact': {'times': 1}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {'value!': {'int!': 0}}}, 'count!': {'AtLeast': {'times': 1}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {'value!': {'int!': 0}}}, 'count!': {'AtMost': {'times': 0}}}}], [{}, {'ErrorVerificationFailure': {'reason': {'TooManyMatchingCalls': {'wanted': {'AtMost': {'times': 0}}, 'allCalls': [{'fn.test': {'value!': {'int!': 0, 'str!': 'a'}}}], 'found': 1}}}}]],
    ],
    'multiplePartialMatchVerify': [
        [[{}, {'fn.clearStubs_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.clearCalls_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.createStub_': {'stub': {'fn.test': {}, '->': {'Ok_': {}}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {'value!': {'int!': 0}}}}}], [{}, {'ErrorVerificationFailure': {'reason': {'TooFewMatchingCalls': {'found': 0, 'allCalls': [], 'wanted': {'AtLeast': {'times': 1}}}}}}]],
        [[{}, {'fn.test': {'value!': {'int!': 0, 'bool!': True}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 0, 'str!': 'a'}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.verifyNoMoreInteractions_': {}}], [{}, {'ErrorVerificationFailure': {'additionalUnverifiedCalls': [{'fn.test': {'value!': {'int!': 0, 'bool!': True}}}, {'fn.test': {'value!': {'int!': 0, 'str!': 'a'}}}, {'fn.test': {'value!': {'int!': 1}}}]}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {'value!': {'int!': 0}}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.verifyNoMoreInteractions_': {}}], [{}, {'ErrorVerificationFailure': {'additionalUnverifiedCalls': [{'fn.test': {'value!': {'int!': 1}}}]}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.verifyNoMoreInteractions_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {'value!': {'int!': 0}}}, 'count!': {'Exact': {'times': 1}}}}], [{}, {'ErrorVerificationFailure': {'reason': {'TooManyMatchingCalls': {'wanted': {'Exact': {'times': 1}}, 'allCalls': [{'fn.test': {'value!': {'int!': 0, 'bool!': True}}}, {'fn.test': {'value!': {'int!': 0, 'str!': 'a'}}}, {'fn.test': {'value!': {'int!': 1}}}], 'found': 2}}}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {'value!': {'int!': 0}}}, 'count!': {'Exact': {'times': 2}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {'value!': {'int!': 0}}}, 'count!': {'Exact': {'times': 3}}}}], [{}, {'ErrorVerificationFailure': {'reason': {'TooFewMatchingCalls': {'wanted': {'Exact': {'times': 3}}, 'allCalls': [{'fn.test': {'value!': {'int!': 0, 'bool!': True}}}, {'fn.test': {'value!': {'int!': 0, 'str!': 'a'}}}, {'fn.test': {'value!': {'int!': 1}}}], 'found': 2}}}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {'value!': {'int!': 0}}}, 'count!': {'AtLeast': {'times': 1}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {'value!': {'int!': 0}}}, 'count!': {'AtMost': {'times': 1}}}}], [{}, {'ErrorVerificationFailure': {'reason': {'TooManyMatchingCalls': {'wanted': {'AtMost': {'times': 1}}, 'allCalls': [{'fn.test': {'value!': {'int!': 0, 'bool!': True}}}, {'fn.test': {'value!': {'int!': 0, 'str!': 'a'}}}, {'fn.test': {'value!': {'int!': 1}}}], 'found': 2}}}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {'value!': {'int!': 0}}}, 'count!': {'AtMost': {'times': 2}}}}], [{}, {'Ok_': {}}]],
    ],
    'strictMatchVerify': [
        [[{}, {'fn.clearStubs_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.clearCalls_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.createStub_': {'stub': {'fn.test': {}, '->': {'Ok_': {}}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {'value!': {'int!': 0}}}, 'strictMatch!': True}}], [{}, {'ErrorVerificationFailure': {'reason': {'TooFewMatchingCalls': {'found': 0, 'allCalls': [], 'wanted': {'AtLeast': {'times': 1}}}}}}]],
        [[{}, {'fn.test': {'value!': {'int!': 0}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.verifyNoMoreInteractions_': {}}], [{}, {'ErrorVerificationFailure': {'additionalUnverifiedCalls': [{'fn.test': {'value!': {'int!': 0}}}]}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {'value!': {'int!': 0}}}, 'strictMatch!': True}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.verifyNoMoreInteractions_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {'value!': {'int!': 1}}}, 'strictMatch!': True}}], [{}, {'ErrorVerificationFailure': {'reason': {'TooFewMatchingCalls': {'found': 0, 'allCalls': [{'fn.test': {'value!': {'int!': 0}}}], 'wanted': {'AtLeast': {'times': 1}}}}}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {'value!': {'int!': 0, 'str!': 'a'}}}, 'strictMatch!': True}}], [{}, {'ErrorVerificationFailure': {'reason': {'TooFewMatchingCalls': {'found': 0, 'allCalls': [{'fn.test': {'value!': {'int!': 0}}}], 'wanted': {'AtLeast': {'times': 1}}}}}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {'value!': {'int!': 0}}}, 'strictMatch!': True, 'count!': {'Exact': {'times': 0}}}}], [{}, {'ErrorVerificationFailure': {'reason': {'TooManyMatchingCalls': {'wanted': {'Exact': {'times': 0}}, 'allCalls': [{'fn.test': {'value!': {'int!': 0}}}], 'found': 1}}}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {'value!': {'int!': 0}}}, 'strictMatch!': True, 'count!': {'Exact': {'times': 2}}}}], [{}, {'ErrorVerificationFailure': {'reason': {'TooFewMatchingCalls': {'wanted': {'Exact': {'times': 2}}, 'allCalls': [{'fn.test': {'value!': {'int!': 0}}}], 'found': 1}}}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {'value!': {'int!': 0}}}, 'strictMatch!': True, 'count!': {'Exact': {'times': 1}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {'value!': {'int!': 0}}}, 'strictMatch!': True, 'count!': {'AtLeast': {'times': 2}}}}], [{}, {'ErrorVerificationFailure': {'reason': {'TooFewMatchingCalls': {'wanted': {'AtLeast': {'times': 2}}, 'allCalls': [{'fn.test': {'value!': {'int!': 0}}}], 'found': 1}}}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {'value!': {'int!': 0}}}, 'strictMatch!': True, 'count!': {'AtLeast': {'times': 1}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {'value!': {'int!': 0}}}, 'strictMatch!': True, 'count!': {'AtMost': {'times': 1}}}}], [{}, {'Ok_': {}}]],
    ],
    'multipleStrictMatchVerify': [
        [[{}, {'fn.clearStubs_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.clearCalls_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.createStub_': {'stub': {'fn.test': {}, '->': {'Ok_': {}}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {'value!': {'int!': 0}}}, 'strictMatch!': True}}], [{}, {'ErrorVerificationFailure': {'reason': {'TooFewMatchingCalls': {'found': 0, 'allCalls': [], 'wanted': {'AtLeast': {'times': 1}}}}}}]],
        [[{}, {'fn.test': {'value!': {'int!': 0}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 0, 'str!': 'a'}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.verifyNoMoreInteractions_': {}}], [{}, {'ErrorVerificationFailure': {'additionalUnverifiedCalls': [{'fn.test': {'value!': {'int!': 0}}}, {'fn.test': {'value!': {'int!': 0, 'str!': 'a'}}}]}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {'value!': {'int!': 0}}}, 'strictMatch!': True}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.verifyNoMoreInteractions_': {}}], [{}, {'ErrorVerificationFailure': {'additionalUnverifiedCalls': [{'fn.test': {'value!': {'int!': 0, 'str!': 'a'}}}]}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.verifyNoMoreInteractions_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {'value!': {'int!': 1}}}, 'strictMatch!': True}}], [{}, {'ErrorVerificationFailure': {'reason': {'TooFewMatchingCalls': {'found': 0, 'allCalls': [{'fn.test': {'value!': {'int!': 0}}}, {'fn.test': {'value!': {'int!': 0, 'str!': 'a'}}}], 'wanted': {'AtLeast': {'times': 1}}}}}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {'value!': {'int!': 0, 'str!': 'b'}}}, 'strictMatch!': True}}], [{}, {'ErrorVerificationFailure': {'reason': {'TooFewMatchingCalls': {'found': 0, 'allCalls': [{'fn.test': {'value!': {'int!': 0}}}, {'fn.test': {'value!': {'int!': 0, 'str!': 'a'}}}], 'wanted': {'AtLeast': {'times': 1}}}}}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {'value!': {'int!': 0}}}, 'strictMatch!': True, 'count!': {'Exact': {'times': 0}}}}], [{}, {'ErrorVerificationFailure': {'reason': {'TooManyMatchingCalls': {'wanted': {'Exact': {'times': 0}}, 'allCalls': [{'fn.test': {'value!': {'int!': 0}}}, {'fn.test': {'value!': {'int!': 0, 'str!': 'a'}}}], 'found': 1}}}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {'value!': {'int!': 0}}}, 'strictMatch!': True, 'count!': {'Exact': {'times': 2}}}}], [{}, {'ErrorVerificationFailure': {'reason': {'TooFewMatchingCalls': {'wanted': {'Exact': {'times': 2}}, 'allCalls': [{'fn.test': {'value!': {'int!': 0}}}, {'fn.test': {'value!': {'int!': 0, 'str!': 'a'}}}], 'found': 1}}}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {'value!': {'int!': 0}}}, 'strictMatch!': True, 'count!': {'Exact': {'times': 1}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {'value!': {'int!': 0}}}, 'strictMatch!': True, 'count!': {'AtLeast': {'times': 2}}}}], [{}, {'ErrorVerificationFailure': {'reason': {'TooFewMatchingCalls': {'wanted': {'AtLeast': {'times': 2}}, 'allCalls': [{'fn.test': {'value!': {'int!': 0}}}, {'fn.test': {'value!': {'int!': 0, 'str!': 'a'}}}], 'found': 1}}}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {'value!': {'int!': 0}}}, 'strictMatch!': True, 'count!': {'AtLeast': {'times': 1}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {'value!': {'int!': 0}}}, 'strictMatch!': True, 'count!': {'AtMost': {'times': 1}}}}], [{}, {'Ok_': {}}]],
    ],
    'multipleNestedPartialMatchVerify': [
        [[{}, {'fn.clearStubs_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.clearCalls_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.createStub_': {'stub': {'fn.test': {}, '->': {'Ok_': {}}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {'value!': {'int!': 0}}}}}], [{}, {'ErrorVerificationFailure': {'reason': {'TooFewMatchingCalls': {'found': 0, 'allCalls': [], 'wanted': {'AtLeast': {'times': 1}}}}}}]],
        [[{}, {'fn.test': {'value!': {'struct!': {'required': True}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.test': {'value!': {'struct!': {'required': True, 'optional!': True}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.verifyNoMoreInteractions_': {}}], [{}, {'ErrorVerificationFailure': {'additionalUnverifiedCalls': [{'fn.test': {'value!': {'struct!': {'required': True}}}}, {'fn.test': {'value!': {'struct!': {'required': True, 'optional!': True}}}}]}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {'value!': {'struct!': {'optional!': True}}}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.verifyNoMoreInteractions_': {}}], [{}, {'ErrorVerificationFailure': {'additionalUnverifiedCalls': [{'fn.test': {'value!': {'struct!': {'required': True}}}}]}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.verifyNoMoreInteractions_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {'value!': {'struct!': {'optional!': True}}}}, 'count!': {'Exact': {'times': 1}}}}], [{}, {'Ok_': {}}]],
    ],
    'multipleReallyNestedPartialMatchVerify': [
        [[{}, {'fn.clearStubs_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.clearCalls_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.createStub_': {'stub': {'fn.test': {}, '->': {'Ok_': {}}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {'value!': {'int!': 0}}}}}], [{}, {'ErrorVerificationFailure': {'reason': {'TooFewMatchingCalls': {'found': 0, 'allCalls': [], 'wanted': {'AtLeast': {'times': 1}}}}}}]],
        [[{}, {'fn.test': {'value!': {'arrStruct!': [{'required': False}, {'required': True}]}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.test': {'value!': {'arrStruct!': [{'required': False}, {'required': True, 'optional!': True}]}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {'value!': {'arrStruct!': [{'optional!': True}]}}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.verifyNoMoreInteractions_': {}}], [{}, {'ErrorVerificationFailure': {'additionalUnverifiedCalls': [{'fn.test': {'value!': {'arrStruct!': [{'required': False}, {'required': True}]}}}]}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.verifyNoMoreInteractions_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {'value!': {'arrStruct!': [{'optional!': True}]}}}, 'count!': {'Exact': {'times': 1}}}}], [{}, {'Ok_': {}}]],
    ],
    'clearCalls': [
        [[{}, {'fn.clearStubs_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.clearCalls_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.createStub_': {'stub': {'fn.test': {}, '->': {'Ok_': {}}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {}}}}], [{}, {'ErrorVerificationFailure': {'reason': {'TooFewMatchingCalls': {'found': 0, 'allCalls': [], 'wanted': {'AtLeast': {'times': 1}}}}}}]],
        [[{}, {'fn.test': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.clearCalls_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {}}}}], [{}, {'ErrorVerificationFailure': {'reason': {'TooFewMatchingCalls': {'found': 0, 'allCalls': [], 'wanted': {'AtLeast': {'times': 1}}}}}}]],
    ],
    'resultSuppliesMissingRequiredFields': [
        [[{}, {'fn.setRandomSeed_': {'seed': 0}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.clearStubs_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.clearCalls_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.test': {}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.createStub_': {'stub': {'fn.test': {}, '->': {'Ok_': {'value!': {'bool!': True, 'struct!': {'optional!': True}}}}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.test': {}}], [{}, {'Ok_': {'value!': {'bool!': True, 'struct!': {'optional!': True, 'required': False}}}}]],
    ],
    'resultWithStartingValue': [
        [[{}, {'fn.clearStubs_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.clearCalls_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.test': {}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.createStub_': {'stub': {'fn.test': {}, '->': {'Ok_': {'value!': {'bool!': False, 'int!': 0, 'num!': 0.1, 'str!': '', 'arrBool!': [False], 'objBool!': {'a': False}, 'struct!': {'required': False}, 'union!': {'Two': {'required': False}}, 'fn!': {'fn.example': {'required': False}}}}}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.test': {}}], [{}, {'Ok_': {'value!': {'bool!': False, 'int!': 0, 'num!': 0.1, 'str!': '', 'arrBool!': [False], 'objBool!': {'a': False}, 'struct!': {'required': False}, 'union!': {'Two': {'required': False}}, 'fn!': {'fn.example': {'required': False}}}}}]],
    ],
}
