#|
#|  Copyright The Telepact Authors
#|
#|  Licensed under the Apache License, Version 2.0 (the "License");
#|  you may not use this file except in compliance with the License.
#|  You may obtain a copy of the License at
#|
#|  https://www.apache.org/licenses/LICENSE-2.0
#|
#|  Unless required by applicable law or agreed to in writing, software
#|  distributed under the License is distributed on an "AS IS" BASIS,
#|  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#|  See the License for the specific language governing permissions and
#|  limitations under the License.
#|

from typing import Any

from cases import get_values, skipped_collection_fields
from cases import additional_union_cases, additional_fn_cases, additional_integer_cases, additional_number_cases, additional_struct_cases


def generate_mock_cases(given_field: str, the_type, correct_values, additional_incorrect_values = []):
    for field, _, incorrect_values, base_path in get_values(given_field, the_type, correct_values, additional_incorrect_values):
        if field in skipped_collection_fields:
            continue

        for incorrect_value, errors in incorrect_values:
            cases = [{'path': ['fn.createStub_', 'stub', 'fn.test', 'value!'] + base_path + path, 'reason': reason} for reason, path in errors if 'RequiredObjectKeyMissing' not in reason]
            if not cases:
                continue

            yield [[{}, {'fn.createStub_': {'stub': {'fn.test': {'value!': {field: incorrect_value}}, '->': {'Ok_': {}}}}}], [{}, {'ErrorInvalidRequestBody_': {'cases': cases}}]]

        for incorrect_value, errors in incorrect_values:
            cases = [{'path': ['fn.createStub_', 'stub', '->', 'Ok_', 'value!'] + base_path + path, 'reason': reason} for reason, path in errors if 'RequiredObjectKeyMissing' not in reason]
            if not cases:
                continue
            yield [[{}, {'fn.createStub_': {'stub': {'fn.test': {}, '->': {'Ok_': {'value!': {field: incorrect_value}}}}}}], [{}, {'ErrorInvalidRequestBody_': {'cases': cases}}]]



invalid_cases = {
    'boolean': [v for v in generate_mock_cases('bool!', bool, [False, True])],
    'integer': [v for v in generate_mock_cases('int!', int, [0, -1, 1, 9223372036854775807, -9223372036854775808], additional_integer_cases)],
    'number': [v for v in generate_mock_cases('num!', float, [0, -1, 1, -1.7976931348623157e+308, -2.2250738585072014e-308, 2.2250738585072014e-308, 1.7976931348623157e+308, -0.1, 0.1], additional_number_cases)],
    'string': [v for v in generate_mock_cases('str!', str, ['', 'abc'])],
    'array': [v for v in generate_mock_cases('arr!', list, [[], [False, 0, 0.1, '']])],
    'object': [v for v in generate_mock_cases('obj!', dict, [{}, {'a': False, 'b': 0, 'c': 0.1, 'd': ''}])],
    'any': [v for v in generate_mock_cases('any!', Any, [False, 0, 0.1, '', [], {}])],
    'struct': [v for v in generate_mock_cases('struct!', dict, [{'required': False}, {'optional!': False, 'required': False}], additional_struct_cases)],
    'union': [v for v in generate_mock_cases('union!', dict, [{'One': {}}, {'Two':{'required': False}}, {'Two':{'optional!': False, 'required': False}}], additional_union_cases)],
    'fn': [v for v in generate_mock_cases('fn!', dict, [{'fn.example': {'required': False}}, {'fn.example': {'optional!': False, 'required': False}}], additional_fn_cases)],
    'sel' : [v for v in generate_mock_cases('sel!', dict, [{}])],
    'stub': [
        [[{}, {'fn.createStub_': {'stub': False}}], [{}, {'ErrorInvalidRequestBody_': {'cases': [{'path': ['fn.createStub_', 'stub'], 'reason': {'TypeUnexpected': {'actual': {'Boolean': {}}, 'expected': {'Object': {}}}}}]}}]],
        [[{}, {'fn.createStub_': {'stub': 0}}], [{}, {'ErrorInvalidRequestBody_': {'cases': [{'path': ['fn.createStub_', 'stub'], 'reason': {'TypeUnexpected': {'actual': {'Number': {}}, 'expected': {'Object': {}}}}}]}}]],
        [[{}, {'fn.createStub_': {'stub': ''}}], [{}, {'ErrorInvalidRequestBody_': {'cases': [{'path': ['fn.createStub_', 'stub'], 'reason': {'TypeUnexpected': {'actual': {'String': {}}, 'expected': {'Object': {}}}}}]}}]],
        [[{}, {'fn.createStub_': {'stub': []}}], [{}, {'ErrorInvalidRequestBody_': {'cases': [{'path': ['fn.createStub_', 'stub'], 'reason': {'TypeUnexpected': {'actual': {'Array': {}}, 'expected': {'Object': {}}}}}]}}]],
        [[{}, {'fn.createStub_': {'stub': {}}}], [{}, {'ErrorInvalidRequestBody_': {'cases': [{'path': ['fn.createStub_', 'stub'], 'reason': {'ObjectKeyRegexMatchCountUnexpected': {'regex': '^fn\\..*$', 'actual': 0, 'expected': 1, 'keys': []}}}]}}]],
        [[{}, {'fn.createStub_': {'stub': {'fn.test': {}}}}], [{}, {'ErrorInvalidRequestBody_': {'cases': [{'path': ['fn.createStub_', 'stub'], 'reason': {'RequiredObjectKeyMissing': {'key': '->'}}}]}}]],
        [[{}, {'fn.createStub_': {'stub': {'fn.test': {}, '->': {}}}}], [{}, {'ErrorInvalidRequestBody_': {'cases': [{'path': ['fn.createStub_', 'stub', '->'], 'reason': {'ObjectSizeUnexpected': {'actual': 0, 'expected': 1}}}]}}]],
        [[{}, {'fn.createStub_': {'stub': {'fn.testAnother': {}, 'fn.test': {}, '->': {'Ok_': {}}}}}], [{}, {'ErrorInvalidRequestBody_': {'cases': [{'path': ['fn.createStub_', 'stub'], 'reason': {'ObjectKeyRegexMatchCountUnexpected': {'regex': '^fn\\..*$', 'actual': 2, 'expected': 1, 'keys': ['->', 'fn.test', 'fn.testAnother']}}}]}}]],
        [[{}, {'fn.createStub_': {'stub': {'wrong': True, 'fn.test': {}, '->': {'Ok_': {}}}}}], [{}, {'ErrorInvalidRequestBody_': {'cases': [{'path': ['fn.createStub_', 'stub', 'wrong'], 'reason': {'ObjectKeyDisallowed': {}}}]}}]],
    ],
}

cases = {
    'emptyPartialMatchStub': [
        [[{}, {'fn.clearStubs_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.clearCalls_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.test': {}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.createStub_': {'stub': {'fn.test': {}, '->': {'Ok_': {}}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.test': {}}], [{}, {'Ok_': {}}]],
    ],
    'partialMatchStub': [
        [[{}, {'fn.clearStubs_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.clearCalls_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1, 'str!': 'a'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.createStub_': {'stub': {'fn.test': {'value!': {'int!': 1}}, '->': {'Ok_': {'value!': {'bool!': True}}}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.test': {}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 0}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1}}}], [{}, {'Ok_': {'value!': {'bool!': True}}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1, 'str!': 'a'}}}], [{}, {'Ok_': {'value!': {'bool!': True}}}]],
    ],
    'multiplePartialMatchStub': [
        [[{}, {'fn.clearStubs_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.clearCalls_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1, 'str!': 'a'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 0, 'str!': 'a'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1, 'str!': 'b'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'bool!': False, 'int!': 1, 'str!': 'a'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.createStub_': {'stub': {'fn.test': {'value!': {'int!': 1}}, '->': {'Ok_': {'value!': {'bool!': True}}}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.createStub_': {'stub': {'fn.test': {'value!': {'str!': 'a'}}, '->': {'Ok_': {'value!': {'bool!': False}}}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.createStub_': {'stub': {'fn.example': {}, '->': {'Ok_': {}}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.test': {}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 0}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1}}}], [{}, {'Ok_': {'value!': {'bool!': True}}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1, 'str!': 'a'}}}], [{}, {'Ok_': {'value!': {'bool!': False}}}]],
        [[{}, {'fn.test': {'value!': {'int!': 0, 'str!': 'a'}}}], [{}, {'Ok_': {'value!': {'bool!': False}}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1, 'str!': 'b'}}}], [{}, {'Ok_': {'value!': {'bool!': True}}}]],
        [[{}, {'fn.test': {'value!': {'bool!': False, 'int!': 1, 'str!': 'a'}}}], [{}, {'Ok_': {'value!': {'bool!': False}}}]],
    ],
    'multiplePartialMatchStubCount': [
        [[{}, {'fn.clearStubs_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.clearCalls_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1, 'str!': 'a'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 0, 'str!': 'a'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1, 'str!': 'b'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'bool!': False, 'int!': 1, 'str!': 'a'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.createStub_': {'count!': 2, 'stub': {'fn.test': {'value!': {'int!': 1}}, '->': {'Ok_': {'value!': {'bool!': True}}}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.createStub_': {'count!': 1, 'stub': {'fn.test': {'value!': {'str!': 'a'}}, '->': {'Ok_': {'value!': {'bool!': False}}}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.createStub_': {'stub': {'fn.example': {}, '->': {'Ok_': {}}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.test': {}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 0}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1}}}], [{}, {'Ok_': {'value!': {'bool!': True}}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1, 'str!': 'a'}}}], [{}, {'Ok_': {'value!': {'bool!': False}}}]],
        [[{}, {'fn.test': {'value!': {'int!': 0, 'str!': 'a'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1, 'str!': 'b'}}}], [{}, {'Ok_': {'value!': {'bool!': True}}}]],
        [[{}, {'fn.test': {'value!': {'bool!': False, 'int!': 1, 'str!': 'a'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
    ],    
    'multipleNestedPartialMatchStub': [
        [[{}, {'fn.clearStubs_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.clearCalls_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1, 'str!': 'a'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 0, 'str!': 'a'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1, 'str!': 'b'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'bool!': False, 'int!': 1, 'str!': 'a'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.createStub_': {'stub': {'fn.test': {'value!': {'struct!': {'optional!': True}}}, '->': {'Ok_': {'value!': {'bool!': True}}}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.createStub_': {'stub': {'fn.test': {'value!': {'struct!': {'required': True}}}, '->': {'Ok_': {'value!': {'bool!': False}}}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.createStub_': {'stub': {'fn.example': {}, '->': {'Ok_': {}}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.test': {}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'struct!': {'required': False}}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'struct!': {'optional!': False, 'required': False}}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'struct!': {'optional!': True, 'required': True}}}}], [{}, {'Ok_': {'value!': {'bool!': False}}}]],
        [[{}, {'fn.test': {'value!': {'struct!': {'optional!': True, 'required': False}}}}], [{}, {'Ok_': {'value!': {'bool!': True}}}]],
        [[{}, {'fn.test': {'value!': {'struct!': {'required': True}}}}], [{}, {'Ok_': {'value!': {'bool!': False}}}]],
        [[{}, {'fn.test': {'value!': {'struct!': {'optional!': False, 'required': True}}}}], [{}, {'Ok_': {'value!': {'bool!': False}}}]],
        [[{}, {'fn.test': {'value!': {'struct!': {'optional!': True, 'required': False}, 'str!': 'b'}}}], [{}, {'Ok_': {'value!': {'bool!': True}}}]],
    ],
    'multipleNestedPartialMatchStubCount': [
        [[{}, {'fn.clearStubs_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.clearCalls_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1, 'str!': 'a'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 0, 'str!': 'a'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1, 'str!': 'b'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'bool!': False, 'int!': 1, 'str!': 'a'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.createStub_': {'count!': 1, 'stub': {'fn.test': {'value!': {'struct!': {'optional!': True}}}, '->': {'Ok_': {'value!': {'bool!': True}}}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.createStub_': {'count!': 2, 'stub': {'fn.test': {'value!': {'struct!': {'required': True}}}, '->': {'Ok_': {'value!': {'bool!': False}}}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.createStub_': {'stub': {'fn.example': {}, '->': {'Ok_': {}}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.test': {}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'struct!': {'required': False}}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'struct!': {'optional!': False, 'required': False}}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'struct!': {'optional!': True, 'required': True}}}}], [{}, {'Ok_': {'value!': {'bool!': False}}}]],
        [[{}, {'fn.test': {'value!': {'struct!': {'optional!': True, 'required': False}}}}], [{}, {'Ok_': {'value!': {'bool!': True}}}]],
        [[{}, {'fn.test': {'value!': {'struct!': {'required': True}}}}], [{}, {'Ok_': {'value!': {'bool!': False}}}]],
        [[{}, {'fn.test': {'value!': {'struct!': {'optional!': False, 'required': True}}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'struct!': {'optional!': True, 'required': False}, 'str!': 'b'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
    ],    
    'multipleReallyNestedPartialMatchStub': [
        [[{}, {'fn.clearStubs_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.clearCalls_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1, 'str!': 'a'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 0, 'str!': 'a'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1, 'str!': 'b'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'bool!': False, 'int!': 1, 'str!': 'a'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.createStub_': {'stub': {'fn.test': {'value!': {'arrStruct!': [{'optional!': True}]}}, '->': {'Ok_': {'value!': {'bool!': True}}}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.createStub_': {'stub': {'fn.test': {'value!': {'arrStruct!': [{'required': True}]}}, '->': {'Ok_': {'value!': {'bool!': False}}}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.createStub_': {'stub': {'fn.example': {}, '->': {'Ok_': {}}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.test': {}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'arrStruct!': [{'required': False}, {'optional!': False, 'required': False}]}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'arrStruct!': [{'required': False}, {'optional!': True, 'required': True}]}}}], [{}, {'Ok_': {'value!': {'bool!': False}}}]],
        [[{}, {'fn.test': {'value!': {'arrStruct!': [{'required': False}, {'optional!': True, 'required': False}]}}}], [{}, {'Ok_': {'value!': {'bool!': True}}}]],
        [[{}, {'fn.test': {'value!': {'arrStruct!': [{'required': False}, {'optional!': False, 'required': True}]}}}], [{}, {'Ok_': {'value!': {'bool!': False}}}]],
        [[{}, {'fn.test': {'value!': {'arrStruct!': [{'required': False}, {'optional!': True, 'required': False}], 'str!': 'b'}}}], [{}, {'Ok_': {'value!': {'bool!': True}}}]],
    ],
    'multipleReallyNestedPartialMatchStubCount': [
        [[{}, {'fn.clearStubs_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.clearCalls_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1, 'str!': 'a'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 0, 'str!': 'a'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1, 'str!': 'b'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'bool!': False, 'int!': 1, 'str!': 'a'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.createStub_': {'count!': 1, 'stub': {'fn.test': {'value!': {'arrStruct!': [{'optional!': True}]}}, '->': {'Ok_': {'value!': {'bool!': True}}}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.createStub_': {'count!': 1, 'stub': {'fn.test': {'value!': {'arrStruct!': [{'required': True}]}}, '->': {'Ok_': {'value!': {'bool!': False}}}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.createStub_': {'stub': {'fn.example': {}, '->': {'Ok_': {}}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.test': {}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'arrStruct!': [{'required': False}, {'optional!': False, 'required': False}]}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'arrStruct!': [{'required': False}, {'optional!': True, 'required': True}]}}}], [{}, {'Ok_': {'value!': {'bool!': False}}}]],
        [[{}, {'fn.test': {'value!': {'arrStruct!': [{'required': False}, {'optional!': True, 'required': False}]}}}], [{}, {'Ok_': {'value!': {'bool!': True}}}]],
        [[{}, {'fn.test': {'value!': {'arrStruct!': [{'required': False}, {'optional!': False, 'required': True}]}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'arrStruct!': [{'required': False}, {'optional!': True, 'required': False}], 'str!': 'b'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
    ],    
    'strictMatchStub': [
        [[{}, {'fn.clearStubs_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.clearCalls_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.createStub_': {'stub': {'fn.test': {'value!': {'int!': 1}}, '->': {'Ok_': {'value!': {'bool!': True}}}}, 'strictMatch!': True}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.test': {}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 0}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1}}}], [{}, {'Ok_': {'value!': {'bool!': True}}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1, 'str!': 'a'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
    ],
    'multipleStrictMatchStub': [
        [[{}, {'fn.clearStubs_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.clearCalls_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'str!': 'a'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.createStub_': {'stub': {'fn.test': {'value!': {'int!': 1}}, '->': {'Ok_': {'value!': {'bool!': True}}}}, 'strictMatch!': True}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.createStub_': {'stub': {'fn.test': {'value!': {'str!': 'a'}}, '->': {'Ok_': {'value!': {'bool!': False}}}}, 'strictMatch!': True}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.test': {}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 0}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1}}}], [{}, {'Ok_': {'value!': {'bool!': True}}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1, 'str!': 'a'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'str!': 'a'}}}], [{}, {'Ok_': {'value!': {'bool!': False}}}]],
        [[{}, {'fn.test': {'value!': {'int!': 0, 'str!': 'a'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1, 'str!': 'b'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'bool!': False, 'int!': 1, 'str!': 'a'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
    ],
    'multipleStrictMatchStubCount': [
        [[{}, {'fn.clearStubs_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.clearCalls_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'str!': 'a'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.createStub_': {'count!': 1, 'stub': {'fn.test': {'value!': {'int!': 1}}, '->': {'Ok_': {'value!': {'bool!': True}}}}, 'strictMatch!': True}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.createStub_': {'count!': 1, 'stub': {'fn.test': {'value!': {'str!': 'a'}}, '->': {'Ok_': {'value!': {'bool!': False}}}}, 'strictMatch!': True}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.test': {}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 0}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1}}}], [{}, {'Ok_': {'value!': {'bool!': True}}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1, 'str!': 'a'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'str!': 'a'}}}], [{}, {'Ok_': {'value!': {'bool!': False}}}]],
        [[{}, {'fn.test': {'value!': {'str!': 'a'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 0, 'str!': 'a'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1, 'str!': 'b'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'bool!': False, 'int!': 1, 'str!': 'a'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
    ],    
    'mixedPartialStrictMatchStub': [
        [[{}, {'fn.clearStubs_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.clearCalls_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1, 'str!': 'a'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1, 'str!': 'b'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'bool!': False, 'int!': 1, 'str!': 'a'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.createStub_': {'stub': {'fn.test': {'value!': {'int!': 1}}, '->': {'Ok_': {'value!': {'bool!': True}}}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.createStub_': {'stub': {'fn.test': {'value!': {'int!': 1, 'str!': 'a'}}, '->': {'Ok_': {'value!': {'bool!': False}}}}, 'strictMatch!': True}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.test': {}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 0}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1}}}], [{}, {'Ok_': {'value!': {'bool!': True}}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1, 'str!': 'a'}}}], [{}, {'Ok_': {'value!': {'bool!': False}}}]],
        [[{}, {'fn.test': {'value!': {'int!': 0, 'str!': 'a'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1, 'str!': 'b'}}}], [{}, {'Ok_': {'value!': {'bool!': True}}}]],
        [[{}, {'fn.test': {'value!': {'bool!': False, 'int!': 1, 'str!': 'a'}}}], [{}, {'Ok_': {'value!': {'bool!': True}}}]],
    ],
    'mixedStrictPartialMatchStub': [
        [[{}, {'fn.clearStubs_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.clearCalls_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1, 'str!': 'a'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1, 'str!': 'b'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'bool!': False, 'int!': 1, 'str!': 'a'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.createStub_': {'stub': {'fn.test': {'value!': {'int!': 1, 'str!': 'a'}}, '->': {'Ok_': {'value!': {'bool!': False}}}}, 'strictMatch!': True}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.createStub_': {'stub': {'fn.test': {'value!': {'int!': 1}}, '->': {'Ok_': {'value!': {'bool!': True}}}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.test': {}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 0}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1}}}], [{}, {'Ok_': {'value!': {'bool!': True}}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1, 'str!': 'a'}}}], [{}, {'Ok_': {'value!': {'bool!': True}}}]],
        [[{}, {'fn.test': {'value!': {'int!': 0, 'str!': 'a'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1, 'str!': 'b'}}}], [{}, {'Ok_': {'value!': {'bool!': True}}}]],
        [[{}, {'fn.test': {'value!': {'bool!': False, 'int!': 1, 'str!': 'a'}}}], [{}, {'Ok_': {'value!': {'bool!': True}}}]],
    ],
    'clearStubs': [
        [[{}, {'fn.clearStubs_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.clearCalls_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.test': {}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.createStub_': {'stub': {'fn.test': {}, '->': {'Ok_': {}}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.test': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.clearStubs_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.test': {}}], [{}, {'ErrorNoMatchingStub_': {}}]],
    ],
    'generation': [
        [[{}, {'fn.setRandomSeed_': {'seed': 0}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.clearStubs_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.clearCalls_': {}}], [{}, {'Ok_': {}}]],
        [[{'@gen_': True}, {'fn.test': {}}], [{'@base64_': {'Ok_': {'value!': {'bytes!': True, 'objBytes!': {'*': True}}}}}, {'Ok_': {'value!': {'any!': True, 'arrBytes!': [], 'arrInt!': [1326349322], 'arrNullAny!': [772162768, None], 'arrNullBytes!': [None], 'arrNullFn!': [{'fn.example': {'required': True}}], 'arrNullStruct!': [None], 'arrNullUnion!': [{'One': {}}], 'arrNum!': [0.06085497655945596], 'bool!': True, 'bytes!': 'OrDL4Q==', 'fn!': {'fn.example': {'required': True}}, 'int!': 208181445, 'nullAny!': 'nu', 'nullBool!': None, 'nullInt!': 806479675, 'nullSel!': None, 'nullStr!': 'iota', 'nullStruct!': {'required': False}, 'nullUnion!': None, 'num!': 0.9951405059523604, 'objAny!': {'lambda': 2038109007}, 'objBool!': {'eta': True}, 'objBytes!': {'kappa': 'Aq7NtA=='}, 'objInt!': {'lambda': 321788014, 'chi': 1251252674}, 'objNullAny!': {}, 'objNullFn!': {'epsilon': None}, 'objNullInt!': {'omicron': 1442683466}, 'objNum!': {'theta': 0.937081863608715, 'delta': 0.5906006514982324}, 'objObj!': {'chi': {'nu': 'nu'}, 'omicron': {}}, 'objStruct!': {}, 'objUnion!': {}, 'str!': 'tau', 'union!': {'Two': {'required': True}}}}}]],
        [[{'@gen_': True}, {'fn.test': {}}], [{'@base64_': {'Ok_': {'value!': {'arrNullBytes!': {'*': True}, 'bytes!': True, 'nullBytes!': True}}}}, {'Ok_': {'value!': {'any!': 'eta', 'arr!': ['zeta'], 'arrBool!': [False], 'arrFn!': [], 'arrNullBool!': [], 'arrNullBytes!': ['Mm4WyA==', 'BWA+Eg=='], 'arrNullFn!': [], 'arrNullInt!': [], 'arrNullSel!': [{}, {'union.ExUnion': {'Two': ['required']}}], 'arrNullStruct!': [{'optional!': True, 'required': False}, {'optional!': True, 'optional2!': 153783732, 'required': False}], 'arrNullUnion!': [], 'arrStruct!': [], 'arrUnion!': [], 'bytes!': 'dRirHg==', 'fn!': {'fn.example': {'optional!': True, 'required': True}}, 'int!': 1343408611, 'nullAny!': 524433852, 'nullBytes!': 'fQ0o7w==', 'nullInt!': None, 'nullStruct!': {'required': False}, 'objAny!': {'chi': 'omega', 'eta': 'delta'}, 'objArr!': {'nu': [522553864, 'tau']}, 'objBool!': {'epsilon': False, 'chi': True}, 'objFn!': {'phi': {'fn.example': {'optional!': True, 'required': False}}, 'lambda': {'fn.example': {'required': False}}}, 'objInt!': {}, 'objNullAny!': {'mu': 168287296}, 'objNullBool!': {}, 'objNullNum!': {'omicron': 0.008515477184446285}, 'objNullStr!': {}, 'objNullStruct!': {'gamma': {'optional2!': 1511866087, 'required': True}, 'lambda': None}, 'objStr!': {'xi': 'alpha'}, 'objUnion!': {'nu': {'Two': {'optional!': False, 'required': True}}, 'epsilon': {'Two': {'optional!': False, 'required': True}}}, 'struct!': {'optional2!': 1213385984, 'required': False}, 'union!': {'One': {}}}}}]],
        [[{'@gen_': True}, {'fn.test': {}}], [{}, {'Ok_': {'value!': {'any!': 'eta', 'arrNullAny!': [], 'arrNullBool!': [None], 'arrNullFn!': [], 'arrNullInt!': [None, None], 'arrNullNum!': [None, 0.49942290619920143], 'arrNullSel!': [{'->': {'Ok_': ['value!']}, 'struct.Value': ['any!', 'arr!', 'arrBool!', 'arrBytes!', 'arrFn!', 'arrInt!', 'arrNullInt!', 'arrObj!', 'bytes!', 'int!', 'nullBool!', 'nullBytes!', 'nullInt!', 'nullNum!', 'nullUnion!', 'objAny!', 'objArr!', 'objBytes!', 'objFn!', 'objInt!', 'objNullAny!', 'objNullBool!', 'objNullBytes!', 'objNullNum!', 'objNullUnion!', 'objObj!', 'objStr!', 'sel!']}, {}], 'arrNullStr!': ['xi'], 'arrNullStruct!': [], 'arrNum!': [], 'arrSel!': [], 'arrStruct!': [{'optional!': True, 'required': False}, {'optional2!': 986836788, 'required': False}], 'nullAny!': 1034752005, 'nullFn!': {'fn.example': {'optional!': False, 'required': True}}, 'nullInt!': 46147706, 'nullStr!': 'omega', 'nullStruct!': None, 'num!': 0.11724380735179586, 'objAny!': {'kappa': False}, 'objArr!': {'eta': [820418549, 'pi'], 'iota': [True]}, 'objInt!': {}, 'objNullFn!': {}, 'objNullSel!': {}, 'objNullStruct!': {'rho': None}, 'objNullUnion!': {'alpha': None}, 'objSel!': {}, 'objStr!': {'epsilon': 'theta'}, 'sel!': {'struct.Value': ['arr!', 'arrAny!', 'arrNullInt!', 'arrNullSel!', 'arrNullStruct!', 'arrNum!', 'arrSel!', 'arrStruct!', 'arrUnion!', 'bool!', 'fn!', 'int!', 'nullAny!', 'nullBool!', 'nullBytes!', 'nullStr!', 'num!', 'objArr!', 'objBytes!', 'objFn!', 'objNullAny!', 'objNullBool!', 'objNullFn!', 'objNullNum!', 'objNullStruct!', 'objNullUnion!', 'objStr!', 'objUnion!', 'union!']}, 'str!': 'rho'}}}]],
        [[{'@gen_': True}, {'fn.test': {}}], [{'@base64_': {'Ok_': {'value!': {'arrBytes!': {'*': True}, 'bytes!': True, 'objBytes!': {'*': True}}}}}, {'Ok_': {'value!': {'arr!': [], 'arrArr!': [['pi', True], [False]], 'arrBool!': [], 'arrBytes!': ['d/LIKw=='], 'arrFn!': [], 'arrNullAny!': [None], 'arrNullBytes!': [None, None], 'arrNullFn!': [{'fn.example': {'required': False}}, {'fn.example': {'required': True}}], 'arrNullNum!': [None, 0.9124964754621017], 'arrNullSel!': [None], 'arrNum!': [0.35751159971464036, 0.8825963981834224], 'arrObj!': [], 'arrStr!': ['upsilon', 'theta'], 'arrStruct!': [{'required': True}, {'optional2!': 1699990288, 'required': False}], 'bytes!': 'QI4QTg==', 'fn!': {'fn.example': {'required': True}}, 'int!': 1269064681, 'nullBool!': None, 'nullFn!': {'fn.example': {'required': False}}, 'nullNum!': None, 'nullStruct!': None, 'num!': 0.1756737624181778, 'objAny!': {'iota': False}, 'objBytes!': {'eta': 'FWNFDQ=='}, 'objInt!': {'chi': 1607136444, 'gamma': 1992752504}, 'objNullInt!': {}, 'objNullNum!': {'rho': 0.9045885591323434, 'mu': 0.9703257139633995}, 'objNullStr!': {'phi': 'alpha', 'nu': None}, 'objNullStruct!': {}, 'objNum!': {'theta': 0.23849520517443085, 'beta': 0.45800734518934383}, 'objStruct!': {'beta': {'optional2!': 2002328898, 'required': True}, 'tau': {'optional!': True, 'required': True}}, 'objUnion!': {}, 'sel!': {'struct.Value': ['any!', 'arrAny!', 'arrBool!', 'arrNullAny!', 'arrNullBytes!', 'arrNullInt!', 'arrNullStruct!', 'arrNullUnion!', 'arrObj!', 'arrSel!', 'arrStr!', 'bytes!', 'int!', 'nullBool!', 'nullBytes!', 'nullNum!', 'nullSel!', 'nullUnion!', 'num!', 'objBytes!', 'objFn!', 'objInt!', 'objNullBytes!', 'objNullFn!', 'objNullNum!', 'objNullSel!', 'objNullStruct!', 'objNum!', 'objObj!', 'objSel!', 'objStruct!', 'sel!', 'str!']}, 'str!': 'epsilon', 'union!': {'One': {}}}}}]],
        [[{'@gen_': True}, {'fn.test': {}}], [{}, {'Ok_': {}}]],
        [[{'@gen_': True}, {'fn.test': {}}], [{}, {'Ok_': {}}]],
        [[{'@gen_': True}, {'fn.test': {}}], [{'@base64_': {'Ok_': {'value!': {'arrNullBytes!': {'*': True}}}}}, {'Ok_': {'value!': {'any!': 'omicron', 'arrAny!': [True], 'arrArr!': [], 'arrFn!': [{'fn.example': {'required': False}}], 'arrNullBytes!': ['XdVWNA==', 'WS140w=='], 'arrNullNum!': [0.07348501452872763, 0.7221775132800348], 'arrNullSel!': [{'struct.ExStruct': ['optional!', 'required']}, None], 'arrNum!': [0.2784186267659155], 'arrObj!': [], 'arrStr!': ['rho', 'pi'], 'arrUnion!': [{'Two': {'required': False}}], 'bool!': False, 'fn!': {'fn.example': {'optional!': True, 'required': True}}, 'nullAny!': True, 'nullFn!': None, 'nullNum!': None, 'nullStr!': None, 'nullStruct!': {'optional!': False, 'required': False}, 'objInt!': {'mu': 1852127189, 'delta': 2033205300}, 'objNullAny!': {}, 'objNullBytes!': {'rho': None}, 'objNullInt!': {'lambda': None}, 'objNullSel!': {'omicron': {'struct.Value': ['any!', 'arr!', 'arrArr!', 'arrBool!', 'arrBytes!', 'arrInt!', 'arrNullAny!', 'arrNullBool!', 'arrNullFn!', 'arrNullInt!', 'arrNullSel!', 'arrNullStruct!', 'arrNullUnion!', 'arrNum!', 'arrObj!', 'arrStruct!', 'bytes!', 'nullBytes!', 'nullNum!', 'nullSel!', 'nullStr!', 'nullUnion!', 'num!', 'objBool!', 'objFn!', 'objNullBytes!', 'objNullNum!', 'objNullStr!', 'objNum!', 'objObj!', 'objStr!', 'objStruct!', 'sel!', 'struct!']}, 'tau': None}, 'objNullStr!': {}, 'objNullStruct!': {}, 'objNullUnion!': {}, 'objNum!': {'epsilon': 0.8692525708439074, 'phi': 0.23024012391932314}, 'objStr!': {'alpha': 'zeta'}, 'objStruct!': {}, 'sel!': {'struct.Value': ['arr!', 'arrArr!', 'arrBool!', 'arrBytes!', 'arrNullBool!', 'arrNullBytes!', 'arrNullFn!', 'arrNullInt!', 'arrNullNum!', 'arrNullStr!', 'arrNum!', 'arrSel!', 'arrStr!', 'bool!', 'bytes!', 'nullFn!', 'nullInt!', 'nullSel!', 'num!', 'obj!', 'objArr!', 'objBool!', 'objBytes!', 'objFn!', 'objInt!', 'objNullBool!', 'objNullFn!', 'objNullInt!', 'objNullSel!', 'objNullStruct!', 'objNullUnion!', 'objNum!', 'objUnion!', 'sel!', 'str!']}, 'union!': {'Two': {'required': False}}}}}]],
        [[{'@gen_': True}, {'fn.test': {}}], [{'@base64_': {'Ok_': {'value!': {'arrBytes!': {'*': True}}}}}, {'Ok_': {'value!': {'any!': 'lambda', 'arr!': [], 'arrAny!': [328534094, 'zeta'], 'arrArr!': [], 'arrBool!': [False], 'arrBytes!': ['JPhsGg==', 'VYV6tw=='], 'arrFn!': [{'fn.example': {'optional!': True, 'required': False}}], 'arrInt!': [], 'arrNullAny!': [None, True], 'arrNullBytes!': [], 'arrNullFn!': [None, None], 'arrNullInt!': [33713460, None], 'arrNullNum!': [], 'arrObj!': [{'beta': True}, {}], 'arrStr!': ['xi'], 'arrUnion!': [{'Two': {'optional!': False, 'required': False}}], 'bool!': False, 'nullBool!': False, 'nullInt!': 1787706437, 'nullNum!': 0.3799016877915252, 'nullSel!': {}, 'obj!': {}, 'objAny!': {}, 'objArr!': {}, 'objBool!': {'pi': True, 'delta': False}, 'objFn!': {'sigma': {'fn.example': {'optional!': False, 'required': True}}}, 'objInt!': {'delta': 235062417, 'kappa': 325744608}, 'objNullAny!': {'zeta': 'chi', 'sigma': None}, 'objNullBytes!': {}, 'objNullSel!': {}, 'objNullStruct!': {}, 'objNullUnion!': {}, 'objStr!': {'gamma': 'theta'}, 'str!': 'mu'}}}]],
        [[{'@gen_': True}, {'fn.test': {}}], [{}, {'Ok_': {'value!': {'arr!': [], 'arrAny!': [287824970], 'arrArr!': [[2027684777, 'rho']], 'arrFn!': [], 'arrNullBool!': [True, False], 'arrNullSel!': [None, {'->': {'Ok_': ['value!']}, 'struct.ExStruct': ['optional!', 'optional2!', 'required'], 'struct.Value': ['any!', 'arr!', 'arrAny!', 'arrInt!', 'arrNullBytes!', 'arrNullSel!', 'arrNullStruct!', 'arrNullUnion!', 'arrStr!', 'bytes!', 'int!', 'nullBytes!', 'nullInt!', 'nullNum!', 'nullStr!', 'obj!', 'objBool!', 'objBytes!', 'objInt!', 'objNullAny!', 'objNullBytes!', 'objNullNum!', 'objNullStr!', 'objStr!', 'objStruct!', 'str!', 'struct!']}], 'arrNullUnion!': [None, None], 'arrNum!': [], 'bool!': False, 'int!': 574922970, 'nullInt!': 165009342, 'nullStr!': None, 'objAny!': {'omicron': 'theta'}, 'objBool!': {}, 'objInt!': {'rho': 604743719, 'tau': 1667612289}, 'objNullFn!': {'upsilon': None, 'gamma': None}, 'objNullNum!': {'tau': None}, 'objNullSel!': {'sigma': {'struct.ExStruct': [], 'union.ExUnion': {'Two': []}}}, 'objNullStr!': {'psi': None, 'pi': None}, 'objObj!': {'alpha': {'pi': 'nu'}}, 'objStr!': {}, 'objStruct!': {'upsilon': {'optional!': False, 'optional2!': 1303675385, 'required': False}, 'sigma': {'optional!': True, 'optional2!': 1977317489, 'required': False}}, 'sel!': {'->': {'Ok_': []}, 'struct.ExStruct': ['optional2!']}, 'struct!': {'optional!': False, 'required': False}, 'union!': {'Two': {'required': False}}}}}]],
        [[{'@gen_': True}, {'fn.test': {}}], [{}, {'Ok_': {}}]],
    ],
    'emptyPartialMatchVerify': [
        [[{}, {'fn.clearStubs_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.clearCalls_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.createStub_': {'stub': {'fn.test': {}, '->': {'Ok_': {}}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {}}}}], [{}, {'ErrorVerificationFailure': {'reason': {'TooFewMatchingCalls': {'allCalls': [], 'found': 0, 'wanted': {'AtLeast': {'times': 1}}}}}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {}}, 'count!': {'Exact': {'times': 1}}}}], [{}, {'ErrorVerificationFailure': {'reason': {'TooFewMatchingCalls': {'allCalls': [], 'found': 0, 'wanted': {'Exact': {'times': 1}}}}}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {}}, 'count!': {'AtLeast': {'times': 1}}}}], [{}, {'ErrorVerificationFailure': {'reason': {'TooFewMatchingCalls': {'allCalls': [], 'wanted': {'AtLeast': {'times': 1}}, 'found': 0}}}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {}}, 'count!': {'AtMost': {'times': 0}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.test': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.verifyNoMoreInteractions_': {}}], [{}, {'ErrorVerificationFailure': {'additionalUnverifiedCalls': [{'fn.test': {}}]}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.verifyNoMoreInteractions_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {}}, 'count!': {'Exact': {'times': 1}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {}}, 'count!': {'AtLeast': {'times': 1}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {}}, 'count!': {'AtLeast': {'times': 2}}}}], [{}, {'ErrorVerificationFailure': {'reason': {'TooFewMatchingCalls': {'allCalls': [{'fn.test': {}}], 'found': 1, 'wanted': {'AtLeast': {'times': 2}}}}}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {}}, 'count!': {'AtMost': {'times': 1}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {}}, 'count!': {'AtMost': {'times': 0}}}}], [{}, {'ErrorVerificationFailure': {'reason': {'TooManyMatchingCalls': {'wanted': {'AtMost': {'times': 0}}, 'allCalls': [{'fn.test': {}}], 'found': 1}}}}]],
    ],
    'partialMatchVerify': [
        [[{}, {'fn.clearStubs_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.clearCalls_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.createStub_': {'stub': {'fn.test': {'value!': {'int!': 0}}, '->': {'Ok_': {'value!': {'bool!': True}}}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {'value!': {'int!': 0}}}}}], [{}, {'ErrorVerificationFailure': {'reason': {'TooFewMatchingCalls': {'found': 0, 'allCalls': [], 'wanted': {'AtLeast': {'times': 1}}}}}}]],
        [[{}, {'fn.test': {'value!': {'int!': 0, 'str!': 'a'}}}], [{}, {'Ok_': {'value!': {'bool!': True}}}]],
        [[{}, {'fn.verifyNoMoreInteractions_': {}}], [{}, {'ErrorVerificationFailure': {'additionalUnverifiedCalls': [{'fn.test': {'value!': {'int!': 0, 'str!': 'a'}}}]}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {'value!': {'int!': 0}}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.verifyNoMoreInteractions_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {'value!': {'int!': 0}}}, 'count!': {'Exact': {'times': 1}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {'value!': {'int!': 0}}}, 'count!': {'AtLeast': {'times': 1}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {'value!': {'int!': 0}}}, 'count!': {'AtMost': {'times': 0}}}}], [{}, {'ErrorVerificationFailure': {'reason': {'TooManyMatchingCalls': {'wanted': {'AtMost': {'times': 0}}, 'allCalls': [{'fn.test': {'value!': {'int!': 0, 'str!': 'a'}}}], 'found': 1}}}}]],
    ],
    'multiplePartialMatchVerify': [
        [[{}, {'fn.clearStubs_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.clearCalls_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.createStub_': {'stub': {'fn.test': {}, '->': {'Ok_': {}}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {'value!': {'int!': 0}}}}}], [{}, {'ErrorVerificationFailure': {'reason': {'TooFewMatchingCalls': {'found': 0, 'allCalls': [], 'wanted': {'AtLeast': {'times': 1}}}}}}]],
        [[{}, {'fn.test': {'value!': {'int!': 0, 'bool!': True}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 0, 'str!': 'a'}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.verifyNoMoreInteractions_': {}}], [{}, {'ErrorVerificationFailure': {'additionalUnverifiedCalls': [{'fn.test': {'value!': {'int!': 0, 'bool!': True}}}, {'fn.test': {'value!': {'int!': 0, 'str!': 'a'}}}, {'fn.test': {'value!': {'int!': 1}}}]}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {'value!': {'int!': 0}}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.verifyNoMoreInteractions_': {}}], [{}, {'ErrorVerificationFailure': {'additionalUnverifiedCalls': [{'fn.test': {'value!': {'int!': 1}}}]}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.verifyNoMoreInteractions_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {'value!': {'int!': 0}}}, 'count!': {'Exact': {'times': 1}}}}], [{}, {'ErrorVerificationFailure': {'reason': {'TooManyMatchingCalls': {'wanted': {'Exact': {'times': 1}}, 'allCalls': [{'fn.test': {'value!': {'int!': 0, 'bool!': True}}}, {'fn.test': {'value!': {'int!': 0, 'str!': 'a'}}}, {'fn.test': {'value!': {'int!': 1}}}], 'found': 2}}}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {'value!': {'int!': 0}}}, 'count!': {'Exact': {'times': 2}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {'value!': {'int!': 0}}}, 'count!': {'Exact': {'times': 3}}}}], [{}, {'ErrorVerificationFailure': {'reason': {'TooFewMatchingCalls': {'wanted': {'Exact': {'times': 3}}, 'allCalls': [{'fn.test': {'value!': {'int!': 0, 'bool!': True}}}, {'fn.test': {'value!': {'int!': 0, 'str!': 'a'}}}, {'fn.test': {'value!': {'int!': 1}}}], 'found': 2}}}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {'value!': {'int!': 0}}}, 'count!': {'AtLeast': {'times': 1}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {'value!': {'int!': 0}}}, 'count!': {'AtMost': {'times': 1}}}}], [{}, {'ErrorVerificationFailure': {'reason': {'TooManyMatchingCalls': {'wanted': {'AtMost': {'times': 1}}, 'allCalls': [{'fn.test': {'value!': {'int!': 0, 'bool!': True}}}, {'fn.test': {'value!': {'int!': 0, 'str!': 'a'}}}, {'fn.test': {'value!': {'int!': 1}}}], 'found': 2}}}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {'value!': {'int!': 0}}}, 'count!': {'AtMost': {'times': 2}}}}], [{}, {'Ok_': {}}]],
    ],
    'strictMatchVerify': [
        [[{}, {'fn.clearStubs_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.clearCalls_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.createStub_': {'stub': {'fn.test': {}, '->': {'Ok_': {}}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {'value!': {'int!': 0}}}, 'strictMatch!': True}}], [{}, {'ErrorVerificationFailure': {'reason': {'TooFewMatchingCalls': {'found': 0, 'allCalls': [], 'wanted': {'AtLeast': {'times': 1}}}}}}]],
        [[{}, {'fn.test': {'value!': {'int!': 0}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.verifyNoMoreInteractions_': {}}], [{}, {'ErrorVerificationFailure': {'additionalUnverifiedCalls': [{'fn.test': {'value!': {'int!': 0}}}]}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {'value!': {'int!': 0}}}, 'strictMatch!': True}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.verifyNoMoreInteractions_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {'value!': {'int!': 1}}}, 'strictMatch!': True}}], [{}, {'ErrorVerificationFailure': {'reason': {'TooFewMatchingCalls': {'found': 0, 'allCalls': [{'fn.test': {'value!': {'int!': 0}}}], 'wanted': {'AtLeast': {'times': 1}}}}}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {'value!': {'int!': 0, 'str!': 'a'}}}, 'strictMatch!': True}}], [{}, {'ErrorVerificationFailure': {'reason': {'TooFewMatchingCalls': {'found': 0, 'allCalls': [{'fn.test': {'value!': {'int!': 0}}}], 'wanted': {'AtLeast': {'times': 1}}}}}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {'value!': {'int!': 0}}}, 'strictMatch!': True, 'count!': {'Exact': {'times': 0}}}}], [{}, {'ErrorVerificationFailure': {'reason': {'TooManyMatchingCalls': {'wanted': {'Exact': {'times': 0}}, 'allCalls': [{'fn.test': {'value!': {'int!': 0}}}], 'found': 1}}}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {'value!': {'int!': 0}}}, 'strictMatch!': True, 'count!': {'Exact': {'times': 2}}}}], [{}, {'ErrorVerificationFailure': {'reason': {'TooFewMatchingCalls': {'wanted': {'Exact': {'times': 2}}, 'allCalls': [{'fn.test': {'value!': {'int!': 0}}}], 'found': 1}}}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {'value!': {'int!': 0}}}, 'strictMatch!': True, 'count!': {'Exact': {'times': 1}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {'value!': {'int!': 0}}}, 'strictMatch!': True, 'count!': {'AtLeast': {'times': 2}}}}], [{}, {'ErrorVerificationFailure': {'reason': {'TooFewMatchingCalls': {'wanted': {'AtLeast': {'times': 2}}, 'allCalls': [{'fn.test': {'value!': {'int!': 0}}}], 'found': 1}}}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {'value!': {'int!': 0}}}, 'strictMatch!': True, 'count!': {'AtLeast': {'times': 1}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {'value!': {'int!': 0}}}, 'strictMatch!': True, 'count!': {'AtMost': {'times': 1}}}}], [{}, {'Ok_': {}}]],
    ],
    'multipleStrictMatchVerify': [
        [[{}, {'fn.clearStubs_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.clearCalls_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.createStub_': {'stub': {'fn.test': {}, '->': {'Ok_': {}}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {'value!': {'int!': 0}}}, 'strictMatch!': True}}], [{}, {'ErrorVerificationFailure': {'reason': {'TooFewMatchingCalls': {'found': 0, 'allCalls': [], 'wanted': {'AtLeast': {'times': 1}}}}}}]],
        [[{}, {'fn.test': {'value!': {'int!': 0}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 0, 'str!': 'a'}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.verifyNoMoreInteractions_': {}}], [{}, {'ErrorVerificationFailure': {'additionalUnverifiedCalls': [{'fn.test': {'value!': {'int!': 0}}}, {'fn.test': {'value!': {'int!': 0, 'str!': 'a'}}}]}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {'value!': {'int!': 0}}}, 'strictMatch!': True}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.verifyNoMoreInteractions_': {}}], [{}, {'ErrorVerificationFailure': {'additionalUnverifiedCalls': [{'fn.test': {'value!': {'int!': 0, 'str!': 'a'}}}]}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.verifyNoMoreInteractions_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {'value!': {'int!': 1}}}, 'strictMatch!': True}}], [{}, {'ErrorVerificationFailure': {'reason': {'TooFewMatchingCalls': {'found': 0, 'allCalls': [{'fn.test': {'value!': {'int!': 0}}}, {'fn.test': {'value!': {'int!': 0, 'str!': 'a'}}}], 'wanted': {'AtLeast': {'times': 1}}}}}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {'value!': {'int!': 0, 'str!': 'b'}}}, 'strictMatch!': True}}], [{}, {'ErrorVerificationFailure': {'reason': {'TooFewMatchingCalls': {'found': 0, 'allCalls': [{'fn.test': {'value!': {'int!': 0}}}, {'fn.test': {'value!': {'int!': 0, 'str!': 'a'}}}], 'wanted': {'AtLeast': {'times': 1}}}}}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {'value!': {'int!': 0}}}, 'strictMatch!': True, 'count!': {'Exact': {'times': 0}}}}], [{}, {'ErrorVerificationFailure': {'reason': {'TooManyMatchingCalls': {'wanted': {'Exact': {'times': 0}}, 'allCalls': [{'fn.test': {'value!': {'int!': 0}}}, {'fn.test': {'value!': {'int!': 0, 'str!': 'a'}}}], 'found': 1}}}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {'value!': {'int!': 0}}}, 'strictMatch!': True, 'count!': {'Exact': {'times': 2}}}}], [{}, {'ErrorVerificationFailure': {'reason': {'TooFewMatchingCalls': {'wanted': {'Exact': {'times': 2}}, 'allCalls': [{'fn.test': {'value!': {'int!': 0}}}, {'fn.test': {'value!': {'int!': 0, 'str!': 'a'}}}], 'found': 1}}}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {'value!': {'int!': 0}}}, 'strictMatch!': True, 'count!': {'Exact': {'times': 1}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {'value!': {'int!': 0}}}, 'strictMatch!': True, 'count!': {'AtLeast': {'times': 2}}}}], [{}, {'ErrorVerificationFailure': {'reason': {'TooFewMatchingCalls': {'wanted': {'AtLeast': {'times': 2}}, 'allCalls': [{'fn.test': {'value!': {'int!': 0}}}, {'fn.test': {'value!': {'int!': 0, 'str!': 'a'}}}], 'found': 1}}}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {'value!': {'int!': 0}}}, 'strictMatch!': True, 'count!': {'AtLeast': {'times': 1}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {'value!': {'int!': 0}}}, 'strictMatch!': True, 'count!': {'AtMost': {'times': 1}}}}], [{}, {'Ok_': {}}]],
    ],
    'multipleNestedPartialMatchVerify': [
        [[{}, {'fn.clearStubs_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.clearCalls_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.createStub_': {'stub': {'fn.test': {}, '->': {'Ok_': {}}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {'value!': {'int!': 0}}}}}], [{}, {'ErrorVerificationFailure': {'reason': {'TooFewMatchingCalls': {'found': 0, 'allCalls': [], 'wanted': {'AtLeast': {'times': 1}}}}}}]],
        [[{}, {'fn.test': {'value!': {'struct!': {'required': True}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.test': {'value!': {'struct!': {'required': True, 'optional!': True}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.verifyNoMoreInteractions_': {}}], [{}, {'ErrorVerificationFailure': {'additionalUnverifiedCalls': [{'fn.test': {'value!': {'struct!': {'required': True}}}}, {'fn.test': {'value!': {'struct!': {'required': True, 'optional!': True}}}}]}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {'value!': {'struct!': {'optional!': True}}}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.verifyNoMoreInteractions_': {}}], [{}, {'ErrorVerificationFailure': {'additionalUnverifiedCalls': [{'fn.test': {'value!': {'struct!': {'required': True}}}}]}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.verifyNoMoreInteractions_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {'value!': {'struct!': {'optional!': True}}}}, 'count!': {'Exact': {'times': 1}}}}], [{}, {'Ok_': {}}]],
    ],
    'multipleReallyNestedPartialMatchVerify': [
        [[{}, {'fn.clearStubs_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.clearCalls_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.createStub_': {'stub': {'fn.test': {}, '->': {'Ok_': {}}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {'value!': {'int!': 0}}}}}], [{}, {'ErrorVerificationFailure': {'reason': {'TooFewMatchingCalls': {'found': 0, 'allCalls': [], 'wanted': {'AtLeast': {'times': 1}}}}}}]],
        [[{}, {'fn.test': {'value!': {'arrStruct!': [{'required': False}, {'required': True}]}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.test': {'value!': {'arrStruct!': [{'required': False}, {'required': True, 'optional!': True}]}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {'value!': {'arrStruct!': [{'optional!': True}]}}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.verifyNoMoreInteractions_': {}}], [{}, {'ErrorVerificationFailure': {'additionalUnverifiedCalls': [{'fn.test': {'value!': {'arrStruct!': [{'required': False}, {'required': True}]}}}]}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.verifyNoMoreInteractions_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {'value!': {'arrStruct!': [{'optional!': True}]}}}, 'count!': {'Exact': {'times': 1}}}}], [{}, {'Ok_': {}}]],
    ],
    'clearCalls': [
        [[{}, {'fn.clearStubs_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.clearCalls_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.createStub_': {'stub': {'fn.test': {}, '->': {'Ok_': {}}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {}}}}], [{}, {'ErrorVerificationFailure': {'reason': {'TooFewMatchingCalls': {'found': 0, 'allCalls': [], 'wanted': {'AtLeast': {'times': 1}}}}}}]],
        [[{}, {'fn.test': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.clearCalls_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {}}}}], [{}, {'ErrorVerificationFailure': {'reason': {'TooFewMatchingCalls': {'found': 0, 'allCalls': [], 'wanted': {'AtLeast': {'times': 1}}}}}}]],
    ],
    'resultSuppliesMissingRequiredFields': [
        [[{}, {'fn.setRandomSeed_': {'seed': 0}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.clearStubs_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.clearCalls_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.test': {}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.createStub_': {'stub': {'fn.test': {}, '->': {'Ok_': {'value!': {'bool!': True, 'struct!': {'optional!': True}}}}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.test': {}}], [{}, {'Ok_': {'value!': {'bool!': True, 'struct!': {'optional!': True, 'required': False}}}}]],
    ],
    'resultWithStartingValue': [
        [[{}, {'fn.clearStubs_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.clearCalls_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.test': {}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.createStub_': {'stub': {'fn.test': {}, '->': {'Ok_': {'value!': {'bool!': False, 'int!': 0, 'num!': 0.1, 'str!': '', 'arrBool!': [False], 'objBool!': {'a': False}, 'struct!': {'required': False}, 'union!': {'Two': {'required': False}}, 'fn!': {'fn.example': {'required': False}}}}}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.test': {}}], [{}, {'Ok_': {'value!': {'bool!': False, 'int!': 0, 'num!': 0.1, 'str!': '', 'arrBool!': [False], 'objBool!': {'a': False}, 'struct!': {'required': False}, 'union!': {'Two': {'required': False}}, 'fn!': {'fn.example': {'required': False}}}}}]],
    ],
}
