#|
#|  Copyright The Telepact Authors
#|
#|  Licensed under the Apache License, Version 2.0 (the "License");
#|  you may not use this file except in compliance with the License.
#|  You may obtain a copy of the License at
#|
#|  https://www.apache.org/licenses/LICENSE-2.0
#|
#|  Unless required by applicable law or agreed to in writing, software
#|  distributed under the License is distributed on an "AS IS" BASIS,
#|  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#|  See the License for the specific language governing permissions and
#|  limitations under the License.
#|

from typing import Any

from cases import get_values, skipped_collection_fields
from cases import additional_union_cases, additional_fn_cases, additional_integer_cases, additional_number_cases, additional_struct_cases


def generate_mock_cases(given_field: str, the_type, correct_values, additional_incorrect_values = []):
    for field, _, incorrect_values, base_path in get_values(given_field, the_type, correct_values, additional_incorrect_values):
        if field in skipped_collection_fields:
            continue

        for incorrect_value, errors in incorrect_values:
            cases = [{'path': ['fn.createStub_', 'stub', 'fn.test', 'value!'] + base_path + path, 'reason': reason} for reason, path in errors if 'RequiredObjectKeyMissing' not in reason]
            if not cases:
                continue

            yield [[{}, {'fn.createStub_': {'stub': {'fn.test': {'value!': {field: incorrect_value}}, '->': {'Ok_': {}}}}}], [{}, {'ErrorInvalidRequestBody_': {'cases': cases}}]]

        for incorrect_value, errors in incorrect_values:
            cases = [{'path': ['fn.createStub_', 'stub', '->', 'Ok_', 'value!'] + base_path + path, 'reason': reason} for reason, path in errors if 'RequiredObjectKeyMissing' not in reason]
            if not cases:
                continue
            yield [[{}, {'fn.createStub_': {'stub': {'fn.test': {}, '->': {'Ok_': {'value!': {field: incorrect_value}}}}}}], [{}, {'ErrorInvalidRequestBody_': {'cases': cases}}]]



invalid_cases = {
    'boolean': [v for v in generate_mock_cases('bool!', bool, [False, True])],
    'integer': [v for v in generate_mock_cases('int!', int, [0, -1, 1, 9223372036854775807, -9223372036854775808], additional_integer_cases)],
    'number': [v for v in generate_mock_cases('num!', float, [0, -1, 1, -1.7976931348623157e+308, -2.2250738585072014e-308, 2.2250738585072014e-308, 1.7976931348623157e+308, -0.1, 0.1], additional_number_cases)],
    'string': [v for v in generate_mock_cases('str!', str, ['', 'abc'])],
    'array': [v for v in generate_mock_cases('arr!', list, [[], [False, 0, 0.1, '']])],
    'object': [v for v in generate_mock_cases('obj!', dict, [{}, {'a': False, 'b': 0, 'c': 0.1, 'd': ''}])],
    'any': [v for v in generate_mock_cases('any!', Any, [False, 0, 0.1, '', [], {}])],
    'struct': [v for v in generate_mock_cases('struct!', dict, [{'required': False}, {'optional!': False, 'required': False}], additional_struct_cases)],
    'union': [v for v in generate_mock_cases('union!', dict, [{'One': {}}, {'Two':{'required': False}}, {'Two':{'optional!': False, 'required': False}}], additional_union_cases)],
    'fn': [v for v in generate_mock_cases('fn!', dict, [{'fn.example': {'required': False}}, {'fn.example': {'optional!': False, 'required': False}}], additional_fn_cases)],
    'sel' : [v for v in generate_mock_cases('sel!', dict, [{}])],
    'stub': [
        [[{}, {'fn.createStub_': {'stub': False}}], [{}, {'ErrorInvalidRequestBody_': {'cases': [{'path': ['fn.createStub_', 'stub'], 'reason': {'TypeUnexpected': {'actual': {'Boolean': {}}, 'expected': {'Object': {}}}}}]}}]],
        [[{}, {'fn.createStub_': {'stub': 0}}], [{}, {'ErrorInvalidRequestBody_': {'cases': [{'path': ['fn.createStub_', 'stub'], 'reason': {'TypeUnexpected': {'actual': {'Number': {}}, 'expected': {'Object': {}}}}}]}}]],
        [[{}, {'fn.createStub_': {'stub': ''}}], [{}, {'ErrorInvalidRequestBody_': {'cases': [{'path': ['fn.createStub_', 'stub'], 'reason': {'TypeUnexpected': {'actual': {'String': {}}, 'expected': {'Object': {}}}}}]}}]],
        [[{}, {'fn.createStub_': {'stub': []}}], [{}, {'ErrorInvalidRequestBody_': {'cases': [{'path': ['fn.createStub_', 'stub'], 'reason': {'TypeUnexpected': {'actual': {'Array': {}}, 'expected': {'Object': {}}}}}]}}]],
        [[{}, {'fn.createStub_': {'stub': {}}}], [{}, {'ErrorInvalidRequestBody_': {'cases': [{'path': ['fn.createStub_', 'stub'], 'reason': {'ObjectKeyRegexMatchCountUnexpected': {'regex': '^fn\\..*$', 'actual': 0, 'expected': 1, 'keys': []}}}]}}]],
        [[{}, {'fn.createStub_': {'stub': {'fn.test': {}}}}], [{}, {'ErrorInvalidRequestBody_': {'cases': [{'path': ['fn.createStub_', 'stub'], 'reason': {'RequiredObjectKeyMissing': {'key': '->'}}}]}}]],
        [[{}, {'fn.createStub_': {'stub': {'fn.test': {}, '->': {}}}}], [{}, {'ErrorInvalidRequestBody_': {'cases': [{'path': ['fn.createStub_', 'stub', '->'], 'reason': {'ObjectSizeUnexpected': {'actual': 0, 'expected': 1}}}]}}]],
        [[{}, {'fn.createStub_': {'stub': {'fn.testAnother': {}, 'fn.test': {}, '->': {'Ok_': {}}}}}], [{}, {'ErrorInvalidRequestBody_': {'cases': [{'path': ['fn.createStub_', 'stub'], 'reason': {'ObjectKeyRegexMatchCountUnexpected': {'regex': '^fn\\..*$', 'actual': 2, 'expected': 1, 'keys': ['->', 'fn.test', 'fn.testAnother']}}}]}}]],
        [[{}, {'fn.createStub_': {'stub': {'wrong': True, 'fn.test': {}, '->': {'Ok_': {}}}}}], [{}, {'ErrorInvalidRequestBody_': {'cases': [{'path': ['fn.createStub_', 'stub', 'wrong'], 'reason': {'ObjectKeyDisallowed': {}}}]}}]],
    ],
}

cases = {
    'emptyPartialMatchStub': [
        [[{}, {'fn.clearStubs_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.clearCalls_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.test': {}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.createStub_': {'stub': {'fn.test': {}, '->': {'Ok_': {}}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.test': {}}], [{}, {'Ok_': {}}]],
    ],
    'partialMatchStub': [
        [[{}, {'fn.clearStubs_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.clearCalls_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1, 'str!': 'a'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.createStub_': {'stub': {'fn.test': {'value!': {'int!': 1}}, '->': {'Ok_': {'value!': {'bool!': True}}}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.test': {}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 0}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1}}}], [{}, {'Ok_': {'value!': {'bool!': True}}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1, 'str!': 'a'}}}], [{}, {'Ok_': {'value!': {'bool!': True}}}]],
    ],
    'multiplePartialMatchStub': [
        [[{}, {'fn.clearStubs_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.clearCalls_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1, 'str!': 'a'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 0, 'str!': 'a'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1, 'str!': 'b'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'bool!': False, 'int!': 1, 'str!': 'a'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.createStub_': {'stub': {'fn.test': {'value!': {'int!': 1}}, '->': {'Ok_': {'value!': {'bool!': True}}}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.createStub_': {'stub': {'fn.test': {'value!': {'str!': 'a'}}, '->': {'Ok_': {'value!': {'bool!': False}}}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.createStub_': {'stub': {'fn.example': {}, '->': {'Ok_': {}}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.test': {}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 0}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1}}}], [{}, {'Ok_': {'value!': {'bool!': True}}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1, 'str!': 'a'}}}], [{}, {'Ok_': {'value!': {'bool!': False}}}]],
        [[{}, {'fn.test': {'value!': {'int!': 0, 'str!': 'a'}}}], [{}, {'Ok_': {'value!': {'bool!': False}}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1, 'str!': 'b'}}}], [{}, {'Ok_': {'value!': {'bool!': True}}}]],
        [[{}, {'fn.test': {'value!': {'bool!': False, 'int!': 1, 'str!': 'a'}}}], [{}, {'Ok_': {'value!': {'bool!': False}}}]],
    ],
    'multiplePartialMatchStubCount': [
        [[{}, {'fn.clearStubs_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.clearCalls_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1, 'str!': 'a'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 0, 'str!': 'a'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1, 'str!': 'b'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'bool!': False, 'int!': 1, 'str!': 'a'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.createStub_': {'count!': 2, 'stub': {'fn.test': {'value!': {'int!': 1}}, '->': {'Ok_': {'value!': {'bool!': True}}}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.createStub_': {'count!': 1, 'stub': {'fn.test': {'value!': {'str!': 'a'}}, '->': {'Ok_': {'value!': {'bool!': False}}}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.createStub_': {'stub': {'fn.example': {}, '->': {'Ok_': {}}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.test': {}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 0}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1}}}], [{}, {'Ok_': {'value!': {'bool!': True}}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1, 'str!': 'a'}}}], [{}, {'Ok_': {'value!': {'bool!': False}}}]],
        [[{}, {'fn.test': {'value!': {'int!': 0, 'str!': 'a'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1, 'str!': 'b'}}}], [{}, {'Ok_': {'value!': {'bool!': True}}}]],
        [[{}, {'fn.test': {'value!': {'bool!': False, 'int!': 1, 'str!': 'a'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
    ],    
    'multipleNestedPartialMatchStub': [
        [[{}, {'fn.clearStubs_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.clearCalls_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1, 'str!': 'a'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 0, 'str!': 'a'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1, 'str!': 'b'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'bool!': False, 'int!': 1, 'str!': 'a'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.createStub_': {'stub': {'fn.test': {'value!': {'struct!': {'optional!': True}}}, '->': {'Ok_': {'value!': {'bool!': True}}}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.createStub_': {'stub': {'fn.test': {'value!': {'struct!': {'required': True}}}, '->': {'Ok_': {'value!': {'bool!': False}}}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.createStub_': {'stub': {'fn.example': {}, '->': {'Ok_': {}}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.test': {}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'struct!': {'required': False}}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'struct!': {'optional!': False, 'required': False}}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'struct!': {'optional!': True, 'required': True}}}}], [{}, {'Ok_': {'value!': {'bool!': False}}}]],
        [[{}, {'fn.test': {'value!': {'struct!': {'optional!': True, 'required': False}}}}], [{}, {'Ok_': {'value!': {'bool!': True}}}]],
        [[{}, {'fn.test': {'value!': {'struct!': {'required': True}}}}], [{}, {'Ok_': {'value!': {'bool!': False}}}]],
        [[{}, {'fn.test': {'value!': {'struct!': {'optional!': False, 'required': True}}}}], [{}, {'Ok_': {'value!': {'bool!': False}}}]],
        [[{}, {'fn.test': {'value!': {'struct!': {'optional!': True, 'required': False}, 'str!': 'b'}}}], [{}, {'Ok_': {'value!': {'bool!': True}}}]],
    ],
    'multipleNestedPartialMatchStubCount': [
        [[{}, {'fn.clearStubs_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.clearCalls_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1, 'str!': 'a'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 0, 'str!': 'a'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1, 'str!': 'b'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'bool!': False, 'int!': 1, 'str!': 'a'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.createStub_': {'count!': 1, 'stub': {'fn.test': {'value!': {'struct!': {'optional!': True}}}, '->': {'Ok_': {'value!': {'bool!': True}}}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.createStub_': {'count!': 2, 'stub': {'fn.test': {'value!': {'struct!': {'required': True}}}, '->': {'Ok_': {'value!': {'bool!': False}}}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.createStub_': {'stub': {'fn.example': {}, '->': {'Ok_': {}}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.test': {}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'struct!': {'required': False}}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'struct!': {'optional!': False, 'required': False}}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'struct!': {'optional!': True, 'required': True}}}}], [{}, {'Ok_': {'value!': {'bool!': False}}}]],
        [[{}, {'fn.test': {'value!': {'struct!': {'optional!': True, 'required': False}}}}], [{}, {'Ok_': {'value!': {'bool!': True}}}]],
        [[{}, {'fn.test': {'value!': {'struct!': {'required': True}}}}], [{}, {'Ok_': {'value!': {'bool!': False}}}]],
        [[{}, {'fn.test': {'value!': {'struct!': {'optional!': False, 'required': True}}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'struct!': {'optional!': True, 'required': False}, 'str!': 'b'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
    ],    
    'multipleReallyNestedPartialMatchStub': [
        [[{}, {'fn.clearStubs_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.clearCalls_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1, 'str!': 'a'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 0, 'str!': 'a'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1, 'str!': 'b'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'bool!': False, 'int!': 1, 'str!': 'a'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.createStub_': {'stub': {'fn.test': {'value!': {'arrStruct!': [{'optional!': True}]}}, '->': {'Ok_': {'value!': {'bool!': True}}}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.createStub_': {'stub': {'fn.test': {'value!': {'arrStruct!': [{'required': True}]}}, '->': {'Ok_': {'value!': {'bool!': False}}}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.createStub_': {'stub': {'fn.example': {}, '->': {'Ok_': {}}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.test': {}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'arrStruct!': [{'required': False}, {'optional!': False, 'required': False}]}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'arrStruct!': [{'required': False}, {'optional!': True, 'required': True}]}}}], [{}, {'Ok_': {'value!': {'bool!': False}}}]],
        [[{}, {'fn.test': {'value!': {'arrStruct!': [{'required': False}, {'optional!': True, 'required': False}]}}}], [{}, {'Ok_': {'value!': {'bool!': True}}}]],
        [[{}, {'fn.test': {'value!': {'arrStruct!': [{'required': False}, {'optional!': False, 'required': True}]}}}], [{}, {'Ok_': {'value!': {'bool!': False}}}]],
        [[{}, {'fn.test': {'value!': {'arrStruct!': [{'required': False}, {'optional!': True, 'required': False}], 'str!': 'b'}}}], [{}, {'Ok_': {'value!': {'bool!': True}}}]],
    ],
    'multipleReallyNestedPartialMatchStubCount': [
        [[{}, {'fn.clearStubs_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.clearCalls_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1, 'str!': 'a'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 0, 'str!': 'a'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1, 'str!': 'b'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'bool!': False, 'int!': 1, 'str!': 'a'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.createStub_': {'count!': 1, 'stub': {'fn.test': {'value!': {'arrStruct!': [{'optional!': True}]}}, '->': {'Ok_': {'value!': {'bool!': True}}}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.createStub_': {'count!': 1, 'stub': {'fn.test': {'value!': {'arrStruct!': [{'required': True}]}}, '->': {'Ok_': {'value!': {'bool!': False}}}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.createStub_': {'stub': {'fn.example': {}, '->': {'Ok_': {}}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.test': {}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'arrStruct!': [{'required': False}, {'optional!': False, 'required': False}]}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'arrStruct!': [{'required': False}, {'optional!': True, 'required': True}]}}}], [{}, {'Ok_': {'value!': {'bool!': False}}}]],
        [[{}, {'fn.test': {'value!': {'arrStruct!': [{'required': False}, {'optional!': True, 'required': False}]}}}], [{}, {'Ok_': {'value!': {'bool!': True}}}]],
        [[{}, {'fn.test': {'value!': {'arrStruct!': [{'required': False}, {'optional!': False, 'required': True}]}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'arrStruct!': [{'required': False}, {'optional!': True, 'required': False}], 'str!': 'b'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
    ],    
    'strictMatchStub': [
        [[{}, {'fn.clearStubs_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.clearCalls_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.createStub_': {'stub': {'fn.test': {'value!': {'int!': 1}}, '->': {'Ok_': {'value!': {'bool!': True}}}}, 'strictMatch!': True}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.test': {}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 0}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1}}}], [{}, {'Ok_': {'value!': {'bool!': True}}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1, 'str!': 'a'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
    ],
    'multipleStrictMatchStub': [
        [[{}, {'fn.clearStubs_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.clearCalls_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'str!': 'a'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.createStub_': {'stub': {'fn.test': {'value!': {'int!': 1}}, '->': {'Ok_': {'value!': {'bool!': True}}}}, 'strictMatch!': True}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.createStub_': {'stub': {'fn.test': {'value!': {'str!': 'a'}}, '->': {'Ok_': {'value!': {'bool!': False}}}}, 'strictMatch!': True}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.test': {}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 0}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1}}}], [{}, {'Ok_': {'value!': {'bool!': True}}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1, 'str!': 'a'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'str!': 'a'}}}], [{}, {'Ok_': {'value!': {'bool!': False}}}]],
        [[{}, {'fn.test': {'value!': {'int!': 0, 'str!': 'a'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1, 'str!': 'b'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'bool!': False, 'int!': 1, 'str!': 'a'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
    ],
    'multipleStrictMatchStubCount': [
        [[{}, {'fn.clearStubs_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.clearCalls_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'str!': 'a'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.createStub_': {'count!': 1, 'stub': {'fn.test': {'value!': {'int!': 1}}, '->': {'Ok_': {'value!': {'bool!': True}}}}, 'strictMatch!': True}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.createStub_': {'count!': 1, 'stub': {'fn.test': {'value!': {'str!': 'a'}}, '->': {'Ok_': {'value!': {'bool!': False}}}}, 'strictMatch!': True}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.test': {}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 0}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1}}}], [{}, {'Ok_': {'value!': {'bool!': True}}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1, 'str!': 'a'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'str!': 'a'}}}], [{}, {'Ok_': {'value!': {'bool!': False}}}]],
        [[{}, {'fn.test': {'value!': {'str!': 'a'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 0, 'str!': 'a'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1, 'str!': 'b'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'bool!': False, 'int!': 1, 'str!': 'a'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
    ],    
    'mixedPartialStrictMatchStub': [
        [[{}, {'fn.clearStubs_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.clearCalls_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1, 'str!': 'a'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1, 'str!': 'b'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'bool!': False, 'int!': 1, 'str!': 'a'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.createStub_': {'stub': {'fn.test': {'value!': {'int!': 1}}, '->': {'Ok_': {'value!': {'bool!': True}}}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.createStub_': {'stub': {'fn.test': {'value!': {'int!': 1, 'str!': 'a'}}, '->': {'Ok_': {'value!': {'bool!': False}}}}, 'strictMatch!': True}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.test': {}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 0}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1}}}], [{}, {'Ok_': {'value!': {'bool!': True}}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1, 'str!': 'a'}}}], [{}, {'Ok_': {'value!': {'bool!': False}}}]],
        [[{}, {'fn.test': {'value!': {'int!': 0, 'str!': 'a'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1, 'str!': 'b'}}}], [{}, {'Ok_': {'value!': {'bool!': True}}}]],
        [[{}, {'fn.test': {'value!': {'bool!': False, 'int!': 1, 'str!': 'a'}}}], [{}, {'Ok_': {'value!': {'bool!': True}}}]],
    ],
    'mixedStrictPartialMatchStub': [
        [[{}, {'fn.clearStubs_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.clearCalls_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1, 'str!': 'a'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1, 'str!': 'b'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'bool!': False, 'int!': 1, 'str!': 'a'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.createStub_': {'stub': {'fn.test': {'value!': {'int!': 1, 'str!': 'a'}}, '->': {'Ok_': {'value!': {'bool!': False}}}}, 'strictMatch!': True}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.createStub_': {'stub': {'fn.test': {'value!': {'int!': 1}}, '->': {'Ok_': {'value!': {'bool!': True}}}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.test': {}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 0}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1}}}], [{}, {'Ok_': {'value!': {'bool!': True}}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1, 'str!': 'a'}}}], [{}, {'Ok_': {'value!': {'bool!': True}}}]],
        [[{}, {'fn.test': {'value!': {'int!': 0, 'str!': 'a'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1, 'str!': 'b'}}}], [{}, {'Ok_': {'value!': {'bool!': True}}}]],
        [[{}, {'fn.test': {'value!': {'bool!': False, 'int!': 1, 'str!': 'a'}}}], [{}, {'Ok_': {'value!': {'bool!': True}}}]],
    ],
    'clearStubs': [
        [[{}, {'fn.clearStubs_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.clearCalls_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.test': {}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.createStub_': {'stub': {'fn.test': {}, '->': {'Ok_': {}}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.test': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.clearStubs_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.test': {}}], [{}, {'ErrorNoMatchingStub_': {}}]],
    ],
    'generation': [
        [[{}, {'fn.setRandomSeed_': {'seed': 0}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.clearStubs_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.clearCalls_': {}}], [{}, {'Ok_': {}}]],
        [[{'@gen_': True}, {'fn.test': {}}], [{'@base64_': {'Ok_': {'value!': {'arrNullBytes!': {'*': True}, 'bytes!': True, 'objBytes!': {'*': True}}}}}, {'Ok_': {'value!': {'any!': True, 'arrBytes!': [], 'arrInt!': [1326349322], 'arrNullAny!': [772162768, None], 'arrNullBool!': [None], 'arrNullBytes!': ['IFcS0w=='], 'arrNullStruct!': [None], 'arrNullUnion!': [{'One': {}}], 'arrNum!': [0.06085497655945596], 'bool!': True, 'bytes!': 'OrDL4Q==', 'fn!': {'fn.example': {'required': True}}, 'int!': 208181445, 'nullAny!': 'nu', 'nullArr!': None, 'nullFn!': {'fn.example': {'required': False}}, 'nullNum!': 0.05951685833722207, 'nullObj!': {'eta': 78455863, 'delta': False}, 'nullStr!': 'lambda', 'obj!': {'eta': False}, 'objAny!': {}, 'objBytes!': {'lambda': 'Ey4Ybg==', 'chi': 'SpSZwg=='}, 'objFn!': {}, 'objNullArr!': {'epsilon': None}, 'objNullBool!': {'omicron': False}, 'objNullSel!': {'theta': {}, 'chi': None}, 'objNullStr!': {'nu': 'tau', 'omicron': None}, 'objNullStruct!': {}, 'objNullUnion!': {}, 'objObj!': {}, 'objStr!': {'tau': 'gamma', 'iota': 'kappa'}, 'sel!': {'->': {'Ok_': ['value!']}, 'struct.ExStruct': ['optional!', 'required']}, 'str!': 'pi', 'union!': {'One': {}}}}}]],
        [[{'@gen_': True}, {'fn.test': {}}], [{'@base64_': {'Ok_': {'value!': {'arrBytes!': {'*': True}, 'bytes!': True}}}}, {'Ok_': {'value!': {'any!': False, 'arr!': [1784432766], 'arrAny!': [], 'arrBool!': [False, False], 'arrBytes!': ['MFQO4A==', 'aMjUQQ=='], 'arrFn!': [{'fn.example': {'required': True}}], 'arrInt!': [394795501], 'arrNullAny!': [152867781, None], 'arrNullArr!': [[]], 'arrNullBool!': [], 'arrNullBytes!': [None, None], 'arrNullObj!': [], 'arrNullSel!': [], 'arrNullStruct!': [], 'arrNullUnion!': [{'Two': {'required': False}}], 'arrObj!': [{'nu': 1201727870}, {}], 'arrSel!': [{'struct.ExStruct': ['optional!', 'optional2!', 'required']}, {'->': {'Ok_': []}, 'struct.ExStruct': ['optional!', 'optional2!'], 'union.ExUnion': {'Two': []}}], 'arrStr!': [], 'arrStruct!': [{'optional2!': 1951329397, 'required': False}], 'bytes!': 'ZDZFxA==', 'fn!': {'fn.example': {'required': True}}, 'nullAny!': 'xi', 'nullArr!': None, 'nullBool!': None, 'nullInt!': 1504447422, 'nullNum!': None, 'nullSel!': None, 'nullStr!': 'delta', 'obj!': {'omicron': 18286848}, 'objArr!': {}, 'objBool!': {'gamma': False, 'tau': False}, 'objInt!': {'delta': 1635388412, 'chi': 1455442554}, 'objNullAny!': {'xi': None}, 'objNullBool!': {'nu': None, 'psi': True}, 'objNullBytes!': {}, 'objNullFn!': {'upsilon': None}, 'objNullNum!': {'delta': 0.368119773160722}, 'objNullObj!': {}, 'objNullSel!': {}, 'objNullStr!': {}, 'objUnion!': {}, 'sel!': {'struct.ExStruct': ['optional!', 'required'], 'union.ExUnion': {'Two': ['optional!']}}, 'str!': 'delta', 'struct!': {'optional2!': 880799723, 'required': False}}}}]],
        [[{'@gen_': True}, {'fn.test': {}}], [{}, {'Ok_': {}}]],
        [[{'@gen_': True}, {'fn.test': {}}], [{}, {'Ok_': {}}]],
        [[{'@gen_': True}, {'fn.test': {}}], [{'@base64_': {'Ok_': {'value!': {'objBytes!': {'*': True}}}}}, {'Ok_': {'value!': {'arrArr!': [[True], [False]], 'arrBool!': [True, False], 'arrBytes!': [], 'arrFn!': [{'fn.example': {'required': False}}, {'fn.example': {'optional!': False, 'required': False}}], 'arrNullAny!': [], 'arrNullArr!': [None, [False]], 'arrNullBool!': [None, False], 'arrNullInt!': [None], 'arrNullStruct!': [], 'arrNum!': [0.699326371168404, 0.4301625166228798], 'arrObj!': [{'pi': False}, {}], 'arrSel!': [], 'arrStr!': ['xi', 'delta'], 'arrStruct!': [{'optional2!': 1289857434, 'required': False}], 'arrUnion!': [{'One': {}}], 'fn!': {'fn.example': {'required': False}}, 'int!': 184477553, 'nullAny!': None, 'nullArr!': None, 'nullBytes!': None, 'nullFn!': None, 'nullInt!': None, 'nullStruct!': {'required': True}, 'num!': 0.9223105371567936, 'obj!': {}, 'objAny!': {'eta': 'gamma', 'omega': False}, 'objArr!': {'delta': [], 'theta': [1020945164]}, 'objBool!': {'kappa': False}, 'objBytes!': {'phi': 'fvlCTg==', 'omicron': 'DRXaLg=='}, 'objFn!': {'pi': {'fn.example': {'optional!': False, 'required': True}}, 'chi': {'fn.example': {'required': False}}}, 'objNullBytes!': {}, 'objNullNum!': {}, 'objNullSel!': {'rho': None}, 'objNullStr!': {'alpha': None}, 'objNum!': {}, 'objObj!': {'epsilon': {'iota': False}}, 'objStr!': {'gamma': 'kappa'}, 'sel!': {}, 'str!': 'tau', 'struct!': {'optional!': True, 'optional2!': 186654781, 'required': False}}}}]],
        [[{'@gen_': True}, {'fn.test': {}}], [{'@base64_': {'Ok_': {'value!': {'bytes!': True, 'objBytes!': {'*': True}}}}}, {'Ok_': {'value!': {'arr!': [557845362], 'arrBool!': [True, True], 'arrInt!': [], 'arrNullAny!': [None, True], 'arrNullArr!': [None, ['tau']], 'arrNullFn!': [], 'arrNullInt!': [], 'arrNullNum!': [None, None], 'arrNullObj!': [], 'arrNullSel!': [], 'arrNullStr!': ['sigma', 'omega'], 'arrNullUnion!': [], 'arrNum!': [0.4465337495536235], 'arrObj!': [{'chi': False, 'sigma': 'omega'}], 'arrSel!': [], 'arrStruct!': [], 'arrUnion!': [], 'bytes!': 'FnekXw==', 'fn!': {'fn.example': {'required': True}}, 'int!': 1702171516, 'nullBool!': None, 'nullInt!': 1309453618, 'nullNum!': None, 'nullObj!': {'epsilon': 1298845271}, 'nullSel!': {'union.ExUnion': {'Two': ['optional!', 'required']}}, 'nullStruct!': None, 'nullUnion!': {'Two': {'required': True}}, 'num!': 0.9975205790239948, 'obj!': {'beta': 'phi'}, 'objBytes!': {'sigma': 'EPCDJA=='}, 'objInt!': {}, 'objNullAny!': {'kappa': None}, 'objNullArr!': {'zeta': [1879195680]}, 'objNullBool!': {'rho': True}, 'objNullBytes!': {}, 'objNullNum!': {}, 'objNullSel!': {'upsilon': {'struct.ExStruct': ['optional!', 'required'], 'struct.Value': ['arrAny!', 'arrBool!', 'arrFn!', 'arrNullArr!', 'arrNullBool!', 'arrNullBytes!', 'arrNullFn!', 'arrNullInt!', 'arrNullNum!', 'arrNullSel!', 'arrObj!', 'arrSel!', 'arrUnion!', 'bytes!', 'fn!', 'nullBool!', 'nullInt!', 'nullSel!', 'nullStruct!', 'nullUnion!', 'num!', 'obj!', 'objAny!', 'objBool!', 'objFn!', 'objNullAny!', 'objNullArr!', 'objNullFn!', 'objNullInt!', 'objNullNum!', 'objNum!', 'objObj!', 'objStr!', 'objUnion!', 'union!']}}, 'objNullStruct!': {'theta': {'optional!': True, 'required': False}, 'omicron': None}, 'objNum!': {'iota': 0.8136852718022117}, 'objObj!': {'alpha': {}, 'rho': {'theta': True, 'iota': 672361291}}, 'objStr!': {'alpha': 'chi'}, 'str!': 'sigma'}}}]],
        [[{'@gen_': True}, {'fn.test': {}}], [{'@base64_': {'Ok_': {'value!': {'arrBytes!': {'*': True}, 'bytes!': True}}}}, {'Ok_': {'value!': {'arrAny!': [1559158978, True], 'arrArr!': [['phi', 296840221]], 'arrBool!': [], 'arrBytes!': ['bLb/dw=='], 'arrFn!': [{'fn.example': {'optional!': False, 'required': True}}], 'arrNullArr!': [[True]], 'arrNullFn!': [{'fn.example': {'optional!': True, 'required': True}}], 'arrNullNum!': [0.733073020695277, 0.696700194709329], 'arrNullStr!': ['upsilon', 'alpha'], 'arrNullStruct!': [{'optional2!': 644574243, 'required': True}, {'optional2!': 630762051, 'required': False}], 'arrStr!': ['alpha'], 'arrStruct!': [], 'bool!': False, 'bytes!': 'Ic35jw==', 'int!': 220248838, 'nullBool!': False, 'nullFn!': None, 'nullInt!': None, 'nullSel!': {'struct.ExStruct': ['optional!', 'optional2!'], 'struct.Value': ['any!', 'arrAny!', 'arrArr!', 'arrBytes!', 'arrNullBool!', 'arrNullFn!', 'arrNullInt!', 'arrNullNum!', 'arrNullObj!', 'arrNullSel!', 'arrNullStr!', 'arrNullStruct!', 'arrNullUnion!', 'arrObj!', 'arrSel!', 'arrStruct!', 'arrUnion!', 'bytes!', 'fn!', 'nullArr!', 'nullBool!', 'nullBytes!', 'nullInt!', 'nullNum!', 'nullObj!', 'nullSel!', 'nullUnion!', 'objArr!', 'objBool!', 'objBytes!', 'objInt!', 'objNullAny!', 'objNullArr!', 'objNullBytes!', 'objNullFn!', 'objNullInt!', 'objNullObj!', 'objNullSel!', 'objNullStruct!', 'objNum!', 'objObj!', 'objSel!', 'objStr!', 'sel!', 'union!']}, 'nullStr!': 'epsilon', 'nullUnion!': {'One': {}}, 'objAny!': {}, 'objBool!': {'kappa': True}, 'objBytes!': {}, 'objFn!': {}, 'objInt!': {}, 'objNullAny!': {'zeta': 'tau'}, 'objNullArr!': {'omega': ['tau'], 'nu': []}, 'objNullBool!': {'tau': None}, 'objNullBytes!': {}, 'objNullFn!': {}, 'objNullInt!': {}, 'objNullNum!': {'epsilon': 0.6181041917847955, 'xi': None}, 'objNullSel!': {'alpha': {'struct.Value': ['arrArr!', 'arrBytes!', 'arrInt!', 'arrNullAny!', 'arrNullArr!', 'arrNullInt!', 'arrNullNum!', 'arrNullObj!', 'arrNullSel!', 'arrNullStr!', 'arrNullUnion!', 'arrSel!', 'arrStruct!', 'arrUnion!', 'fn!', 'int!', 'nullInt!', 'nullNum!', 'nullSel!', 'num!', 'obj!', 'objArr!', 'objBool!', 'objBytes!', 'objFn!', 'objInt!', 'objNullArr!', 'objNullBytes!', 'objNullFn!', 'objNullNum!', 'objNullSel!', 'objNullStr!', 'objNullStruct!', 'objStr!', 'objStruct!', 'objUnion!', 'union!']}}, 'objNullStr!': {'pi': 'alpha', 'phi': None}, 'objNullStruct!': {}, 'objNullUnion!': {'psi': {'Two': {'optional!': False, 'required': False}}, 'lambda': {'Two': {'optional!': False, 'required': False}}}, 'objObj!': {'sigma': {'sigma': False}}, 'objStr!': {'upsilon': 'gamma', 'nu': 'tau'}, 'objUnion!': {}, 'sel!': {'struct.ExStruct': ['optional!', 'required'], 'union.ExUnion': {'Two': []}}}}}]],
        [[{'@gen_': True}, {'fn.test': {}}], [{}, {'Ok_': {}}]],
    ],
    'emptyPartialMatchVerify': [
        [[{}, {'fn.clearStubs_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.clearCalls_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.createStub_': {'stub': {'fn.test': {}, '->': {'Ok_': {}}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {}}}}], [{}, {'ErrorVerificationFailure': {'reason': {'TooFewMatchingCalls': {'allCalls': [], 'found': 0, 'wanted': {'AtLeast': {'times': 1}}}}}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {}}, 'count!': {'Exact': {'times': 1}}}}], [{}, {'ErrorVerificationFailure': {'reason': {'TooFewMatchingCalls': {'allCalls': [], 'found': 0, 'wanted': {'Exact': {'times': 1}}}}}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {}}, 'count!': {'AtLeast': {'times': 1}}}}], [{}, {'ErrorVerificationFailure': {'reason': {'TooFewMatchingCalls': {'allCalls': [], 'wanted': {'AtLeast': {'times': 1}}, 'found': 0}}}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {}}, 'count!': {'AtMost': {'times': 0}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.test': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.verifyNoMoreInteractions_': {}}], [{}, {'ErrorVerificationFailure': {'additionalUnverifiedCalls': [{'fn.test': {}}]}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.verifyNoMoreInteractions_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {}}, 'count!': {'Exact': {'times': 1}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {}}, 'count!': {'AtLeast': {'times': 1}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {}}, 'count!': {'AtLeast': {'times': 2}}}}], [{}, {'ErrorVerificationFailure': {'reason': {'TooFewMatchingCalls': {'allCalls': [{'fn.test': {}}], 'found': 1, 'wanted': {'AtLeast': {'times': 2}}}}}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {}}, 'count!': {'AtMost': {'times': 1}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {}}, 'count!': {'AtMost': {'times': 0}}}}], [{}, {'ErrorVerificationFailure': {'reason': {'TooManyMatchingCalls': {'wanted': {'AtMost': {'times': 0}}, 'allCalls': [{'fn.test': {}}], 'found': 1}}}}]],
    ],
    'partialMatchVerify': [
        [[{}, {'fn.clearStubs_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.clearCalls_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.createStub_': {'stub': {'fn.test': {'value!': {'int!': 0}}, '->': {'Ok_': {'value!': {'bool!': True}}}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {'value!': {'int!': 0}}}}}], [{}, {'ErrorVerificationFailure': {'reason': {'TooFewMatchingCalls': {'found': 0, 'allCalls': [], 'wanted': {'AtLeast': {'times': 1}}}}}}]],
        [[{}, {'fn.test': {'value!': {'int!': 0, 'str!': 'a'}}}], [{}, {'Ok_': {'value!': {'bool!': True}}}]],
        [[{}, {'fn.verifyNoMoreInteractions_': {}}], [{}, {'ErrorVerificationFailure': {'additionalUnverifiedCalls': [{'fn.test': {'value!': {'int!': 0, 'str!': 'a'}}}]}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {'value!': {'int!': 0}}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.verifyNoMoreInteractions_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {'value!': {'int!': 0}}}, 'count!': {'Exact': {'times': 1}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {'value!': {'int!': 0}}}, 'count!': {'AtLeast': {'times': 1}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {'value!': {'int!': 0}}}, 'count!': {'AtMost': {'times': 0}}}}], [{}, {'ErrorVerificationFailure': {'reason': {'TooManyMatchingCalls': {'wanted': {'AtMost': {'times': 0}}, 'allCalls': [{'fn.test': {'value!': {'int!': 0, 'str!': 'a'}}}], 'found': 1}}}}]],
    ],
    'multiplePartialMatchVerify': [
        [[{}, {'fn.clearStubs_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.clearCalls_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.createStub_': {'stub': {'fn.test': {}, '->': {'Ok_': {}}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {'value!': {'int!': 0}}}}}], [{}, {'ErrorVerificationFailure': {'reason': {'TooFewMatchingCalls': {'found': 0, 'allCalls': [], 'wanted': {'AtLeast': {'times': 1}}}}}}]],
        [[{}, {'fn.test': {'value!': {'int!': 0, 'bool!': True}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 0, 'str!': 'a'}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.verifyNoMoreInteractions_': {}}], [{}, {'ErrorVerificationFailure': {'additionalUnverifiedCalls': [{'fn.test': {'value!': {'int!': 0, 'bool!': True}}}, {'fn.test': {'value!': {'int!': 0, 'str!': 'a'}}}, {'fn.test': {'value!': {'int!': 1}}}]}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {'value!': {'int!': 0}}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.verifyNoMoreInteractions_': {}}], [{}, {'ErrorVerificationFailure': {'additionalUnverifiedCalls': [{'fn.test': {'value!': {'int!': 1}}}]}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.verifyNoMoreInteractions_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {'value!': {'int!': 0}}}, 'count!': {'Exact': {'times': 1}}}}], [{}, {'ErrorVerificationFailure': {'reason': {'TooManyMatchingCalls': {'wanted': {'Exact': {'times': 1}}, 'allCalls': [{'fn.test': {'value!': {'int!': 0, 'bool!': True}}}, {'fn.test': {'value!': {'int!': 0, 'str!': 'a'}}}, {'fn.test': {'value!': {'int!': 1}}}], 'found': 2}}}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {'value!': {'int!': 0}}}, 'count!': {'Exact': {'times': 2}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {'value!': {'int!': 0}}}, 'count!': {'Exact': {'times': 3}}}}], [{}, {'ErrorVerificationFailure': {'reason': {'TooFewMatchingCalls': {'wanted': {'Exact': {'times': 3}}, 'allCalls': [{'fn.test': {'value!': {'int!': 0, 'bool!': True}}}, {'fn.test': {'value!': {'int!': 0, 'str!': 'a'}}}, {'fn.test': {'value!': {'int!': 1}}}], 'found': 2}}}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {'value!': {'int!': 0}}}, 'count!': {'AtLeast': {'times': 1}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {'value!': {'int!': 0}}}, 'count!': {'AtMost': {'times': 1}}}}], [{}, {'ErrorVerificationFailure': {'reason': {'TooManyMatchingCalls': {'wanted': {'AtMost': {'times': 1}}, 'allCalls': [{'fn.test': {'value!': {'int!': 0, 'bool!': True}}}, {'fn.test': {'value!': {'int!': 0, 'str!': 'a'}}}, {'fn.test': {'value!': {'int!': 1}}}], 'found': 2}}}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {'value!': {'int!': 0}}}, 'count!': {'AtMost': {'times': 2}}}}], [{}, {'Ok_': {}}]],
    ],
    'strictMatchVerify': [
        [[{}, {'fn.clearStubs_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.clearCalls_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.createStub_': {'stub': {'fn.test': {}, '->': {'Ok_': {}}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {'value!': {'int!': 0}}}, 'strictMatch!': True}}], [{}, {'ErrorVerificationFailure': {'reason': {'TooFewMatchingCalls': {'found': 0, 'allCalls': [], 'wanted': {'AtLeast': {'times': 1}}}}}}]],
        [[{}, {'fn.test': {'value!': {'int!': 0}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.verifyNoMoreInteractions_': {}}], [{}, {'ErrorVerificationFailure': {'additionalUnverifiedCalls': [{'fn.test': {'value!': {'int!': 0}}}]}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {'value!': {'int!': 0}}}, 'strictMatch!': True}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.verifyNoMoreInteractions_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {'value!': {'int!': 1}}}, 'strictMatch!': True}}], [{}, {'ErrorVerificationFailure': {'reason': {'TooFewMatchingCalls': {'found': 0, 'allCalls': [{'fn.test': {'value!': {'int!': 0}}}], 'wanted': {'AtLeast': {'times': 1}}}}}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {'value!': {'int!': 0, 'str!': 'a'}}}, 'strictMatch!': True}}], [{}, {'ErrorVerificationFailure': {'reason': {'TooFewMatchingCalls': {'found': 0, 'allCalls': [{'fn.test': {'value!': {'int!': 0}}}], 'wanted': {'AtLeast': {'times': 1}}}}}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {'value!': {'int!': 0}}}, 'strictMatch!': True, 'count!': {'Exact': {'times': 0}}}}], [{}, {'ErrorVerificationFailure': {'reason': {'TooManyMatchingCalls': {'wanted': {'Exact': {'times': 0}}, 'allCalls': [{'fn.test': {'value!': {'int!': 0}}}], 'found': 1}}}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {'value!': {'int!': 0}}}, 'strictMatch!': True, 'count!': {'Exact': {'times': 2}}}}], [{}, {'ErrorVerificationFailure': {'reason': {'TooFewMatchingCalls': {'wanted': {'Exact': {'times': 2}}, 'allCalls': [{'fn.test': {'value!': {'int!': 0}}}], 'found': 1}}}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {'value!': {'int!': 0}}}, 'strictMatch!': True, 'count!': {'Exact': {'times': 1}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {'value!': {'int!': 0}}}, 'strictMatch!': True, 'count!': {'AtLeast': {'times': 2}}}}], [{}, {'ErrorVerificationFailure': {'reason': {'TooFewMatchingCalls': {'wanted': {'AtLeast': {'times': 2}}, 'allCalls': [{'fn.test': {'value!': {'int!': 0}}}], 'found': 1}}}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {'value!': {'int!': 0}}}, 'strictMatch!': True, 'count!': {'AtLeast': {'times': 1}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {'value!': {'int!': 0}}}, 'strictMatch!': True, 'count!': {'AtMost': {'times': 1}}}}], [{}, {'Ok_': {}}]],
    ],
    'multipleStrictMatchVerify': [
        [[{}, {'fn.clearStubs_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.clearCalls_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.createStub_': {'stub': {'fn.test': {}, '->': {'Ok_': {}}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {'value!': {'int!': 0}}}, 'strictMatch!': True}}], [{}, {'ErrorVerificationFailure': {'reason': {'TooFewMatchingCalls': {'found': 0, 'allCalls': [], 'wanted': {'AtLeast': {'times': 1}}}}}}]],
        [[{}, {'fn.test': {'value!': {'int!': 0}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 0, 'str!': 'a'}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.verifyNoMoreInteractions_': {}}], [{}, {'ErrorVerificationFailure': {'additionalUnverifiedCalls': [{'fn.test': {'value!': {'int!': 0}}}, {'fn.test': {'value!': {'int!': 0, 'str!': 'a'}}}]}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {'value!': {'int!': 0}}}, 'strictMatch!': True}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.verifyNoMoreInteractions_': {}}], [{}, {'ErrorVerificationFailure': {'additionalUnverifiedCalls': [{'fn.test': {'value!': {'int!': 0, 'str!': 'a'}}}]}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.verifyNoMoreInteractions_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {'value!': {'int!': 1}}}, 'strictMatch!': True}}], [{}, {'ErrorVerificationFailure': {'reason': {'TooFewMatchingCalls': {'found': 0, 'allCalls': [{'fn.test': {'value!': {'int!': 0}}}, {'fn.test': {'value!': {'int!': 0, 'str!': 'a'}}}], 'wanted': {'AtLeast': {'times': 1}}}}}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {'value!': {'int!': 0, 'str!': 'b'}}}, 'strictMatch!': True}}], [{}, {'ErrorVerificationFailure': {'reason': {'TooFewMatchingCalls': {'found': 0, 'allCalls': [{'fn.test': {'value!': {'int!': 0}}}, {'fn.test': {'value!': {'int!': 0, 'str!': 'a'}}}], 'wanted': {'AtLeast': {'times': 1}}}}}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {'value!': {'int!': 0}}}, 'strictMatch!': True, 'count!': {'Exact': {'times': 0}}}}], [{}, {'ErrorVerificationFailure': {'reason': {'TooManyMatchingCalls': {'wanted': {'Exact': {'times': 0}}, 'allCalls': [{'fn.test': {'value!': {'int!': 0}}}, {'fn.test': {'value!': {'int!': 0, 'str!': 'a'}}}], 'found': 1}}}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {'value!': {'int!': 0}}}, 'strictMatch!': True, 'count!': {'Exact': {'times': 2}}}}], [{}, {'ErrorVerificationFailure': {'reason': {'TooFewMatchingCalls': {'wanted': {'Exact': {'times': 2}}, 'allCalls': [{'fn.test': {'value!': {'int!': 0}}}, {'fn.test': {'value!': {'int!': 0, 'str!': 'a'}}}], 'found': 1}}}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {'value!': {'int!': 0}}}, 'strictMatch!': True, 'count!': {'Exact': {'times': 1}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {'value!': {'int!': 0}}}, 'strictMatch!': True, 'count!': {'AtLeast': {'times': 2}}}}], [{}, {'ErrorVerificationFailure': {'reason': {'TooFewMatchingCalls': {'wanted': {'AtLeast': {'times': 2}}, 'allCalls': [{'fn.test': {'value!': {'int!': 0}}}, {'fn.test': {'value!': {'int!': 0, 'str!': 'a'}}}], 'found': 1}}}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {'value!': {'int!': 0}}}, 'strictMatch!': True, 'count!': {'AtLeast': {'times': 1}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {'value!': {'int!': 0}}}, 'strictMatch!': True, 'count!': {'AtMost': {'times': 1}}}}], [{}, {'Ok_': {}}]],
    ],
    'multipleNestedPartialMatchVerify': [
        [[{}, {'fn.clearStubs_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.clearCalls_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.createStub_': {'stub': {'fn.test': {}, '->': {'Ok_': {}}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {'value!': {'int!': 0}}}}}], [{}, {'ErrorVerificationFailure': {'reason': {'TooFewMatchingCalls': {'found': 0, 'allCalls': [], 'wanted': {'AtLeast': {'times': 1}}}}}}]],
        [[{}, {'fn.test': {'value!': {'struct!': {'required': True}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.test': {'value!': {'struct!': {'required': True, 'optional!': True}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.verifyNoMoreInteractions_': {}}], [{}, {'ErrorVerificationFailure': {'additionalUnverifiedCalls': [{'fn.test': {'value!': {'struct!': {'required': True}}}}, {'fn.test': {'value!': {'struct!': {'required': True, 'optional!': True}}}}]}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {'value!': {'struct!': {'optional!': True}}}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.verifyNoMoreInteractions_': {}}], [{}, {'ErrorVerificationFailure': {'additionalUnverifiedCalls': [{'fn.test': {'value!': {'struct!': {'required': True}}}}]}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.verifyNoMoreInteractions_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {'value!': {'struct!': {'optional!': True}}}}, 'count!': {'Exact': {'times': 1}}}}], [{}, {'Ok_': {}}]],
    ],
    'multipleReallyNestedPartialMatchVerify': [
        [[{}, {'fn.clearStubs_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.clearCalls_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.createStub_': {'stub': {'fn.test': {}, '->': {'Ok_': {}}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {'value!': {'int!': 0}}}}}], [{}, {'ErrorVerificationFailure': {'reason': {'TooFewMatchingCalls': {'found': 0, 'allCalls': [], 'wanted': {'AtLeast': {'times': 1}}}}}}]],
        [[{}, {'fn.test': {'value!': {'arrStruct!': [{'required': False}, {'required': True}]}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.test': {'value!': {'arrStruct!': [{'required': False}, {'required': True, 'optional!': True}]}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {'value!': {'arrStruct!': [{'optional!': True}]}}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.verifyNoMoreInteractions_': {}}], [{}, {'ErrorVerificationFailure': {'additionalUnverifiedCalls': [{'fn.test': {'value!': {'arrStruct!': [{'required': False}, {'required': True}]}}}]}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.verifyNoMoreInteractions_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {'value!': {'arrStruct!': [{'optional!': True}]}}}, 'count!': {'Exact': {'times': 1}}}}], [{}, {'Ok_': {}}]],
    ],
    'clearCalls': [
        [[{}, {'fn.clearStubs_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.clearCalls_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.createStub_': {'stub': {'fn.test': {}, '->': {'Ok_': {}}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {}}}}], [{}, {'ErrorVerificationFailure': {'reason': {'TooFewMatchingCalls': {'found': 0, 'allCalls': [], 'wanted': {'AtLeast': {'times': 1}}}}}}]],
        [[{}, {'fn.test': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.clearCalls_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {}}}}], [{}, {'ErrorVerificationFailure': {'reason': {'TooFewMatchingCalls': {'found': 0, 'allCalls': [], 'wanted': {'AtLeast': {'times': 1}}}}}}]],
    ],
    'resultSuppliesMissingRequiredFields': [
        [[{}, {'fn.setRandomSeed_': {'seed': 0}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.clearStubs_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.clearCalls_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.test': {}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.createStub_': {'stub': {'fn.test': {}, '->': {'Ok_': {'value!': {'bool!': True, 'struct!': {'optional!': True}}}}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.test': {}}], [{}, {'Ok_': {'value!': {'bool!': True, 'struct!': {'optional!': True, 'required': False}}}}]],
    ],
    'resultWithStartingValue': [
        [[{}, {'fn.clearStubs_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.clearCalls_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.test': {}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.createStub_': {'stub': {'fn.test': {}, '->': {'Ok_': {'value!': {'bool!': False, 'int!': 0, 'num!': 0.1, 'str!': '', 'arrBool!': [False], 'objBool!': {'a': False}, 'struct!': {'required': False}, 'union!': {'Two': {'required': False}}, 'fn!': {'fn.example': {'required': False}}}}}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.test': {}}], [{}, {'Ok_': {'value!': {'bool!': False, 'int!': 0, 'num!': 0.1, 'str!': '', 'arrBool!': [False], 'objBool!': {'a': False}, 'struct!': {'required': False}, 'union!': {'Two': {'required': False}}, 'fn!': {'fn.example': {'required': False}}}}}]],
    ],
}
