cases = {
    'binary': [
        ['\x92\x81\xA4_bin\x91\xd2\x00\x00\x00\x00\x81\x00\x80', [{}, {'_errorParseFailure': {'reasons': ['IncompatibleBinaryEncoding']}}]],
        ['\x80', [{}, {'_errorParseFailure': {'reasons': ['InvalidJson']}}]],
        ['\x92\x81\xA4_bin\x91\xd2\xf1"1\xe0\x81\x08\x80','\x92\x81\xA4_bin\x91\xd2\xf1"1\xe0\x81\x0b\x80'],
        ['\x92\x81\xA4_bin\x91\xd2\xf1"1\xe0\x81\x7f\x80', [{}, {'_errorParseFailure': {'reasons': ['BinaryDecodeFailure']}}]],
        ['false', [{}, {'_errorParseFailure': {'reasons': ['MessageMustBeArrayWithTwoElements']}}]],
        #['1337', [{}, {'_errorParseFailure': {'reasons': ['MessageMustBeArrayWithTwoElements']}}]],
        ['""', [{}, {'_errorParseFailure': {'reasons': ['MessageMustBeArrayWithTwoElements']}}]],
        ['{}', [{}, {'_errorParseFailure': {'reasons': ['MessageMustBeArrayWithTwoElements']}}]],
        [[{}, {}], [{}, {'_errorParseFailure': {'reasons': ['BodyMustBeUnionType']}}]],
        [[False, {'fn._ping': {}}], [{}, {'_errorParseFailure': {'reasons': ['HeadersMustBeObject']}}]],
        [[0, {'fn._ping': {}}], [{}, {'_errorParseFailure': {'reasons': ['HeadersMustBeObject']}}]],
        [['', {'fn._ping': {}}], [{}, {'_errorParseFailure': {'reasons': ['HeadersMustBeObject']}}]],
        [[[], {'fn._ping': {}}], [{}, {'_errorParseFailure': {'reasons': ['HeadersMustBeObject']}}]],
        [[{}, False], [{}, {'_errorParseFailure': {'reasons': ['BodyMustBeObject']}}]],
        [[{}, 0], [{}, {'_errorParseFailure': {'reasons': ['BodyMustBeObject']}}]],
        [[{}, ''], [{}, {'_errorParseFailure': {'reasons': ['BodyMustBeObject']}}]],
        [[{}, []], [{}, {'_errorParseFailure': {'reasons': ['BodyMustBeObject']}}]],
        [[{'_bin': False}, {'fn._ping': {}}], [{}, {'_errorInvalidRequestHeaders': {'cases': [{'path': 'headers{_bin}', 'reason': {'TypeUnexpected': {'actual': {'Boolean': {}}, 'expected': {'Array': {}}}}}]}}]],
        [[{'_bin': 0}, {'fn._ping': {}}], [{}, {'_errorInvalidRequestHeaders': {'cases': [{'path': 'headers{_bin}', 'reason': {'TypeUnexpected': {'actual': {'Number': {}}, 'expected': {'Array': {}}}}}]}}]],
        [[{'_bin': ''}, {'fn._ping': {}}], [{}, {'_errorInvalidRequestHeaders': {'cases': [{'path': 'headers{_bin}', 'reason': {'TypeUnexpected': {'actual': {'String': {}}, 'expected': {'Array': {}}}}}]}}]],
        [[{'_bin': {}}, {'fn._ping': {}}], [{}, {'_errorInvalidRequestHeaders': {'cases': [{'path': 'headers{_bin}', 'reason': {'TypeUnexpected': {'actual': {'Object': {}}, 'expected': {'Array': {}}}}}]}}]],
        [[{'_bin': [False]}, {'fn._ping': {}}], [{}, {'_errorInvalidRequestHeaders': {'cases': [{'path': 'headers{_bin}', 'reason': {'TypeUnexpected': {'actual': {'Boolean': {}}, 'expected': {'Integer': {}}}}}]}}]],
        [[{'_bin': [0.1]}, {'fn._ping': {}}], [{}, {'_errorInvalidRequestHeaders': {'cases': [{'path': 'headers{_bin}', 'reason': {'TypeUnexpected': {'actual': {'Number': {}}, 'expected': {'Integer': {}}}}}]}}]],
        [[{'_bin': ['']}, {'fn._ping': {}}], [{}, {'_errorInvalidRequestHeaders': {'cases': [{'path': 'headers{_bin}', 'reason': {'TypeUnexpected': {'actual': {'String': {}}, 'expected': {'Integer': {}}}}}]}}]],
        [[{'_bin': [[]]}, {'fn._ping': {}}], [{}, {'_errorInvalidRequestHeaders': {'cases': [{'path': 'headers{_bin}', 'reason': {'TypeUnexpected': {'actual': {'Array': {}}, 'expected': {'Integer': {}}}}}]}}]],
        [[{'_bin': [{}]}, {'fn._ping': {}}], [{}, {'_errorInvalidRequestHeaders': {'cases': [{'path': 'headers{_bin}', 'reason': {'TypeUnexpected': {'actual': {'Object': {}}, 'expected': {'Integer': {}}}}}]}}]]
    ]
}
