cases = {
    'emptyPartialMatchStub': [
        [[{}, {'fn._clearStubs': {}}], [{}, {'ok': {}}]],
        [[{}, {'fn._clearCalls': {}}], [{}, {'ok': {}}]],
        [[{}, {'fn.test': {}}], [{}, {'_errorNoMatchingStub': {}}]],
        [[{}, {'fn._createStub': {'stub': {'fn.test': {}, '->': {'ok': {}}}}}], [{}, {'ok': {}}]],
        [[{}, {'fn.test': {}}], [{}, {'ok': {}}]],
    ],
    'partialMatchStub': [
        [[{}, {'fn._clearStubs': {}}], [{}, {'ok': {}}]],
        [[{}, {'fn._clearCalls': {}}], [{}, {'ok': {}}]],
        [[{}, {'fn.test': {'value': {'int': 1}}}], [{}, {'_errorNoMatchingStub': {}}]],
        [[{}, {'fn.test': {'value': {'int': 1, 'str': 'a'}}}], [{}, {'_errorNoMatchingStub': {}}]],
        [[{}, {'fn._createStub': {'stub': {'fn.test': {'value': {'int': 1}}, '->': {'ok': {'value': {'bool': True}}}}}}], [{}, {'ok': {}}]],
        [[{}, {'fn.test': {}}], [{}, {'_errorNoMatchingStub': {}}]],
        [[{}, {'fn.test': {'value': {'int': 0}}}], [{}, {'_errorNoMatchingStub': {}}]],
        [[{}, {'fn.test': {'value': {'int': 1}}}], [{}, {'ok': {'value': {'bool': True}}}]],
        [[{}, {'fn.test': {'value': {'int': 1, 'str': 'a'}}}], [{}, {'ok': {'value': {'bool': True}}}]],
    ],
    'multiplePartialMatchStub': [
        [[{}, {'fn._clearStubs': {}}], [{}, {'ok': {}}]],
        [[{}, {'fn._clearCalls': {}}], [{}, {'ok': {}}]],
        [[{}, {'fn.test': {'value': {'int': 1}}}], [{}, {'_errorNoMatchingStub': {}}]],
        [[{}, {'fn.test': {'value': {'int': 1, 'str': 'a'}}}], [{}, {'_errorNoMatchingStub': {}}]],
        [[{}, {'fn.test': {'value': {'int': 0, 'str': 'a'}}}], [{}, {'_errorNoMatchingStub': {}}]],
        [[{}, {'fn.test': {'value': {'int': 1, 'str': 'b'}}}], [{}, {'_errorNoMatchingStub': {}}]],
        [[{}, {'fn.test': {'value': {'bool': False, 'int': 1, 'str': 'a'}}}], [{}, {'_errorNoMatchingStub': {}}]],
        [[{}, {'fn._createStub': {'stub': {'fn.test': {'value': {'int': 1}}, '->': {'ok': {'value': {'bool': True}}}}}}], [{}, {'ok': {}}]],
        [[{}, {'fn._createStub': {'stub': {'fn.test': {'value': {'str': 'a'}}, '->': {'ok': {'value': {'bool': False}}}}}}], [{}, {'ok': {}}]],
        [[{}, {'fn._createStub': {'stub': {'fn.example': {}, '->': {'ok': {}}}}}], [{}, {'ok': {}}]],
        [[{}, {'fn.test': {}}], [{}, {'_errorNoMatchingStub': {}}]],
        [[{}, {'fn.test': {'value': {'int': 0}}}], [{}, {'_errorNoMatchingStub': {}}]],
        [[{}, {'fn.test': {'value': {'int': 1}}}], [{}, {'ok': {'value': {'bool': True}}}]],
        [[{}, {'fn.test': {'value': {'int': 1, 'str': 'a'}}}], [{}, {'ok': {'value': {'bool': False}}}]],
        [[{}, {'fn.test': {'value': {'int': 0, 'str': 'a'}}}], [{}, {'ok': {'value': {'bool': False}}}]],
        [[{}, {'fn.test': {'value': {'int': 1, 'str': 'b'}}}], [{}, {'ok': {'value': {'bool': True}}}]],
        [[{}, {'fn.test': {'value': {'bool': False, 'int': 1, 'str': 'a'}}}], [{}, {'ok': {'value': {'bool': False}}}]],
    ],
    'multipleNestedPartialMatchStub': [
        [[{}, {'fn._clearStubs': {}}], [{}, {'ok': {}}]],
        [[{}, {'fn._clearCalls': {}}], [{}, {'ok': {}}]],
        [[{}, {'fn.test': {'value': {'int': 1}}}], [{}, {'_errorNoMatchingStub': {}}]],
        [[{}, {'fn.test': {'value': {'int': 1, 'str': 'a'}}}], [{}, {'_errorNoMatchingStub': {}}]],
        [[{}, {'fn.test': {'value': {'int': 0, 'str': 'a'}}}], [{}, {'_errorNoMatchingStub': {}}]],
        [[{}, {'fn.test': {'value': {'int': 1, 'str': 'b'}}}], [{}, {'_errorNoMatchingStub': {}}]],
        [[{}, {'fn.test': {'value': {'bool': False, 'int': 1, 'str': 'a'}}}], [{}, {'_errorNoMatchingStub': {}}]],
        [[{}, {'fn._createStub': {'stub': {'fn.test': {'value': {'struct': {'optional': True}}}, '->': {'ok': {'value': {'bool': True}}}}}}], [{}, {'ok': {}}]],
        [[{}, {'fn._createStub': {'stub': {'fn.test': {'value': {'struct': {'required': True}}}, '->': {'ok': {'value': {'bool': False}}}}}}], [{}, {'ok': {}}]],
        [[{}, {'fn._createStub': {'stub': {'fn.example': {}, '->': {'ok': {}}}}}], [{}, {'ok': {}}]],
        [[{}, {'fn.test': {}}], [{}, {'_errorNoMatchingStub': {}}]],
        [[{}, {'fn.test': {'value': {'struct': {'optional': False, 'required': False}}}}], [{}, {'_errorNoMatchingStub': {}}]],
        [[{}, {'fn.test': {'value': {'struct': {'optional': True, 'required': False}}}}], [{}, {'ok': {'value': {'bool': True}}}]],
        [[{}, {'fn.test': {'value': {'struct': {'optional': True, 'required': True}}}}], [{}, {'ok': {'value': {'bool': False}}}]],
        [[{}, {'fn.test': {'value': {'struct': {'optional': False, 'required': True}}}}], [{}, {'ok': {'value': {'bool': False}}}]],
        [[{}, {'fn.test': {'value': {'struct': {'optional': True, 'required': False}, 'str': 'b'}}}], [{}, {'ok': {'value': {'bool': True}}}]],
    ],
    'multipleReallyNestedPartialMatchStub': [
        [[{}, {'fn._clearStubs': {}}], [{}, {'ok': {}}]],
        [[{}, {'fn._clearCalls': {}}], [{}, {'ok': {}}]],
        [[{}, {'fn.test': {'value': {'int': 1}}}], [{}, {'_errorNoMatchingStub': {}}]],
        [[{}, {'fn.test': {'value': {'int': 1, 'str': 'a'}}}], [{}, {'_errorNoMatchingStub': {}}]],
        [[{}, {'fn.test': {'value': {'int': 0, 'str': 'a'}}}], [{}, {'_errorNoMatchingStub': {}}]],
        [[{}, {'fn.test': {'value': {'int': 1, 'str': 'b'}}}], [{}, {'_errorNoMatchingStub': {}}]],
        [[{}, {'fn.test': {'value': {'bool': False, 'int': 1, 'str': 'a'}}}], [{}, {'_errorNoMatchingStub': {}}]],
        [[{}, {'fn._createStub': {'stub': {'fn.test': {'value': {'arrStruct': [{'optional': True}]}}, '->': {'ok': {'value': {'bool': True}}}}}}], [{}, {'ok': {}}]],
        [[{}, {'fn._createStub': {'stub': {'fn.test': {'value': {'arrStruct': [{'required': True}]}}, '->': {'ok': {'value': {'bool': False}}}}}}], [{}, {'ok': {}}]],
        [[{}, {'fn._createStub': {'stub': {'fn.example': {}, '->': {'ok': {}}}}}], [{}, {'ok': {}}]],
        [[{}, {'fn.test': {}}], [{}, {'_errorNoMatchingStub': {}}]],
        [[{}, {'fn.test': {'value': {'arrStruct': [{'required': False}, {'optional': False, 'required': False}]}}}], [{}, {'_errorNoMatchingStub': {}}]],
        [[{}, {'fn.test': {'value': {'arrStruct': [{'required': False}, {'optional': True, 'required': False}]}}}], [{}, {'ok': {'value': {'bool': True}}}]],
        [[{}, {'fn.test': {'value': {'arrStruct': [{'required': False}, {'optional': True, 'required': True}]}}}], [{}, {'ok': {'value': {'bool': False}}}]],
        [[{}, {'fn.test': {'value': {'arrStruct': [{'required': False}, {'optional': False, 'required': True}]}}}], [{}, {'ok': {'value': {'bool': False}}}]],
        [[{}, {'fn.test': {'value': {'arrStruct': [{'required': False}, {'optional': True, 'required': False}], 'str': 'b'}}}], [{}, {'ok': {'value': {'bool': True}}}]],
    ],
    'strictMatchStub': [
        [[{}, {'fn._clearStubs': {}}], [{}, {'ok': {}}]],
        [[{}, {'fn._clearCalls': {}}], [{}, {'ok': {}}]],
        [[{}, {'fn.test': {'value': {'int': 1}}}], [{}, {'_errorNoMatchingStub': {}}]],
        [[{}, {'fn._createStub': {'stub': {'fn.test': {'value': {'int': 1}}, '->': {'ok': {'value': {'bool': True}}}}, 'strictMatch': True}}], [{}, {'ok': {}}]],
        [[{}, {'fn.test': {}}], [{}, {'_errorNoMatchingStub': {}}]],
        [[{}, {'fn.test': {'value': {'int': 0}}}], [{}, {'_errorNoMatchingStub': {}}]],
        [[{}, {'fn.test': {'value': {'int': 1}}}], [{}, {'ok': {'value': {'bool': True}}}]],
        [[{}, {'fn.test': {'value': {'int': 1, 'str': 'a'}}}], [{}, {'_errorNoMatchingStub': {}}]],
    ],
    'multipleStrictMatchStub': [
        [[{}, {'fn._clearStubs': {}}], [{}, {'ok': {}}]],
        [[{}, {'fn._clearCalls': {}}], [{}, {'ok': {}}]],
        [[{}, {'fn.test': {'value': {'int': 1}}}], [{}, {'_errorNoMatchingStub': {}}]],
        [[{}, {'fn.test': {'value': {'str': 'a'}}}], [{}, {'_errorNoMatchingStub': {}}]],
        [[{}, {'fn._createStub': {'stub': {'fn.test': {'value': {'int': 1}}, '->': {'ok': {'value': {'bool': True}}}}, 'strictMatch': True}}], [{}, {'ok': {}}]],
        [[{}, {'fn._createStub': {'stub': {'fn.test': {'value': {'str': 'a'}}, '->': {'ok': {'value': {'bool': False}}}}, 'strictMatch': True}}], [{}, {'ok': {}}]],
        [[{}, {'fn.test': {}}], [{}, {'_errorNoMatchingStub': {}}]],
        [[{}, {'fn.test': {'value': {'int': 0}}}], [{}, {'_errorNoMatchingStub': {}}]],
        [[{}, {'fn.test': {'value': {'int': 1}}}], [{}, {'ok': {'value': {'bool': True}}}]],
        [[{}, {'fn.test': {'value': {'int': 1, 'str': 'a'}}}], [{}, {'_errorNoMatchingStub': {}}]],
        [[{}, {'fn.test': {'value': {'str': 'a'}}}], [{}, {'ok': {'value': {'bool': False}}}]],
        [[{}, {'fn.test': {'value': {'int': 0, 'str': 'a'}}}], [{}, {'_errorNoMatchingStub': {}}]],
        [[{}, {'fn.test': {'value': {'int': 1, 'str': 'b'}}}], [{}, {'_errorNoMatchingStub': {}}]],
        [[{}, {'fn.test': {'value': {'bool': False, 'int': 1, 'str': 'a'}}}], [{}, {'_errorNoMatchingStub': {}}]],
    ],
    'mixedPartialStrictMatchStub': [
        [[{}, {'fn._clearStubs': {}}], [{}, {'ok': {}}]],
        [[{}, {'fn._clearCalls': {}}], [{}, {'ok': {}}]],
        [[{}, {'fn.test': {'value': {'int': 1}}}], [{}, {'_errorNoMatchingStub': {}}]],
        [[{}, {'fn.test': {'value': {'int': 1, 'str': 'a'}}}], [{}, {'_errorNoMatchingStub': {}}]],
        [[{}, {'fn.test': {'value': {'int': 1, 'str': 'b'}}}], [{}, {'_errorNoMatchingStub': {}}]],
        [[{}, {'fn.test': {'value': {'bool': False, 'int': 1, 'str': 'a'}}}], [{}, {'_errorNoMatchingStub': {}}]],
        [[{}, {'fn._createStub': {'stub': {'fn.test': {'value': {'int': 1}}, '->': {'ok': {'value': {'bool': True}}}}}}], [{}, {'ok': {}}]],
        [[{}, {'fn._createStub': {'stub': {'fn.test': {'value': {'int': 1, 'str': 'a'}}, '->': {'ok': {'value': {'bool': False}}}}, 'strictMatch': True}}], [{}, {'ok': {}}]],
        [[{}, {'fn.test': {}}], [{}, {'_errorNoMatchingStub': {}}]],
        [[{}, {'fn.test': {'value': {'int': 0}}}], [{}, {'_errorNoMatchingStub': {}}]],
        [[{}, {'fn.test': {'value': {'int': 1}}}], [{}, {'ok': {'value': {'bool': True}}}]],
        [[{}, {'fn.test': {'value': {'int': 1, 'str': 'a'}}}], [{}, {'ok': {'value': {'bool': False}}}]],
        [[{}, {'fn.test': {'value': {'int': 0, 'str': 'a'}}}], [{}, {'_errorNoMatchingStub': {}}]],
        [[{}, {'fn.test': {'value': {'int': 1, 'str': 'b'}}}], [{}, {'ok': {'value': {'bool': True}}}]],
        [[{}, {'fn.test': {'value': {'bool': False, 'int': 1, 'str': 'a'}}}], [{}, {'ok': {'value': {'bool': True}}}]],
    ],
    'mixedStrictPartialMatchStub': [
        [[{}, {'fn._clearStubs': {}}], [{}, {'ok': {}}]],
        [[{}, {'fn._clearCalls': {}}], [{}, {'ok': {}}]],
        [[{}, {'fn.test': {'value': {'int': 1}}}], [{}, {'_errorNoMatchingStub': {}}]],
        [[{}, {'fn.test': {'value': {'int': 1, 'str': 'a'}}}], [{}, {'_errorNoMatchingStub': {}}]],
        [[{}, {'fn.test': {'value': {'int': 1, 'str': 'b'}}}], [{}, {'_errorNoMatchingStub': {}}]],
        [[{}, {'fn.test': {'value': {'bool': False, 'int': 1, 'str': 'a'}}}], [{}, {'_errorNoMatchingStub': {}}]],
        [[{}, {'fn._createStub': {'stub': {'fn.test': {'value': {'int': 1, 'str': 'a'}}, '->': {'ok': {'value': {'bool': False}}}}, 'strictMatch': True}}], [{}, {'ok': {}}]],
        [[{}, {'fn._createStub': {'stub': {'fn.test': {'value': {'int': 1}}, '->': {'ok': {'value': {'bool': True}}}}}}], [{}, {'ok': {}}]],
        [[{}, {'fn.test': {}}], [{}, {'_errorNoMatchingStub': {}}]],
        [[{}, {'fn.test': {'value': {'int': 0}}}], [{}, {'_errorNoMatchingStub': {}}]],
        [[{}, {'fn.test': {'value': {'int': 1}}}], [{}, {'ok': {'value': {'bool': True}}}]],
        [[{}, {'fn.test': {'value': {'int': 1, 'str': 'a'}}}], [{}, {'ok': {'value': {'bool': True}}}]],
        [[{}, {'fn.test': {'value': {'int': 0, 'str': 'a'}}}], [{}, {'_errorNoMatchingStub': {}}]],
        [[{}, {'fn.test': {'value': {'int': 1, 'str': 'b'}}}], [{}, {'ok': {'value': {'bool': True}}}]],
        [[{}, {'fn.test': {'value': {'bool': False, 'int': 1, 'str': 'a'}}}], [{}, {'ok': {'value': {'bool': True}}}]],
    ],
    'clearStubs': [
        [[{}, {'fn._clearStubs': {}}], [{}, {'ok': {}}]],
        [[{}, {'fn._clearCalls': {}}], [{}, {'ok': {}}]],
        [[{}, {'fn.test': {}}], [{}, {'_errorNoMatchingStub': {}}]],
        [[{}, {'fn._createStub': {'stub': {'fn.test': {}, '->': {'ok': {}}}}}], [{}, {'ok': {}}]],
        [[{}, {'fn.test': {}}], [{}, {'ok': {}}]],
        [[{}, {'fn._clearStubs': {}}], [{}, {'ok': {}}]],
        [[{}, {'fn.test': {}}], [{}, {'_errorNoMatchingStub': {}}]],
    ],
    'generation': [
        [[{}, {'fn._clearStubs': {}}], [{}, {'ok': {}}]],
        [[{}, {'fn._clearCalls': {}}], [{}, {'ok': {}}]],
        [[{'_mockEnableGeneratedStub': True}, {'fn.test': {}}], [{}, {'ok': {'value': {'arrArr': [[794471793, 'L+Uz1w'], []], 'arrFn': [], 'arrInt': [996984527, 1157490780], 'arrNullEnum': [{'two': {'required': False}}], 'arrNullFn': [{'optional': False, 'required': True}], 'arrNullInt': [], 'arrNullP2Enum': [{'two': {'enest': [837716109, 1513704002], 'ewrap': False}}, None], 'arrNullP2Str': [{'nest': [1787378757, 1328144282], 'wrap': False}], 'arrNullStr': [], 'arrNullStruct': [{'optional': True, 'required': False}], 'arrP2Enum': [], 'arrStruct': [{'required': False}], 'fn': {'required': False}, 'int': 342738416, 'nullAny': None, 'nullArr': None, 'nullFn': {'required': False}, 'nullNum': None, 'nullObj': None, 'nullP2Str': {'nest': [1070152012, 350928277], 'wrap': False}, 'nullStr': None, 'nullStruct': None, 'num': 0.41169920729372433, 'objBool': {'Vg2zTg': True, 'cLONfA': True}, 'objEnum': {'XNsgvQ': {'one': {}}, 'fmoFaA': {'two': {'optional': False, 'required': True}}}, 'objNullArr': {'SPhqCg': [867900630, 106931780], 'ULNNrA': None}, 'objNullBool': {}, 'objNullFn': {}, 'objNullInt': {'P7rgaw': None, 'dft53A': 1418160570}, 'objNum': {'SvfamQ': 0.31723206103436735}, 'objObj': {'I+KHVQ': {'Xvi6Ww': 'S5FD0Q'}}, 'objP2Enum': {'X5OWpA': {'two': {'enest': [], 'ewrap': True}}}, 'objP2Str': {'Ac5eDg': {'nest': [1458640444], 'wrap': True}}, 'objStr': {'A9daKA': 'IxnDQQ'}, 'objStruct': {}, 'p2Str': {'nest': [107290051], 'wrap': False}, 'pEnumAny': {'one': {}}, 'pEnumFn': {'two': {'ewrap': {'optional': True, 'required': True}}}, 'pEnumNullArr': {'one': {}}, 'pEnumNullBool': {'one': {}}, 'pEnumNullInt': {'one': {}}, 'pEnumNullObj': {'two': {'ewrap': {}}}, 'pEnumNullP2Enum': {'two': {'ewrap': {'two': {'enest': [], 'ewrap': False}}}}, 'pEnumNullP2Str': {'two': {'ewrap': {'nest': [689679052], 'wrap': False}}}, 'pEnumStr': {'two': {'ewrap': 'a6/Ggg'}}, 'pStrAny': {'wrap': 865585358}, 'pStrArr': {'wrap': []}, 'pStrEnum': {'wrap': {'two': {'optional': True, 'required': False}}}, 'pStrFn': {'wrap': {'optional': True, 'required': True}}, 'pStrInt': {'wrap': 519516928}, 'pStrNullAny': {'wrap': 'ORx/LA'}, 'pStrNullArr': {'wrap': []}, 'pStrNullNum': {'wrap': 0.348971671961984}, 'pStrNullObj': {'wrap': None}, 'pStrNullP2Enum': {'wrap': {'two': {'enest': [], 'ewrap': True}}}, 'pStrNullStr': {'wrap': None}, 'pStrNullStruct': {'wrap': {'optional': False, 'required': False}}, 'pStrObj': {'wrap': {'Fbh2GQ': 1633783999, 'I18DjA': False}}, 'pStrP2Enum': {'wrap': {'one': {}}}, 'pStrP2Str': {'wrap': {'nest': [1034606775], 'wrap': False}}, 'pdStr': {'dwrap': {'wrap': True}}}}}]],
        [[{'_mockEnableGeneratedStub': True}, {'fn.test': {}}], [{}, {'ok': {}}]],
        [[{'_mockEnableGeneratedStub': True}, {'fn.test': {}}], [{}, {'ok': {'value': {'arrEnum': [{'one': {}}, {'two': {'required': False}}], 'arrNullArr': [None, None], 'arrNullBool': [None, False], 'arrNullObj': [{}, {'a56N+g': 629192200}], 'arrNullP2Str': [{'nest': [17621586, 1021151523], 'wrap': True}, None], 'arrNullStruct': [], 'arrNum': [0.27416063514685657], 'arrStr': [], 'arrStruct': [], 'fn': {'optional': True, 'required': False}, 'int': 1125421402, 'nullStr': 'O1c+Xw', 'obj': {'G7SaVw': True, 'Kb4rmA': True}, 'objAny': {'R/J9Tw': 1605435877, 'YNLVsA': True}, 'objArr': {'OV+qyA': [False, True]}, 'objInt': {}, 'objNullArr': {'HkLQag': ['bLWJNg'], 'bt4QNw': None}, 'objNullFn': {'U+OTCQ': None}, 'objNullNum': {'EE2aQQ': None, 'R+goGg': 0.26713475720539054}, 'objNullObj': {'XSrLyg': {'C5j6BA': 1518930466, 'dZCVsQ': 1647834647}, 'dpiZfQ': {'A6l5QA': 30364094, 'ZyHiHw': 409369397}}, 'objNullP2Enum': {'FfW7eg': None, 'P/NJ6Q': {'two': {'enest': [], 'ewrap': False}}}, 'objNullStruct': {'A4qXoA': {'required': True}, 'S7DsNA': {'required': False}}, 'objNum': {}, 'objP2Enum': {'bobAkQ': {'one': {}}, 'drpL9w': {'one': {}}}, 'objP2Str': {'Dj2wkw': {'nest': [], 'wrap': True}, 'PhTzzg': {'nest': [1232732668, 2054541445], 'wrap': True}}, 'objStr': {}, 'objStruct': {}, 'p2Str': {'nest': [], 'wrap': False}, 'pEnumArr': {'two': {'ewrap': ['bD/iLA']}}, 'pEnumEnum': {'two': {'ewrap': {'one': {}}}}, 'pEnumNullFn': {'one': {}}, 'pEnumNullInt': {'one': {}}, 'pEnumNullNum': {'one': {}}, 'pEnumNullObj': {'one': {}}, 'pEnumNullP2Enum': {'one': {}}, 'pEnumNullP2Str': {'one': {}}, 'pEnumNullStr': {'one': {}}, 'pEnumNum': {'two': {'ewrap': 0.39889448629729785}}, 'pEnumP2Enum': {'two': {'ewrap': {'one': {}}}}, 'pEnumP2Str': {'one': {}}, 'pEnumStruct': {'two': {'ewrap': {'optional': True, 'required': False}}}, 'pStrArr': {'wrap': []}, 'pStrFn': {'wrap': {'optional': True, 'required': True}}, 'pStrInt': {'wrap': 540659403}, 'pStrNullAny': {'wrap': None}, 'pStrNullArr': {'wrap': ['VuE98g', True]}, 'pStrNullBool': {'wrap': None}, 'pStrNullEnum': {'wrap': None}, 'pStrNullInt': {'wrap': None}, 'pStrNullNum': {'wrap': 0.3774721242707453}, 'pStrNullObj': {'wrap': None}, 'pStrNullP2Enum': {'wrap': None}, 'pStrObj': {'wrap': {}}, 'pStrStruct': {'wrap': {'optional': True, 'required': False}}, 'struct': {'required': True}}}}]],
        [[{'_mockEnableGeneratedStub': True}, {'fn.test': {}}], [{}, {'ok': {'value': {'arrEnum': [], 'arrFn': [{'required': False}], 'arrNullBool': [False, False], 'arrNullEnum': [None], 'arrNullFn': [{'optional': True, 'required': True}, None], 'arrNullObj': [], 'arrNullStr': [], 'arrNum': [], 'arrP2Enum': [{'one': {}}, {'two': {'enest': [557925161], 'ewrap': True}}], 'arrStr': ['NOQfug', 'Sqheaw'], 'arrStruct': [{'optional': False, 'required': False}, {'optional': False, 'required': False}], 'enum': {'one': {}}, 'nullArr': None, 'nullBool': True, 'nullFn': None, 'nullNum': None, 'nullP2Str': {'nest': [252052250], 'wrap': True}, 'nullStruct': None, 'num': 0.21166269900731877, 'objAny': {}, 'objInt': {'SCzDWA': 1285827761, 'UPVmyg': 134905915}, 'objNullAny': {'E6wFIg': False, 'Ola9BA': None}, 'objNullFn': {'KKikIQ': {'optional': True, 'required': False}, 'RJfuKw': None}, 'objNullInt': {}, 'objNullP2Enum': {'dHNwzA': None}, 'objNullStruct': {'IFy8gg': {'optional': True, 'required': True}, 'VQ0m9g': {'required': True}}, 'objP2Str': {'UHfSPQ': {'nest': [], 'wrap': False}, 'e+sU6A': {'nest': [480983462, 484200423], 'wrap': False}}, 'pEnumArr': {'one': {}}, 'pEnumFn': {'one': {}}, 'pEnumNullAny': {'two': {'ewrap': 85279280}}, 'pEnumNullArr': {'one': {}}, 'pEnumNullInt': {'two': {'ewrap': None}}, 'pEnumNullNum': {'one': {}}, 'pEnumNullObj': {'one': {}}, 'pEnumNullP2Enum': {'one': {}}, 'pEnumNullP2Str': {'one': {}}, 'pEnumNullStr': {'one': {}}, 'pEnumNullStruct': {'one': {}}, 'pEnumP2Enum': {'one': {}}, 'pEnumP2Str': {'one': {}}, 'pStrAny': {'wrap': 1896941395}, 'pStrBool': {'wrap': False}, 'pStrEnum': {'wrap': {'one': {}}}, 'pStrFn': {'wrap': {'optional': True, 'required': True}}, 'pStrInt': {'wrap': 1954937958}, 'pStrNullArr': {'wrap': None}, 'pStrNullBool': {'wrap': True}, 'pStrNullFn': {'wrap': {'optional': True, 'required': False}}, 'pStrNullInt': {'wrap': None}, 'pStrNullNum': {'wrap': None}, 'pStrNullObj': {'wrap': {}}, 'pStrNullP2Enum': {'wrap': None}, 'pStrNullStruct': {'wrap': None}, 'pStrNum': {'wrap': 0.4077925467799474}, 'pStrP2Enum': {'wrap': {'one': {}}}, 'pStrP2Str': {'wrap': {'nest': [478943623, 1557672116], 'wrap': True}}, 'pStrStruct': {'wrap': {'required': True}}, 'pdStr': {'dwrap': {'wrap': False}}, 'struct': {'required': True}}}}]],
        [[{'_mockEnableGeneratedStub': True}, {'fn.test': {}}], [{}, {'ok': {'value': {'arrArr': [['PnZVUA'], [True]], 'arrBool': [], 'arrEnum': [], 'arrFn': [{'optional': True, 'required': False}], 'arrNullArr': [], 'arrNullBool': [None], 'arrNullEnum': [{'two': {'optional': True, 'required': True}}], 'arrNullInt': [None, None], 'arrNullNum': [None], 'arrNum': [], 'arrP2Enum': [{'two': {'enest': [1516883683], 'ewrap': True}}, {'two': {'enest': [], 'ewrap': True}}], 'int': 502328887, 'nullAny': None, 'nullArr': [], 'nullBool': False, 'nullEnum': None, 'nullFn': None, 'nullInt': None, 'nullNum': None, 'nullObj': None, 'nullP2Enum': {'one': {}}, 'nullP2Str': None, 'objAny': {}, 'objBool': {}, 'objEnum': {'MpsAIg': {'two': {'required': True}}, 'NIz8bg': {'two': {'required': False}}}, 'objNullAny': {'QCQrRg': None, 'UwXyNA': None}, 'objNullArr': {}, 'objNullBool': {}, 'objNullEnum': {}, 'objNullFn': {}, 'objNullInt': {'S5XguA': None}, 'objNullObj': {'c0zizQ': None}, 'objNullP2Enum': {}, 'objStr': {'UlrEpg': 'dvR+5w'}, 'objStruct': {'AJMMOQ': {'optional': True, 'required': False}, 'Rd6FMg': {'required': True}}, 'p2Enum': {'one': {}}, 'p2Str': {'nest': [], 'wrap': False}, 'pEnumAny': {'two': {'ewrap': 259509165}}, 'pEnumBool': {'one': {}}, 'pEnumEnum': {'one': {}}, 'pEnumFn': {'one': {}}, 'pEnumNullAny': {'two': {'ewrap': 'cxmOBg'}}, 'pEnumNullBool': {'two': {'ewrap': True}}, 'pEnumNullEnum': {'two': {'ewrap': None}}, 'pEnumNullInt': {'two': {'ewrap': 1688860379}}, 'pEnumNullNum': {'two': {'ewrap': None}}, 'pEnumNullP2Enum': {'two': {'ewrap': None}}, 'pEnumNullStr': {'two': {'ewrap': 'Uh8Urw'}}, 'pEnumNullStruct': {'two': {'ewrap': None}}, 'pEnumObj': {'two': {'ewrap': {'L7Wz8g': 'dsZ4wA', 'Ujbqpw': True}}}, 'pEnumP2Str': {'two': {'ewrap': {'nest': [], 'wrap': True}}}, 'pEnumStruct': {'one': {}}, 'pStrArr': {'wrap': []}, 'pStrBool': {'wrap': True}, 'pStrFn': {'wrap': {'required': True}}, 'pStrInt': {'wrap': 1877251727}, 'pStrNullArr': {'wrap': None}, 'pStrNullBool': {'wrap': True}, 'pStrNullFn': {'wrap': {'optional': True, 'required': False}}, 'pStrNullInt': {'wrap': None}, 'pStrNullP2Enum': {'wrap': {'one': {}}}, 'pStrNullP2Str': {'wrap': None}, 'pStrP2Enum': {'wrap': {'one': {}}}, 'pStrStruct': {'wrap': {'required': False}}, 'struct': {'required': True}}}}]],
    ],
    'emptyPartialMatchVerify': [
        [[{}, {'fn._clearStubs': {}}], [{}, {'ok': {}}]],
        [[{}, {'fn._clearCalls': {}}], [{}, {'ok': {}}]],
        [[{}, {'fn._createStub': {'stub': {'fn.test': {}, '->': {'ok': {}}}}}], [{}, {'ok': {}}]],
        [[{}, {'fn._verify': {'call': {'fn.test': {}}}}], [{}, {'errorVerificationFailure': {'reason': {'tooFewMatchingCalls': {'allCalls': [], 'found': 0, 'wanted': {'atLeast': {'times': 1}}}}}}]],
        [[{}, {'fn._verify': {'call': {'fn.test': {}}, 'count': {'exact': {'times': 1}}}}], [{}, {'errorVerificationFailure': {'reason': {'tooFewMatchingCalls': {'allCalls': [], 'found': 0, 'wanted': {'exact': {'times': 1}}}}}}]],
        [[{}, {'fn._verify': {'call': {'fn.test': {}}, 'count': {'atLeast': {'times': 1}}}}], [{}, {'errorVerificationFailure': {'reason': {'tooFewMatchingCalls': {'allCalls': [], 'wanted': {'atLeast': {'times': 1}}, 'found': 0}}}}]],
        [[{}, {'fn._verify': {'call': {'fn.test': {}}, 'count': {'atMost': {'times': 0}}}}], [{}, {'ok': {}}]],
        [[{}, {'fn.test': {}}], [{}, {'ok': {}}]],
        [[{}, {'fn._verifyNoMoreInteractions': {}}], [{}, {'errorVerificationFailure': {'additionalUnverifiedCalls': [{'fn.test': {}}]}}]],
        [[{}, {'fn._verify': {'call': {'fn.test': {}}}}], [{}, {'ok': {}}]],
        [[{}, {'fn._verifyNoMoreInteractions': {}}], [{}, {'ok': {}}]],
        [[{}, {'fn._verify': {'call': {'fn.test': {}}, 'count': {'exact': {'times': 1}}}}], [{}, {'ok': {}}]],
        [[{}, {'fn._verify': {'call': {'fn.test': {}}, 'count': {'atLeast': {'times': 1}}}}], [{}, {'ok': {}}]],
        [[{}, {'fn._verify': {'call': {'fn.test': {}}, 'count': {'atLeast': {'times': 2}}}}], [{}, {'errorVerificationFailure': {'reason': {'tooFewMatchingCalls': {'allCalls': [{'fn.test': {}}], 'found': 1, 'wanted': {'atLeast': {'times': 2}}}}}}]],
        [[{}, {'fn._verify': {'call': {'fn.test': {}}, 'count': {'atMost': {'times': 1}}}}], [{}, {'ok': {}}]],
        [[{}, {'fn._verify': {'call': {'fn.test': {}}, 'count': {'atMost': {'times': 0}}}}], [{}, {'errorVerificationFailure': {'reason': {'tooManyMatchingCalls': {'wanted': {'atMost': {'times': 0}}, 'allCalls': [{'fn.test': {}}], 'found': 1}}}}]],
    ],
    'partialMatchVerify': [
        [[{}, {'fn._clearStubs': {}}], [{}, {'ok': {}}]],
        [[{}, {'fn._clearCalls': {}}], [{}, {'ok': {}}]],
        [[{}, {'fn._createStub': {'stub': {'fn.test': {'value': {'int': 0}}, '->': {'ok': {'value': {'bool': True}}}}}}], [{}, {'ok': {}}]],
        [[{}, {'fn._verify': {'call': {'fn.test': {'value': {'int': 0}}}}}], [{}, {'errorVerificationFailure': {'reason': {'tooFewMatchingCalls': {'found': 0, 'allCalls': [], 'wanted': {'atLeast': {'times': 1}}}}}}]],
        [[{}, {'fn.test': {'value': {'int': 0, 'str': 'a'}}}], [{}, {'ok': {'value': {'bool': True}}}]],
        [[{}, {'fn._verifyNoMoreInteractions': {}}], [{}, {'errorVerificationFailure': {'additionalUnverifiedCalls': [{'fn.test': {'value': {'int': 0, 'str': 'a'}}}]}}]],
        [[{}, {'fn._verify': {'call': {'fn.test': {'value': {'int': 0}}}}}], [{}, {'ok': {}}]],
        [[{}, {'fn._verifyNoMoreInteractions': {}}], [{}, {'ok': {}}]],
        [[{}, {'fn._verify': {'call': {'fn.test': {'value': {'int': 0}}}, 'count': {'exact': {'times': 1}}}}], [{}, {'ok': {}}]],
        [[{}, {'fn._verify': {'call': {'fn.test': {'value': {'int': 0}}}, 'count': {'atLeast': {'times': 1}}}}], [{}, {'ok': {}}]],
        [[{}, {'fn._verify': {'call': {'fn.test': {'value': {'int': 0}}}, 'count': {'atMost': {'times': 0}}}}], [{}, {'errorVerificationFailure': {'reason': {'tooManyMatchingCalls': {'wanted': {'atMost': {'times': 0}}, 'allCalls': [{'fn.test': {'value': {'int': 0, 'str': 'a'}}}], 'found': 1}}}}]],
    ],
    'multiplePartialMatchVerify': [
        [[{}, {'fn._clearStubs': {}}], [{}, {'ok': {}}]],
        [[{}, {'fn._clearCalls': {}}], [{}, {'ok': {}}]],
        [[{}, {'fn._createStub': {'stub': {'fn.test': {}, '->': {'ok': {}}}}}], [{}, {'ok': {}}]],
        [[{}, {'fn._verify': {'call': {'fn.test': {'value': {'int': 0}}}}}], [{}, {'errorVerificationFailure': {'reason': {'tooFewMatchingCalls': {'found': 0, 'allCalls': [], 'wanted': {'atLeast': {'times': 1}}}}}}]],
        [[{}, {'fn.test': {'value': {'int': 0, 'bool': True}}}], [{}, {'ok': {}}]],
        [[{}, {'fn.test': {'value': {'int': 0, 'str': 'a'}}}], [{}, {'ok': {}}]],
        [[{}, {'fn.test': {'value': {'int': 1}}}], [{}, {'ok': {}}]],
        [[{}, {'fn._verifyNoMoreInteractions': {}}], [{}, {'errorVerificationFailure': {'additionalUnverifiedCalls': [{'fn.test': {'value': {'int': 0, 'bool': True}}}, {'fn.test': {'value': {'int': 0, 'str': 'a'}}}, {'fn.test': {'value': {'int': 1}}}]}}]],
        [[{}, {'fn._verify': {'call': {'fn.test': {'value': {'int': 0}}}}}], [{}, {'ok': {}}]],
        [[{}, {'fn._verifyNoMoreInteractions': {}}], [{}, {'errorVerificationFailure': {'additionalUnverifiedCalls': [{'fn.test': {'value': {'int': 1}}}]}}]],
        [[{}, {'fn._verify': {'call': {'fn.test': {}}}}], [{}, {'ok': {}}]],
        [[{}, {'fn._verifyNoMoreInteractions': {}}], [{}, {'ok': {}}]],
        [[{}, {'fn._verify': {'call': {'fn.test': {'value': {'int': 0}}}, 'count': {'exact': {'times': 1}}}}], [{}, {'errorVerificationFailure': {'reason': {'tooManyMatchingCalls': {'wanted': {'exact': {'times': 1}}, 'allCalls': [{'fn.test': {'value': {'int': 0, 'bool': True}}}, {'fn.test': {'value': {'int': 0, 'str': 'a'}}}, {'fn.test': {'value': {'int': 1}}}], 'found': 2}}}}]],
        [[{}, {'fn._verify': {'call': {'fn.test': {'value': {'int': 0}}}, 'count': {'exact': {'times': 2}}}}], [{}, {'ok': {}}]],
        [[{}, {'fn._verify': {'call': {'fn.test': {'value': {'int': 0}}}, 'count': {'exact': {'times': 3}}}}], [{}, {'errorVerificationFailure': {'reason': {'tooFewMatchingCalls': {'wanted': {'exact': {'times': 3}}, 'allCalls': [{'fn.test': {'value': {'int': 0, 'bool': True}}}, {'fn.test': {'value': {'int': 0, 'str': 'a'}}}, {'fn.test': {'value': {'int': 1}}}], 'found': 2}}}}]],
        [[{}, {'fn._verify': {'call': {'fn.test': {'value': {'int': 0}}}, 'count': {'atLeast': {'times': 1}}}}], [{}, {'ok': {}}]],
        [[{}, {'fn._verify': {'call': {'fn.test': {'value': {'int': 0}}}, 'count': {'atMost': {'times': 1}}}}], [{}, {'errorVerificationFailure': {'reason': {'tooManyMatchingCalls': {'wanted': {'atMost': {'times': 1}}, 'allCalls': [{'fn.test': {'value': {'int': 0, 'bool': True}}}, {'fn.test': {'value': {'int': 0, 'str': 'a'}}}, {'fn.test': {'value': {'int': 1}}}], 'found': 2}}}}]],
        [[{}, {'fn._verify': {'call': {'fn.test': {'value': {'int': 0}}}, 'count': {'atMost': {'times': 2}}}}], [{}, {'ok': {}}]],
    ],
    'strictMatchVerify': [
        [[{}, {'fn._clearStubs': {}}], [{}, {'ok': {}}]],
        [[{}, {'fn._clearCalls': {}}], [{}, {'ok': {}}]],
        [[{}, {'fn._createStub': {'stub': {'fn.test': {}, '->': {'ok': {}}}}}], [{}, {'ok': {}}]],
        [[{}, {'fn._verify': {'call': {'fn.test': {'value': {'int': 0}}}, 'strictMatch': True}}], [{}, {'errorVerificationFailure': {'reason': {'tooFewMatchingCalls': {'found': 0, 'allCalls': [], 'wanted': {'atLeast': {'times': 1}}}}}}]],
        [[{}, {'fn.test': {'value': {'int': 0}}}], [{}, {'ok': {}}]],
        [[{}, {'fn._verifyNoMoreInteractions': {}}], [{}, {'errorVerificationFailure': {'additionalUnverifiedCalls': [{'fn.test': {'value': {'int': 0}}}]}}]],
        [[{}, {'fn._verify': {'call': {'fn.test': {'value': {'int': 0}}}, 'strictMatch': True}}], [{}, {'ok': {}}]],
        [[{}, {'fn._verifyNoMoreInteractions': {}}], [{}, {'ok': {}}]],
        [[{}, {'fn._verify': {'call': {'fn.test': {'value': {'int': 1}}}, 'strictMatch': True}}], [{}, {'errorVerificationFailure': {'reason': {'tooFewMatchingCalls': {'found': 0, 'allCalls': [{'fn.test': {'value': {'int': 0}}}], 'wanted': {'atLeast': {'times': 1}}}}}}]],
        [[{}, {'fn._verify': {'call': {'fn.test': {'value': {'int': 0, 'str': 'a'}}}, 'strictMatch': True}}], [{}, {'errorVerificationFailure': {'reason': {'tooFewMatchingCalls': {'found': 0, 'allCalls': [{'fn.test': {'value': {'int': 0}}}], 'wanted': {'atLeast': {'times': 1}}}}}}]],
        [[{}, {'fn._verify': {'call': {'fn.test': {'value': {'int': 0}}}, 'strictMatch': True, 'count': {'exact': {'times': 0}}}}], [{}, {'errorVerificationFailure': {'reason': {'tooManyMatchingCalls': {'wanted': {'exact': {'times': 0}}, 'allCalls': [{'fn.test': {'value': {'int': 0}}}], 'found': 1}}}}]],
        [[{}, {'fn._verify': {'call': {'fn.test': {'value': {'int': 0}}}, 'strictMatch': True, 'count': {'exact': {'times': 2}}}}], [{}, {'errorVerificationFailure': {'reason': {'tooFewMatchingCalls': {'wanted': {'exact': {'times': 2}}, 'allCalls': [{'fn.test': {'value': {'int': 0}}}], 'found': 1}}}}]],
        [[{}, {'fn._verify': {'call': {'fn.test': {'value': {'int': 0}}}, 'strictMatch': True, 'count': {'exact': {'times': 1}}}}], [{}, {'ok': {}}]],
        [[{}, {'fn._verify': {'call': {'fn.test': {'value': {'int': 0}}}, 'strictMatch': True, 'count': {'atLeast': {'times': 2}}}}], [{}, {'errorVerificationFailure': {'reason': {'tooFewMatchingCalls': {'wanted': {'atLeast': {'times': 2}}, 'allCalls': [{'fn.test': {'value': {'int': 0}}}], 'found': 1}}}}]],
        [[{}, {'fn._verify': {'call': {'fn.test': {'value': {'int': 0}}}, 'strictMatch': True, 'count': {'atLeast': {'times': 1}}}}], [{}, {'ok': {}}]],
        [[{}, {'fn._verify': {'call': {'fn.test': {'value': {'int': 0}}}, 'strictMatch': True, 'count': {'atMost': {'times': 1}}}}], [{}, {'ok': {}}]],
    ],
    'multipleStrictMatchVerify': [
        [[{}, {'fn._clearStubs': {}}], [{}, {'ok': {}}]],
        [[{}, {'fn._clearCalls': {}}], [{}, {'ok': {}}]],
        [[{}, {'fn._createStub': {'stub': {'fn.test': {}, '->': {'ok': {}}}}}], [{}, {'ok': {}}]],
        [[{}, {'fn._verify': {'call': {'fn.test': {'value': {'int': 0}}}, 'strictMatch': True}}], [{}, {'errorVerificationFailure': {'reason': {'tooFewMatchingCalls': {'found': 0, 'allCalls': [], 'wanted': {'atLeast': {'times': 1}}}}}}]],
        [[{}, {'fn.test': {'value': {'int': 0}}}], [{}, {'ok': {}}]],
        [[{}, {'fn.test': {'value': {'int': 0, 'str': 'a'}}}], [{}, {'ok': {}}]],
        [[{}, {'fn._verifyNoMoreInteractions': {}}], [{}, {'errorVerificationFailure': {'additionalUnverifiedCalls': [{'fn.test': {'value': {'int': 0}}}, {'fn.test': {'value': {'int': 0, 'str': 'a'}}}]}}]],
        [[{}, {'fn._verify': {'call': {'fn.test': {'value': {'int': 0}}}, 'strictMatch': True}}], [{}, {'ok': {}}]],
        [[{}, {'fn._verifyNoMoreInteractions': {}}], [{}, {'errorVerificationFailure': {'additionalUnverifiedCalls': [{'fn.test': {'value': {'int': 0, 'str': 'a'}}}]}}]],
        [[{}, {'fn._verify': {'call': {'fn.test': {}}}}], [{}, {'ok': {}}]],
        [[{}, {'fn._verifyNoMoreInteractions': {}}], [{}, {'ok': {}}]],
        [[{}, {'fn._verify': {'call': {'fn.test': {'value': {'int': 1}}}, 'strictMatch': True}}], [{}, {'errorVerificationFailure': {'reason': {'tooFewMatchingCalls': {'found': 0, 'allCalls': [{'fn.test': {'value': {'int': 0}}}, {'fn.test': {'value': {'int': 0, 'str': 'a'}}}], 'wanted': {'atLeast': {'times': 1}}}}}}]],
        [[{}, {'fn._verify': {'call': {'fn.test': {'value': {'int': 0, 'str': 'b'}}}, 'strictMatch': True}}], [{}, {'errorVerificationFailure': {'reason': {'tooFewMatchingCalls': {'found': 0, 'allCalls': [{'fn.test': {'value': {'int': 0}}}, {'fn.test': {'value': {'int': 0, 'str': 'a'}}}], 'wanted': {'atLeast': {'times': 1}}}}}}]],
        [[{}, {'fn._verify': {'call': {'fn.test': {'value': {'int': 0}}}, 'strictMatch': True, 'count': {'exact': {'times': 0}}}}], [{}, {'errorVerificationFailure': {'reason': {'tooManyMatchingCalls': {'wanted': {'exact': {'times': 0}}, 'allCalls': [{'fn.test': {'value': {'int': 0}}}, {'fn.test': {'value': {'int': 0, 'str': 'a'}}}], 'found': 1}}}}]],
        [[{}, {'fn._verify': {'call': {'fn.test': {'value': {'int': 0}}}, 'strictMatch': True, 'count': {'exact': {'times': 2}}}}], [{}, {'errorVerificationFailure': {'reason': {'tooFewMatchingCalls': {'wanted': {'exact': {'times': 2}}, 'allCalls': [{'fn.test': {'value': {'int': 0}}}, {'fn.test': {'value': {'int': 0, 'str': 'a'}}}], 'found': 1}}}}]],
        [[{}, {'fn._verify': {'call': {'fn.test': {'value': {'int': 0}}}, 'strictMatch': True, 'count': {'exact': {'times': 1}}}}], [{}, {'ok': {}}]],
        [[{}, {'fn._verify': {'call': {'fn.test': {'value': {'int': 0}}}, 'strictMatch': True, 'count': {'atLeast': {'times': 2}}}}], [{}, {'errorVerificationFailure': {'reason': {'tooFewMatchingCalls': {'wanted': {'atLeast': {'times': 2}}, 'allCalls': [{'fn.test': {'value': {'int': 0}}}, {'fn.test': {'value': {'int': 0, 'str': 'a'}}}], 'found': 1}}}}]],
        [[{}, {'fn._verify': {'call': {'fn.test': {'value': {'int': 0}}}, 'strictMatch': True, 'count': {'atLeast': {'times': 1}}}}], [{}, {'ok': {}}]],
        [[{}, {'fn._verify': {'call': {'fn.test': {'value': {'int': 0}}}, 'strictMatch': True, 'count': {'atMost': {'times': 1}}}}], [{}, {'ok': {}}]],
    ],
    'multipleNestedPartialMatchVerify': [
        [[{}, {'fn._clearStubs': {}}], [{}, {'ok': {}}]],
        [[{}, {'fn._clearCalls': {}}], [{}, {'ok': {}}]],
        [[{}, {'fn._createStub': {'stub': {'fn.test': {}, '->': {'ok': {}}}}}], [{}, {'ok': {}}]],
        [[{}, {'fn._verify': {'call': {'fn.test': {'value': {'int': 0}}}}}], [{}, {'errorVerificationFailure': {'reason': {'tooFewMatchingCalls': {'found': 0, 'allCalls': [], 'wanted': {'atLeast': {'times': 1}}}}}}]],
        [[{}, {'fn.test': {'value': {'struct': {'required': True}}}}], [{}, {'ok': {}}]],
        [[{}, {'fn.test': {'value': {'struct': {'required': True, 'optional': True}}}}], [{}, {'ok': {}}]],
        [[{}, {'fn._verifyNoMoreInteractions': {}}], [{}, {'errorVerificationFailure': {'additionalUnverifiedCalls': [{'fn.test': {'value': {'struct': {'required': True}}}}, {'fn.test': {'value': {'struct': {'required': True, 'optional': True}}}}]}}]],
        [[{}, {'fn._verify': {'call': {'fn.test': {'value': {'struct': {'optional': True}}}}}}], [{}, {'ok': {}}]],
        [[{}, {'fn._verifyNoMoreInteractions': {}}], [{}, {'errorVerificationFailure': {'additionalUnverifiedCalls': [{'fn.test': {'value': {'struct': {'required': True}}}}]}}]],
        [[{}, {'fn._verify': {'call': {'fn.test': {}}}}], [{}, {'ok': {}}]],
        [[{}, {'fn._verifyNoMoreInteractions': {}}], [{}, {'ok': {}}]],
        [[{}, {'fn._verify': {'call': {'fn.test': {'value': {'struct': {'optional': True}}}}, 'count': {'exact': {'times': 1}}}}], [{}, {'ok': {}}]],
    ],
    'multipleReallyNestedPartialMatchVerify': [
        [[{}, {'fn._clearStubs': {}}], [{}, {'ok': {}}]],
        [[{}, {'fn._clearCalls': {}}], [{}, {'ok': {}}]],
        [[{}, {'fn._createStub': {'stub': {'fn.test': {}, '->': {'ok': {}}}}}], [{}, {'ok': {}}]],
        [[{}, {'fn._verify': {'call': {'fn.test': {'value': {'int': 0}}}}}], [{}, {'errorVerificationFailure': {'reason': {'tooFewMatchingCalls': {'found': 0, 'allCalls': [], 'wanted': {'atLeast': {'times': 1}}}}}}]],
        [[{}, {'fn.test': {'value': {'arrStruct': [{'required': False}, {'required': True}]}}}], [{}, {'ok': {}}]],
        [[{}, {'fn.test': {'value': {'arrStruct': [{'required': False}, {'required': True, 'optional': True}]}}}], [{}, {'ok': {}}]],
        [[{}, {'fn._verify': {'call': {'fn.test': {'value': {'arrStruct': [{'optional': True}]}}}}}], [{}, {'ok': {}}]],
        [[{}, {'fn._verifyNoMoreInteractions': {}}], [{}, {'errorVerificationFailure': {'additionalUnverifiedCalls': [{'fn.test': {'value': {'arrStruct': [{'required': False}, {'required': True}]}}}]}}]],
        [[{}, {'fn._verify': {'call': {'fn.test': {}}}}], [{}, {'ok': {}}]],
        [[{}, {'fn._verifyNoMoreInteractions': {}}], [{}, {'ok': {}}]],
        [[{}, {'fn._verify': {'call': {'fn.test': {'value': {'arrStruct': [{'optional': True}]}}}, 'count': {'exact': {'times': 1}}}}], [{}, {'ok': {}}]],
    ],
    'clearCalls': [
        [[{}, {'fn._clearStubs': {}}], [{}, {'ok': {}}]],
        [[{}, {'fn._clearCalls': {}}], [{}, {'ok': {}}]],
        [[{}, {'fn._createStub': {'stub': {'fn.test': {}, '->': {'ok': {}}}}}], [{}, {'ok': {}}]],
        [[{}, {'fn._verify': {'call': {'fn.test': {}}}}], [{}, {'errorVerificationFailure': {'reason': {'tooFewMatchingCalls': {'found': 0, 'allCalls': [], 'wanted': {'atLeast': {'times': 1}}}}}}]],
        [[{}, {'fn.test': {}}], [{}, {'ok': {}}]],
        [[{}, {'fn._verify': {'call': {'fn.test': {}}}}], [{}, {'ok': {}}]],
        [[{}, {'fn._clearCalls': {}}], [{}, {'ok': {}}]],
        [[{}, {'fn._verify': {'call': {'fn.test': {}}}}], [{}, {'errorVerificationFailure': {'reason': {'tooFewMatchingCalls': {'found': 0, 'allCalls': [], 'wanted': {'atLeast': {'times': 1}}}}}}]],
    ],
    'resultSuppliesMissingRequiredFields': [
        [[{}, {'fn._clearStubs': {}}], [{}, {'ok': {}}]],
        [[{}, {'fn._clearCalls': {}}], [{}, {'ok': {}}]],
        [[{}, {'fn.test': {}}], [{}, {'_errorNoMatchingStub': {}}]],
        [[{}, {'fn._createStub': {'stub': {'fn.test': {}, '->': {'ok': {'value': {'bool': True, 'struct': {'optional': True}}}}}}}], [{}, {'ok': {}}]],
        [[{}, {'fn.test': {}}], [{}, {'ok': {'value': {'bool': True, 'struct': {'optional': True, 'required': False}}}}]],
    ],
    'resultWithStartingValue': [
        [[{}, {'fn._clearStubs': {}}], [{}, {'ok': {}}]],
        [[{}, {'fn._clearCalls': {}}], [{}, {'ok': {}}]],
        [[{}, {'fn.test': {}}], [{}, {'_errorNoMatchingStub': {}}]],
        [[{}, {'fn._createStub': {'stub': {'fn.test': {}, '->': {'ok': {'value': {'bool': False, 'int': 0, 'num': 0.1, 'str': '', 'arrBool': [False], 'objBool': {'a': False}, 'struct': {'required': False}, 'enum': {'two': {'required': False}}, 'fn': {'required': False}}}}}}}], [{}, {'ok': {}}]],
        [[{}, {'fn.test': {}}], [{}, {'ok': {'value': {'bool': False, 'int': 0, 'num': 0.1, 'str': '', 'arrBool': [False], 'objBool': {'a': False}, 'struct': {'required': False}, 'enum': {'two': {'required': False}}, 'fn': {'required': False}}}}]],
    ],
}
