from typing import Any

from test.cases import get_values
from test.cases import additional_union_cases, additional_fn_cases, additional_integer_cases, additional_number_cases, additional_p2Union_cases, additional_p2Str_cases, additional_struct_cases


def generate_mock_cases(given_field: str, the_type, correct_values, additional_incorrect_values = []):
    for field, _, incorrect_values, base_path in get_values(given_field, the_type, correct_values, additional_incorrect_values):
        for incorrect_value, errors in incorrect_values:
            cases = [{'path': ['fn._createStub', 'stub', 'fn.test', 'value!'] + base_path + path, 'reason': reason} for reason, path in errors if 'RequiredStructFieldMissing' not in reason]
            if not cases:
                continue

            yield [[{}, {'fn._createStub': {'stub': {'fn.test': {'value!': {field: incorrect_value}}, '->': {'Ok': {}}}}}], [{}, {'_ErrorInvalidRequestBody': {'cases': cases}}]]

        for incorrect_value, errors in incorrect_values:
            cases = [{'path': ['fn._createStub', 'stub', '->', 'Ok', 'value!'] + base_path + path, 'reason': reason} for reason, path in errors if 'RequiredStructFieldMissing' not in reason]
            if not cases:
                continue
            yield [[{}, {'fn._createStub': {'stub': {'fn.test': {}, '->': {'Ok': {'value!': {field: incorrect_value}}}}}}], [{}, {'_ErrorInvalidRequestBody': {'cases': cases}}]]



invalid_cases = {
    'boolean': [v for v in generate_mock_cases('bool!', bool, [False, True])],
    'integer': [v for v in generate_mock_cases('int!', int, [0, -1, 1, 9223372036854775807, -9223372036854775808], additional_integer_cases)],
    'number': [v for v in generate_mock_cases('num!', float, [0, -1, 1, -1.7976931348623157e+308, -2.2250738585072014e-308, 2.2250738585072014e-308, 1.7976931348623157e+308, -0.1, 0.1], additional_number_cases)],
    'string': [v for v in generate_mock_cases('str!', str, ['', 'abc'])],
    'array': [v for v in generate_mock_cases('arr!', list, [[], [False, 0, 0.1, '']])],
    'object': [v for v in generate_mock_cases('obj!', dict, [{}, {'a': False, 'b': 0, 'c': 0.1, 'd': ''}])],
    'any': [v for v in generate_mock_cases('any!', Any, [False, 0, 0.1, '', [], {}])],
    'struct': [v for v in generate_mock_cases('struct!', dict, [{'required': False}, {'optional!': False, 'required': False}], additional_struct_cases)],
    'union': [v for v in generate_mock_cases('union!', dict, [{'One': {}}, {'Two':{'required': False}}, {'Two':{'optional!': False, 'required': False}}], additional_union_cases)],
    'fn': [v for v in generate_mock_cases('fn!', dict, [{'fn.example': {'required': False}}, {'fn.example': {'optional!': False, 'required': False}}], additional_fn_cases)],
    'p2Str': [v for v in generate_mock_cases('p2Str!', dict, [{'wrap': False, 'nest': [0]}, {'wrap': True, 'nest': [1]}], additional_p2Str_cases)],
    'p2Union': [v for v in generate_mock_cases('p2Union!', dict, [{'Two': {'ewrap': False, 'enest': [0]}}, {'Two': {'ewrap': True, 'enest': [1]}}], additional_p2Union_cases)],
    'stub': [
        [[{}, {'fn._createStub': {'stub': False}}], [{}, {'_ErrorInvalidRequestBody': {'cases': [{'path': ['fn._createStub', 'stub'], 'reason': {'TypeUnexpected': {'actual': {'Boolean': {}}, 'expected': {'Object': {}}}}}]}}]],
        [[{}, {'fn._createStub': {'stub': 0}}], [{}, {'_ErrorInvalidRequestBody': {'cases': [{'path': ['fn._createStub', 'stub'], 'reason': {'TypeUnexpected': {'actual': {'Number': {}}, 'expected': {'Object': {}}}}}]}}]],
        [[{}, {'fn._createStub': {'stub': ''}}], [{}, {'_ErrorInvalidRequestBody': {'cases': [{'path': ['fn._createStub', 'stub'], 'reason': {'TypeUnexpected': {'actual': {'String': {}}, 'expected': {'Object': {}}}}}]}}]],
        [[{}, {'fn._createStub': {'stub': []}}], [{}, {'_ErrorInvalidRequestBody': {'cases': [{'path': ['fn._createStub', 'stub'], 'reason': {'TypeUnexpected': {'actual': {'Array': {}}, 'expected': {'Object': {}}}}}]}}]],
        [[{}, {'fn._createStub': {'stub': {}}}], [{}, {'_ErrorInvalidRequestBody': {'cases': [{'path': ['fn._createStub', 'stub'], 'reason': {'ObjectKeyRegexMatchCountUnexpected': {'regex': '^fn\\..*$', 'actual': 0, 'expected': 1}}}]}}]],
        [[{}, {'fn._createStub': {'stub': {'fn.test': {}}}}], [{}, {'_ErrorInvalidRequestBody': {'cases': [{'path': ['fn._createStub', 'stub', '->'], 'reason': {'RequiredObjectKeyMissing': {}}}]}}]],
    ],
}

cases = {
    'emptyPartialMatchStub': [
        [[{}, {'fn._clearStubs': {}}], [{}, {'Ok': {}}]],
        [[{}, {'fn._clearCalls': {}}], [{}, {'Ok': {}}]],
        [[{}, {'fn.test': {}}], [{}, {'_ErrorNoMatchingStub': {}}]],
        [[{}, {'fn._createStub': {'stub': {'fn.test': {}, '->': {'Ok': {}}}}}], [{}, {'Ok': {}}]],
        [[{}, {'fn.test': {}}], [{}, {'Ok': {}}]],
    ],
    'partialMatchStub': [
        [[{}, {'fn._clearStubs': {}}], [{}, {'Ok': {}}]],
        [[{}, {'fn._clearCalls': {}}], [{}, {'Ok': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1}}}], [{}, {'_ErrorNoMatchingStub': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1, 'str!': 'a'}}}], [{}, {'_ErrorNoMatchingStub': {}}]],
        [[{}, {'fn._createStub': {'stub': {'fn.test': {'value!': {'int!': 1}}, '->': {'Ok': {'value!': {'bool!': True}}}}}}], [{}, {'Ok': {}}]],
        [[{}, {'fn.test': {}}], [{}, {'_ErrorNoMatchingStub': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 0}}}], [{}, {'_ErrorNoMatchingStub': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1}}}], [{}, {'Ok': {'value!': {'bool!': True}}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1, 'str!': 'a'}}}], [{}, {'Ok': {'value!': {'bool!': True}}}]],
    ],
    'multiplePartialMatchStub': [
        [[{}, {'fn._clearStubs': {}}], [{}, {'Ok': {}}]],
        [[{}, {'fn._clearCalls': {}}], [{}, {'Ok': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1}}}], [{}, {'_ErrorNoMatchingStub': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1, 'str!': 'a'}}}], [{}, {'_ErrorNoMatchingStub': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 0, 'str!': 'a'}}}], [{}, {'_ErrorNoMatchingStub': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1, 'str!': 'b'}}}], [{}, {'_ErrorNoMatchingStub': {}}]],
        [[{}, {'fn.test': {'value!': {'bool!': False, 'int!': 1, 'str!': 'a'}}}], [{}, {'_ErrorNoMatchingStub': {}}]],
        [[{}, {'fn._createStub': {'stub': {'fn.test': {'value!': {'int!': 1}}, '->': {'Ok': {'value!': {'bool!': True}}}}}}], [{}, {'Ok': {}}]],
        [[{}, {'fn._createStub': {'stub': {'fn.test': {'value!': {'str!': 'a'}}, '->': {'Ok': {'value!': {'bool!': False}}}}}}], [{}, {'Ok': {}}]],
        [[{}, {'fn._createStub': {'stub': {'fn.example': {}, '->': {'Ok': {}}}}}], [{}, {'Ok': {}}]],
        [[{}, {'fn.test': {}}], [{}, {'_ErrorNoMatchingStub': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 0}}}], [{}, {'_ErrorNoMatchingStub': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1}}}], [{}, {'Ok': {'value!': {'bool!': True}}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1, 'str!': 'a'}}}], [{}, {'Ok': {'value!': {'bool!': False}}}]],
        [[{}, {'fn.test': {'value!': {'int!': 0, 'str!': 'a'}}}], [{}, {'Ok': {'value!': {'bool!': False}}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1, 'str!': 'b'}}}], [{}, {'Ok': {'value!': {'bool!': True}}}]],
        [[{}, {'fn.test': {'value!': {'bool!': False, 'int!': 1, 'str!': 'a'}}}], [{}, {'Ok': {'value!': {'bool!': False}}}]],
    ],
    'multiplePartialMatchStubCount': [
        [[{}, {'fn._clearStubs': {}}], [{}, {'Ok': {}}]],
        [[{}, {'fn._clearCalls': {}}], [{}, {'Ok': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1}}}], [{}, {'_ErrorNoMatchingStub': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1, 'str!': 'a'}}}], [{}, {'_ErrorNoMatchingStub': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 0, 'str!': 'a'}}}], [{}, {'_ErrorNoMatchingStub': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1, 'str!': 'b'}}}], [{}, {'_ErrorNoMatchingStub': {}}]],
        [[{}, {'fn.test': {'value!': {'bool!': False, 'int!': 1, 'str!': 'a'}}}], [{}, {'_ErrorNoMatchingStub': {}}]],
        [[{}, {'fn._createStub': {'count!': 2, 'stub': {'fn.test': {'value!': {'int!': 1}}, '->': {'Ok': {'value!': {'bool!': True}}}}}}], [{}, {'Ok': {}}]],
        [[{}, {'fn._createStub': {'count!': 1, 'stub': {'fn.test': {'value!': {'str!': 'a'}}, '->': {'Ok': {'value!': {'bool!': False}}}}}}], [{}, {'Ok': {}}]],
        [[{}, {'fn._createStub': {'stub': {'fn.example': {}, '->': {'Ok': {}}}}}], [{}, {'Ok': {}}]],
        [[{}, {'fn.test': {}}], [{}, {'_ErrorNoMatchingStub': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 0}}}], [{}, {'_ErrorNoMatchingStub': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1}}}], [{}, {'Ok': {'value!': {'bool!': True}}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1, 'str!': 'a'}}}], [{}, {'Ok': {'value!': {'bool!': False}}}]],
        [[{}, {'fn.test': {'value!': {'int!': 0, 'str!': 'a'}}}], [{}, {'_ErrorNoMatchingStub': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1, 'str!': 'b'}}}], [{}, {'Ok': {'value!': {'bool!': True}}}]],
        [[{}, {'fn.test': {'value!': {'bool!': False, 'int!': 1, 'str!': 'a'}}}], [{}, {'_ErrorNoMatchingStub': {}}]],
    ],    
    'multipleNestedPartialMatchStub': [
        [[{}, {'fn._clearStubs': {}}], [{}, {'Ok': {}}]],
        [[{}, {'fn._clearCalls': {}}], [{}, {'Ok': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1}}}], [{}, {'_ErrorNoMatchingStub': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1, 'str!': 'a'}}}], [{}, {'_ErrorNoMatchingStub': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 0, 'str!': 'a'}}}], [{}, {'_ErrorNoMatchingStub': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1, 'str!': 'b'}}}], [{}, {'_ErrorNoMatchingStub': {}}]],
        [[{}, {'fn.test': {'value!': {'bool!': False, 'int!': 1, 'str!': 'a'}}}], [{}, {'_ErrorNoMatchingStub': {}}]],
        [[{}, {'fn._createStub': {'stub': {'fn.test': {'value!': {'struct!': {'optional!': True}}}, '->': {'Ok': {'value!': {'bool!': True}}}}}}], [{}, {'Ok': {}}]],
        [[{}, {'fn._createStub': {'stub': {'fn.test': {'value!': {'struct!': {'required': True}}}, '->': {'Ok': {'value!': {'bool!': False}}}}}}], [{}, {'Ok': {}}]],
        [[{}, {'fn._createStub': {'stub': {'fn.example': {}, '->': {'Ok': {}}}}}], [{}, {'Ok': {}}]],
        [[{}, {'fn.test': {}}], [{}, {'_ErrorNoMatchingStub': {}}]],
        [[{}, {'fn.test': {'value!': {'struct!': {'required': False}}}}], [{}, {'_ErrorNoMatchingStub': {}}]],
        [[{}, {'fn.test': {'value!': {'struct!': {'optional!': False, 'required': False}}}}], [{}, {'_ErrorNoMatchingStub': {}}]],
        [[{}, {'fn.test': {'value!': {'struct!': {'optional!': True, 'required': True}}}}], [{}, {'Ok': {'value!': {'bool!': False}}}]],
        [[{}, {'fn.test': {'value!': {'struct!': {'optional!': True, 'required': False}}}}], [{}, {'Ok': {'value!': {'bool!': True}}}]],
        [[{}, {'fn.test': {'value!': {'struct!': {'required': True}}}}], [{}, {'Ok': {'value!': {'bool!': False}}}]],
        [[{}, {'fn.test': {'value!': {'struct!': {'optional!': False, 'required': True}}}}], [{}, {'Ok': {'value!': {'bool!': False}}}]],
        [[{}, {'fn.test': {'value!': {'struct!': {'optional!': True, 'required': False}, 'str!': 'b'}}}], [{}, {'Ok': {'value!': {'bool!': True}}}]],
    ],
    'multipleNestedPartialMatchStubCount': [
        [[{}, {'fn._clearStubs': {}}], [{}, {'Ok': {}}]],
        [[{}, {'fn._clearCalls': {}}], [{}, {'Ok': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1}}}], [{}, {'_ErrorNoMatchingStub': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1, 'str!': 'a'}}}], [{}, {'_ErrorNoMatchingStub': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 0, 'str!': 'a'}}}], [{}, {'_ErrorNoMatchingStub': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1, 'str!': 'b'}}}], [{}, {'_ErrorNoMatchingStub': {}}]],
        [[{}, {'fn.test': {'value!': {'bool!': False, 'int!': 1, 'str!': 'a'}}}], [{}, {'_ErrorNoMatchingStub': {}}]],
        [[{}, {'fn._createStub': {'count!': 1, 'stub': {'fn.test': {'value!': {'struct!': {'optional!': True}}}, '->': {'Ok': {'value!': {'bool!': True}}}}}}], [{}, {'Ok': {}}]],
        [[{}, {'fn._createStub': {'count!': 2, 'stub': {'fn.test': {'value!': {'struct!': {'required': True}}}, '->': {'Ok': {'value!': {'bool!': False}}}}}}], [{}, {'Ok': {}}]],
        [[{}, {'fn._createStub': {'stub': {'fn.example': {}, '->': {'Ok': {}}}}}], [{}, {'Ok': {}}]],
        [[{}, {'fn.test': {}}], [{}, {'_ErrorNoMatchingStub': {}}]],
        [[{}, {'fn.test': {'value!': {'struct!': {'required': False}}}}], [{}, {'_ErrorNoMatchingStub': {}}]],
        [[{}, {'fn.test': {'value!': {'struct!': {'optional!': False, 'required': False}}}}], [{}, {'_ErrorNoMatchingStub': {}}]],
        [[{}, {'fn.test': {'value!': {'struct!': {'optional!': True, 'required': True}}}}], [{}, {'Ok': {'value!': {'bool!': False}}}]],
        [[{}, {'fn.test': {'value!': {'struct!': {'optional!': True, 'required': False}}}}], [{}, {'Ok': {'value!': {'bool!': True}}}]],
        [[{}, {'fn.test': {'value!': {'struct!': {'required': True}}}}], [{}, {'Ok': {'value!': {'bool!': False}}}]],
        [[{}, {'fn.test': {'value!': {'struct!': {'optional!': False, 'required': True}}}}], [{}, {'_ErrorNoMatchingStub': {}}]],
        [[{}, {'fn.test': {'value!': {'struct!': {'optional!': True, 'required': False}, 'str!': 'b'}}}], [{}, {'_ErrorNoMatchingStub': {}}]],
    ],    
    'multipleReallyNestedPartialMatchStub': [
        [[{}, {'fn._clearStubs': {}}], [{}, {'Ok': {}}]],
        [[{}, {'fn._clearCalls': {}}], [{}, {'Ok': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1}}}], [{}, {'_ErrorNoMatchingStub': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1, 'str!': 'a'}}}], [{}, {'_ErrorNoMatchingStub': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 0, 'str!': 'a'}}}], [{}, {'_ErrorNoMatchingStub': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1, 'str!': 'b'}}}], [{}, {'_ErrorNoMatchingStub': {}}]],
        [[{}, {'fn.test': {'value!': {'bool!': False, 'int!': 1, 'str!': 'a'}}}], [{}, {'_ErrorNoMatchingStub': {}}]],
        [[{}, {'fn._createStub': {'stub': {'fn.test': {'value!': {'arrStruct!': [{'optional!': True}]}}, '->': {'Ok': {'value!': {'bool!': True}}}}}}], [{}, {'Ok': {}}]],
        [[{}, {'fn._createStub': {'stub': {'fn.test': {'value!': {'arrStruct!': [{'required': True}]}}, '->': {'Ok': {'value!': {'bool!': False}}}}}}], [{}, {'Ok': {}}]],
        [[{}, {'fn._createStub': {'stub': {'fn.example': {}, '->': {'Ok': {}}}}}], [{}, {'Ok': {}}]],
        [[{}, {'fn.test': {}}], [{}, {'_ErrorNoMatchingStub': {}}]],
        [[{}, {'fn.test': {'value!': {'arrStruct!': [{'required': False}, {'optional!': False, 'required': False}]}}}], [{}, {'_ErrorNoMatchingStub': {}}]],
        [[{}, {'fn.test': {'value!': {'arrStruct!': [{'required': False}, {'optional!': True, 'required': False}]}}}], [{}, {'Ok': {'value!': {'bool!': True}}}]],
        [[{}, {'fn.test': {'value!': {'arrStruct!': [{'required': False}, {'optional!': True, 'required': True}]}}}], [{}, {'Ok': {'value!': {'bool!': False}}}]],
        [[{}, {'fn.test': {'value!': {'arrStruct!': [{'required': False}, {'optional!': False, 'required': True}]}}}], [{}, {'Ok': {'value!': {'bool!': False}}}]],
        [[{}, {'fn.test': {'value!': {'arrStruct!': [{'required': False}, {'optional!': True, 'required': False}], 'str!': 'b'}}}], [{}, {'Ok': {'value!': {'bool!': True}}}]],
    ],
    'strictMatchStub': [
        [[{}, {'fn._clearStubs': {}}], [{}, {'Ok': {}}]],
        [[{}, {'fn._clearCalls': {}}], [{}, {'Ok': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1}}}], [{}, {'_ErrorNoMatchingStub': {}}]],
        [[{}, {'fn._createStub': {'stub': {'fn.test': {'value!': {'int!': 1}}, '->': {'Ok': {'value!': {'bool!': True}}}}, 'strictMatch!': True}}], [{}, {'Ok': {}}]],
        [[{}, {'fn.test': {}}], [{}, {'_ErrorNoMatchingStub': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 0}}}], [{}, {'_ErrorNoMatchingStub': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1}}}], [{}, {'Ok': {'value!': {'bool!': True}}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1, 'str!': 'a'}}}], [{}, {'_ErrorNoMatchingStub': {}}]],
    ],
    'multipleStrictMatchStub': [
        [[{}, {'fn._clearStubs': {}}], [{}, {'Ok': {}}]],
        [[{}, {'fn._clearCalls': {}}], [{}, {'Ok': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1}}}], [{}, {'_ErrorNoMatchingStub': {}}]],
        [[{}, {'fn.test': {'value!': {'str!': 'a'}}}], [{}, {'_ErrorNoMatchingStub': {}}]],
        [[{}, {'fn._createStub': {'stub': {'fn.test': {'value!': {'int!': 1}}, '->': {'Ok': {'value!': {'bool!': True}}}}, 'strictMatch!': True}}], [{}, {'Ok': {}}]],
        [[{}, {'fn._createStub': {'stub': {'fn.test': {'value!': {'str!': 'a'}}, '->': {'Ok': {'value!': {'bool!': False}}}}, 'strictMatch!': True}}], [{}, {'Ok': {}}]],
        [[{}, {'fn.test': {}}], [{}, {'_ErrorNoMatchingStub': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 0}}}], [{}, {'_ErrorNoMatchingStub': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1}}}], [{}, {'Ok': {'value!': {'bool!': True}}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1, 'str!': 'a'}}}], [{}, {'_ErrorNoMatchingStub': {}}]],
        [[{}, {'fn.test': {'value!': {'str!': 'a'}}}], [{}, {'Ok': {'value!': {'bool!': False}}}]],
        [[{}, {'fn.test': {'value!': {'int!': 0, 'str!': 'a'}}}], [{}, {'_ErrorNoMatchingStub': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1, 'str!': 'b'}}}], [{}, {'_ErrorNoMatchingStub': {}}]],
        [[{}, {'fn.test': {'value!': {'bool!': False, 'int!': 1, 'str!': 'a'}}}], [{}, {'_ErrorNoMatchingStub': {}}]],
    ],
    'mixedPartialStrictMatchStub': [
        [[{}, {'fn._clearStubs': {}}], [{}, {'Ok': {}}]],
        [[{}, {'fn._clearCalls': {}}], [{}, {'Ok': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1}}}], [{}, {'_ErrorNoMatchingStub': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1, 'str!': 'a'}}}], [{}, {'_ErrorNoMatchingStub': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1, 'str!': 'b'}}}], [{}, {'_ErrorNoMatchingStub': {}}]],
        [[{}, {'fn.test': {'value!': {'bool!': False, 'int!': 1, 'str!': 'a'}}}], [{}, {'_ErrorNoMatchingStub': {}}]],
        [[{}, {'fn._createStub': {'stub': {'fn.test': {'value!': {'int!': 1}}, '->': {'Ok': {'value!': {'bool!': True}}}}}}], [{}, {'Ok': {}}]],
        [[{}, {'fn._createStub': {'stub': {'fn.test': {'value!': {'int!': 1, 'str!': 'a'}}, '->': {'Ok': {'value!': {'bool!': False}}}}, 'strictMatch!': True}}], [{}, {'Ok': {}}]],
        [[{}, {'fn.test': {}}], [{}, {'_ErrorNoMatchingStub': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 0}}}], [{}, {'_ErrorNoMatchingStub': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1}}}], [{}, {'Ok': {'value!': {'bool!': True}}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1, 'str!': 'a'}}}], [{}, {'Ok': {'value!': {'bool!': False}}}]],
        [[{}, {'fn.test': {'value!': {'int!': 0, 'str!': 'a'}}}], [{}, {'_ErrorNoMatchingStub': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1, 'str!': 'b'}}}], [{}, {'Ok': {'value!': {'bool!': True}}}]],
        [[{}, {'fn.test': {'value!': {'bool!': False, 'int!': 1, 'str!': 'a'}}}], [{}, {'Ok': {'value!': {'bool!': True}}}]],
    ],
    'mixedStrictPartialMatchStub': [
        [[{}, {'fn._clearStubs': {}}], [{}, {'Ok': {}}]],
        [[{}, {'fn._clearCalls': {}}], [{}, {'Ok': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1}}}], [{}, {'_ErrorNoMatchingStub': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1, 'str!': 'a'}}}], [{}, {'_ErrorNoMatchingStub': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1, 'str!': 'b'}}}], [{}, {'_ErrorNoMatchingStub': {}}]],
        [[{}, {'fn.test': {'value!': {'bool!': False, 'int!': 1, 'str!': 'a'}}}], [{}, {'_ErrorNoMatchingStub': {}}]],
        [[{}, {'fn._createStub': {'stub': {'fn.test': {'value!': {'int!': 1, 'str!': 'a'}}, '->': {'Ok': {'value!': {'bool!': False}}}}, 'strictMatch!': True}}], [{}, {'Ok': {}}]],
        [[{}, {'fn._createStub': {'stub': {'fn.test': {'value!': {'int!': 1}}, '->': {'Ok': {'value!': {'bool!': True}}}}}}], [{}, {'Ok': {}}]],
        [[{}, {'fn.test': {}}], [{}, {'_ErrorNoMatchingStub': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 0}}}], [{}, {'_ErrorNoMatchingStub': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1}}}], [{}, {'Ok': {'value!': {'bool!': True}}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1, 'str!': 'a'}}}], [{}, {'Ok': {'value!': {'bool!': True}}}]],
        [[{}, {'fn.test': {'value!': {'int!': 0, 'str!': 'a'}}}], [{}, {'_ErrorNoMatchingStub': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1, 'str!': 'b'}}}], [{}, {'Ok': {'value!': {'bool!': True}}}]],
        [[{}, {'fn.test': {'value!': {'bool!': False, 'int!': 1, 'str!': 'a'}}}], [{}, {'Ok': {'value!': {'bool!': True}}}]],
    ],
    'clearStubs': [
        [[{}, {'fn._clearStubs': {}}], [{}, {'Ok': {}}]],
        [[{}, {'fn._clearCalls': {}}], [{}, {'Ok': {}}]],
        [[{}, {'fn.test': {}}], [{}, {'_ErrorNoMatchingStub': {}}]],
        [[{}, {'fn._createStub': {'stub': {'fn.test': {}, '->': {'Ok': {}}}}}], [{}, {'Ok': {}}]],
        [[{}, {'fn.test': {}}], [{}, {'Ok': {}}]],
        [[{}, {'fn._clearStubs': {}}], [{}, {'Ok': {}}]],
        [[{}, {'fn.test': {}}], [{}, {'_ErrorNoMatchingStub': {}}]],
    ],
    'generation': [
        [[{}, {'fn._setRandomSeed': {'seed': 0}}], [{}, {'Ok': {}}]],
        [[{}, {'fn._clearStubs': {}}], [{}, {'Ok': {}}]],
        [[{}, {'fn._clearCalls': {}}], [{}, {'Ok': {}}]],
        [[{'_mockEnableGeneratedStub': True}, {'fn.test': {}}], [{}, {'Ok': {'value!': {'arrArr': [[794471793, 'L+Uz1w'], []], 'arrInt': [], 'arrNullAny': [True, None], 'arrNullBool': [True], 'arrNullInt': [1680572000], 'arrNullNum': [None], 'arrNullObj': [], 'arrNullStr': ['fFlptw', None], 'arrNullStruct': [{'required': False}, None], 'arrNullUnion': [{'One': {}}, {'One': {}}], 'arrNum': [0.3827860703493389, 0.2856478705854433], 'arrObj': [], 'arrP2Str': [{'nest': [1179349310, 1049906079], 'wrap': True}], 'arrStr': ['MERT2A'], 'arrStruct': [{'required': False}, {'required': False}], 'arrUnion': [{'Two': {'required': False}}, {'One': {}}], 'int!': 2128634632, 'nullArr': None, 'nullBool': None, 'nullFn': None, 'nullNum': 0.3797700886126377, 'nullP2Str': {'nest': [1710661176, 629579281], 'wrap': True}, 'nullP2Union': {'Two': {'enest': [], 'ewrap': True}}, 'nullStr': 'Vg2zTg', 'obj!': {'B7paZw': 1557864637, 'fmoFaA': 'MGjeJg'}, 'objInt': {'SPhqCg': 1339056763, 'ULNNrA': 1024109173}, 'objNullAny': {'M7sc1g': None}, 'objNullArr': {'OiQwYg': None}, 'objNullBool': {}, 'objNullFn': {'dft53A': {'optional!': True, 'required': True}, 'fDiAYQ': None}, 'objNullP2Union': {'SvfamQ': None}, 'objNullStr': {'I+KHVQ': None}, 'objNullStruct': {'S5FD0Q': {'required': True}, 'UJVMDQ': {'required': False}}, 'objNullUnion': {}, 'objNum': {'Z9TvxQ': 0.26473592959131875}, 'objP2Union': {'CgRGJw': {'One': {}}, 'dH5SfQ': {'One': {}}}, 'objStr': {}, 'objStruct': {}, 'pStrAny': {'wrap': 'bKmdWA'}, 'pStrNullAny': {'wrap': False}, 'pStrNullFn': {'wrap': None}, 'pStrNullNum': {'wrap': None}, 'pStrNullObj': {'wrap': None}, 'pStrNullP2Str': {'wrap': {'nest': [], 'wrap': True}}, 'pStrNullStr': {'wrap': 'EtZIWQ'}, 'pStrNullStruct': {'wrap': None}, 'pStrNullUnion': {'wrap': {'One': {}}}, 'pStrStruct': {'wrap': {'required': True}}, 'pUnionAny': {'Two': {'ewrap': 'VCNz7w'}}, 'pUnionFn': {'Two': {'ewrap': {'optional!': True, 'required': False}}}, 'pUnionInt': {'One': {}}, 'pUnionNullBool': {'One': {}}, 'pUnionNullFn': {'One': {}}, 'pUnionNullInt': {'One': {}}, 'pUnionNullNum': {'One': {}}, 'pUnionNullObj': {'One': {}}, 'pUnionNullStruct': {'Two': {'ewrap': None}}, 'pUnionNullUnion': {'One': {}}, 'pUnionNum': {'One': {}}, 'pUnionP2Str': {'Two': {'ewrap': {'nest': [1177796587], 'wrap': True}}}, 'pUnionP2Union': {'One': {}}, 'pUnionStr': {'One': {}}, 'pUnionStruct': {'One': {}}, 'pUnionUnion': {'One': {}}, 'str!': 'YWGQvw', 'struct!': {'required': False}, 'union!': {'One': {}}}}}]],
        [[{'_mockEnableGeneratedStub': True}, {'fn.test': {}}], [{}, {'Ok': {'value!': {'any': False, 'arrArr': [[]], 'arrInt': [72727194, 1685557195], 'arrNullBool': [False, None], 'arrNullFn': [None], 'arrNullNum': [None, None], 'arrNullObj': [None, {}], 'arrNullUnion': [{'Two': {'optional!': True, 'required': True}}, {'One': {}}], 'arrObj': [{'A5A23Q': True, 'Xi4+IA': 'VnLRng'}, {}], 'arrP2Union': [{'Two': {'enest': [949466385, 770274934], 'ewrap': False}}], 'arrStruct': [], 'fn!': {'optional!': True, 'required': False}, 'int!': 1125421402, 'nullStruct': {'optional!': True, 'required': True}, 'nullUnion': None, 'num!': 0.2326904993106884, 'objAny': {}, 'objBool': {'YNLVsA': False, 'eEGbrg': False}, 'objFn': {'SQ/Eug': {'required': True}}, 'objNullArr': {}, 'objNullObj': {}, 'objNullP2Union': {'HkLQag': {'One': {}}, 'YRFa0Q': None}, 'objNullStr': {}, 'objNum': {'U+OTCQ': 0.2754375531145432}, 'objP2Str': {'EZ11Jw': {'nest': [1989712253, 1902878834], 'wrap': False}, 'R+goGg': {'nest': [245902632, 273521217], 'wrap': True}}, 'p2Str!': {'nest': [1563085770, 495747387], 'wrap': False}, 'pStrArr': {'wrap': []}, 'pStrBool': {'wrap': True}, 'pStrFn': {'wrap': {'required': True}}, 'pStrInt': {'wrap': 1083019535}, 'pStrNullArr': {'wrap': None}, 'pStrNullNum': {'wrap': None}, 'pStrNullP2Str': {'wrap': None}, 'pStrNullP2Union': {'wrap': None}, 'pStrNullStr': {'wrap': None}, 'pStrNullUnion': {'wrap': None}, 'pStrObj': {'wrap': {'SIHKZA': 2113922, 'bobAkQ': 'drpL9w'}}, 'pStrP2Str': {'wrap': {'nest': [], 'wrap': True}}, 'pStrStr': {'wrap': 'SXoB/A'}, 'pStrStruct': {'wrap': {'required': False}}, 'pUnionAny': {'One': {}}, 'pUnionBool': {'Two': {'ewrap': False}}, 'pUnionInt': {'Two': {'ewrap': 931916926}}, 'pUnionNullAny': {'One': {}}, 'pUnionNullBool': {'Two': {'ewrap': True}}, 'pUnionNullP2Union': {'One': {}}, 'pUnionNullStr': {'One': {}}, 'pUnionNullStruct': {'One': {}}, 'pUnionNullUnion': {'One': {}}, 'pUnionNum': {'One': {}}, 'pUnionObj': {'One': {}}, 'pUnionP2Str': {'One': {}}, 'pUnionStr': {'Two': {'ewrap': 'NPDkYA'}}, 'pUnionUnion': {'Two': {'ewrap': {'One': {}}}}, 'pdStr!': {'dwrap': {'wrap': False}}, 'struct!': {'optional!': False, 'required': True}, 'union!': {'Two': {'optional!': False, 'required': True}}}}}]],
        [[{'_mockEnableGeneratedStub': True}, {'fn.test': {}}], [{}, {'Ok': {}}]],
        [[{'_mockEnableGeneratedStub': True}, {'fn.test': {}}], [{}, {'Ok': {'value!': {'any': 'NDIKRQ', 'arr!': [], 'arrAny': [], 'arrArr': [], 'arrInt': [], 'arrNullArr': [[1560713546], None], 'arrNullBool': [], 'arrNullFn': [None, {'required': True}], 'arrNullP2Str': [], 'arrNullUnion': [None], 'arrNum': [], 'arrP2Str': [], 'arrStr': ['fCcjfw', 'fLT/TA'], 'bool!': True, 'fn!': {'optional!': True, 'required': False}, 'nullBool': False, 'nullFn': {'optional!': False, 'required': False}, 'nullNum': None, 'nullObj': {'Lqt5uQ': 'WHxNXw', 'Xn8ssg': True}, 'nullStr': None, 'nullUnion': None, 'obj!': {'IUFDKQ': True, 'RrgmYg': False}, 'objAny': {'EW0uYQ': 'Aux2Rw', 'NOQfug': 'SDb9yA'}, 'objArr': {'H7rsEg': [542394521, True], 'WqDYDA': []}, 'objBool': {'Xolo+A': False}, 'objNullAny': {'BZJ9wg': True, 'MA60Dg': False}, 'objNullInt': {}, 'objNullNum': {'Xy7gfQ': 0.31268476914397053}, 'objNullStruct': {'SCzDWA': None, 'UPVmyg': None}, 'objNullUnion': {'E6wFIg': {'One': {}}, 'Ola9BA': None}, 'objNum': {'D3tgDw': 0.24439647805094442}, 'objObj': {'RJfuKw': {'KKikIQ': False, 'YuVvNA': 'L8P60g'}, 'XUn3ow': {'UVC2WQ': 'Efpq/w'}}, 'objUnion': {'IFy8gg': {'Two': {'optional!': True, 'required': True}}, 'VQ0m9g': {'Two': {'required': True}}}, 'pStrArr': {'wrap': [1994835713, 'HNxP5w']}, 'pStrBool': {'wrap': False}, 'pStrInt': {'wrap': 837392640}, 'pStrNullInt': {'wrap': 567828475}, 'pStrNullObj': {'wrap': {'PxMNxA': 'Zvyj4g'}}, 'pStrNullStr': {'wrap': None}, 'pStrObj': {'wrap': {'bPMnSA': 'NMiDBg'}}, 'pStrP2Str': {'wrap': {'nest': [], 'wrap': False}}, 'pStrP2Union': {'wrap': {'Two': {'enest': [189850649], 'ewrap': False}}}, 'pStrStr': {'wrap': 'buzJjA'}, 'pUnionAny': {'One': {}}, 'pUnionArr': {'One': {}}, 'pUnionInt': {'One': {}}, 'pUnionNullBool': {'One': {}}, 'pUnionNullFn': {'One': {}}, 'pUnionNullInt': {'One': {}}, 'pUnionNullP2Str': {'One': {}}, 'pUnionNullStr': {'Two': {'ewrap': 'XrprQw'}}, 'pUnionNum': {'Two': {'ewrap': 0.22136663983470237}}, 'pUnionP2Str': {'Two': {'ewrap': {'nest': [240416817], 'wrap': True}}}, 'pUnionP2Union': {'One': {}}, 'pUnionStruct': {'Two': {'ewrap': {'required': True}}}, 'pUnionUnion': {'Two': {'ewrap': {'One': {}}}}, 'struct!': {'required': False}}}}]],
        [[{'_mockEnableGeneratedStub': True}, {'fn.test': {}}], [{}, {'Ok': {'value!': {'arrArr': [[], [785179212, True]], 'arrFn': [{'required': True}], 'arrInt': [468154882, 1212661523], 'arrNullAny': [None], 'arrNullBool': [], 'arrNullFn': [], 'arrNullInt': [470083431], 'arrNullNum': [], 'arrNullP2Str': [], 'arrNullP2Union': [None], 'arrNullStr': ['Q4Vfew'], 'arrNullStruct': [None, None], 'arrNullUnion': [None, None], 'arrNum': [0.32707592899638815], 'arrUnion': [], 'fn!': {'optional!': True, 'required': False}, 'nullArr': None, 'nullStr': None, 'nullStruct': None, 'nullUnion': {'One': {}}, 'num!': 0.27274133653453936, 'obj!': {'BUYkxQ': True, 'WM3TKA': 10338790}, 'objArr': {'A3QWcg': [False]}, 'objNullBool': {}, 'objNullInt': {}, 'objNullNum': {'MpsAIg': 0.3757001112882113, 'U0436Q': 0.20010123350040954}, 'objNullP2Str': {'MYwoXQ': {'nest': [], 'wrap': False}, 'dW+tKw': {'nest': [1076112198, 314175751], 'wrap': False}}, 'objNullP2Union': {'IfPx9g': {'One': {}}, 'bBX5/w': {'Two': {'enest': [1490695963, 1268113592], 'ewrap': True}}}, 'objNullStr': {'CdHeyQ': None, 'Po5ukw': None}, 'objP2Union': {'UlrEpg': {'Two': {'enest': [245963069], 'ewrap': True}}}, 'objUnion': {'Go8y9Q': {'One': {}}, 'c5hj3w': {'One': {}}}, 'p2Str!': {'nest': [], 'wrap': False}, 'p2Union!': {'Two': {'enest': [259509165], 'ewrap': True}}, 'pStrAny': {'wrap': 'Z3J1qQ'}, 'pStrBool': {'wrap': False}, 'pStrInt': {'wrap': 783023339}, 'pStrNullAny': {'wrap': None}, 'pStrNullFn': {'wrap': None}, 'pStrNullInt': {'wrap': None}, 'pStrNullNum': {'wrap': None}, 'pStrNullP2Union': {'wrap': None}, 'pStrNullStr': {'wrap': 'LfcFeA'}, 'pStrObj': {'wrap': {'BV82Qg': 676400016}}, 'pStrP2Str': {'wrap': {'nest': [1377768623], 'wrap': False}}, 'pStrP2Union': {'wrap': {'One': {}}}, 'pStrStruct': {'wrap': {'optional!': False, 'required': True}}, 'pStrUnion': {'wrap': {'Two': {'required': False}}}, 'pUnionBool': {'Two': {'ewrap': False}}, 'pUnionNullAny': {'One': {}}, 'pUnionNullBool': {'Two': {'ewrap': True}}, 'pUnionNullInt': {'One': {}}, 'pUnionNullObj': {'Two': {'ewrap': None}}, 'pUnionNullP2Str': {'One': {}}, 'pUnionNullP2Union': {'One': {}}, 'pUnionNullUnion': {'One': {}}, 'pUnionNum': {'One': {}}, 'pUnionObj': {'One': {}}, 'pUnionStruct': {'Two': {'ewrap': {'optional!': False, 'required': True}}}, 'union!': {'One': {}}}}}]],
    ],
    'emptyPartialMatchVerify': [
        [[{}, {'fn._clearStubs': {}}], [{}, {'Ok': {}}]],
        [[{}, {'fn._clearCalls': {}}], [{}, {'Ok': {}}]],
        [[{}, {'fn._createStub': {'stub': {'fn.test': {}, '->': {'Ok': {}}}}}], [{}, {'Ok': {}}]],
        [[{}, {'fn._verify': {'call': {'fn.test': {}}}}], [{}, {'ErrorVerificationFailure': {'reason': {'TooFewMatchingCalls': {'allCalls': [], 'found': 0, 'wanted': {'AtLeast': {'times': 1}}}}}}]],
        [[{}, {'fn._verify': {'call': {'fn.test': {}}, 'count!': {'Exact': {'times': 1}}}}], [{}, {'ErrorVerificationFailure': {'reason': {'TooFewMatchingCalls': {'allCalls': [], 'found': 0, 'wanted': {'Exact': {'times': 1}}}}}}]],
        [[{}, {'fn._verify': {'call': {'fn.test': {}}, 'count!': {'AtLeast': {'times': 1}}}}], [{}, {'ErrorVerificationFailure': {'reason': {'TooFewMatchingCalls': {'allCalls': [], 'wanted': {'AtLeast': {'times': 1}}, 'found': 0}}}}]],
        [[{}, {'fn._verify': {'call': {'fn.test': {}}, 'count!': {'AtMost': {'times': 0}}}}], [{}, {'Ok': {}}]],
        [[{}, {'fn.test': {}}], [{}, {'Ok': {}}]],
        [[{}, {'fn._verifyNoMoreInteractions': {}}], [{}, {'ErrorVerificationFailure': {'additionalUnverifiedCalls': [{'fn.test': {}}]}}]],
        [[{}, {'fn._verify': {'call': {'fn.test': {}}}}], [{}, {'Ok': {}}]],
        [[{}, {'fn._verifyNoMoreInteractions': {}}], [{}, {'Ok': {}}]],
        [[{}, {'fn._verify': {'call': {'fn.test': {}}, 'count!': {'Exact': {'times': 1}}}}], [{}, {'Ok': {}}]],
        [[{}, {'fn._verify': {'call': {'fn.test': {}}, 'count!': {'AtLeast': {'times': 1}}}}], [{}, {'Ok': {}}]],
        [[{}, {'fn._verify': {'call': {'fn.test': {}}, 'count!': {'AtLeast': {'times': 2}}}}], [{}, {'ErrorVerificationFailure': {'reason': {'TooFewMatchingCalls': {'allCalls': [{'fn.test': {}}], 'found': 1, 'wanted': {'AtLeast': {'times': 2}}}}}}]],
        [[{}, {'fn._verify': {'call': {'fn.test': {}}, 'count!': {'AtMost': {'times': 1}}}}], [{}, {'Ok': {}}]],
        [[{}, {'fn._verify': {'call': {'fn.test': {}}, 'count!': {'AtMost': {'times': 0}}}}], [{}, {'ErrorVerificationFailure': {'reason': {'TooManyMatchingCalls': {'wanted': {'AtMost': {'times': 0}}, 'allCalls': [{'fn.test': {}}], 'found': 1}}}}]],
    ],
    'partialMatchVerify': [
        [[{}, {'fn._clearStubs': {}}], [{}, {'Ok': {}}]],
        [[{}, {'fn._clearCalls': {}}], [{}, {'Ok': {}}]],
        [[{}, {'fn._createStub': {'stub': {'fn.test': {'value!': {'int!': 0}}, '->': {'Ok': {'value!': {'bool!': True}}}}}}], [{}, {'Ok': {}}]],
        [[{}, {'fn._verify': {'call': {'fn.test': {'value!': {'int!': 0}}}}}], [{}, {'ErrorVerificationFailure': {'reason': {'TooFewMatchingCalls': {'found': 0, 'allCalls': [], 'wanted': {'AtLeast': {'times': 1}}}}}}]],
        [[{}, {'fn.test': {'value!': {'int!': 0, 'str!': 'a'}}}], [{}, {'Ok': {'value!': {'bool!': True}}}]],
        [[{}, {'fn._verifyNoMoreInteractions': {}}], [{}, {'ErrorVerificationFailure': {'additionalUnverifiedCalls': [{'fn.test': {'value!': {'int!': 0, 'str!': 'a'}}}]}}]],
        [[{}, {'fn._verify': {'call': {'fn.test': {'value!': {'int!': 0}}}}}], [{}, {'Ok': {}}]],
        [[{}, {'fn._verifyNoMoreInteractions': {}}], [{}, {'Ok': {}}]],
        [[{}, {'fn._verify': {'call': {'fn.test': {'value!': {'int!': 0}}}, 'count!': {'Exact': {'times': 1}}}}], [{}, {'Ok': {}}]],
        [[{}, {'fn._verify': {'call': {'fn.test': {'value!': {'int!': 0}}}, 'count!': {'AtLeast': {'times': 1}}}}], [{}, {'Ok': {}}]],
        [[{}, {'fn._verify': {'call': {'fn.test': {'value!': {'int!': 0}}}, 'count!': {'AtMost': {'times': 0}}}}], [{}, {'ErrorVerificationFailure': {'reason': {'TooManyMatchingCalls': {'wanted': {'AtMost': {'times': 0}}, 'allCalls': [{'fn.test': {'value!': {'int!': 0, 'str!': 'a'}}}], 'found': 1}}}}]],
    ],
    'multiplePartialMatchVerify': [
        [[{}, {'fn._clearStubs': {}}], [{}, {'Ok': {}}]],
        [[{}, {'fn._clearCalls': {}}], [{}, {'Ok': {}}]],
        [[{}, {'fn._createStub': {'stub': {'fn.test': {}, '->': {'Ok': {}}}}}], [{}, {'Ok': {}}]],
        [[{}, {'fn._verify': {'call': {'fn.test': {'value!': {'int!': 0}}}}}], [{}, {'ErrorVerificationFailure': {'reason': {'TooFewMatchingCalls': {'found': 0, 'allCalls': [], 'wanted': {'AtLeast': {'times': 1}}}}}}]],
        [[{}, {'fn.test': {'value!': {'int!': 0, 'bool!': True}}}], [{}, {'Ok': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 0, 'str!': 'a'}}}], [{}, {'Ok': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1}}}], [{}, {'Ok': {}}]],
        [[{}, {'fn._verifyNoMoreInteractions': {}}], [{}, {'ErrorVerificationFailure': {'additionalUnverifiedCalls': [{'fn.test': {'value!': {'int!': 0, 'bool!': True}}}, {'fn.test': {'value!': {'int!': 0, 'str!': 'a'}}}, {'fn.test': {'value!': {'int!': 1}}}]}}]],
        [[{}, {'fn._verify': {'call': {'fn.test': {'value!': {'int!': 0}}}}}], [{}, {'Ok': {}}]],
        [[{}, {'fn._verifyNoMoreInteractions': {}}], [{}, {'ErrorVerificationFailure': {'additionalUnverifiedCalls': [{'fn.test': {'value!': {'int!': 1}}}]}}]],
        [[{}, {'fn._verify': {'call': {'fn.test': {}}}}], [{}, {'Ok': {}}]],
        [[{}, {'fn._verifyNoMoreInteractions': {}}], [{}, {'Ok': {}}]],
        [[{}, {'fn._verify': {'call': {'fn.test': {'value!': {'int!': 0}}}, 'count!': {'Exact': {'times': 1}}}}], [{}, {'ErrorVerificationFailure': {'reason': {'TooManyMatchingCalls': {'wanted': {'Exact': {'times': 1}}, 'allCalls': [{'fn.test': {'value!': {'int!': 0, 'bool!': True}}}, {'fn.test': {'value!': {'int!': 0, 'str!': 'a'}}}, {'fn.test': {'value!': {'int!': 1}}}], 'found': 2}}}}]],
        [[{}, {'fn._verify': {'call': {'fn.test': {'value!': {'int!': 0}}}, 'count!': {'Exact': {'times': 2}}}}], [{}, {'Ok': {}}]],
        [[{}, {'fn._verify': {'call': {'fn.test': {'value!': {'int!': 0}}}, 'count!': {'Exact': {'times': 3}}}}], [{}, {'ErrorVerificationFailure': {'reason': {'TooFewMatchingCalls': {'wanted': {'Exact': {'times': 3}}, 'allCalls': [{'fn.test': {'value!': {'int!': 0, 'bool!': True}}}, {'fn.test': {'value!': {'int!': 0, 'str!': 'a'}}}, {'fn.test': {'value!': {'int!': 1}}}], 'found': 2}}}}]],
        [[{}, {'fn._verify': {'call': {'fn.test': {'value!': {'int!': 0}}}, 'count!': {'AtLeast': {'times': 1}}}}], [{}, {'Ok': {}}]],
        [[{}, {'fn._verify': {'call': {'fn.test': {'value!': {'int!': 0}}}, 'count!': {'AtMost': {'times': 1}}}}], [{}, {'ErrorVerificationFailure': {'reason': {'TooManyMatchingCalls': {'wanted': {'AtMost': {'times': 1}}, 'allCalls': [{'fn.test': {'value!': {'int!': 0, 'bool!': True}}}, {'fn.test': {'value!': {'int!': 0, 'str!': 'a'}}}, {'fn.test': {'value!': {'int!': 1}}}], 'found': 2}}}}]],
        [[{}, {'fn._verify': {'call': {'fn.test': {'value!': {'int!': 0}}}, 'count!': {'AtMost': {'times': 2}}}}], [{}, {'Ok': {}}]],
    ],
    'strictMatchVerify': [
        [[{}, {'fn._clearStubs': {}}], [{}, {'Ok': {}}]],
        [[{}, {'fn._clearCalls': {}}], [{}, {'Ok': {}}]],
        [[{}, {'fn._createStub': {'stub': {'fn.test': {}, '->': {'Ok': {}}}}}], [{}, {'Ok': {}}]],
        [[{}, {'fn._verify': {'call': {'fn.test': {'value!': {'int!': 0}}}, 'strictMatch!': True}}], [{}, {'ErrorVerificationFailure': {'reason': {'TooFewMatchingCalls': {'found': 0, 'allCalls': [], 'wanted': {'AtLeast': {'times': 1}}}}}}]],
        [[{}, {'fn.test': {'value!': {'int!': 0}}}], [{}, {'Ok': {}}]],
        [[{}, {'fn._verifyNoMoreInteractions': {}}], [{}, {'ErrorVerificationFailure': {'additionalUnverifiedCalls': [{'fn.test': {'value!': {'int!': 0}}}]}}]],
        [[{}, {'fn._verify': {'call': {'fn.test': {'value!': {'int!': 0}}}, 'strictMatch!': True}}], [{}, {'Ok': {}}]],
        [[{}, {'fn._verifyNoMoreInteractions': {}}], [{}, {'Ok': {}}]],
        [[{}, {'fn._verify': {'call': {'fn.test': {'value!': {'int!': 1}}}, 'strictMatch!': True}}], [{}, {'ErrorVerificationFailure': {'reason': {'TooFewMatchingCalls': {'found': 0, 'allCalls': [{'fn.test': {'value!': {'int!': 0}}}], 'wanted': {'AtLeast': {'times': 1}}}}}}]],
        [[{}, {'fn._verify': {'call': {'fn.test': {'value!': {'int!': 0, 'str!': 'a'}}}, 'strictMatch!': True}}], [{}, {'ErrorVerificationFailure': {'reason': {'TooFewMatchingCalls': {'found': 0, 'allCalls': [{'fn.test': {'value!': {'int!': 0}}}], 'wanted': {'AtLeast': {'times': 1}}}}}}]],
        [[{}, {'fn._verify': {'call': {'fn.test': {'value!': {'int!': 0}}}, 'strictMatch!': True, 'count!': {'Exact': {'times': 0}}}}], [{}, {'ErrorVerificationFailure': {'reason': {'TooManyMatchingCalls': {'wanted': {'Exact': {'times': 0}}, 'allCalls': [{'fn.test': {'value!': {'int!': 0}}}], 'found': 1}}}}]],
        [[{}, {'fn._verify': {'call': {'fn.test': {'value!': {'int!': 0}}}, 'strictMatch!': True, 'count!': {'Exact': {'times': 2}}}}], [{}, {'ErrorVerificationFailure': {'reason': {'TooFewMatchingCalls': {'wanted': {'Exact': {'times': 2}}, 'allCalls': [{'fn.test': {'value!': {'int!': 0}}}], 'found': 1}}}}]],
        [[{}, {'fn._verify': {'call': {'fn.test': {'value!': {'int!': 0}}}, 'strictMatch!': True, 'count!': {'Exact': {'times': 1}}}}], [{}, {'Ok': {}}]],
        [[{}, {'fn._verify': {'call': {'fn.test': {'value!': {'int!': 0}}}, 'strictMatch!': True, 'count!': {'AtLeast': {'times': 2}}}}], [{}, {'ErrorVerificationFailure': {'reason': {'TooFewMatchingCalls': {'wanted': {'AtLeast': {'times': 2}}, 'allCalls': [{'fn.test': {'value!': {'int!': 0}}}], 'found': 1}}}}]],
        [[{}, {'fn._verify': {'call': {'fn.test': {'value!': {'int!': 0}}}, 'strictMatch!': True, 'count!': {'AtLeast': {'times': 1}}}}], [{}, {'Ok': {}}]],
        [[{}, {'fn._verify': {'call': {'fn.test': {'value!': {'int!': 0}}}, 'strictMatch!': True, 'count!': {'AtMost': {'times': 1}}}}], [{}, {'Ok': {}}]],
    ],
    'multipleStrictMatchVerify': [
        [[{}, {'fn._clearStubs': {}}], [{}, {'Ok': {}}]],
        [[{}, {'fn._clearCalls': {}}], [{}, {'Ok': {}}]],
        [[{}, {'fn._createStub': {'stub': {'fn.test': {}, '->': {'Ok': {}}}}}], [{}, {'Ok': {}}]],
        [[{}, {'fn._verify': {'call': {'fn.test': {'value!': {'int!': 0}}}, 'strictMatch!': True}}], [{}, {'ErrorVerificationFailure': {'reason': {'TooFewMatchingCalls': {'found': 0, 'allCalls': [], 'wanted': {'AtLeast': {'times': 1}}}}}}]],
        [[{}, {'fn.test': {'value!': {'int!': 0}}}], [{}, {'Ok': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 0, 'str!': 'a'}}}], [{}, {'Ok': {}}]],
        [[{}, {'fn._verifyNoMoreInteractions': {}}], [{}, {'ErrorVerificationFailure': {'additionalUnverifiedCalls': [{'fn.test': {'value!': {'int!': 0}}}, {'fn.test': {'value!': {'int!': 0, 'str!': 'a'}}}]}}]],
        [[{}, {'fn._verify': {'call': {'fn.test': {'value!': {'int!': 0}}}, 'strictMatch!': True}}], [{}, {'Ok': {}}]],
        [[{}, {'fn._verifyNoMoreInteractions': {}}], [{}, {'ErrorVerificationFailure': {'additionalUnverifiedCalls': [{'fn.test': {'value!': {'int!': 0, 'str!': 'a'}}}]}}]],
        [[{}, {'fn._verify': {'call': {'fn.test': {}}}}], [{}, {'Ok': {}}]],
        [[{}, {'fn._verifyNoMoreInteractions': {}}], [{}, {'Ok': {}}]],
        [[{}, {'fn._verify': {'call': {'fn.test': {'value!': {'int!': 1}}}, 'strictMatch!': True}}], [{}, {'ErrorVerificationFailure': {'reason': {'TooFewMatchingCalls': {'found': 0, 'allCalls': [{'fn.test': {'value!': {'int!': 0}}}, {'fn.test': {'value!': {'int!': 0, 'str!': 'a'}}}], 'wanted': {'AtLeast': {'times': 1}}}}}}]],
        [[{}, {'fn._verify': {'call': {'fn.test': {'value!': {'int!': 0, 'str!': 'b'}}}, 'strictMatch!': True}}], [{}, {'ErrorVerificationFailure': {'reason': {'TooFewMatchingCalls': {'found': 0, 'allCalls': [{'fn.test': {'value!': {'int!': 0}}}, {'fn.test': {'value!': {'int!': 0, 'str!': 'a'}}}], 'wanted': {'AtLeast': {'times': 1}}}}}}]],
        [[{}, {'fn._verify': {'call': {'fn.test': {'value!': {'int!': 0}}}, 'strictMatch!': True, 'count!': {'Exact': {'times': 0}}}}], [{}, {'ErrorVerificationFailure': {'reason': {'TooManyMatchingCalls': {'wanted': {'Exact': {'times': 0}}, 'allCalls': [{'fn.test': {'value!': {'int!': 0}}}, {'fn.test': {'value!': {'int!': 0, 'str!': 'a'}}}], 'found': 1}}}}]],
        [[{}, {'fn._verify': {'call': {'fn.test': {'value!': {'int!': 0}}}, 'strictMatch!': True, 'count!': {'Exact': {'times': 2}}}}], [{}, {'ErrorVerificationFailure': {'reason': {'TooFewMatchingCalls': {'wanted': {'Exact': {'times': 2}}, 'allCalls': [{'fn.test': {'value!': {'int!': 0}}}, {'fn.test': {'value!': {'int!': 0, 'str!': 'a'}}}], 'found': 1}}}}]],
        [[{}, {'fn._verify': {'call': {'fn.test': {'value!': {'int!': 0}}}, 'strictMatch!': True, 'count!': {'Exact': {'times': 1}}}}], [{}, {'Ok': {}}]],
        [[{}, {'fn._verify': {'call': {'fn.test': {'value!': {'int!': 0}}}, 'strictMatch!': True, 'count!': {'AtLeast': {'times': 2}}}}], [{}, {'ErrorVerificationFailure': {'reason': {'TooFewMatchingCalls': {'wanted': {'AtLeast': {'times': 2}}, 'allCalls': [{'fn.test': {'value!': {'int!': 0}}}, {'fn.test': {'value!': {'int!': 0, 'str!': 'a'}}}], 'found': 1}}}}]],
        [[{}, {'fn._verify': {'call': {'fn.test': {'value!': {'int!': 0}}}, 'strictMatch!': True, 'count!': {'AtLeast': {'times': 1}}}}], [{}, {'Ok': {}}]],
        [[{}, {'fn._verify': {'call': {'fn.test': {'value!': {'int!': 0}}}, 'strictMatch!': True, 'count!': {'AtMost': {'times': 1}}}}], [{}, {'Ok': {}}]],
    ],
    'multipleNestedPartialMatchVerify': [
        [[{}, {'fn._clearStubs': {}}], [{}, {'Ok': {}}]],
        [[{}, {'fn._clearCalls': {}}], [{}, {'Ok': {}}]],
        [[{}, {'fn._createStub': {'stub': {'fn.test': {}, '->': {'Ok': {}}}}}], [{}, {'Ok': {}}]],
        [[{}, {'fn._verify': {'call': {'fn.test': {'value!': {'int!': 0}}}}}], [{}, {'ErrorVerificationFailure': {'reason': {'TooFewMatchingCalls': {'found': 0, 'allCalls': [], 'wanted': {'AtLeast': {'times': 1}}}}}}]],
        [[{}, {'fn.test': {'value!': {'struct!': {'required': True}}}}], [{}, {'Ok': {}}]],
        [[{}, {'fn.test': {'value!': {'struct!': {'required': True, 'optional!': True}}}}], [{}, {'Ok': {}}]],
        [[{}, {'fn._verifyNoMoreInteractions': {}}], [{}, {'ErrorVerificationFailure': {'additionalUnverifiedCalls': [{'fn.test': {'value!': {'struct!': {'required': True}}}}, {'fn.test': {'value!': {'struct!': {'required': True, 'optional!': True}}}}]}}]],
        [[{}, {'fn._verify': {'call': {'fn.test': {'value!': {'struct!': {'optional!': True}}}}}}], [{}, {'Ok': {}}]],
        [[{}, {'fn._verifyNoMoreInteractions': {}}], [{}, {'ErrorVerificationFailure': {'additionalUnverifiedCalls': [{'fn.test': {'value!': {'struct!': {'required': True}}}}]}}]],
        [[{}, {'fn._verify': {'call': {'fn.test': {}}}}], [{}, {'Ok': {}}]],
        [[{}, {'fn._verifyNoMoreInteractions': {}}], [{}, {'Ok': {}}]],
        [[{}, {'fn._verify': {'call': {'fn.test': {'value!': {'struct!': {'optional!': True}}}}, 'count!': {'Exact': {'times': 1}}}}], [{}, {'Ok': {}}]],
    ],
    'multipleReallyNestedPartialMatchVerify': [
        [[{}, {'fn._clearStubs': {}}], [{}, {'Ok': {}}]],
        [[{}, {'fn._clearCalls': {}}], [{}, {'Ok': {}}]],
        [[{}, {'fn._createStub': {'stub': {'fn.test': {}, '->': {'Ok': {}}}}}], [{}, {'Ok': {}}]],
        [[{}, {'fn._verify': {'call': {'fn.test': {'value!': {'int!': 0}}}}}], [{}, {'ErrorVerificationFailure': {'reason': {'TooFewMatchingCalls': {'found': 0, 'allCalls': [], 'wanted': {'AtLeast': {'times': 1}}}}}}]],
        [[{}, {'fn.test': {'value!': {'arrStruct!': [{'required': False}, {'required': True}]}}}], [{}, {'Ok': {}}]],
        [[{}, {'fn.test': {'value!': {'arrStruct!': [{'required': False}, {'required': True, 'optional!': True}]}}}], [{}, {'Ok': {}}]],
        [[{}, {'fn._verify': {'call': {'fn.test': {'value!': {'arrStruct!': [{'optional!': True}]}}}}}], [{}, {'Ok': {}}]],
        [[{}, {'fn._verifyNoMoreInteractions': {}}], [{}, {'ErrorVerificationFailure': {'additionalUnverifiedCalls': [{'fn.test': {'value!': {'arrStruct!': [{'required': False}, {'required': True}]}}}]}}]],
        [[{}, {'fn._verify': {'call': {'fn.test': {}}}}], [{}, {'Ok': {}}]],
        [[{}, {'fn._verifyNoMoreInteractions': {}}], [{}, {'Ok': {}}]],
        [[{}, {'fn._verify': {'call': {'fn.test': {'value!': {'arrStruct!': [{'optional!': True}]}}}, 'count!': {'Exact': {'times': 1}}}}], [{}, {'Ok': {}}]],
    ],
    'clearCalls': [
        [[{}, {'fn._clearStubs': {}}], [{}, {'Ok': {}}]],
        [[{}, {'fn._clearCalls': {}}], [{}, {'Ok': {}}]],
        [[{}, {'fn._createStub': {'stub': {'fn.test': {}, '->': {'Ok': {}}}}}], [{}, {'Ok': {}}]],
        [[{}, {'fn._verify': {'call': {'fn.test': {}}}}], [{}, {'ErrorVerificationFailure': {'reason': {'TooFewMatchingCalls': {'found': 0, 'allCalls': [], 'wanted': {'AtLeast': {'times': 1}}}}}}]],
        [[{}, {'fn.test': {}}], [{}, {'Ok': {}}]],
        [[{}, {'fn._verify': {'call': {'fn.test': {}}}}], [{}, {'Ok': {}}]],
        [[{}, {'fn._clearCalls': {}}], [{}, {'Ok': {}}]],
        [[{}, {'fn._verify': {'call': {'fn.test': {}}}}], [{}, {'ErrorVerificationFailure': {'reason': {'TooFewMatchingCalls': {'found': 0, 'allCalls': [], 'wanted': {'AtLeast': {'times': 1}}}}}}]],
    ],
    'resultSuppliesMissingRequiredFields': [
        [[{}, {'fn._setRandomSeed': {'seed': 0}}], [{}, {'Ok': {}}]],
        [[{}, {'fn._clearStubs': {}}], [{}, {'Ok': {}}]],
        [[{}, {'fn._clearCalls': {}}], [{}, {'Ok': {}}]],
        [[{}, {'fn.test': {}}], [{}, {'_ErrorNoMatchingStub': {}}]],
        [[{}, {'fn._createStub': {'stub': {'fn.test': {}, '->': {'Ok': {'value!': {'bool!': True, 'struct!': {'optional!': True}}}}}}}], [{}, {'Ok': {}}]],
        [[{}, {'fn.test': {}}], [{}, {'Ok': {'value!': {'bool!': True, 'struct!': {'optional!': True, 'required': False}}}}]],
    ],
    'resultWithStartingValue': [
        [[{}, {'fn._clearStubs': {}}], [{}, {'Ok': {}}]],
        [[{}, {'fn._clearCalls': {}}], [{}, {'Ok': {}}]],
        [[{}, {'fn.test': {}}], [{}, {'_ErrorNoMatchingStub': {}}]],
        [[{}, {'fn._createStub': {'stub': {'fn.test': {}, '->': {'Ok': {'value!': {'bool!': False, 'int!': 0, 'num!': 0.1, 'str!': '', 'arrBool!': [False], 'objBool!': {'a': False}, 'struct!': {'required': False}, 'union!': {'Two': {'required': False}}, 'fn!': {'fn.example': {'required': False}}}}}}}}], [{}, {'Ok': {}}]],
        [[{}, {'fn.test': {}}], [{}, {'Ok': {'value!': {'bool!': False, 'int!': 0, 'num!': 0.1, 'str!': '', 'arrBool!': [False], 'objBool!': {'a': False}, 'struct!': {'required': False}, 'union!': {'Two': {'required': False}}, 'fn!': {'fn.example': {'required': False}}}}}]],
    ],
}
