#|
#|  Copyright The Telepact Authors
#|
#|  Licensed under the Apache License, Version 2.0 (the "License");
#|  you may not use this file except in compliance with the License.
#|  You may obtain a copy of the License at
#|
#|  https://www.apache.org/licenses/LICENSE-2.0
#|
#|  Unless required by applicable law or agreed to in writing, software
#|  distributed under the License is distributed on an "AS IS" BASIS,
#|  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#|  See the License for the specific language governing permissions and
#|  limitations under the License.
#|

version: 2

updates:
  - package-ecosystem: "npm"
    directory: "/bind/dart"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "00:00"
      timezone: "UTC"
    labels:
      - "dependabot"
    open-pull-requests-limit: 1
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  - package-ecosystem: "npm"
    directory: "/lib/ts"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "01:00"
      timezone: "UTC"
    labels:
      - "dependabot"
    open-pull-requests-limit: 1
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  - package-ecosystem: "npm"
    directory: "/sdk/prettier"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "02:00"
      timezone: "UTC"
    labels:
      - "dependabot"
    open-pull-requests-limit: 1
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  - package-ecosystem: "npm"
    directory: "/sdk/console"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "03:00"
      timezone: "UTC"
    labels:
      - "dependabot"
    open-pull-requests-limit: 1
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  - package-ecosystem: "npm"
    directory: "/test/console-self-hosted"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "UTC"
    labels:
      - "dependabot"
    open-pull-requests-limit: 1
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  - package-ecosystem: "npm"
    directory: "/test/lib/ts"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "05:00"
      timezone: "UTC"
    labels:
      - "dependabot"
    open-pull-requests-limit: 1
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  - package-ecosystem: "pip"
    directory: "/lib/py"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "UTC"
    labels:
      - "dependabot"
    open-pull-requests-limit: 1
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  - package-ecosystem: "pip"
    directory: "/sdk/cli"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "07:00"
      timezone: "UTC"
    labels:
      - "dependabot"
    open-pull-requests-limit: 1
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  - package-ecosystem: "pip"
    directory: "/test/lib/py"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "08:00"
      timezone: "UTC"
    labels:
      - "dependabot"
    open-pull-requests-limit: 1
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
      - dependency-name: "telepact"
      - dependency-name: "test/lib/py/telepact.tar.gz"

  - package-ecosystem: "pip"
    directory: "/test/runner"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "UTC"
    labels:
      - "dependabot"
    open-pull-requests-limit: 1
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  - package-ecosystem: "pip"
    directory: "/tool/telepact_project_cli"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "10:00"
      timezone: "UTC"
    labels:
      - "dependabot"
    open-pull-requests-limit: 1
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  - package-ecosystem: "maven"
    directory: "/lib/java"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "11:00"
      timezone: "UTC"
    labels:
      - "dependabot"
    open-pull-requests-limit: 1
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  - package-ecosystem: "maven"
    directory: "/test/lib/java"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "12:00"
      timezone: "UTC"
    labels:
      - "dependabot"
    open-pull-requests-limit: 1
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  - package-ecosystem: "gomod"
    directory: "/lib/go"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "13:00"
      timezone: "UTC"
    labels:
      - "dependabot"
    open-pull-requests-limit: 1
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  - package-ecosystem: "gomod"
    directory: "/test/lib/go"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "14:00"
      timezone: "UTC"
    labels:
      - "dependabot"
    open-pull-requests-limit: 1
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  - package-ecosystem: "pub"
    directory: "/bind/dart"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "15:00"
      timezone: "UTC"
    labels:
      - "dependabot"
    open-pull-requests-limit: 1
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
