from typing import Any

from qa.test.cases import get_values
from qa.test.cases import additional_union_cases, additional_fn_cases, additional_integer_cases, additional_number_cases, additional_p2Union_cases, additional_p2Str_cases, additional_struct_cases


def generate_mock_cases(given_field: str, the_type, correct_values, additional_incorrect_values = []):
    for field, _, incorrect_values, base_path in get_values(given_field, the_type, correct_values, additional_incorrect_values):
        for incorrect_value, errors in incorrect_values:
            cases = [{'path': ['fn.createStub_', 'stub', 'fn.test', 'value!'] + base_path + path, 'reason': reason} for reason, path in errors if 'RequiredObjectKeyMissing' not in reason]
            if not cases:
                continue

            yield [[{}, {'fn.createStub_': {'stub': {'fn.test': {'value!': {field: incorrect_value}}, '->': {'Ok_': {}}}}}], [{}, {'ErrorInvalidRequestBody_': {'cases': cases}}]]

        for incorrect_value, errors in incorrect_values:
            cases = [{'path': ['fn.createStub_', 'stub', '->', 'Ok_', 'value!'] + base_path + path, 'reason': reason} for reason, path in errors if 'RequiredObjectKeyMissing' not in reason]
            if not cases:
                continue
            yield [[{}, {'fn.createStub_': {'stub': {'fn.test': {}, '->': {'Ok_': {'value!': {field: incorrect_value}}}}}}], [{}, {'ErrorInvalidRequestBody_': {'cases': cases}}]]



invalid_cases = {
    'boolean': [v for v in generate_mock_cases('bool!', bool, [False, True])],
    'integer': [v for v in generate_mock_cases('int!', int, [0, -1, 1, 9223372036854775807, -9223372036854775808], additional_integer_cases)],
    'number': [v for v in generate_mock_cases('num!', float, [0, -1, 1, -1.7976931348623157e+308, -2.2250738585072014e-308, 2.2250738585072014e-308, 1.7976931348623157e+308, -0.1, 0.1], additional_number_cases)],
    'string': [v for v in generate_mock_cases('str!', str, ['', 'abc'])],
    'array': [v for v in generate_mock_cases('arr!', list, [[], [False, 0, 0.1, '']])],
    'object': [v for v in generate_mock_cases('obj!', dict, [{}, {'a': False, 'b': 0, 'c': 0.1, 'd': ''}])],
    'any': [v for v in generate_mock_cases('any!', Any, [False, 0, 0.1, '', [], {}])],
    'struct': [v for v in generate_mock_cases('struct!', dict, [{'required': False}, {'optional!': False, 'required': False}], additional_struct_cases)],
    'union': [v for v in generate_mock_cases('union!', dict, [{'One': {}}, {'Two':{'required': False}}, {'Two':{'optional!': False, 'required': False}}], additional_union_cases)],
    'fn': [v for v in generate_mock_cases('fn!', dict, [{'fn.example': {'required': False}}, {'fn.example': {'optional!': False, 'required': False}}], additional_fn_cases)],
    'stub': [
        [[{}, {'fn.createStub_': {'stub': False}}], [{}, {'ErrorInvalidRequestBody_': {'cases': [{'path': ['fn.createStub_', 'stub'], 'reason': {'TypeUnexpected': {'actual': {'Boolean': {}}, 'expected': {'Object': {}}}}}]}}]],
        [[{}, {'fn.createStub_': {'stub': 0}}], [{}, {'ErrorInvalidRequestBody_': {'cases': [{'path': ['fn.createStub_', 'stub'], 'reason': {'TypeUnexpected': {'actual': {'Number': {}}, 'expected': {'Object': {}}}}}]}}]],
        [[{}, {'fn.createStub_': {'stub': ''}}], [{}, {'ErrorInvalidRequestBody_': {'cases': [{'path': ['fn.createStub_', 'stub'], 'reason': {'TypeUnexpected': {'actual': {'String': {}}, 'expected': {'Object': {}}}}}]}}]],
        [[{}, {'fn.createStub_': {'stub': []}}], [{}, {'ErrorInvalidRequestBody_': {'cases': [{'path': ['fn.createStub_', 'stub'], 'reason': {'TypeUnexpected': {'actual': {'Array': {}}, 'expected': {'Object': {}}}}}]}}]],
        [[{}, {'fn.createStub_': {'stub': {}}}], [{}, {'ErrorInvalidRequestBody_': {'cases': [{'path': ['fn.createStub_', 'stub'], 'reason': {'ObjectKeyRegexMatchCountUnexpected': {'regex': '^fn\\..*$', 'actual': 0, 'expected': 1, 'keys': []}}}]}}]],
        [[{}, {'fn.createStub_': {'stub': {'fn.test': {}}}}], [{}, {'ErrorInvalidRequestBody_': {'cases': [{'path': ['fn.createStub_', 'stub'], 'reason': {'RequiredObjectKeyMissing': {'key': '->'}}}]}}]],
        [[{}, {'fn.createStub_': {'stub': {'fn.test': {}, '->': {}}}}], [{}, {'ErrorInvalidRequestBody_': {'cases': [{'path': ['fn.createStub_', 'stub', '->'], 'reason': {'ObjectSizeUnexpected': {'actual': 0, 'expected': 1}}}]}}]],
        [[{}, {'fn.createStub_': {'stub': {'fn.testAnother': {}, 'fn.test': {}, '->': {'Ok_': {}}}}}], [{}, {'ErrorInvalidRequestBody_': {'cases': [{'path': ['fn.createStub_', 'stub'], 'reason': {'ObjectKeyRegexMatchCountUnexpected': {'regex': '^fn\\..*$', 'actual': 2, 'expected': 1, 'keys': ['->', 'fn.test', 'fn.testAnother']}}}]}}]],
        [[{}, {'fn.createStub_': {'stub': {'wrong': True, 'fn.test': {}, '->': {'Ok_': {}}}}}], [{}, {'ErrorInvalidRequestBody_': {'cases': [{'path': ['fn.createStub_', 'stub', 'wrong'], 'reason': {'ObjectKeyDisallowed': {}}}]}}]],
    ],
}

cases = {
    'emptyPartialMatchStub': [
        [[{}, {'fn.clearStubs_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.clearCalls_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.test': {}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.createStub_': {'stub': {'fn.test': {}, '->': {'Ok_': {}}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.test': {}}], [{}, {'Ok_': {}}]],
    ],
    'partialMatchStub': [
        [[{}, {'fn.clearStubs_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.clearCalls_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1, 'str!': 'a'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.createStub_': {'stub': {'fn.test': {'value!': {'int!': 1}}, '->': {'Ok_': {'value!': {'bool!': True}}}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.test': {}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 0}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1}}}], [{}, {'Ok_': {'value!': {'bool!': True}}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1, 'str!': 'a'}}}], [{}, {'Ok_': {'value!': {'bool!': True}}}]],
    ],
    'multiplePartialMatchStub': [
        [[{}, {'fn.clearStubs_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.clearCalls_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1, 'str!': 'a'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 0, 'str!': 'a'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1, 'str!': 'b'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'bool!': False, 'int!': 1, 'str!': 'a'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.createStub_': {'stub': {'fn.test': {'value!': {'int!': 1}}, '->': {'Ok_': {'value!': {'bool!': True}}}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.createStub_': {'stub': {'fn.test': {'value!': {'str!': 'a'}}, '->': {'Ok_': {'value!': {'bool!': False}}}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.createStub_': {'stub': {'fn.example': {}, '->': {'Ok_': {}}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.test': {}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 0}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1}}}], [{}, {'Ok_': {'value!': {'bool!': True}}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1, 'str!': 'a'}}}], [{}, {'Ok_': {'value!': {'bool!': False}}}]],
        [[{}, {'fn.test': {'value!': {'int!': 0, 'str!': 'a'}}}], [{}, {'Ok_': {'value!': {'bool!': False}}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1, 'str!': 'b'}}}], [{}, {'Ok_': {'value!': {'bool!': True}}}]],
        [[{}, {'fn.test': {'value!': {'bool!': False, 'int!': 1, 'str!': 'a'}}}], [{}, {'Ok_': {'value!': {'bool!': False}}}]],
    ],
    'multiplePartialMatchStubCount': [
        [[{}, {'fn.clearStubs_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.clearCalls_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1, 'str!': 'a'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 0, 'str!': 'a'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1, 'str!': 'b'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'bool!': False, 'int!': 1, 'str!': 'a'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.createStub_': {'count!': 2, 'stub': {'fn.test': {'value!': {'int!': 1}}, '->': {'Ok_': {'value!': {'bool!': True}}}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.createStub_': {'count!': 1, 'stub': {'fn.test': {'value!': {'str!': 'a'}}, '->': {'Ok_': {'value!': {'bool!': False}}}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.createStub_': {'stub': {'fn.example': {}, '->': {'Ok_': {}}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.test': {}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 0}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1}}}], [{}, {'Ok_': {'value!': {'bool!': True}}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1, 'str!': 'a'}}}], [{}, {'Ok_': {'value!': {'bool!': False}}}]],
        [[{}, {'fn.test': {'value!': {'int!': 0, 'str!': 'a'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1, 'str!': 'b'}}}], [{}, {'Ok_': {'value!': {'bool!': True}}}]],
        [[{}, {'fn.test': {'value!': {'bool!': False, 'int!': 1, 'str!': 'a'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
    ],    
    'multipleNestedPartialMatchStub': [
        [[{}, {'fn.clearStubs_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.clearCalls_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1, 'str!': 'a'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 0, 'str!': 'a'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1, 'str!': 'b'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'bool!': False, 'int!': 1, 'str!': 'a'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.createStub_': {'stub': {'fn.test': {'value!': {'struct!': {'optional!': True}}}, '->': {'Ok_': {'value!': {'bool!': True}}}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.createStub_': {'stub': {'fn.test': {'value!': {'struct!': {'required': True}}}, '->': {'Ok_': {'value!': {'bool!': False}}}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.createStub_': {'stub': {'fn.example': {}, '->': {'Ok_': {}}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.test': {}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'struct!': {'required': False}}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'struct!': {'optional!': False, 'required': False}}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'struct!': {'optional!': True, 'required': True}}}}], [{}, {'Ok_': {'value!': {'bool!': False}}}]],
        [[{}, {'fn.test': {'value!': {'struct!': {'optional!': True, 'required': False}}}}], [{}, {'Ok_': {'value!': {'bool!': True}}}]],
        [[{}, {'fn.test': {'value!': {'struct!': {'required': True}}}}], [{}, {'Ok_': {'value!': {'bool!': False}}}]],
        [[{}, {'fn.test': {'value!': {'struct!': {'optional!': False, 'required': True}}}}], [{}, {'Ok_': {'value!': {'bool!': False}}}]],
        [[{}, {'fn.test': {'value!': {'struct!': {'optional!': True, 'required': False}, 'str!': 'b'}}}], [{}, {'Ok_': {'value!': {'bool!': True}}}]],
    ],
    'multipleNestedPartialMatchStubCount': [
        [[{}, {'fn.clearStubs_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.clearCalls_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1, 'str!': 'a'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 0, 'str!': 'a'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1, 'str!': 'b'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'bool!': False, 'int!': 1, 'str!': 'a'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.createStub_': {'count!': 1, 'stub': {'fn.test': {'value!': {'struct!': {'optional!': True}}}, '->': {'Ok_': {'value!': {'bool!': True}}}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.createStub_': {'count!': 2, 'stub': {'fn.test': {'value!': {'struct!': {'required': True}}}, '->': {'Ok_': {'value!': {'bool!': False}}}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.createStub_': {'stub': {'fn.example': {}, '->': {'Ok_': {}}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.test': {}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'struct!': {'required': False}}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'struct!': {'optional!': False, 'required': False}}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'struct!': {'optional!': True, 'required': True}}}}], [{}, {'Ok_': {'value!': {'bool!': False}}}]],
        [[{}, {'fn.test': {'value!': {'struct!': {'optional!': True, 'required': False}}}}], [{}, {'Ok_': {'value!': {'bool!': True}}}]],
        [[{}, {'fn.test': {'value!': {'struct!': {'required': True}}}}], [{}, {'Ok_': {'value!': {'bool!': False}}}]],
        [[{}, {'fn.test': {'value!': {'struct!': {'optional!': False, 'required': True}}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'struct!': {'optional!': True, 'required': False}, 'str!': 'b'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
    ],    
    'multipleReallyNestedPartialMatchStub': [
        [[{}, {'fn.clearStubs_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.clearCalls_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1, 'str!': 'a'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 0, 'str!': 'a'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1, 'str!': 'b'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'bool!': False, 'int!': 1, 'str!': 'a'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.createStub_': {'stub': {'fn.test': {'value!': {'arrStruct!': [{'optional!': True}]}}, '->': {'Ok_': {'value!': {'bool!': True}}}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.createStub_': {'stub': {'fn.test': {'value!': {'arrStruct!': [{'required': True}]}}, '->': {'Ok_': {'value!': {'bool!': False}}}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.createStub_': {'stub': {'fn.example': {}, '->': {'Ok_': {}}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.test': {}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'arrStruct!': [{'required': False}, {'optional!': False, 'required': False}]}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'arrStruct!': [{'required': False}, {'optional!': True, 'required': True}]}}}], [{}, {'Ok_': {'value!': {'bool!': False}}}]],
        [[{}, {'fn.test': {'value!': {'arrStruct!': [{'required': False}, {'optional!': True, 'required': False}]}}}], [{}, {'Ok_': {'value!': {'bool!': True}}}]],
        [[{}, {'fn.test': {'value!': {'arrStruct!': [{'required': False}, {'optional!': False, 'required': True}]}}}], [{}, {'Ok_': {'value!': {'bool!': False}}}]],
        [[{}, {'fn.test': {'value!': {'arrStruct!': [{'required': False}, {'optional!': True, 'required': False}], 'str!': 'b'}}}], [{}, {'Ok_': {'value!': {'bool!': True}}}]],
    ],
    'multipleReallyNestedPartialMatchStubCount': [
        [[{}, {'fn.clearStubs_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.clearCalls_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1, 'str!': 'a'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 0, 'str!': 'a'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1, 'str!': 'b'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'bool!': False, 'int!': 1, 'str!': 'a'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.createStub_': {'count!': 1, 'stub': {'fn.test': {'value!': {'arrStruct!': [{'optional!': True}]}}, '->': {'Ok_': {'value!': {'bool!': True}}}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.createStub_': {'count!': 1, 'stub': {'fn.test': {'value!': {'arrStruct!': [{'required': True}]}}, '->': {'Ok_': {'value!': {'bool!': False}}}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.createStub_': {'stub': {'fn.example': {}, '->': {'Ok_': {}}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.test': {}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'arrStruct!': [{'required': False}, {'optional!': False, 'required': False}]}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'arrStruct!': [{'required': False}, {'optional!': True, 'required': True}]}}}], [{}, {'Ok_': {'value!': {'bool!': False}}}]],
        [[{}, {'fn.test': {'value!': {'arrStruct!': [{'required': False}, {'optional!': True, 'required': False}]}}}], [{}, {'Ok_': {'value!': {'bool!': True}}}]],
        [[{}, {'fn.test': {'value!': {'arrStruct!': [{'required': False}, {'optional!': False, 'required': True}]}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'arrStruct!': [{'required': False}, {'optional!': True, 'required': False}], 'str!': 'b'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
    ],    
    'strictMatchStub': [
        [[{}, {'fn.clearStubs_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.clearCalls_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.createStub_': {'stub': {'fn.test': {'value!': {'int!': 1}}, '->': {'Ok_': {'value!': {'bool!': True}}}}, 'strictMatch!': True}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.test': {}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 0}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1}}}], [{}, {'Ok_': {'value!': {'bool!': True}}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1, 'str!': 'a'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
    ],
    'multipleStrictMatchStub': [
        [[{}, {'fn.clearStubs_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.clearCalls_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'str!': 'a'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.createStub_': {'stub': {'fn.test': {'value!': {'int!': 1}}, '->': {'Ok_': {'value!': {'bool!': True}}}}, 'strictMatch!': True}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.createStub_': {'stub': {'fn.test': {'value!': {'str!': 'a'}}, '->': {'Ok_': {'value!': {'bool!': False}}}}, 'strictMatch!': True}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.test': {}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 0}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1}}}], [{}, {'Ok_': {'value!': {'bool!': True}}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1, 'str!': 'a'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'str!': 'a'}}}], [{}, {'Ok_': {'value!': {'bool!': False}}}]],
        [[{}, {'fn.test': {'value!': {'int!': 0, 'str!': 'a'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1, 'str!': 'b'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'bool!': False, 'int!': 1, 'str!': 'a'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
    ],
    'multipleStrictMatchStubCount': [
        [[{}, {'fn.clearStubs_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.clearCalls_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'str!': 'a'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.createStub_': {'count!': 1, 'stub': {'fn.test': {'value!': {'int!': 1}}, '->': {'Ok_': {'value!': {'bool!': True}}}}, 'strictMatch!': True}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.createStub_': {'count!': 1, 'stub': {'fn.test': {'value!': {'str!': 'a'}}, '->': {'Ok_': {'value!': {'bool!': False}}}}, 'strictMatch!': True}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.test': {}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 0}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1}}}], [{}, {'Ok_': {'value!': {'bool!': True}}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1, 'str!': 'a'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'str!': 'a'}}}], [{}, {'Ok_': {'value!': {'bool!': False}}}]],
        [[{}, {'fn.test': {'value!': {'str!': 'a'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 0, 'str!': 'a'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1, 'str!': 'b'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'bool!': False, 'int!': 1, 'str!': 'a'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
    ],    
    'mixedPartialStrictMatchStub': [
        [[{}, {'fn.clearStubs_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.clearCalls_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1, 'str!': 'a'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1, 'str!': 'b'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'bool!': False, 'int!': 1, 'str!': 'a'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.createStub_': {'stub': {'fn.test': {'value!': {'int!': 1}}, '->': {'Ok_': {'value!': {'bool!': True}}}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.createStub_': {'stub': {'fn.test': {'value!': {'int!': 1, 'str!': 'a'}}, '->': {'Ok_': {'value!': {'bool!': False}}}}, 'strictMatch!': True}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.test': {}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 0}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1}}}], [{}, {'Ok_': {'value!': {'bool!': True}}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1, 'str!': 'a'}}}], [{}, {'Ok_': {'value!': {'bool!': False}}}]],
        [[{}, {'fn.test': {'value!': {'int!': 0, 'str!': 'a'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1, 'str!': 'b'}}}], [{}, {'Ok_': {'value!': {'bool!': True}}}]],
        [[{}, {'fn.test': {'value!': {'bool!': False, 'int!': 1, 'str!': 'a'}}}], [{}, {'Ok_': {'value!': {'bool!': True}}}]],
    ],
    'mixedStrictPartialMatchStub': [
        [[{}, {'fn.clearStubs_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.clearCalls_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1, 'str!': 'a'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1, 'str!': 'b'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'bool!': False, 'int!': 1, 'str!': 'a'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.createStub_': {'stub': {'fn.test': {'value!': {'int!': 1, 'str!': 'a'}}, '->': {'Ok_': {'value!': {'bool!': False}}}}, 'strictMatch!': True}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.createStub_': {'stub': {'fn.test': {'value!': {'int!': 1}}, '->': {'Ok_': {'value!': {'bool!': True}}}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.test': {}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 0}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1}}}], [{}, {'Ok_': {'value!': {'bool!': True}}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1, 'str!': 'a'}}}], [{}, {'Ok_': {'value!': {'bool!': True}}}]],
        [[{}, {'fn.test': {'value!': {'int!': 0, 'str!': 'a'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1, 'str!': 'b'}}}], [{}, {'Ok_': {'value!': {'bool!': True}}}]],
        [[{}, {'fn.test': {'value!': {'bool!': False, 'int!': 1, 'str!': 'a'}}}], [{}, {'Ok_': {'value!': {'bool!': True}}}]],
    ],
    'clearStubs': [
        [[{}, {'fn.clearStubs_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.clearCalls_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.test': {}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.createStub_': {'stub': {'fn.test': {}, '->': {'Ok_': {}}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.test': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.clearStubs_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.test': {}}], [{}, {'ErrorNoMatchingStub_': {}}]],
    ],
    'generation': [
        [[{}, {'fn.setRandomSeed_': {'seed': 0}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.clearStubs_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.clearCalls_': {}}], [{}, {'Ok_': {}}]],
        [[{'_gen': True}, {'fn.test': {}}], [{}, {'Ok_': {'value!': {'any!': True, 'arrFn!': [], 'arrNullAny!': [225740852], 'arrNullArr!': [[591276622]], 'arrNullBool!': [False], 'arrNullFn!': [], 'arrNum!': [0.5445731252173768], 'arrObj!': [{'HzuD3g': False, 'B8oYiw': 2053581748}], 'bool!': True, 'fn!': {'fn.example': {'required': False}}, 'int!': 155154031, 'nullArr!': [False], 'nullBool!': True, 'nullNum!': 0.37554636382290457, 'nullStr!': None, 'nullStruct!': {'optional2!': 2146219813, 'required': True}, 'num!': 0.036533858178432035, 'objAny!': {}, 'objBool!': {'HyB1gg': True}, 'objNullAny!': {'HNHEPg': None}, 'objNullArr!': {'KXpvWQ': None}, 'objNullFn!': {'PuKmug': None, 'Y299zQ': {'fn.example': {'optional!': False, 'required': True}}}, 'objNullNum!': {'QYFAxA': None}, 'objNullObj!': {'CkST/g': {'OYP7mQ': True, 'IKht+Q': 117660595}}, 'objNullUnion!': {}, 'objNum!': {'KGGV9w': 0.11150402068696172, 'dRYIPQ': 0.7007149293556413}, 'objStr!': {'IX7gOg': 'aSXcZg', 'Hev3vQ': 'ISwRAw'}, 'objStruct!': {'R3Oc8A': {'optional2!': 657248562, 'required': True}}, 'objUnion!': {'MhZGwg': {'One': {}}, 'avyIYA': {'One': {}}}, 'union!': {'One': {}}}}}]],
        [[{'_gen': True}, {'fn.test': {}}], [{}, {'Ok_': {}}]],
        [[{'_gen': True}, {'fn.test': {}}], [{}, {'Ok_': {}}]],
        [[{'_gen': True}, {'fn.test': {}}], [{}, {'Ok_': {}}]],
        [[{'_gen': True}, {'fn.test': {}}], [{}, {'Ok_': {}}]],
        [[{'_gen': True}, {'fn.test': {}}], [{}, {'Ok_': {'value!': {'arr!': [False, True], 'arrAny!': [], 'arrArr!': [[], [90193426]], 'arrBool!': [], 'arrFn!': [], 'arrNullAny!': [False, 1757992001], 'arrNullArr!': [[False]], 'arrNullInt!': [2011730071, None], 'arrNullObj!': [{}], 'arrNullStr!': [], 'arrNullStruct!': [None, None], 'arrStr!': [], 'arrStruct!': [], 'bool!': False, 'fn!': {'fn.example': {'required': False}}, 'nullArr!': None, 'nullBool!': True, 'nullFn!': None, 'nullInt!': 2098014447, 'nullObj!': None, 'num!': 0.42988221507048335, 'objArr!': {'FzbzVQ': []}, 'objBool!': {'fNftFQ': True, 'ZoEO5w': False}, 'objFn!': {}, 'objInt!': {'bGTuZA': 1139106137}, 'objNullArr!': {'XYNwog': [231065357, True], 'WCLFYg': ['TLgnTQ', 1220537637]}, 'objNullBool!': {'bgmaVw': None}, 'objNullFn!': {'WawLvg': {'fn.example': {'required': True}}, 'UeZmpw': None}, 'objNullInt!': {'GtesKw': None, 'VMAa/g': None}, 'objNullNum!': {'asXKjg': 0.008515477184446285}, 'objNullStr!': {}, 'objNullStruct!': {'bPw3Cg': {'optional2!': 1511866087, 'required': True}, 'HmPbsg': None}, 'objStruct!': {'IrLrtQ': {'required': False}}, 'objUnion!': {}, 'struct!': {'optional!': True, 'optional2!': 484036347, 'required': False}, 'union!': {'One': {}}}}}]],
        [[{'_gen': True}, {'fn.test': {}}], [{}, {'Ok_': {}}]],
        [[{'_gen': True}, {'fn.test': {}}], [{}, {'Ok_': {}}]],
        [[{'_gen': True}, {'fn.test': {}}], [{}, {'Ok_': {'value!': {'arr!': ['Tx/xiA', False], 'arrAny!': [True, True], 'arrNullAny!': [], 'arrNullArr!': [None], 'arrNullFn!': [], 'arrNullInt!': [None, None], 'arrNullNum!': [None, 0.49942290619920143], 'arrNullObj!': [{'NyRopQ': 1946086041, 'NAwK5A': 2089482048}, {'DChKeQ': True, 'C2yU2Q': False}], 'arrNullStr!': [None, 'HQGqMA'], 'arrNullStruct!': [], 'arrNullUnion!': [None, {'One': {}}], 'arrNum!': [], 'arrObj!': [], 'arrStr!': [], 'arrStruct!': [{'optional2!': 1294988167, 'required': True}, {'optional!': False, 'optional2!': 762857662, 'required': False}], 'arrUnion!': [{'One': {}}, {'One': {}}], 'nullFn!': {'fn.example': {'required': False}}, 'nullInt!': 923766970, 'nullNum!': None, 'nullObj!': None, 'nullStr!': 'A68hCA', 'nullStruct!': {'optional!': False, 'optional2!': 227625195, 'required': False}, 'nullUnion!': None, 'num!': 0.6006366734395906, 'obj!': {'Y3LtzQ': 218593023, 'BRY30Q': 70924902}, 'objArr!': {}, 'objFn!': {'DqRNNw': {'fn.example': {'required': True}}, 'KpwP7A': {'fn.example': {'required': False}}}, 'objNullAny!': {}, 'objNullNum!': {'OP+5Eg': None}, 'objNullStruct!': {'QvKNRA': {'optional!': True, 'optional2!': 1292529908, 'required': True}, 'fKCY3w': None}, 'objNullUnion!': {}, 'objNum!': {}, 'objStruct!': {'PNpjDA': {'optional!': True, 'optional2!': 2066233746, 'required': False}}, 'objUnion!': {'fvlCTg': {'One': {}}, 'DRXaLg': {'One': {}}}, 'struct!': {'optional!': False, 'optional2!': 1327910780, 'required': True}}}}]],
        [[{'_gen': True}, {'fn.test': {}}], [{}, {'Ok_': {}}]],
        [[{'_gen': True}, {'fn.test': {}}], [{}, {'Ok_': {'value!': {'arrBool!': [], 'arrNullAny!': [], 'arrNullBool!': [None], 'arrNullInt!': [None], 'arrNullStruct!': [], 'arrNullUnion!': [None], 'arrStruct!': [], 'arrUnion!': [{'One': {}}], 'bool!': True, 'int!': 825841033, 'nullAny!': 'cR7iVg', 'nullArr!': [False], 'nullFn!': None, 'nullInt!': None, 'nullNum!': None, 'nullObj!': None, 'nullUnion!': None, 'objBool!': {}, 'objFn!': {'Ki799g': {'fn.example': {'optional!': False, 'required': True}}, 'f+36+A': {'fn.example': {'optional!': True, 'required': False}}}, 'objNullArr!': {'M4EwOA': [], 'PWShVA': None}, 'objNullBool!': {'SvmJtw': None, 'HkKSWw': False}, 'objNullInt!': {'bDG0Xw': 1400962264, 'RQ/vJw': None}, 'objNullNum!': {}, 'objNullObj!': {'OSgElQ': {'UEWBXQ': True}}, 'objNullStr!': {'P2WAfw': 'FSxo7w', 'RabAwg': None}, 'objNullStruct!': {}, 'objNullUnion!': {}, 'objObj!': {'d/LIKw': {'A6AFGA': 1759883530, 'ZXUTfA': True}}, 'objStr!': {'JRL8ag': 'dvm91Q', 'L57QAg': 'DAdQmA'}, 'objStruct!': {'f0GJNQ': {'optional!': False, 'required': True}, 'FUTN7g': {'optional2!': 1682481020, 'required': True}}, 'objUnion!': {'JGboDg': {'One': {}}, 'Xv3Lyw': {'One': {}}}, 'union!': {'One': {}}}}}]],
        [[{'_gen': True}, {'fn.test': {}}], [{}, {'Ok_': {'value!': {'any!': 743025969, 'arrAny!': [1835151967, 892240628], 'arrNullAny!': [True], 'arrNullArr!': [], 'arrNullBool!': [None], 'arrNullInt!': [None], 'arrNullNum!': [None], 'arrNullObj!': [{'YOxLRg': False}], 'arrNum!': [], 'arrStr!': ['aJoUOw'], 'arrStruct!': [{'required': False}], 'fn!': {'fn.example': {'optional!': True, 'required': False}}, 'nullAny!': None, 'nullArr!': ['fE7eRw', True], 'nullFn!': None, 'nullInt!': 404512936, 'nullNum!': None, 'nullStr!': 'Ga/G/w', 'nullStruct!': None, 'num!': 0.7947967130666583, 'obj!': {}, 'objAny!': {}, 'objBool!': {'Yd2zvw': False, 'FAzqKQ': True}, 'objNullArr!': {'b3Y1MQ': None, 'SsVsTw': None}, 'objNullFn!': {'XrBaWA': None}, 'objNullNum!': {}, 'objNullObj!': {}, 'objNullStr!': {'LI7w2g': 'S5sUAg', 'Lc4DIA': None}, 'objNullStruct!': {'Fh/a0w': None}, 'objNullUnion!': {'AghbAg': None}, 'objNum!': {'OrjcVg': 0.46344568462271507, 'ZLWmqw': 0.00959141506328779}, 'objUnion!': {'evy7sA': {'One': {}}}, 'str!': 'WRv49w', 'struct!': {'required': False}, 'union!': {'One': {}}}}}]],
        [[{'_gen': True}, {'fn.test': {}}], [{}, {'Ok_': {}}]],
    ],
    'emptyPartialMatchVerify': [
        [[{}, {'fn.clearStubs_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.clearCalls_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.createStub_': {'stub': {'fn.test': {}, '->': {'Ok_': {}}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {}}}}], [{}, {'ErrorVerificationFailure': {'reason': {'TooFewMatchingCalls': {'allCalls': [], 'found': 0, 'wanted': {'AtLeast': {'times': 1}}}}}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {}}, 'count!': {'Exact': {'times': 1}}}}], [{}, {'ErrorVerificationFailure': {'reason': {'TooFewMatchingCalls': {'allCalls': [], 'found': 0, 'wanted': {'Exact': {'times': 1}}}}}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {}}, 'count!': {'AtLeast': {'times': 1}}}}], [{}, {'ErrorVerificationFailure': {'reason': {'TooFewMatchingCalls': {'allCalls': [], 'wanted': {'AtLeast': {'times': 1}}, 'found': 0}}}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {}}, 'count!': {'AtMost': {'times': 0}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.test': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.verifyNoMoreInteractions_': {}}], [{}, {'ErrorVerificationFailure': {'additionalUnverifiedCalls': [{'fn.test': {}}]}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.verifyNoMoreInteractions_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {}}, 'count!': {'Exact': {'times': 1}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {}}, 'count!': {'AtLeast': {'times': 1}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {}}, 'count!': {'AtLeast': {'times': 2}}}}], [{}, {'ErrorVerificationFailure': {'reason': {'TooFewMatchingCalls': {'allCalls': [{'fn.test': {}}], 'found': 1, 'wanted': {'AtLeast': {'times': 2}}}}}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {}}, 'count!': {'AtMost': {'times': 1}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {}}, 'count!': {'AtMost': {'times': 0}}}}], [{}, {'ErrorVerificationFailure': {'reason': {'TooManyMatchingCalls': {'wanted': {'AtMost': {'times': 0}}, 'allCalls': [{'fn.test': {}}], 'found': 1}}}}]],
    ],
    'partialMatchVerify': [
        [[{}, {'fn.clearStubs_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.clearCalls_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.createStub_': {'stub': {'fn.test': {'value!': {'int!': 0}}, '->': {'Ok_': {'value!': {'bool!': True}}}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {'value!': {'int!': 0}}}}}], [{}, {'ErrorVerificationFailure': {'reason': {'TooFewMatchingCalls': {'found': 0, 'allCalls': [], 'wanted': {'AtLeast': {'times': 1}}}}}}]],
        [[{}, {'fn.test': {'value!': {'int!': 0, 'str!': 'a'}}}], [{}, {'Ok_': {'value!': {'bool!': True}}}]],
        [[{}, {'fn.verifyNoMoreInteractions_': {}}], [{}, {'ErrorVerificationFailure': {'additionalUnverifiedCalls': [{'fn.test': {'value!': {'int!': 0, 'str!': 'a'}}}]}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {'value!': {'int!': 0}}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.verifyNoMoreInteractions_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {'value!': {'int!': 0}}}, 'count!': {'Exact': {'times': 1}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {'value!': {'int!': 0}}}, 'count!': {'AtLeast': {'times': 1}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {'value!': {'int!': 0}}}, 'count!': {'AtMost': {'times': 0}}}}], [{}, {'ErrorVerificationFailure': {'reason': {'TooManyMatchingCalls': {'wanted': {'AtMost': {'times': 0}}, 'allCalls': [{'fn.test': {'value!': {'int!': 0, 'str!': 'a'}}}], 'found': 1}}}}]],
    ],
    'multiplePartialMatchVerify': [
        [[{}, {'fn.clearStubs_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.clearCalls_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.createStub_': {'stub': {'fn.test': {}, '->': {'Ok_': {}}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {'value!': {'int!': 0}}}}}], [{}, {'ErrorVerificationFailure': {'reason': {'TooFewMatchingCalls': {'found': 0, 'allCalls': [], 'wanted': {'AtLeast': {'times': 1}}}}}}]],
        [[{}, {'fn.test': {'value!': {'int!': 0, 'bool!': True}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 0, 'str!': 'a'}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.verifyNoMoreInteractions_': {}}], [{}, {'ErrorVerificationFailure': {'additionalUnverifiedCalls': [{'fn.test': {'value!': {'int!': 0, 'bool!': True}}}, {'fn.test': {'value!': {'int!': 0, 'str!': 'a'}}}, {'fn.test': {'value!': {'int!': 1}}}]}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {'value!': {'int!': 0}}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.verifyNoMoreInteractions_': {}}], [{}, {'ErrorVerificationFailure': {'additionalUnverifiedCalls': [{'fn.test': {'value!': {'int!': 1}}}]}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.verifyNoMoreInteractions_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {'value!': {'int!': 0}}}, 'count!': {'Exact': {'times': 1}}}}], [{}, {'ErrorVerificationFailure': {'reason': {'TooManyMatchingCalls': {'wanted': {'Exact': {'times': 1}}, 'allCalls': [{'fn.test': {'value!': {'int!': 0, 'bool!': True}}}, {'fn.test': {'value!': {'int!': 0, 'str!': 'a'}}}, {'fn.test': {'value!': {'int!': 1}}}], 'found': 2}}}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {'value!': {'int!': 0}}}, 'count!': {'Exact': {'times': 2}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {'value!': {'int!': 0}}}, 'count!': {'Exact': {'times': 3}}}}], [{}, {'ErrorVerificationFailure': {'reason': {'TooFewMatchingCalls': {'wanted': {'Exact': {'times': 3}}, 'allCalls': [{'fn.test': {'value!': {'int!': 0, 'bool!': True}}}, {'fn.test': {'value!': {'int!': 0, 'str!': 'a'}}}, {'fn.test': {'value!': {'int!': 1}}}], 'found': 2}}}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {'value!': {'int!': 0}}}, 'count!': {'AtLeast': {'times': 1}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {'value!': {'int!': 0}}}, 'count!': {'AtMost': {'times': 1}}}}], [{}, {'ErrorVerificationFailure': {'reason': {'TooManyMatchingCalls': {'wanted': {'AtMost': {'times': 1}}, 'allCalls': [{'fn.test': {'value!': {'int!': 0, 'bool!': True}}}, {'fn.test': {'value!': {'int!': 0, 'str!': 'a'}}}, {'fn.test': {'value!': {'int!': 1}}}], 'found': 2}}}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {'value!': {'int!': 0}}}, 'count!': {'AtMost': {'times': 2}}}}], [{}, {'Ok_': {}}]],
    ],
    'strictMatchVerify': [
        [[{}, {'fn.clearStubs_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.clearCalls_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.createStub_': {'stub': {'fn.test': {}, '->': {'Ok_': {}}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {'value!': {'int!': 0}}}, 'strictMatch!': True}}], [{}, {'ErrorVerificationFailure': {'reason': {'TooFewMatchingCalls': {'found': 0, 'allCalls': [], 'wanted': {'AtLeast': {'times': 1}}}}}}]],
        [[{}, {'fn.test': {'value!': {'int!': 0}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.verifyNoMoreInteractions_': {}}], [{}, {'ErrorVerificationFailure': {'additionalUnverifiedCalls': [{'fn.test': {'value!': {'int!': 0}}}]}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {'value!': {'int!': 0}}}, 'strictMatch!': True}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.verifyNoMoreInteractions_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {'value!': {'int!': 1}}}, 'strictMatch!': True}}], [{}, {'ErrorVerificationFailure': {'reason': {'TooFewMatchingCalls': {'found': 0, 'allCalls': [{'fn.test': {'value!': {'int!': 0}}}], 'wanted': {'AtLeast': {'times': 1}}}}}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {'value!': {'int!': 0, 'str!': 'a'}}}, 'strictMatch!': True}}], [{}, {'ErrorVerificationFailure': {'reason': {'TooFewMatchingCalls': {'found': 0, 'allCalls': [{'fn.test': {'value!': {'int!': 0}}}], 'wanted': {'AtLeast': {'times': 1}}}}}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {'value!': {'int!': 0}}}, 'strictMatch!': True, 'count!': {'Exact': {'times': 0}}}}], [{}, {'ErrorVerificationFailure': {'reason': {'TooManyMatchingCalls': {'wanted': {'Exact': {'times': 0}}, 'allCalls': [{'fn.test': {'value!': {'int!': 0}}}], 'found': 1}}}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {'value!': {'int!': 0}}}, 'strictMatch!': True, 'count!': {'Exact': {'times': 2}}}}], [{}, {'ErrorVerificationFailure': {'reason': {'TooFewMatchingCalls': {'wanted': {'Exact': {'times': 2}}, 'allCalls': [{'fn.test': {'value!': {'int!': 0}}}], 'found': 1}}}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {'value!': {'int!': 0}}}, 'strictMatch!': True, 'count!': {'Exact': {'times': 1}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {'value!': {'int!': 0}}}, 'strictMatch!': True, 'count!': {'AtLeast': {'times': 2}}}}], [{}, {'ErrorVerificationFailure': {'reason': {'TooFewMatchingCalls': {'wanted': {'AtLeast': {'times': 2}}, 'allCalls': [{'fn.test': {'value!': {'int!': 0}}}], 'found': 1}}}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {'value!': {'int!': 0}}}, 'strictMatch!': True, 'count!': {'AtLeast': {'times': 1}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {'value!': {'int!': 0}}}, 'strictMatch!': True, 'count!': {'AtMost': {'times': 1}}}}], [{}, {'Ok_': {}}]],
    ],
    'multipleStrictMatchVerify': [
        [[{}, {'fn.clearStubs_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.clearCalls_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.createStub_': {'stub': {'fn.test': {}, '->': {'Ok_': {}}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {'value!': {'int!': 0}}}, 'strictMatch!': True}}], [{}, {'ErrorVerificationFailure': {'reason': {'TooFewMatchingCalls': {'found': 0, 'allCalls': [], 'wanted': {'AtLeast': {'times': 1}}}}}}]],
        [[{}, {'fn.test': {'value!': {'int!': 0}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 0, 'str!': 'a'}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.verifyNoMoreInteractions_': {}}], [{}, {'ErrorVerificationFailure': {'additionalUnverifiedCalls': [{'fn.test': {'value!': {'int!': 0}}}, {'fn.test': {'value!': {'int!': 0, 'str!': 'a'}}}]}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {'value!': {'int!': 0}}}, 'strictMatch!': True}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.verifyNoMoreInteractions_': {}}], [{}, {'ErrorVerificationFailure': {'additionalUnverifiedCalls': [{'fn.test': {'value!': {'int!': 0, 'str!': 'a'}}}]}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.verifyNoMoreInteractions_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {'value!': {'int!': 1}}}, 'strictMatch!': True}}], [{}, {'ErrorVerificationFailure': {'reason': {'TooFewMatchingCalls': {'found': 0, 'allCalls': [{'fn.test': {'value!': {'int!': 0}}}, {'fn.test': {'value!': {'int!': 0, 'str!': 'a'}}}], 'wanted': {'AtLeast': {'times': 1}}}}}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {'value!': {'int!': 0, 'str!': 'b'}}}, 'strictMatch!': True}}], [{}, {'ErrorVerificationFailure': {'reason': {'TooFewMatchingCalls': {'found': 0, 'allCalls': [{'fn.test': {'value!': {'int!': 0}}}, {'fn.test': {'value!': {'int!': 0, 'str!': 'a'}}}], 'wanted': {'AtLeast': {'times': 1}}}}}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {'value!': {'int!': 0}}}, 'strictMatch!': True, 'count!': {'Exact': {'times': 0}}}}], [{}, {'ErrorVerificationFailure': {'reason': {'TooManyMatchingCalls': {'wanted': {'Exact': {'times': 0}}, 'allCalls': [{'fn.test': {'value!': {'int!': 0}}}, {'fn.test': {'value!': {'int!': 0, 'str!': 'a'}}}], 'found': 1}}}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {'value!': {'int!': 0}}}, 'strictMatch!': True, 'count!': {'Exact': {'times': 2}}}}], [{}, {'ErrorVerificationFailure': {'reason': {'TooFewMatchingCalls': {'wanted': {'Exact': {'times': 2}}, 'allCalls': [{'fn.test': {'value!': {'int!': 0}}}, {'fn.test': {'value!': {'int!': 0, 'str!': 'a'}}}], 'found': 1}}}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {'value!': {'int!': 0}}}, 'strictMatch!': True, 'count!': {'Exact': {'times': 1}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {'value!': {'int!': 0}}}, 'strictMatch!': True, 'count!': {'AtLeast': {'times': 2}}}}], [{}, {'ErrorVerificationFailure': {'reason': {'TooFewMatchingCalls': {'wanted': {'AtLeast': {'times': 2}}, 'allCalls': [{'fn.test': {'value!': {'int!': 0}}}, {'fn.test': {'value!': {'int!': 0, 'str!': 'a'}}}], 'found': 1}}}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {'value!': {'int!': 0}}}, 'strictMatch!': True, 'count!': {'AtLeast': {'times': 1}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {'value!': {'int!': 0}}}, 'strictMatch!': True, 'count!': {'AtMost': {'times': 1}}}}], [{}, {'Ok_': {}}]],
    ],
    'multipleNestedPartialMatchVerify': [
        [[{}, {'fn.clearStubs_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.clearCalls_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.createStub_': {'stub': {'fn.test': {}, '->': {'Ok_': {}}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {'value!': {'int!': 0}}}}}], [{}, {'ErrorVerificationFailure': {'reason': {'TooFewMatchingCalls': {'found': 0, 'allCalls': [], 'wanted': {'AtLeast': {'times': 1}}}}}}]],
        [[{}, {'fn.test': {'value!': {'struct!': {'required': True}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.test': {'value!': {'struct!': {'required': True, 'optional!': True}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.verifyNoMoreInteractions_': {}}], [{}, {'ErrorVerificationFailure': {'additionalUnverifiedCalls': [{'fn.test': {'value!': {'struct!': {'required': True}}}}, {'fn.test': {'value!': {'struct!': {'required': True, 'optional!': True}}}}]}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {'value!': {'struct!': {'optional!': True}}}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.verifyNoMoreInteractions_': {}}], [{}, {'ErrorVerificationFailure': {'additionalUnverifiedCalls': [{'fn.test': {'value!': {'struct!': {'required': True}}}}]}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.verifyNoMoreInteractions_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {'value!': {'struct!': {'optional!': True}}}}, 'count!': {'Exact': {'times': 1}}}}], [{}, {'Ok_': {}}]],
    ],
    'multipleReallyNestedPartialMatchVerify': [
        [[{}, {'fn.clearStubs_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.clearCalls_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.createStub_': {'stub': {'fn.test': {}, '->': {'Ok_': {}}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {'value!': {'int!': 0}}}}}], [{}, {'ErrorVerificationFailure': {'reason': {'TooFewMatchingCalls': {'found': 0, 'allCalls': [], 'wanted': {'AtLeast': {'times': 1}}}}}}]],
        [[{}, {'fn.test': {'value!': {'arrStruct!': [{'required': False}, {'required': True}]}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.test': {'value!': {'arrStruct!': [{'required': False}, {'required': True, 'optional!': True}]}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {'value!': {'arrStruct!': [{'optional!': True}]}}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.verifyNoMoreInteractions_': {}}], [{}, {'ErrorVerificationFailure': {'additionalUnverifiedCalls': [{'fn.test': {'value!': {'arrStruct!': [{'required': False}, {'required': True}]}}}]}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.verifyNoMoreInteractions_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {'value!': {'arrStruct!': [{'optional!': True}]}}}, 'count!': {'Exact': {'times': 1}}}}], [{}, {'Ok_': {}}]],
    ],
    'clearCalls': [
        [[{}, {'fn.clearStubs_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.clearCalls_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.createStub_': {'stub': {'fn.test': {}, '->': {'Ok_': {}}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {}}}}], [{}, {'ErrorVerificationFailure': {'reason': {'TooFewMatchingCalls': {'found': 0, 'allCalls': [], 'wanted': {'AtLeast': {'times': 1}}}}}}]],
        [[{}, {'fn.test': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.clearCalls_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {}}}}], [{}, {'ErrorVerificationFailure': {'reason': {'TooFewMatchingCalls': {'found': 0, 'allCalls': [], 'wanted': {'AtLeast': {'times': 1}}}}}}]],
    ],
    'resultSuppliesMissingRequiredFields': [
        [[{}, {'fn.setRandomSeed_': {'seed': 0}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.clearStubs_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.clearCalls_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.test': {}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.createStub_': {'stub': {'fn.test': {}, '->': {'Ok_': {'value!': {'bool!': True, 'struct!': {'optional!': True}}}}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.test': {}}], [{}, {'Ok_': {'value!': {'bool!': True, 'struct!': {'optional!': True, 'required': True}}}}]],
    ],
    'resultWithStartingValue': [
        [[{}, {'fn.clearStubs_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.clearCalls_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.test': {}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.createStub_': {'stub': {'fn.test': {}, '->': {'Ok_': {'value!': {'bool!': False, 'int!': 0, 'num!': 0.1, 'str!': '', 'arrBool!': [False], 'objBool!': {'a': False}, 'struct!': {'required': False}, 'union!': {'Two': {'required': False}}, 'fn!': {'fn.example': {'required': False}}}}}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.test': {}}], [{}, {'Ok_': {'value!': {'bool!': False, 'int!': 0, 'num!': 0.1, 'str!': '', 'arrBool!': [False], 'objBool!': {'a': False}, 'struct!': {'required': False}, 'union!': {'Two': {'required': False}}, 'fn!': {'fn.example': {'required': False}}}}}]],
    ],
}
