from typing import Any

from qa.test.cases import get_values
from qa.test.cases import additional_union_cases, additional_fn_cases, additional_integer_cases, additional_number_cases, additional_p2Union_cases, additional_p2Str_cases, additional_struct_cases


def generate_mock_cases(given_field: str, the_type, correct_values, additional_incorrect_values = []):
    for field, _, incorrect_values, base_path in get_values(given_field, the_type, correct_values, additional_incorrect_values):
        for incorrect_value, errors in incorrect_values:
            cases = [{'path': ['fn._createStub', 'stub', 'fn.test', 'value!'] + base_path + path, 'reason': reason} for reason, path in errors if 'RequiredObjectKeyMissing' not in reason]
            if not cases:
                continue

            yield [[{}, {'fn._createStub': {'stub': {'fn.test': {'value!': {field: incorrect_value}}, '->': {'Ok': {}}}}}], [{}, {'_ErrorInvalidRequestBody': {'cases': cases}}]]

        for incorrect_value, errors in incorrect_values:
            cases = [{'path': ['fn._createStub', 'stub', '->', 'Ok', 'value!'] + base_path + path, 'reason': reason} for reason, path in errors if 'RequiredObjectKeyMissing' not in reason]
            if not cases:
                continue
            yield [[{}, {'fn._createStub': {'stub': {'fn.test': {}, '->': {'Ok': {'value!': {field: incorrect_value}}}}}}], [{}, {'_ErrorInvalidRequestBody': {'cases': cases}}]]



invalid_cases = {
    'boolean': [v for v in generate_mock_cases('bool!', bool, [False, True])],
    'integer': [v for v in generate_mock_cases('int!', int, [0, -1, 1, 9223372036854775807, -9223372036854775808], additional_integer_cases)],
    'number': [v for v in generate_mock_cases('num!', float, [0, -1, 1, -1.7976931348623157e+308, -2.2250738585072014e-308, 2.2250738585072014e-308, 1.7976931348623157e+308, -0.1, 0.1], additional_number_cases)],
    'string': [v for v in generate_mock_cases('str!', str, ['', 'abc'])],
    'array': [v for v in generate_mock_cases('arr!', list, [[], [False, 0, 0.1, '']])],
    'object': [v for v in generate_mock_cases('obj!', dict, [{}, {'a': False, 'b': 0, 'c': 0.1, 'd': ''}])],
    'any': [v for v in generate_mock_cases('any!', Any, [False, 0, 0.1, '', [], {}])],
    'struct': [v for v in generate_mock_cases('struct!', dict, [{'required': False}, {'optional!': False, 'required': False}], additional_struct_cases)],
    'union': [v for v in generate_mock_cases('union!', dict, [{'One': {}}, {'Two':{'required': False}}, {'Two':{'optional!': False, 'required': False}}], additional_union_cases)],
    'fn': [v for v in generate_mock_cases('fn!', dict, [{'fn.example': {'required': False}}, {'fn.example': {'optional!': False, 'required': False}}], additional_fn_cases)],
    'p2Str': [v for v in generate_mock_cases('p2Str!', dict, [{'wrap': False, 'nest': [0]}, {'wrap': True, 'nest': [1]}], additional_p2Str_cases)],
    'p2Union': [v for v in generate_mock_cases('p2Union!', dict, [{'Two': {'ewrap': False, 'enest': [0]}}, {'Two': {'ewrap': True, 'enest': [1]}}], additional_p2Union_cases)],
    'stub': [
        [[{}, {'fn._createStub': {'stub': False}}], [{}, {'_ErrorInvalidRequestBody': {'cases': [{'path': ['fn._createStub', 'stub'], 'reason': {'TypeUnexpected': {'actual': {'Boolean': {}}, 'expected': {'Object': {}}}}}]}}]],
        [[{}, {'fn._createStub': {'stub': 0}}], [{}, {'_ErrorInvalidRequestBody': {'cases': [{'path': ['fn._createStub', 'stub'], 'reason': {'TypeUnexpected': {'actual': {'Number': {}}, 'expected': {'Object': {}}}}}]}}]],
        [[{}, {'fn._createStub': {'stub': ''}}], [{}, {'_ErrorInvalidRequestBody': {'cases': [{'path': ['fn._createStub', 'stub'], 'reason': {'TypeUnexpected': {'actual': {'String': {}}, 'expected': {'Object': {}}}}}]}}]],
        [[{}, {'fn._createStub': {'stub': []}}], [{}, {'_ErrorInvalidRequestBody': {'cases': [{'path': ['fn._createStub', 'stub'], 'reason': {'TypeUnexpected': {'actual': {'Array': {}}, 'expected': {'Object': {}}}}}]}}]],
        [[{}, {'fn._createStub': {'stub': {}}}], [{}, {'_ErrorInvalidRequestBody': {'cases': [{'path': ['fn._createStub', 'stub'], 'reason': {'ObjectKeyRegexMatchCountUnexpected': {'regex': '^fn\\..*$', 'actual': 0, 'expected': 1}}}]}}]],
        [[{}, {'fn._createStub': {'stub': {'fn.test': {}}}}], [{}, {'_ErrorInvalidRequestBody': {'cases': [{'path': ['fn._createStub', 'stub', '->'], 'reason': {'RequiredObjectKeyMissing': {}}}]}}]],
        [[{}, {'fn._createStub': {'stub': {'fn.test': {}, '->': {}}}}], [{}, {'_ErrorInvalidRequestBody': {'cases': [{'path': ['fn._createStub', 'stub', '->'], 'reason': {'ObjectSizeUnexpected': {'actual': 0, 'expected': 1}}}]}}]],
        [[{}, {'fn._createStub': {'stub': {'fn.testAnother': {}, 'fn.test': {}, '->': {'Ok': {}}}}}], [{}, {'_ErrorInvalidRequestBody': {'cases': [{'path': ['fn._createStub', 'stub'], 'reason': {'ObjectKeyRegexMatchCountUnexpected': {'regex': '^fn\\..*$', 'actual': 2, 'expected': 1}}}]}}]],
        [[{}, {'fn._createStub': {'stub': {'wrong': True, 'fn.test': {}, '->': {'Ok': {}}}}}], [{}, {'_ErrorInvalidRequestBody': {'cases': [{'path': ['fn._createStub', 'stub', 'wrong'], 'reason': {'ObjectKeyDisallowed': {}}}]}}]],
    ],
}

cases = {
    'emptyPartialMatchStub': [
        [[{}, {'fn._clearStubs': {}}], [{}, {'Ok': {}}]],
        [[{}, {'fn._clearCalls': {}}], [{}, {'Ok': {}}]],
        [[{}, {'fn.test': {}}], [{}, {'_ErrorNoMatchingStub': {}}]],
        [[{}, {'fn._createStub': {'stub': {'fn.test': {}, '->': {'Ok': {}}}}}], [{}, {'Ok': {}}]],
        [[{}, {'fn.test': {}}], [{}, {'Ok': {}}]],
    ],
    'partialMatchStub': [
        [[{}, {'fn._clearStubs': {}}], [{}, {'Ok': {}}]],
        [[{}, {'fn._clearCalls': {}}], [{}, {'Ok': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1}}}], [{}, {'_ErrorNoMatchingStub': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1, 'str!': 'a'}}}], [{}, {'_ErrorNoMatchingStub': {}}]],
        [[{}, {'fn._createStub': {'stub': {'fn.test': {'value!': {'int!': 1}}, '->': {'Ok': {'value!': {'bool!': True}}}}}}], [{}, {'Ok': {}}]],
        [[{}, {'fn.test': {}}], [{}, {'_ErrorNoMatchingStub': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 0}}}], [{}, {'_ErrorNoMatchingStub': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1}}}], [{}, {'Ok': {'value!': {'bool!': True}}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1, 'str!': 'a'}}}], [{}, {'Ok': {'value!': {'bool!': True}}}]],
    ],
    'multiplePartialMatchStub': [
        [[{}, {'fn._clearStubs': {}}], [{}, {'Ok': {}}]],
        [[{}, {'fn._clearCalls': {}}], [{}, {'Ok': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1}}}], [{}, {'_ErrorNoMatchingStub': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1, 'str!': 'a'}}}], [{}, {'_ErrorNoMatchingStub': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 0, 'str!': 'a'}}}], [{}, {'_ErrorNoMatchingStub': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1, 'str!': 'b'}}}], [{}, {'_ErrorNoMatchingStub': {}}]],
        [[{}, {'fn.test': {'value!': {'bool!': False, 'int!': 1, 'str!': 'a'}}}], [{}, {'_ErrorNoMatchingStub': {}}]],
        [[{}, {'fn._createStub': {'stub': {'fn.test': {'value!': {'int!': 1}}, '->': {'Ok': {'value!': {'bool!': True}}}}}}], [{}, {'Ok': {}}]],
        [[{}, {'fn._createStub': {'stub': {'fn.test': {'value!': {'str!': 'a'}}, '->': {'Ok': {'value!': {'bool!': False}}}}}}], [{}, {'Ok': {}}]],
        [[{}, {'fn._createStub': {'stub': {'fn.example': {}, '->': {'Ok': {}}}}}], [{}, {'Ok': {}}]],
        [[{}, {'fn.test': {}}], [{}, {'_ErrorNoMatchingStub': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 0}}}], [{}, {'_ErrorNoMatchingStub': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1}}}], [{}, {'Ok': {'value!': {'bool!': True}}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1, 'str!': 'a'}}}], [{}, {'Ok': {'value!': {'bool!': False}}}]],
        [[{}, {'fn.test': {'value!': {'int!': 0, 'str!': 'a'}}}], [{}, {'Ok': {'value!': {'bool!': False}}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1, 'str!': 'b'}}}], [{}, {'Ok': {'value!': {'bool!': True}}}]],
        [[{}, {'fn.test': {'value!': {'bool!': False, 'int!': 1, 'str!': 'a'}}}], [{}, {'Ok': {'value!': {'bool!': False}}}]],
    ],
    'multiplePartialMatchStubCount': [
        [[{}, {'fn._clearStubs': {}}], [{}, {'Ok': {}}]],
        [[{}, {'fn._clearCalls': {}}], [{}, {'Ok': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1}}}], [{}, {'_ErrorNoMatchingStub': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1, 'str!': 'a'}}}], [{}, {'_ErrorNoMatchingStub': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 0, 'str!': 'a'}}}], [{}, {'_ErrorNoMatchingStub': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1, 'str!': 'b'}}}], [{}, {'_ErrorNoMatchingStub': {}}]],
        [[{}, {'fn.test': {'value!': {'bool!': False, 'int!': 1, 'str!': 'a'}}}], [{}, {'_ErrorNoMatchingStub': {}}]],
        [[{}, {'fn._createStub': {'count!': 2, 'stub': {'fn.test': {'value!': {'int!': 1}}, '->': {'Ok': {'value!': {'bool!': True}}}}}}], [{}, {'Ok': {}}]],
        [[{}, {'fn._createStub': {'count!': 1, 'stub': {'fn.test': {'value!': {'str!': 'a'}}, '->': {'Ok': {'value!': {'bool!': False}}}}}}], [{}, {'Ok': {}}]],
        [[{}, {'fn._createStub': {'stub': {'fn.example': {}, '->': {'Ok': {}}}}}], [{}, {'Ok': {}}]],
        [[{}, {'fn.test': {}}], [{}, {'_ErrorNoMatchingStub': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 0}}}], [{}, {'_ErrorNoMatchingStub': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1}}}], [{}, {'Ok': {'value!': {'bool!': True}}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1, 'str!': 'a'}}}], [{}, {'Ok': {'value!': {'bool!': False}}}]],
        [[{}, {'fn.test': {'value!': {'int!': 0, 'str!': 'a'}}}], [{}, {'_ErrorNoMatchingStub': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1, 'str!': 'b'}}}], [{}, {'Ok': {'value!': {'bool!': True}}}]],
        [[{}, {'fn.test': {'value!': {'bool!': False, 'int!': 1, 'str!': 'a'}}}], [{}, {'_ErrorNoMatchingStub': {}}]],
    ],    
    'multipleNestedPartialMatchStub': [
        [[{}, {'fn._clearStubs': {}}], [{}, {'Ok': {}}]],
        [[{}, {'fn._clearCalls': {}}], [{}, {'Ok': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1}}}], [{}, {'_ErrorNoMatchingStub': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1, 'str!': 'a'}}}], [{}, {'_ErrorNoMatchingStub': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 0, 'str!': 'a'}}}], [{}, {'_ErrorNoMatchingStub': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1, 'str!': 'b'}}}], [{}, {'_ErrorNoMatchingStub': {}}]],
        [[{}, {'fn.test': {'value!': {'bool!': False, 'int!': 1, 'str!': 'a'}}}], [{}, {'_ErrorNoMatchingStub': {}}]],
        [[{}, {'fn._createStub': {'stub': {'fn.test': {'value!': {'struct!': {'optional!': True}}}, '->': {'Ok': {'value!': {'bool!': True}}}}}}], [{}, {'Ok': {}}]],
        [[{}, {'fn._createStub': {'stub': {'fn.test': {'value!': {'struct!': {'required': True}}}, '->': {'Ok': {'value!': {'bool!': False}}}}}}], [{}, {'Ok': {}}]],
        [[{}, {'fn._createStub': {'stub': {'fn.example': {}, '->': {'Ok': {}}}}}], [{}, {'Ok': {}}]],
        [[{}, {'fn.test': {}}], [{}, {'_ErrorNoMatchingStub': {}}]],
        [[{}, {'fn.test': {'value!': {'struct!': {'required': False}}}}], [{}, {'_ErrorNoMatchingStub': {}}]],
        [[{}, {'fn.test': {'value!': {'struct!': {'optional!': False, 'required': False}}}}], [{}, {'_ErrorNoMatchingStub': {}}]],
        [[{}, {'fn.test': {'value!': {'struct!': {'optional!': True, 'required': True}}}}], [{}, {'Ok': {'value!': {'bool!': False}}}]],
        [[{}, {'fn.test': {'value!': {'struct!': {'optional!': True, 'required': False}}}}], [{}, {'Ok': {'value!': {'bool!': True}}}]],
        [[{}, {'fn.test': {'value!': {'struct!': {'required': True}}}}], [{}, {'Ok': {'value!': {'bool!': False}}}]],
        [[{}, {'fn.test': {'value!': {'struct!': {'optional!': False, 'required': True}}}}], [{}, {'Ok': {'value!': {'bool!': False}}}]],
        [[{}, {'fn.test': {'value!': {'struct!': {'optional!': True, 'required': False}, 'str!': 'b'}}}], [{}, {'Ok': {'value!': {'bool!': True}}}]],
    ],
    'multipleNestedPartialMatchStubCount': [
        [[{}, {'fn._clearStubs': {}}], [{}, {'Ok': {}}]],
        [[{}, {'fn._clearCalls': {}}], [{}, {'Ok': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1}}}], [{}, {'_ErrorNoMatchingStub': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1, 'str!': 'a'}}}], [{}, {'_ErrorNoMatchingStub': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 0, 'str!': 'a'}}}], [{}, {'_ErrorNoMatchingStub': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1, 'str!': 'b'}}}], [{}, {'_ErrorNoMatchingStub': {}}]],
        [[{}, {'fn.test': {'value!': {'bool!': False, 'int!': 1, 'str!': 'a'}}}], [{}, {'_ErrorNoMatchingStub': {}}]],
        [[{}, {'fn._createStub': {'count!': 1, 'stub': {'fn.test': {'value!': {'struct!': {'optional!': True}}}, '->': {'Ok': {'value!': {'bool!': True}}}}}}], [{}, {'Ok': {}}]],
        [[{}, {'fn._createStub': {'count!': 2, 'stub': {'fn.test': {'value!': {'struct!': {'required': True}}}, '->': {'Ok': {'value!': {'bool!': False}}}}}}], [{}, {'Ok': {}}]],
        [[{}, {'fn._createStub': {'stub': {'fn.example': {}, '->': {'Ok': {}}}}}], [{}, {'Ok': {}}]],
        [[{}, {'fn.test': {}}], [{}, {'_ErrorNoMatchingStub': {}}]],
        [[{}, {'fn.test': {'value!': {'struct!': {'required': False}}}}], [{}, {'_ErrorNoMatchingStub': {}}]],
        [[{}, {'fn.test': {'value!': {'struct!': {'optional!': False, 'required': False}}}}], [{}, {'_ErrorNoMatchingStub': {}}]],
        [[{}, {'fn.test': {'value!': {'struct!': {'optional!': True, 'required': True}}}}], [{}, {'Ok': {'value!': {'bool!': False}}}]],
        [[{}, {'fn.test': {'value!': {'struct!': {'optional!': True, 'required': False}}}}], [{}, {'Ok': {'value!': {'bool!': True}}}]],
        [[{}, {'fn.test': {'value!': {'struct!': {'required': True}}}}], [{}, {'Ok': {'value!': {'bool!': False}}}]],
        [[{}, {'fn.test': {'value!': {'struct!': {'optional!': False, 'required': True}}}}], [{}, {'_ErrorNoMatchingStub': {}}]],
        [[{}, {'fn.test': {'value!': {'struct!': {'optional!': True, 'required': False}, 'str!': 'b'}}}], [{}, {'_ErrorNoMatchingStub': {}}]],
    ],    
    'multipleReallyNestedPartialMatchStub': [
        [[{}, {'fn._clearStubs': {}}], [{}, {'Ok': {}}]],
        [[{}, {'fn._clearCalls': {}}], [{}, {'Ok': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1}}}], [{}, {'_ErrorNoMatchingStub': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1, 'str!': 'a'}}}], [{}, {'_ErrorNoMatchingStub': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 0, 'str!': 'a'}}}], [{}, {'_ErrorNoMatchingStub': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1, 'str!': 'b'}}}], [{}, {'_ErrorNoMatchingStub': {}}]],
        [[{}, {'fn.test': {'value!': {'bool!': False, 'int!': 1, 'str!': 'a'}}}], [{}, {'_ErrorNoMatchingStub': {}}]],
        [[{}, {'fn._createStub': {'stub': {'fn.test': {'value!': {'arrStruct!': [{'optional!': True}]}}, '->': {'Ok': {'value!': {'bool!': True}}}}}}], [{}, {'Ok': {}}]],
        [[{}, {'fn._createStub': {'stub': {'fn.test': {'value!': {'arrStruct!': [{'required': True}]}}, '->': {'Ok': {'value!': {'bool!': False}}}}}}], [{}, {'Ok': {}}]],
        [[{}, {'fn._createStub': {'stub': {'fn.example': {}, '->': {'Ok': {}}}}}], [{}, {'Ok': {}}]],
        [[{}, {'fn.test': {}}], [{}, {'_ErrorNoMatchingStub': {}}]],
        [[{}, {'fn.test': {'value!': {'arrStruct!': [{'required': False}, {'optional!': False, 'required': False}]}}}], [{}, {'_ErrorNoMatchingStub': {}}]],
        [[{}, {'fn.test': {'value!': {'arrStruct!': [{'required': False}, {'optional!': True, 'required': True}]}}}], [{}, {'Ok': {'value!': {'bool!': False}}}]],
        [[{}, {'fn.test': {'value!': {'arrStruct!': [{'required': False}, {'optional!': True, 'required': False}]}}}], [{}, {'Ok': {'value!': {'bool!': True}}}]],
        [[{}, {'fn.test': {'value!': {'arrStruct!': [{'required': False}, {'optional!': False, 'required': True}]}}}], [{}, {'Ok': {'value!': {'bool!': False}}}]],
        [[{}, {'fn.test': {'value!': {'arrStruct!': [{'required': False}, {'optional!': True, 'required': False}], 'str!': 'b'}}}], [{}, {'Ok': {'value!': {'bool!': True}}}]],
    ],
    'multipleReallyNestedPartialMatchStubCount': [
        [[{}, {'fn._clearStubs': {}}], [{}, {'Ok': {}}]],
        [[{}, {'fn._clearCalls': {}}], [{}, {'Ok': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1}}}], [{}, {'_ErrorNoMatchingStub': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1, 'str!': 'a'}}}], [{}, {'_ErrorNoMatchingStub': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 0, 'str!': 'a'}}}], [{}, {'_ErrorNoMatchingStub': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1, 'str!': 'b'}}}], [{}, {'_ErrorNoMatchingStub': {}}]],
        [[{}, {'fn.test': {'value!': {'bool!': False, 'int!': 1, 'str!': 'a'}}}], [{}, {'_ErrorNoMatchingStub': {}}]],
        [[{}, {'fn._createStub': {'count!': 1, 'stub': {'fn.test': {'value!': {'arrStruct!': [{'optional!': True}]}}, '->': {'Ok': {'value!': {'bool!': True}}}}}}], [{}, {'Ok': {}}]],
        [[{}, {'fn._createStub': {'count!': 1, 'stub': {'fn.test': {'value!': {'arrStruct!': [{'required': True}]}}, '->': {'Ok': {'value!': {'bool!': False}}}}}}], [{}, {'Ok': {}}]],
        [[{}, {'fn._createStub': {'stub': {'fn.example': {}, '->': {'Ok': {}}}}}], [{}, {'Ok': {}}]],
        [[{}, {'fn.test': {}}], [{}, {'_ErrorNoMatchingStub': {}}]],
        [[{}, {'fn.test': {'value!': {'arrStruct!': [{'required': False}, {'optional!': False, 'required': False}]}}}], [{}, {'_ErrorNoMatchingStub': {}}]],
        [[{}, {'fn.test': {'value!': {'arrStruct!': [{'required': False}, {'optional!': True, 'required': True}]}}}], [{}, {'Ok': {'value!': {'bool!': False}}}]],
        [[{}, {'fn.test': {'value!': {'arrStruct!': [{'required': False}, {'optional!': True, 'required': False}]}}}], [{}, {'Ok': {'value!': {'bool!': True}}}]],
        [[{}, {'fn.test': {'value!': {'arrStruct!': [{'required': False}, {'optional!': False, 'required': True}]}}}], [{}, {'_ErrorNoMatchingStub': {}}]],
        [[{}, {'fn.test': {'value!': {'arrStruct!': [{'required': False}, {'optional!': True, 'required': False}], 'str!': 'b'}}}], [{}, {'_ErrorNoMatchingStub': {}}]],
    ],    
    'strictMatchStub': [
        [[{}, {'fn._clearStubs': {}}], [{}, {'Ok': {}}]],
        [[{}, {'fn._clearCalls': {}}], [{}, {'Ok': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1}}}], [{}, {'_ErrorNoMatchingStub': {}}]],
        [[{}, {'fn._createStub': {'stub': {'fn.test': {'value!': {'int!': 1}}, '->': {'Ok': {'value!': {'bool!': True}}}}, 'strictMatch!': True}}], [{}, {'Ok': {}}]],
        [[{}, {'fn.test': {}}], [{}, {'_ErrorNoMatchingStub': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 0}}}], [{}, {'_ErrorNoMatchingStub': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1}}}], [{}, {'Ok': {'value!': {'bool!': True}}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1, 'str!': 'a'}}}], [{}, {'_ErrorNoMatchingStub': {}}]],
    ],
    'multipleStrictMatchStub': [
        [[{}, {'fn._clearStubs': {}}], [{}, {'Ok': {}}]],
        [[{}, {'fn._clearCalls': {}}], [{}, {'Ok': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1}}}], [{}, {'_ErrorNoMatchingStub': {}}]],
        [[{}, {'fn.test': {'value!': {'str!': 'a'}}}], [{}, {'_ErrorNoMatchingStub': {}}]],
        [[{}, {'fn._createStub': {'stub': {'fn.test': {'value!': {'int!': 1}}, '->': {'Ok': {'value!': {'bool!': True}}}}, 'strictMatch!': True}}], [{}, {'Ok': {}}]],
        [[{}, {'fn._createStub': {'stub': {'fn.test': {'value!': {'str!': 'a'}}, '->': {'Ok': {'value!': {'bool!': False}}}}, 'strictMatch!': True}}], [{}, {'Ok': {}}]],
        [[{}, {'fn.test': {}}], [{}, {'_ErrorNoMatchingStub': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 0}}}], [{}, {'_ErrorNoMatchingStub': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1}}}], [{}, {'Ok': {'value!': {'bool!': True}}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1, 'str!': 'a'}}}], [{}, {'_ErrorNoMatchingStub': {}}]],
        [[{}, {'fn.test': {'value!': {'str!': 'a'}}}], [{}, {'Ok': {'value!': {'bool!': False}}}]],
        [[{}, {'fn.test': {'value!': {'int!': 0, 'str!': 'a'}}}], [{}, {'_ErrorNoMatchingStub': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1, 'str!': 'b'}}}], [{}, {'_ErrorNoMatchingStub': {}}]],
        [[{}, {'fn.test': {'value!': {'bool!': False, 'int!': 1, 'str!': 'a'}}}], [{}, {'_ErrorNoMatchingStub': {}}]],
    ],
    'multipleStrictMatchStubCount': [
        [[{}, {'fn._clearStubs': {}}], [{}, {'Ok': {}}]],
        [[{}, {'fn._clearCalls': {}}], [{}, {'Ok': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1}}}], [{}, {'_ErrorNoMatchingStub': {}}]],
        [[{}, {'fn.test': {'value!': {'str!': 'a'}}}], [{}, {'_ErrorNoMatchingStub': {}}]],
        [[{}, {'fn._createStub': {'count!': 1, 'stub': {'fn.test': {'value!': {'int!': 1}}, '->': {'Ok': {'value!': {'bool!': True}}}}, 'strictMatch!': True}}], [{}, {'Ok': {}}]],
        [[{}, {'fn._createStub': {'count!': 1, 'stub': {'fn.test': {'value!': {'str!': 'a'}}, '->': {'Ok': {'value!': {'bool!': False}}}}, 'strictMatch!': True}}], [{}, {'Ok': {}}]],
        [[{}, {'fn.test': {}}], [{}, {'_ErrorNoMatchingStub': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 0}}}], [{}, {'_ErrorNoMatchingStub': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1}}}], [{}, {'Ok': {'value!': {'bool!': True}}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1}}}], [{}, {'_ErrorNoMatchingStub': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1, 'str!': 'a'}}}], [{}, {'_ErrorNoMatchingStub': {}}]],
        [[{}, {'fn.test': {'value!': {'str!': 'a'}}}], [{}, {'Ok': {'value!': {'bool!': False}}}]],
        [[{}, {'fn.test': {'value!': {'str!': 'a'}}}], [{}, {'_ErrorNoMatchingStub': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 0, 'str!': 'a'}}}], [{}, {'_ErrorNoMatchingStub': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1, 'str!': 'b'}}}], [{}, {'_ErrorNoMatchingStub': {}}]],
        [[{}, {'fn.test': {'value!': {'bool!': False, 'int!': 1, 'str!': 'a'}}}], [{}, {'_ErrorNoMatchingStub': {}}]],
    ],    
    'mixedPartialStrictMatchStub': [
        [[{}, {'fn._clearStubs': {}}], [{}, {'Ok': {}}]],
        [[{}, {'fn._clearCalls': {}}], [{}, {'Ok': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1}}}], [{}, {'_ErrorNoMatchingStub': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1, 'str!': 'a'}}}], [{}, {'_ErrorNoMatchingStub': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1, 'str!': 'b'}}}], [{}, {'_ErrorNoMatchingStub': {}}]],
        [[{}, {'fn.test': {'value!': {'bool!': False, 'int!': 1, 'str!': 'a'}}}], [{}, {'_ErrorNoMatchingStub': {}}]],
        [[{}, {'fn._createStub': {'stub': {'fn.test': {'value!': {'int!': 1}}, '->': {'Ok': {'value!': {'bool!': True}}}}}}], [{}, {'Ok': {}}]],
        [[{}, {'fn._createStub': {'stub': {'fn.test': {'value!': {'int!': 1, 'str!': 'a'}}, '->': {'Ok': {'value!': {'bool!': False}}}}, 'strictMatch!': True}}], [{}, {'Ok': {}}]],
        [[{}, {'fn.test': {}}], [{}, {'_ErrorNoMatchingStub': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 0}}}], [{}, {'_ErrorNoMatchingStub': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1}}}], [{}, {'Ok': {'value!': {'bool!': True}}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1, 'str!': 'a'}}}], [{}, {'Ok': {'value!': {'bool!': False}}}]],
        [[{}, {'fn.test': {'value!': {'int!': 0, 'str!': 'a'}}}], [{}, {'_ErrorNoMatchingStub': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1, 'str!': 'b'}}}], [{}, {'Ok': {'value!': {'bool!': True}}}]],
        [[{}, {'fn.test': {'value!': {'bool!': False, 'int!': 1, 'str!': 'a'}}}], [{}, {'Ok': {'value!': {'bool!': True}}}]],
    ],
    'mixedStrictPartialMatchStub': [
        [[{}, {'fn._clearStubs': {}}], [{}, {'Ok': {}}]],
        [[{}, {'fn._clearCalls': {}}], [{}, {'Ok': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1}}}], [{}, {'_ErrorNoMatchingStub': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1, 'str!': 'a'}}}], [{}, {'_ErrorNoMatchingStub': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1, 'str!': 'b'}}}], [{}, {'_ErrorNoMatchingStub': {}}]],
        [[{}, {'fn.test': {'value!': {'bool!': False, 'int!': 1, 'str!': 'a'}}}], [{}, {'_ErrorNoMatchingStub': {}}]],
        [[{}, {'fn._createStub': {'stub': {'fn.test': {'value!': {'int!': 1, 'str!': 'a'}}, '->': {'Ok': {'value!': {'bool!': False}}}}, 'strictMatch!': True}}], [{}, {'Ok': {}}]],
        [[{}, {'fn._createStub': {'stub': {'fn.test': {'value!': {'int!': 1}}, '->': {'Ok': {'value!': {'bool!': True}}}}}}], [{}, {'Ok': {}}]],
        [[{}, {'fn.test': {}}], [{}, {'_ErrorNoMatchingStub': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 0}}}], [{}, {'_ErrorNoMatchingStub': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1}}}], [{}, {'Ok': {'value!': {'bool!': True}}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1, 'str!': 'a'}}}], [{}, {'Ok': {'value!': {'bool!': True}}}]],
        [[{}, {'fn.test': {'value!': {'int!': 0, 'str!': 'a'}}}], [{}, {'_ErrorNoMatchingStub': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1, 'str!': 'b'}}}], [{}, {'Ok': {'value!': {'bool!': True}}}]],
        [[{}, {'fn.test': {'value!': {'bool!': False, 'int!': 1, 'str!': 'a'}}}], [{}, {'Ok': {'value!': {'bool!': True}}}]],
    ],
    'clearStubs': [
        [[{}, {'fn._clearStubs': {}}], [{}, {'Ok': {}}]],
        [[{}, {'fn._clearCalls': {}}], [{}, {'Ok': {}}]],
        [[{}, {'fn.test': {}}], [{}, {'_ErrorNoMatchingStub': {}}]],
        [[{}, {'fn._createStub': {'stub': {'fn.test': {}, '->': {'Ok': {}}}}}], [{}, {'Ok': {}}]],
        [[{}, {'fn.test': {}}], [{}, {'Ok': {}}]],
        [[{}, {'fn._clearStubs': {}}], [{}, {'Ok': {}}]],
        [[{}, {'fn.test': {}}], [{}, {'_ErrorNoMatchingStub': {}}]],
    ],
    'generation': [
        [[{}, {'fn._setRandomSeed': {'seed': 0}}], [{}, {'Ok': {}}]],
        [[{}, {'fn._clearStubs': {}}], [{}, {'Ok': {}}]],
        [[{}, {'fn._clearCalls': {}}], [{}, {'Ok': {}}]],
        [[{'_gen': True}, {'fn.test': {}}], [{}, {'Ok': {'value!': {'arrArr!': [[794471793, 'L+Uz1w'], []], 'arrInt!': [], 'arrNullAny!': [True, None], 'arrNullBool!': [True], 'arrNullInt!': [1680572000], 'arrNullNum!': [None], 'arrNullObj!': [], 'arrNullStr!': ['fFlptw', None], 'arrNullStruct!': [{'optional2!': 1502988430, 'required': False}, None], 'arrNullUnion!': [{'One': {}}, {'One': {}}], 'arrObj!': [{}, {'GTWswA': 'RktxPg'}], 'arrP2Str!': [{'nest': [973693770, 662438587], 'wrap': True}, {'nest': [2030201366, 1700663191], 'wrap': False}], 'arrP2StrArr!': [{'nest': [['XC1ajw'], [1500066554, 'fuBjCA']], 'wrap': True}], 'arrP2StrBool!': [{'nest': [True], 'wrap': False}, {'nest': [True, False], 'wrap': False}], 'arrP2StrFn!': [{'nest': [{'fn.example': {'optional!': True, 'required': False}}], 'wrap': True}], 'arrP2StrInt!': [{'nest': [], 'wrap': True}, {'nest': [605224016], 'wrap': False}], 'arrP2StrStr!': [{'nest': ['NzotgQ', 'MGjeJg'], 'wrap': False}, {'nest': ['XNsgvQ'], 'wrap': True}], 'arrPStrAny!': [{'wrap': 1024109173}, {'wrap': 1339056763}], 'arrPStrArr!': [{'wrap': []}], 'arrPStrFn!': [{'wrap': {'fn.example': {'required': False}}}], 'arrPStrNum!': [{'wrap': 0.9217369393081111}, {'wrap': 0.9324983236996914}], 'arrPStrObj!': [{'wrap': {'fDiAYQ': True}}], 'arrPStrStruct!': [{'wrap': {'optional!': True, 'optional2!': 1769935372, 'required': False}}], 'arrStr!': ['S5FD0Q', 'dCm+Ng'], 'fn!': {'fn.example': {'optional!': False, 'required': True}}, 'int!': 1458640444, 'nullArr!': None, 'nullFn!': {'fn.example': {'required': False}}, 'nullInt!': 267470400, 'nullNum!': None, 'nullStr!': 'bKmdWA', 'objAny!': {}, 'objArr!': {'ZZm0pQ': [300616840, False], 'dB/S6Q': [True]}, 'objBool!': {}, 'objNullAny!': {'EtZIWQ': 689679052}, 'objNullArr!': {'T5epkQ': None, 'bp26Gw': None}, 'objNullFn!': {'XqK10A': None, 'a6/Ggg': None}, 'objNullInt!': {'SOuj2g': 1627877096, 'ekVe/A': None}, 'objNullObj!': {'QViRlA': None}, 'objNullP2Union!': {'csrnOQ': {'Two': {'enest': [132759029], 'ewrap': False}}}, 'objNullStr!': {'C+VEcQ': None}, 'objNullUnion!': {}, 'objObj!': {'ANcQqQ': {}}, 'objP2Union!': {}, 'objStruct!': {}, 'objUnion!': {}, 'p2Str!': {'nest': [1067558173], 'wrap': True}, 'p2Union!': {'One': {}}, 'pStrArr!': {'wrap': [True]}, 'pStrBool!': {'wrap': False}, 'pStrInt!': {'wrap': 1678648246}, 'pStrNullAny!': {'wrap': 156288322}, 'pStrNullArr!': {'wrap': None}, 'pStrNullNum!': {'wrap': None}, 'pStrNullStruct!': {'wrap': None}, 'pStrNullUnion!': {'wrap': {'One': {}}}, 'pStrNum!': {'wrap': 0.21947857747761468}, 'pStrP2Union!': {'wrap': {'One': {}}}, 'pStrUnion!': {'wrap': {'One': {}}}, 'pUnionArr!': {'Two': {'ewrap': ['LSQMog', False]}}, 'pUnionFn!': {'Two': {'ewrap': {'fn.example': {'required': True}}}}, 'pUnionInt!': {'One': {}}, 'pUnionNullArr!': {'Two': {'ewrap': [True, True]}}, 'pUnionNullFn!': {'One': {}}, 'pUnionNullInt!': {'One': {}}, 'pUnionNullNum!': {'One': {}}, 'pUnionNullP2Union!': {'One': {}}, 'pUnionNullStr!': {'One': {}}, 'pUnionNum!': {'One': {}}, 'pUnionP2Str!': {'Two': {'ewrap': {'nest': [430407563], 'wrap': True}}}}}}]],
        [[{'_gen': True}, {'fn.test': {}}], [{}, {'Ok': {'value!': {'any!': True, 'arrAny!': [False, False], 'arrArr!': [[], ['bQDMKQ', 1207074127]], 'arrBool!': [False], 'arrNullBool!': [], 'arrNullP2Str!': [], 'arrNullStr!': [None, 'JbdV+A'], 'arrNullStruct!': [], 'arrNullUnion!': [], 'arrP2Str!': [{'nest': [279480590], 'wrap': True}], 'arrP2StrAny!': [{'nest': [], 'wrap': False}, {'nest': [], 'wrap': False}], 'arrP2StrBool!': [{'nest': [False, False], 'wrap': True}, {'nest': [True], 'wrap': True}], 'arrP2StrFn!': [{'nest': [], 'wrap': False}, {'nest': [{'fn.example': {'required': False}}, {'fn.example': {'optional!': True, 'required': False}}], 'wrap': True}], 'arrP2StrNum!': [{'nest': [], 'wrap': False}, {'nest': [0.3992976152334817, 0.49711221852205334], 'wrap': True}], 'arrP2StrObj!': [{'nest': [{'Lmw/0g': 'A4qXoA'}, {'G/W4FQ': False, 'WiqHHg': 'IZGNzA'}], 'wrap': True}, {'nest': [{'ACBBgg': 'QMMo0A', 'drpL9w': 'WEXUzQ'}, {'PhTzzg': 'SXoB/A', 'enXQhQ': 'K8ifCw'}], 'wrap': True}], 'arrP2StrP2Str!': [], 'arrP2StrStr!': [], 'arrP2StrStruct!': [{'nest': [{'optional!': False, 'optional2!': 1816125996, 'required': True}, {'optional!': False, 'optional2!': 1915476849, 'required': True}], 'wrap': True}, {'nest': [{'required': False}, {'optional2!': 2026533166, 'required': False}], 'wrap': True}], 'arrP2StrUnion!': [{'nest': [], 'wrap': True}], 'arrP2Union!': [{'Two': {'enest': [1628072989, 2043612818], 'ewrap': True}}, {'One': {}}], 'arrPStrArr!': [], 'arrPStrFn!': [{'wrap': {'fn.example': {'optional!': False, 'required': False}}}], 'arrPStrNum!': [{'wrap': 0.5015945744242494}], 'arrPStrObj!': [], 'arrPStrP2Union!': [{'wrap': {'One': {}}}, {'wrap': {'Two': {'enest': [], 'ewrap': True}}}], 'arrPStrStr!': [], 'arrPStrStruct!': [], 'arrStruct!': [], 'bool!': True, 'fn!': {'fn.example': {'required': False}}, 'nullAny!': 'aOPtlw', 'nullBool!': None, 'nullP2Str!': None, 'nullUnion!': {'One': {}}, 'num!': 0.9935814985044215, 'objAny!': {}, 'objBool!': {'f6ILlQ': True, 'fCcjfw': True}, 'objFn!': {}, 'objInt!': {'O7gDdw': 1668410340}, 'objNullFn!': {'VwgJTg': {'fn.example': {'optional!': False, 'required': False}}, 'bSGraA': {'fn.example': {'optional!': False, 'required': True}}}, 'objNullP2Union!': {}, 'objNullUnion!': {}, 'objObj!': {}, 'objP2Union!': {'RrgmYg': {'Two': {'enest': [557925161], 'ewrap': True}}, 'S/lMTw': {'One': {}}}, 'objStr!': {'EW0uYQ': 'L6R9hg', 'Sqheaw': 'SDb9yA'}, 'objStruct!': {'bO1PnQ': {'optional!': False, 'required': False}}, 'objUnion!': {}, 'pStrAny!': {'wrap': 1586063608}, 'pStrArr!': {'wrap': ['TmgcpA']}, 'pStrInt!': {'wrap': 1432117008}, 'pStrNullBool!': {'wrap': False}, 'pStrNullObj!': {'wrap': None}, 'pStrNullP2Str!': {'wrap': {'nest': [755620722], 'wrap': False}}, 'pStrNum!': {'wrap': 0.5517161141856183}, 'pStrP2Union!': {'wrap': {'Two': {'enest': [1880548631, 978763012], 'ewrap': True}}}, 'pStrStr!': {'wrap': 'ZBq7sw'}, 'pStrStruct!': {'wrap': {'optional!': True, 'required': True}}, 'pStrUnion!': {'wrap': {'One': {}}}, 'pUnionFn!': {'Two': {'ewrap': {'fn.example': {'optional!': False, 'required': True}}}}, 'pUnionNullArr!': {'Two': {'ewrap': None}}, 'pUnionNullNum!': {'Two': {'ewrap': 0.6307595929274147}}, 'pUnionNullP2Union!': {'Two': {'ewrap': {'Two': {'enest': [1015681519, 1713022204], 'ewrap': True}}}}, 'pUnionNullStr!': {'Two': {'ewrap': 'dubHAQ'}}, 'pUnionNullUnion!': {'One': {}}, 'pUnionNum!': {'One': {}}, 'pUnionObj!': {'One': {}}, 'pUnionUnion!': {'One': {}}, 'struct!': {'optional!': True, 'optional2!': 317113517, 'required': False}}}}]],
        [[{'_gen': True}, {'fn.test': {}}], [{}, {'Ok': {}}]],
        [[{'_gen': True}, {'fn.test': {}}], [{}, {'Ok': {'value!': {'arrBool!': [True], 'arrFn!': [{'fn.example': {'required': False}}, {'fn.example': {'optional!': True, 'required': False}}], 'arrInt!': [1861011852], 'arrNullBool!': [True, None], 'arrNullInt!': [None], 'arrNullObj!': [{'OYBxRQ': 'JVgNyw', 'cLPpqA': True}], 'arrNullP2Union!': [], 'arrNullStr!': [None], 'arrNullUnion!': [{'Two': {'optional!': False, 'required': True}}], 'arrNum!': [], 'arrObj!': [{}], 'arrP2Str!': [{'nest': [469826665], 'wrap': False}, {'nest': [], 'wrap': False}], 'arrP2StrBool!': [], 'arrP2StrFn!': [{'nest': [{'fn.example': {'required': True}}], 'wrap': False}, {'nest': [{'fn.example': {'optional!': False, 'required': True}}, {'fn.example': {'required': True}}], 'wrap': False}], 'arrP2StrP2Str!': [{'nest': [{'nest': [1047942480, 1916855113], 'wrap': True}], 'wrap': True}, {'nest': [{'nest': [], 'wrap': False}], 'wrap': True}], 'arrP2StrP2Union!': [{'nest': [{'Two': {'enest': [1111553469], 'ewrap': True}}, {'Two': {'enest': [], 'ewrap': False}}], 'wrap': True}], 'arrP2StrStruct!': [{'nest': [{'optional2!': 1658207729, 'required': True}, {'optional2!': 822069293, 'required': True}], 'wrap': True}], 'arrP2StrUnion!': [{'nest': [{'Two': {'required': True}}, {'One': {}}], 'wrap': True}], 'arrP2Union!': [], 'arrPStrArr!': [{'wrap': []}, {'wrap': [1655206112]}], 'arrPStrBool!': [], 'arrPStrStruct!': [{'wrap': {'optional!': True, 'optional2!': 282867411, 'required': True}}], 'arrPStrUnion!': [{'wrap': {'Two': {'optional!': True, 'required': False}}}], 'arrStruct!': [{'optional!': True, 'optional2!': 507586429, 'required': False}], 'arrUnion!': [], 'bool!': True, 'nullBool!': True, 'nullFn!': {'fn.example': {'optional!': True, 'required': False}}, 'nullObj!': None, 'nullP2Union!': None, 'nullStruct!': None, 'obj!': {'Iee10g': False}, 'objAny!': {'R6gtKg': 1268113592, 'bBX5/w': True}, 'objFn!': {'c0zizQ': {'fn.example': {'optional!': True, 'required': True}}}, 'objNullNum!': {'UlrEpg': None}, 'objNullObj!': {'BeTMAA': {'Dv2Iig': 'eVAbGA', 'c5hj3w': False}, 'Rd6FMg': None}, 'objNullP2Str!': {}, 'objNullP2Union!': {'D3fLrQ': None}, 'objNullStr!': {'I4gCzw': 'XVPDZQ', 'Z3J1qQ': None}, 'objNullStruct!': {'Dwx6SA': None, 'cxmOBg': None}, 'objNullUnion!': {'ELCEkg': None, 'ZGZKYA': None}, 'objP2Str!': {}, 'objP2Union!': {'IFMBJA': {'Two': {'enest': [85878355], 'ewrap': False}}, 'LfcFeA': {'Two': {'enest': [], 'ewrap': True}}}, 'objStr!': {'Uh8Urw': 'XeNQvA'}, 'objStruct!': {'ITjK/Q': {'optional2!': 1992718528, 'required': True}, 'Y9JMyw': {'optional!': False, 'optional2!': 1379330727, 'required': False}}, 'objUnion!': {'A/pg7A': {'Two': {'required': False}}}, 'pStrAny!': {'wrap': False}, 'pStrFn!': {'wrap': {'fn.example': {'required': False}}}, 'pStrInt!': {'wrap': 198040860}, 'pStrNullAny!': {'wrap': None}, 'pStrNullArr!': {'wrap': [1932445831]}, 'pStrNullBool!': {'wrap': True}, 'pStrNullFn!': {'wrap': {'fn.example': {'required': True}}}, 'pStrNullInt!': {'wrap': 952416938}, 'pStrNullNum!': {'wrap': None}, 'pStrNullStruct!': {'wrap': None}, 'pStrObj!': {'wrap': {'VNCIbw': True}}, 'pStrP2Str!': {'wrap': {'nest': [], 'wrap': True}}, 'pStrP2Union!': {'wrap': {'One': {}}}, 'pStrStr!': {'wrap': 'c1YcFA'}, 'pStrStruct!': {'wrap': {'optional!': True, 'optional2!': 1168697273, 'required': False}}, 'pStrUnion!': {'wrap': {'One': {}}}, 'pUnionNullAny!': {'Two': {'ewrap': 981212258}}, 'pUnionNullFn!': {'One': {}}, 'pUnionNullNum!': {'Two': {'ewrap': 0.7736163641203271}}, 'pUnionNullP2Union!': {'Two': {'ewrap': {'Two': {'enest': [2034200035, 336536544], 'ewrap': False}}}}, 'pUnionNullUnion!': {'Two': {'ewrap': {'Two': {'optional!': False, 'required': False}}}}, 'pUnionObj!': {'Two': {'ewrap': {}}}, 'pUnionP2Str!': {'One': {}}, 'pUnionStruct!': {'One': {}}, 'str!': 'eCKmKA'}}}]],
        [[{'_gen': True}, {'fn.test': {}}], [{}, {'Ok': {'value!': {'any!': False, 'arr!': ['KMgSvg'], 'arrInt!': [1409243825], 'arrNullAny!': [True], 'arrNullArr!': [[1414590108]], 'arrNullFn!': [None], 'arrNullObj!': [None, {'IvuwoA': 'GpfIHg', 'ds2I/w': True}], 'arrNullStr!': [None], 'arrNullUnion!': [], 'arrObj!': [{}], 'arrP2Str!': [{'nest': [1939342725, 323424218], 'wrap': True}, {'nest': [894989569, 1779847078], 'wrap': True}], 'arrP2StrFn!': [{'nest': [{'fn.example': {'optional!': True, 'required': False}}, {'fn.example': {'required': True}}], 'wrap': False}], 'arrP2StrInt!': [{'nest': [1166332589], 'wrap': True}, {'nest': [], 'wrap': False}], 'arrP2StrP2Str!': [{'nest': [], 'wrap': False}, {'nest': [], 'wrap': False}], 'arrP2StrP2Union!': [{'nest': [], 'wrap': False}], 'arrP2StrStr!': [], 'arrP2StrUnion!': [{'nest': [{'Two': {'optional!': False, 'required': False}}, {'Two': {'required': False}}], 'wrap': True}], 'arrP2Union!': [], 'arrPStrBool!': [{'wrap': True}], 'arrPStrStruct!': [{'wrap': {'optional!': False, 'optional2!': 944893682, 'required': True}}], 'arrPStrUnion!': [{'wrap': {'One': {}}}, {'wrap': {'Two': {'optional!': False, 'required': True}}}], 'fn!': {'fn.example': {'required': False}}, 'int!': 1708033264, 'nullAny!': 'Sq8AHA', 'nullArr!': None, 'nullBool!': None, 'nullFn!': {'fn.example': {'required': False}}, 'nullInt!': 1791298080, 'nullObj!': None, 'nullStr!': None, 'nullUnion!': {'Two': {'optional!': True, 'required': False}}, 'num!': 0.05271092804740692, 'obj!': {'OAf9Wg': 'JH8kaA', 'UdfXbw': True}, 'objNullAny!': {'SAAYgA': None}, 'objNullInt!': {}, 'objNullP2Str!': {'LMYA8w': None, 'Q7xWVw': {'nest': [], 'wrap': True}}, 'objNullP2Union!': {'PKmehg': {'One': {}}, 'ebW5Tw': {'Two': {'enest': [1547606891, 969209544], 'ewrap': True}}}, 'objNullStr!': {'avEM4w': 'YCDtmQ'}, 'objNullStruct!': {}, 'objNullUnion!': {}, 'objObj!': {'NGm20Q': {'Grbuwg': 1867036688, 'fXPMNw': 'WgHvDQ'}}, 'objStruct!': {}, 'p2Str!': {'nest': [1215624769, 1947916262], 'wrap': False}, 'p2Union!': {'Two': {'enest': [779008195], 'ewrap': False}}, 'pStrBool!': {'wrap': True}, 'pStrFn!': {'wrap': {'fn.example': {'optional!': True, 'required': False}}}, 'pStrNullAny!': {'wrap': None}, 'pStrNullArr!': {'wrap': None}, 'pStrNullFn!': {'wrap': None}, 'pStrNullInt!': {'wrap': 350753180}, 'pStrNullObj!': {'wrap': {'FQapIQ': 2117553927}}, 'pStrNullP2Str!': {'wrap': {'nest': [74437795], 'wrap': False}}, 'pStrNullP2Union!': {'wrap': {'Two': {'enest': [691819541, 1301046058], 'ewrap': False}}}, 'pStrNullStr!': {'wrap': 'AOWH9g'}, 'pStrNullStruct!': {'wrap': None}, 'pStrNum!': {'wrap': 0.2992912024721928}, 'pStrObj!': {'wrap': {'JYGfzg': 1820626428, 'ZJtshQ': 218995467}}, 'pStrStruct!': {'wrap': {'required': True}}, 'pUnionAny!': {'Two': {'ewrap': True}}, 'pUnionArr!': {'Two': {'ewrap': [True, 1185429846]}}, 'pUnionBool!': {'One': {}}, 'pUnionInt!': {'Two': {'ewrap': 1327700784}}, 'pUnionNullBool!': {'One': {}}, 'pUnionNullFn!': {'One': {}}, 'pUnionNullNum!': {'Two': {'ewrap': 0.006556842013521512}}, 'pUnionNullObj!': {'Two': {'ewrap': {'WC5bvw': False, 'couwYA': True}}}, 'pUnionNullP2Str!': {'Two': {'ewrap': {'nest': [585046710, 837157815], 'wrap': True}}}, 'pUnionNullStruct!': {'One': {}}, 'pUnionP2Str!': {'Two': {'ewrap': {'nest': [], 'wrap': True}}}, 'str!': 'E7op8g', 'struct!': {'optional!': True, 'required': True}, 'union!': {'Two': {'required': True}}}}}]],
    ],
    'emptyPartialMatchVerify': [
        [[{}, {'fn._clearStubs': {}}], [{}, {'Ok': {}}]],
        [[{}, {'fn._clearCalls': {}}], [{}, {'Ok': {}}]],
        [[{}, {'fn._createStub': {'stub': {'fn.test': {}, '->': {'Ok': {}}}}}], [{}, {'Ok': {}}]],
        [[{}, {'fn._verify': {'call': {'fn.test': {}}}}], [{}, {'ErrorVerificationFailure': {'reason': {'TooFewMatchingCalls': {'allCalls': [], 'found': 0, 'wanted': {'AtLeast': {'times': 1}}}}}}]],
        [[{}, {'fn._verify': {'call': {'fn.test': {}}, 'count!': {'Exact': {'times': 1}}}}], [{}, {'ErrorVerificationFailure': {'reason': {'TooFewMatchingCalls': {'allCalls': [], 'found': 0, 'wanted': {'Exact': {'times': 1}}}}}}]],
        [[{}, {'fn._verify': {'call': {'fn.test': {}}, 'count!': {'AtLeast': {'times': 1}}}}], [{}, {'ErrorVerificationFailure': {'reason': {'TooFewMatchingCalls': {'allCalls': [], 'wanted': {'AtLeast': {'times': 1}}, 'found': 0}}}}]],
        [[{}, {'fn._verify': {'call': {'fn.test': {}}, 'count!': {'AtMost': {'times': 0}}}}], [{}, {'Ok': {}}]],
        [[{}, {'fn.test': {}}], [{}, {'Ok': {}}]],
        [[{}, {'fn._verifyNoMoreInteractions': {}}], [{}, {'ErrorVerificationFailure': {'additionalUnverifiedCalls': [{'fn.test': {}}]}}]],
        [[{}, {'fn._verify': {'call': {'fn.test': {}}}}], [{}, {'Ok': {}}]],
        [[{}, {'fn._verifyNoMoreInteractions': {}}], [{}, {'Ok': {}}]],
        [[{}, {'fn._verify': {'call': {'fn.test': {}}, 'count!': {'Exact': {'times': 1}}}}], [{}, {'Ok': {}}]],
        [[{}, {'fn._verify': {'call': {'fn.test': {}}, 'count!': {'AtLeast': {'times': 1}}}}], [{}, {'Ok': {}}]],
        [[{}, {'fn._verify': {'call': {'fn.test': {}}, 'count!': {'AtLeast': {'times': 2}}}}], [{}, {'ErrorVerificationFailure': {'reason': {'TooFewMatchingCalls': {'allCalls': [{'fn.test': {}}], 'found': 1, 'wanted': {'AtLeast': {'times': 2}}}}}}]],
        [[{}, {'fn._verify': {'call': {'fn.test': {}}, 'count!': {'AtMost': {'times': 1}}}}], [{}, {'Ok': {}}]],
        [[{}, {'fn._verify': {'call': {'fn.test': {}}, 'count!': {'AtMost': {'times': 0}}}}], [{}, {'ErrorVerificationFailure': {'reason': {'TooManyMatchingCalls': {'wanted': {'AtMost': {'times': 0}}, 'allCalls': [{'fn.test': {}}], 'found': 1}}}}]],
    ],
    'partialMatchVerify': [
        [[{}, {'fn._clearStubs': {}}], [{}, {'Ok': {}}]],
        [[{}, {'fn._clearCalls': {}}], [{}, {'Ok': {}}]],
        [[{}, {'fn._createStub': {'stub': {'fn.test': {'value!': {'int!': 0}}, '->': {'Ok': {'value!': {'bool!': True}}}}}}], [{}, {'Ok': {}}]],
        [[{}, {'fn._verify': {'call': {'fn.test': {'value!': {'int!': 0}}}}}], [{}, {'ErrorVerificationFailure': {'reason': {'TooFewMatchingCalls': {'found': 0, 'allCalls': [], 'wanted': {'AtLeast': {'times': 1}}}}}}]],
        [[{}, {'fn.test': {'value!': {'int!': 0, 'str!': 'a'}}}], [{}, {'Ok': {'value!': {'bool!': True}}}]],
        [[{}, {'fn._verifyNoMoreInteractions': {}}], [{}, {'ErrorVerificationFailure': {'additionalUnverifiedCalls': [{'fn.test': {'value!': {'int!': 0, 'str!': 'a'}}}]}}]],
        [[{}, {'fn._verify': {'call': {'fn.test': {'value!': {'int!': 0}}}}}], [{}, {'Ok': {}}]],
        [[{}, {'fn._verifyNoMoreInteractions': {}}], [{}, {'Ok': {}}]],
        [[{}, {'fn._verify': {'call': {'fn.test': {'value!': {'int!': 0}}}, 'count!': {'Exact': {'times': 1}}}}], [{}, {'Ok': {}}]],
        [[{}, {'fn._verify': {'call': {'fn.test': {'value!': {'int!': 0}}}, 'count!': {'AtLeast': {'times': 1}}}}], [{}, {'Ok': {}}]],
        [[{}, {'fn._verify': {'call': {'fn.test': {'value!': {'int!': 0}}}, 'count!': {'AtMost': {'times': 0}}}}], [{}, {'ErrorVerificationFailure': {'reason': {'TooManyMatchingCalls': {'wanted': {'AtMost': {'times': 0}}, 'allCalls': [{'fn.test': {'value!': {'int!': 0, 'str!': 'a'}}}], 'found': 1}}}}]],
    ],
    'multiplePartialMatchVerify': [
        [[{}, {'fn._clearStubs': {}}], [{}, {'Ok': {}}]],
        [[{}, {'fn._clearCalls': {}}], [{}, {'Ok': {}}]],
        [[{}, {'fn._createStub': {'stub': {'fn.test': {}, '->': {'Ok': {}}}}}], [{}, {'Ok': {}}]],
        [[{}, {'fn._verify': {'call': {'fn.test': {'value!': {'int!': 0}}}}}], [{}, {'ErrorVerificationFailure': {'reason': {'TooFewMatchingCalls': {'found': 0, 'allCalls': [], 'wanted': {'AtLeast': {'times': 1}}}}}}]],
        [[{}, {'fn.test': {'value!': {'int!': 0, 'bool!': True}}}], [{}, {'Ok': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 0, 'str!': 'a'}}}], [{}, {'Ok': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1}}}], [{}, {'Ok': {}}]],
        [[{}, {'fn._verifyNoMoreInteractions': {}}], [{}, {'ErrorVerificationFailure': {'additionalUnverifiedCalls': [{'fn.test': {'value!': {'int!': 0, 'bool!': True}}}, {'fn.test': {'value!': {'int!': 0, 'str!': 'a'}}}, {'fn.test': {'value!': {'int!': 1}}}]}}]],
        [[{}, {'fn._verify': {'call': {'fn.test': {'value!': {'int!': 0}}}}}], [{}, {'Ok': {}}]],
        [[{}, {'fn._verifyNoMoreInteractions': {}}], [{}, {'ErrorVerificationFailure': {'additionalUnverifiedCalls': [{'fn.test': {'value!': {'int!': 1}}}]}}]],
        [[{}, {'fn._verify': {'call': {'fn.test': {}}}}], [{}, {'Ok': {}}]],
        [[{}, {'fn._verifyNoMoreInteractions': {}}], [{}, {'Ok': {}}]],
        [[{}, {'fn._verify': {'call': {'fn.test': {'value!': {'int!': 0}}}, 'count!': {'Exact': {'times': 1}}}}], [{}, {'ErrorVerificationFailure': {'reason': {'TooManyMatchingCalls': {'wanted': {'Exact': {'times': 1}}, 'allCalls': [{'fn.test': {'value!': {'int!': 0, 'bool!': True}}}, {'fn.test': {'value!': {'int!': 0, 'str!': 'a'}}}, {'fn.test': {'value!': {'int!': 1}}}], 'found': 2}}}}]],
        [[{}, {'fn._verify': {'call': {'fn.test': {'value!': {'int!': 0}}}, 'count!': {'Exact': {'times': 2}}}}], [{}, {'Ok': {}}]],
        [[{}, {'fn._verify': {'call': {'fn.test': {'value!': {'int!': 0}}}, 'count!': {'Exact': {'times': 3}}}}], [{}, {'ErrorVerificationFailure': {'reason': {'TooFewMatchingCalls': {'wanted': {'Exact': {'times': 3}}, 'allCalls': [{'fn.test': {'value!': {'int!': 0, 'bool!': True}}}, {'fn.test': {'value!': {'int!': 0, 'str!': 'a'}}}, {'fn.test': {'value!': {'int!': 1}}}], 'found': 2}}}}]],
        [[{}, {'fn._verify': {'call': {'fn.test': {'value!': {'int!': 0}}}, 'count!': {'AtLeast': {'times': 1}}}}], [{}, {'Ok': {}}]],
        [[{}, {'fn._verify': {'call': {'fn.test': {'value!': {'int!': 0}}}, 'count!': {'AtMost': {'times': 1}}}}], [{}, {'ErrorVerificationFailure': {'reason': {'TooManyMatchingCalls': {'wanted': {'AtMost': {'times': 1}}, 'allCalls': [{'fn.test': {'value!': {'int!': 0, 'bool!': True}}}, {'fn.test': {'value!': {'int!': 0, 'str!': 'a'}}}, {'fn.test': {'value!': {'int!': 1}}}], 'found': 2}}}}]],
        [[{}, {'fn._verify': {'call': {'fn.test': {'value!': {'int!': 0}}}, 'count!': {'AtMost': {'times': 2}}}}], [{}, {'Ok': {}}]],
    ],
    'strictMatchVerify': [
        [[{}, {'fn._clearStubs': {}}], [{}, {'Ok': {}}]],
        [[{}, {'fn._clearCalls': {}}], [{}, {'Ok': {}}]],
        [[{}, {'fn._createStub': {'stub': {'fn.test': {}, '->': {'Ok': {}}}}}], [{}, {'Ok': {}}]],
        [[{}, {'fn._verify': {'call': {'fn.test': {'value!': {'int!': 0}}}, 'strictMatch!': True}}], [{}, {'ErrorVerificationFailure': {'reason': {'TooFewMatchingCalls': {'found': 0, 'allCalls': [], 'wanted': {'AtLeast': {'times': 1}}}}}}]],
        [[{}, {'fn.test': {'value!': {'int!': 0}}}], [{}, {'Ok': {}}]],
        [[{}, {'fn._verifyNoMoreInteractions': {}}], [{}, {'ErrorVerificationFailure': {'additionalUnverifiedCalls': [{'fn.test': {'value!': {'int!': 0}}}]}}]],
        [[{}, {'fn._verify': {'call': {'fn.test': {'value!': {'int!': 0}}}, 'strictMatch!': True}}], [{}, {'Ok': {}}]],
        [[{}, {'fn._verifyNoMoreInteractions': {}}], [{}, {'Ok': {}}]],
        [[{}, {'fn._verify': {'call': {'fn.test': {'value!': {'int!': 1}}}, 'strictMatch!': True}}], [{}, {'ErrorVerificationFailure': {'reason': {'TooFewMatchingCalls': {'found': 0, 'allCalls': [{'fn.test': {'value!': {'int!': 0}}}], 'wanted': {'AtLeast': {'times': 1}}}}}}]],
        [[{}, {'fn._verify': {'call': {'fn.test': {'value!': {'int!': 0, 'str!': 'a'}}}, 'strictMatch!': True}}], [{}, {'ErrorVerificationFailure': {'reason': {'TooFewMatchingCalls': {'found': 0, 'allCalls': [{'fn.test': {'value!': {'int!': 0}}}], 'wanted': {'AtLeast': {'times': 1}}}}}}]],
        [[{}, {'fn._verify': {'call': {'fn.test': {'value!': {'int!': 0}}}, 'strictMatch!': True, 'count!': {'Exact': {'times': 0}}}}], [{}, {'ErrorVerificationFailure': {'reason': {'TooManyMatchingCalls': {'wanted': {'Exact': {'times': 0}}, 'allCalls': [{'fn.test': {'value!': {'int!': 0}}}], 'found': 1}}}}]],
        [[{}, {'fn._verify': {'call': {'fn.test': {'value!': {'int!': 0}}}, 'strictMatch!': True, 'count!': {'Exact': {'times': 2}}}}], [{}, {'ErrorVerificationFailure': {'reason': {'TooFewMatchingCalls': {'wanted': {'Exact': {'times': 2}}, 'allCalls': [{'fn.test': {'value!': {'int!': 0}}}], 'found': 1}}}}]],
        [[{}, {'fn._verify': {'call': {'fn.test': {'value!': {'int!': 0}}}, 'strictMatch!': True, 'count!': {'Exact': {'times': 1}}}}], [{}, {'Ok': {}}]],
        [[{}, {'fn._verify': {'call': {'fn.test': {'value!': {'int!': 0}}}, 'strictMatch!': True, 'count!': {'AtLeast': {'times': 2}}}}], [{}, {'ErrorVerificationFailure': {'reason': {'TooFewMatchingCalls': {'wanted': {'AtLeast': {'times': 2}}, 'allCalls': [{'fn.test': {'value!': {'int!': 0}}}], 'found': 1}}}}]],
        [[{}, {'fn._verify': {'call': {'fn.test': {'value!': {'int!': 0}}}, 'strictMatch!': True, 'count!': {'AtLeast': {'times': 1}}}}], [{}, {'Ok': {}}]],
        [[{}, {'fn._verify': {'call': {'fn.test': {'value!': {'int!': 0}}}, 'strictMatch!': True, 'count!': {'AtMost': {'times': 1}}}}], [{}, {'Ok': {}}]],
    ],
    'multipleStrictMatchVerify': [
        [[{}, {'fn._clearStubs': {}}], [{}, {'Ok': {}}]],
        [[{}, {'fn._clearCalls': {}}], [{}, {'Ok': {}}]],
        [[{}, {'fn._createStub': {'stub': {'fn.test': {}, '->': {'Ok': {}}}}}], [{}, {'Ok': {}}]],
        [[{}, {'fn._verify': {'call': {'fn.test': {'value!': {'int!': 0}}}, 'strictMatch!': True}}], [{}, {'ErrorVerificationFailure': {'reason': {'TooFewMatchingCalls': {'found': 0, 'allCalls': [], 'wanted': {'AtLeast': {'times': 1}}}}}}]],
        [[{}, {'fn.test': {'value!': {'int!': 0}}}], [{}, {'Ok': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 0, 'str!': 'a'}}}], [{}, {'Ok': {}}]],
        [[{}, {'fn._verifyNoMoreInteractions': {}}], [{}, {'ErrorVerificationFailure': {'additionalUnverifiedCalls': [{'fn.test': {'value!': {'int!': 0}}}, {'fn.test': {'value!': {'int!': 0, 'str!': 'a'}}}]}}]],
        [[{}, {'fn._verify': {'call': {'fn.test': {'value!': {'int!': 0}}}, 'strictMatch!': True}}], [{}, {'Ok': {}}]],
        [[{}, {'fn._verifyNoMoreInteractions': {}}], [{}, {'ErrorVerificationFailure': {'additionalUnverifiedCalls': [{'fn.test': {'value!': {'int!': 0, 'str!': 'a'}}}]}}]],
        [[{}, {'fn._verify': {'call': {'fn.test': {}}}}], [{}, {'Ok': {}}]],
        [[{}, {'fn._verifyNoMoreInteractions': {}}], [{}, {'Ok': {}}]],
        [[{}, {'fn._verify': {'call': {'fn.test': {'value!': {'int!': 1}}}, 'strictMatch!': True}}], [{}, {'ErrorVerificationFailure': {'reason': {'TooFewMatchingCalls': {'found': 0, 'allCalls': [{'fn.test': {'value!': {'int!': 0}}}, {'fn.test': {'value!': {'int!': 0, 'str!': 'a'}}}], 'wanted': {'AtLeast': {'times': 1}}}}}}]],
        [[{}, {'fn._verify': {'call': {'fn.test': {'value!': {'int!': 0, 'str!': 'b'}}}, 'strictMatch!': True}}], [{}, {'ErrorVerificationFailure': {'reason': {'TooFewMatchingCalls': {'found': 0, 'allCalls': [{'fn.test': {'value!': {'int!': 0}}}, {'fn.test': {'value!': {'int!': 0, 'str!': 'a'}}}], 'wanted': {'AtLeast': {'times': 1}}}}}}]],
        [[{}, {'fn._verify': {'call': {'fn.test': {'value!': {'int!': 0}}}, 'strictMatch!': True, 'count!': {'Exact': {'times': 0}}}}], [{}, {'ErrorVerificationFailure': {'reason': {'TooManyMatchingCalls': {'wanted': {'Exact': {'times': 0}}, 'allCalls': [{'fn.test': {'value!': {'int!': 0}}}, {'fn.test': {'value!': {'int!': 0, 'str!': 'a'}}}], 'found': 1}}}}]],
        [[{}, {'fn._verify': {'call': {'fn.test': {'value!': {'int!': 0}}}, 'strictMatch!': True, 'count!': {'Exact': {'times': 2}}}}], [{}, {'ErrorVerificationFailure': {'reason': {'TooFewMatchingCalls': {'wanted': {'Exact': {'times': 2}}, 'allCalls': [{'fn.test': {'value!': {'int!': 0}}}, {'fn.test': {'value!': {'int!': 0, 'str!': 'a'}}}], 'found': 1}}}}]],
        [[{}, {'fn._verify': {'call': {'fn.test': {'value!': {'int!': 0}}}, 'strictMatch!': True, 'count!': {'Exact': {'times': 1}}}}], [{}, {'Ok': {}}]],
        [[{}, {'fn._verify': {'call': {'fn.test': {'value!': {'int!': 0}}}, 'strictMatch!': True, 'count!': {'AtLeast': {'times': 2}}}}], [{}, {'ErrorVerificationFailure': {'reason': {'TooFewMatchingCalls': {'wanted': {'AtLeast': {'times': 2}}, 'allCalls': [{'fn.test': {'value!': {'int!': 0}}}, {'fn.test': {'value!': {'int!': 0, 'str!': 'a'}}}], 'found': 1}}}}]],
        [[{}, {'fn._verify': {'call': {'fn.test': {'value!': {'int!': 0}}}, 'strictMatch!': True, 'count!': {'AtLeast': {'times': 1}}}}], [{}, {'Ok': {}}]],
        [[{}, {'fn._verify': {'call': {'fn.test': {'value!': {'int!': 0}}}, 'strictMatch!': True, 'count!': {'AtMost': {'times': 1}}}}], [{}, {'Ok': {}}]],
    ],
    'multipleNestedPartialMatchVerify': [
        [[{}, {'fn._clearStubs': {}}], [{}, {'Ok': {}}]],
        [[{}, {'fn._clearCalls': {}}], [{}, {'Ok': {}}]],
        [[{}, {'fn._createStub': {'stub': {'fn.test': {}, '->': {'Ok': {}}}}}], [{}, {'Ok': {}}]],
        [[{}, {'fn._verify': {'call': {'fn.test': {'value!': {'int!': 0}}}}}], [{}, {'ErrorVerificationFailure': {'reason': {'TooFewMatchingCalls': {'found': 0, 'allCalls': [], 'wanted': {'AtLeast': {'times': 1}}}}}}]],
        [[{}, {'fn.test': {'value!': {'struct!': {'required': True}}}}], [{}, {'Ok': {}}]],
        [[{}, {'fn.test': {'value!': {'struct!': {'required': True, 'optional!': True}}}}], [{}, {'Ok': {}}]],
        [[{}, {'fn._verifyNoMoreInteractions': {}}], [{}, {'ErrorVerificationFailure': {'additionalUnverifiedCalls': [{'fn.test': {'value!': {'struct!': {'required': True}}}}, {'fn.test': {'value!': {'struct!': {'required': True, 'optional!': True}}}}]}}]],
        [[{}, {'fn._verify': {'call': {'fn.test': {'value!': {'struct!': {'optional!': True}}}}}}], [{}, {'Ok': {}}]],
        [[{}, {'fn._verifyNoMoreInteractions': {}}], [{}, {'ErrorVerificationFailure': {'additionalUnverifiedCalls': [{'fn.test': {'value!': {'struct!': {'required': True}}}}]}}]],
        [[{}, {'fn._verify': {'call': {'fn.test': {}}}}], [{}, {'Ok': {}}]],
        [[{}, {'fn._verifyNoMoreInteractions': {}}], [{}, {'Ok': {}}]],
        [[{}, {'fn._verify': {'call': {'fn.test': {'value!': {'struct!': {'optional!': True}}}}, 'count!': {'Exact': {'times': 1}}}}], [{}, {'Ok': {}}]],
    ],
    'multipleReallyNestedPartialMatchVerify': [
        [[{}, {'fn._clearStubs': {}}], [{}, {'Ok': {}}]],
        [[{}, {'fn._clearCalls': {}}], [{}, {'Ok': {}}]],
        [[{}, {'fn._createStub': {'stub': {'fn.test': {}, '->': {'Ok': {}}}}}], [{}, {'Ok': {}}]],
        [[{}, {'fn._verify': {'call': {'fn.test': {'value!': {'int!': 0}}}}}], [{}, {'ErrorVerificationFailure': {'reason': {'TooFewMatchingCalls': {'found': 0, 'allCalls': [], 'wanted': {'AtLeast': {'times': 1}}}}}}]],
        [[{}, {'fn.test': {'value!': {'arrStruct!': [{'required': False}, {'required': True}]}}}], [{}, {'Ok': {}}]],
        [[{}, {'fn.test': {'value!': {'arrStruct!': [{'required': False}, {'required': True, 'optional!': True}]}}}], [{}, {'Ok': {}}]],
        [[{}, {'fn._verify': {'call': {'fn.test': {'value!': {'arrStruct!': [{'optional!': True}]}}}}}], [{}, {'Ok': {}}]],
        [[{}, {'fn._verifyNoMoreInteractions': {}}], [{}, {'ErrorVerificationFailure': {'additionalUnverifiedCalls': [{'fn.test': {'value!': {'arrStruct!': [{'required': False}, {'required': True}]}}}]}}]],
        [[{}, {'fn._verify': {'call': {'fn.test': {}}}}], [{}, {'Ok': {}}]],
        [[{}, {'fn._verifyNoMoreInteractions': {}}], [{}, {'Ok': {}}]],
        [[{}, {'fn._verify': {'call': {'fn.test': {'value!': {'arrStruct!': [{'optional!': True}]}}}, 'count!': {'Exact': {'times': 1}}}}], [{}, {'Ok': {}}]],
    ],
    'clearCalls': [
        [[{}, {'fn._clearStubs': {}}], [{}, {'Ok': {}}]],
        [[{}, {'fn._clearCalls': {}}], [{}, {'Ok': {}}]],
        [[{}, {'fn._createStub': {'stub': {'fn.test': {}, '->': {'Ok': {}}}}}], [{}, {'Ok': {}}]],
        [[{}, {'fn._verify': {'call': {'fn.test': {}}}}], [{}, {'ErrorVerificationFailure': {'reason': {'TooFewMatchingCalls': {'found': 0, 'allCalls': [], 'wanted': {'AtLeast': {'times': 1}}}}}}]],
        [[{}, {'fn.test': {}}], [{}, {'Ok': {}}]],
        [[{}, {'fn._verify': {'call': {'fn.test': {}}}}], [{}, {'Ok': {}}]],
        [[{}, {'fn._clearCalls': {}}], [{}, {'Ok': {}}]],
        [[{}, {'fn._verify': {'call': {'fn.test': {}}}}], [{}, {'ErrorVerificationFailure': {'reason': {'TooFewMatchingCalls': {'found': 0, 'allCalls': [], 'wanted': {'AtLeast': {'times': 1}}}}}}]],
    ],
    'resultSuppliesMissingRequiredFields': [
        [[{}, {'fn._setRandomSeed': {'seed': 0}}], [{}, {'Ok': {}}]],
        [[{}, {'fn._clearStubs': {}}], [{}, {'Ok': {}}]],
        [[{}, {'fn._clearCalls': {}}], [{}, {'Ok': {}}]],
        [[{}, {'fn.test': {}}], [{}, {'_ErrorNoMatchingStub': {}}]],
        [[{}, {'fn._createStub': {'stub': {'fn.test': {}, '->': {'Ok': {'value!': {'bool!': True, 'struct!': {'optional!': True}}}}}}}], [{}, {'Ok': {}}]],
        [[{}, {'fn.test': {}}], [{}, {'Ok': {'value!': {'bool!': True, 'struct!': {'optional!': True, 'required': False}}}}]],
    ],
    'resultWithStartingValue': [
        [[{}, {'fn._clearStubs': {}}], [{}, {'Ok': {}}]],
        [[{}, {'fn._clearCalls': {}}], [{}, {'Ok': {}}]],
        [[{}, {'fn.test': {}}], [{}, {'_ErrorNoMatchingStub': {}}]],
        [[{}, {'fn._createStub': {'stub': {'fn.test': {}, '->': {'Ok': {'value!': {'bool!': False, 'int!': 0, 'num!': 0.1, 'str!': '', 'arrBool!': [False], 'objBool!': {'a': False}, 'struct!': {'required': False}, 'union!': {'Two': {'required': False}}, 'fn!': {'fn.example': {'required': False}}}}}}}}], [{}, {'Ok': {}}]],
        [[{}, {'fn.test': {}}], [{}, {'Ok': {'value!': {'bool!': False, 'int!': 0, 'num!': 0.1, 'str!': '', 'arrBool!': [False], 'objBool!': {'a': False}, 'struct!': {'required': False}, 'union!': {'Two': {'required': False}}, 'fn!': {'fn.example': {'required': False}}}}}]],
    ],
}
