from typing import Any

from qa.test.cases import get_values
from qa.test.cases import additional_union_cases, additional_fn_cases, additional_integer_cases, additional_number_cases, additional_p2Union_cases, additional_p2Str_cases, additional_struct_cases


def generate_mock_cases(given_field: str, the_type, correct_values, additional_incorrect_values = []):
    for field, _, incorrect_values, base_path in get_values(given_field, the_type, correct_values, additional_incorrect_values):
        for incorrect_value, errors in incorrect_values:
            cases = [{'path': ['fn.createStub_', 'stub', 'fn.test', 'value!'] + base_path + path, 'reason': reason} for reason, path in errors if 'RequiredObjectKeyMissing' not in reason]
            if not cases:
                continue

            yield [[{}, {'fn.createStub_': {'stub': {'fn.test': {'value!': {field: incorrect_value}}, '->': {'Ok_': {}}}}}], [{}, {'ErrorInvalidRequestBody_': {'cases': cases}}]]

        for incorrect_value, errors in incorrect_values:
            cases = [{'path': ['fn.createStub_', 'stub', '->', 'Ok_', 'value!'] + base_path + path, 'reason': reason} for reason, path in errors if 'RequiredObjectKeyMissing' not in reason]
            if not cases:
                continue
            yield [[{}, {'fn.createStub_': {'stub': {'fn.test': {}, '->': {'Ok_': {'value!': {field: incorrect_value}}}}}}], [{}, {'ErrorInvalidRequestBody_': {'cases': cases}}]]



invalid_cases = {
    'boolean': [v for v in generate_mock_cases('bool!', bool, [False, True])],
    'integer': [v for v in generate_mock_cases('int!', int, [0, -1, 1, 9223372036854775807, -9223372036854775808], additional_integer_cases)],
    'number': [v for v in generate_mock_cases('num!', float, [0, -1, 1, -1.7976931348623157e+308, -2.2250738585072014e-308, 2.2250738585072014e-308, 1.7976931348623157e+308, -0.1, 0.1], additional_number_cases)],
    'string': [v for v in generate_mock_cases('str!', str, ['', 'abc'])],
    'array': [v for v in generate_mock_cases('arr!', list, [[], [False, 0, 0.1, '']])],
    'object': [v for v in generate_mock_cases('obj!', dict, [{}, {'a': False, 'b': 0, 'c': 0.1, 'd': ''}])],
    'any': [v for v in generate_mock_cases('any!', Any, [False, 0, 0.1, '', [], {}])],
    'struct': [v for v in generate_mock_cases('struct!', dict, [{'required': False}, {'optional!': False, 'required': False}], additional_struct_cases)],
    'union': [v for v in generate_mock_cases('union!', dict, [{'One': {}}, {'Two':{'required': False}}, {'Two':{'optional!': False, 'required': False}}], additional_union_cases)],
    'fn': [v for v in generate_mock_cases('fn!', dict, [{'fn.example': {'required': False}}, {'fn.example': {'optional!': False, 'required': False}}], additional_fn_cases)],
    'stub': [
        [[{}, {'fn.createStub_': {'stub': False}}], [{}, {'ErrorInvalidRequestBody_': {'cases': [{'path': ['fn.createStub_', 'stub'], 'reason': {'TypeUnexpected': {'actual': {'Boolean': {}}, 'expected': {'Object': {}}}}}]}}]],
        [[{}, {'fn.createStub_': {'stub': 0}}], [{}, {'ErrorInvalidRequestBody_': {'cases': [{'path': ['fn.createStub_', 'stub'], 'reason': {'TypeUnexpected': {'actual': {'Number': {}}, 'expected': {'Object': {}}}}}]}}]],
        [[{}, {'fn.createStub_': {'stub': ''}}], [{}, {'ErrorInvalidRequestBody_': {'cases': [{'path': ['fn.createStub_', 'stub'], 'reason': {'TypeUnexpected': {'actual': {'String': {}}, 'expected': {'Object': {}}}}}]}}]],
        [[{}, {'fn.createStub_': {'stub': []}}], [{}, {'ErrorInvalidRequestBody_': {'cases': [{'path': ['fn.createStub_', 'stub'], 'reason': {'TypeUnexpected': {'actual': {'Array': {}}, 'expected': {'Object': {}}}}}]}}]],
        [[{}, {'fn.createStub_': {'stub': {}}}], [{}, {'ErrorInvalidRequestBody_': {'cases': [{'path': ['fn.createStub_', 'stub'], 'reason': {'ObjectKeyRegexMatchCountUnexpected': {'regex': '^fn\\..*$', 'actual': 0, 'expected': 1, 'keys': []}}}]}}]],
        [[{}, {'fn.createStub_': {'stub': {'fn.test': {}}}}], [{}, {'ErrorInvalidRequestBody_': {'cases': [{'path': ['fn.createStub_', 'stub'], 'reason': {'RequiredObjectKeyMissing': {'key': '->'}}}]}}]],
        [[{}, {'fn.createStub_': {'stub': {'fn.test': {}, '->': {}}}}], [{}, {'ErrorInvalidRequestBody_': {'cases': [{'path': ['fn.createStub_', 'stub', '->'], 'reason': {'ObjectSizeUnexpected': {'actual': 0, 'expected': 1}}}]}}]],
        [[{}, {'fn.createStub_': {'stub': {'fn.testAnother': {}, 'fn.test': {}, '->': {'Ok_': {}}}}}], [{}, {'ErrorInvalidRequestBody_': {'cases': [{'path': ['fn.createStub_', 'stub'], 'reason': {'ObjectKeyRegexMatchCountUnexpected': {'regex': '^fn\\..*$', 'actual': 2, 'expected': 1, 'keys': ['->', 'fn.test', 'fn.testAnother']}}}]}}]],
        [[{}, {'fn.createStub_': {'stub': {'wrong': True, 'fn.test': {}, '->': {'Ok_': {}}}}}], [{}, {'ErrorInvalidRequestBody_': {'cases': [{'path': ['fn.createStub_', 'stub', 'wrong'], 'reason': {'ObjectKeyDisallowed': {}}}]}}]],
    ],
}

cases = {
    'emptyPartialMatchStub': [
        [[{}, {'fn.clearStubs_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.clearCalls_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.test': {}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.createStub_': {'stub': {'fn.test': {}, '->': {'Ok_': {}}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.test': {}}], [{}, {'Ok_': {}}]],
    ],
    'partialMatchStub': [
        [[{}, {'fn.clearStubs_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.clearCalls_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1, 'str!': 'a'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.createStub_': {'stub': {'fn.test': {'value!': {'int!': 1}}, '->': {'Ok_': {'value!': {'bool!': True}}}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.test': {}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 0}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1}}}], [{}, {'Ok_': {'value!': {'bool!': True}}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1, 'str!': 'a'}}}], [{}, {'Ok_': {'value!': {'bool!': True}}}]],
    ],
    'multiplePartialMatchStub': [
        [[{}, {'fn.clearStubs_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.clearCalls_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1, 'str!': 'a'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 0, 'str!': 'a'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1, 'str!': 'b'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'bool!': False, 'int!': 1, 'str!': 'a'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.createStub_': {'stub': {'fn.test': {'value!': {'int!': 1}}, '->': {'Ok_': {'value!': {'bool!': True}}}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.createStub_': {'stub': {'fn.test': {'value!': {'str!': 'a'}}, '->': {'Ok_': {'value!': {'bool!': False}}}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.createStub_': {'stub': {'fn.example': {}, '->': {'Ok_': {}}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.test': {}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 0}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1}}}], [{}, {'Ok_': {'value!': {'bool!': True}}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1, 'str!': 'a'}}}], [{}, {'Ok_': {'value!': {'bool!': False}}}]],
        [[{}, {'fn.test': {'value!': {'int!': 0, 'str!': 'a'}}}], [{}, {'Ok_': {'value!': {'bool!': False}}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1, 'str!': 'b'}}}], [{}, {'Ok_': {'value!': {'bool!': True}}}]],
        [[{}, {'fn.test': {'value!': {'bool!': False, 'int!': 1, 'str!': 'a'}}}], [{}, {'Ok_': {'value!': {'bool!': False}}}]],
    ],
    'multiplePartialMatchStubCount': [
        [[{}, {'fn.clearStubs_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.clearCalls_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1, 'str!': 'a'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 0, 'str!': 'a'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1, 'str!': 'b'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'bool!': False, 'int!': 1, 'str!': 'a'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.createStub_': {'count!': 2, 'stub': {'fn.test': {'value!': {'int!': 1}}, '->': {'Ok_': {'value!': {'bool!': True}}}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.createStub_': {'count!': 1, 'stub': {'fn.test': {'value!': {'str!': 'a'}}, '->': {'Ok_': {'value!': {'bool!': False}}}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.createStub_': {'stub': {'fn.example': {}, '->': {'Ok_': {}}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.test': {}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 0}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1}}}], [{}, {'Ok_': {'value!': {'bool!': True}}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1, 'str!': 'a'}}}], [{}, {'Ok_': {'value!': {'bool!': False}}}]],
        [[{}, {'fn.test': {'value!': {'int!': 0, 'str!': 'a'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1, 'str!': 'b'}}}], [{}, {'Ok_': {'value!': {'bool!': True}}}]],
        [[{}, {'fn.test': {'value!': {'bool!': False, 'int!': 1, 'str!': 'a'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
    ],    
    'multipleNestedPartialMatchStub': [
        [[{}, {'fn.clearStubs_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.clearCalls_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1, 'str!': 'a'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 0, 'str!': 'a'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1, 'str!': 'b'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'bool!': False, 'int!': 1, 'str!': 'a'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.createStub_': {'stub': {'fn.test': {'value!': {'struct!': {'optional!': True}}}, '->': {'Ok_': {'value!': {'bool!': True}}}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.createStub_': {'stub': {'fn.test': {'value!': {'struct!': {'required': True}}}, '->': {'Ok_': {'value!': {'bool!': False}}}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.createStub_': {'stub': {'fn.example': {}, '->': {'Ok_': {}}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.test': {}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'struct!': {'required': False}}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'struct!': {'optional!': False, 'required': False}}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'struct!': {'optional!': True, 'required': True}}}}], [{}, {'Ok_': {'value!': {'bool!': False}}}]],
        [[{}, {'fn.test': {'value!': {'struct!': {'optional!': True, 'required': False}}}}], [{}, {'Ok_': {'value!': {'bool!': True}}}]],
        [[{}, {'fn.test': {'value!': {'struct!': {'required': True}}}}], [{}, {'Ok_': {'value!': {'bool!': False}}}]],
        [[{}, {'fn.test': {'value!': {'struct!': {'optional!': False, 'required': True}}}}], [{}, {'Ok_': {'value!': {'bool!': False}}}]],
        [[{}, {'fn.test': {'value!': {'struct!': {'optional!': True, 'required': False}, 'str!': 'b'}}}], [{}, {'Ok_': {'value!': {'bool!': True}}}]],
    ],
    'multipleNestedPartialMatchStubCount': [
        [[{}, {'fn.clearStubs_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.clearCalls_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1, 'str!': 'a'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 0, 'str!': 'a'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1, 'str!': 'b'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'bool!': False, 'int!': 1, 'str!': 'a'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.createStub_': {'count!': 1, 'stub': {'fn.test': {'value!': {'struct!': {'optional!': True}}}, '->': {'Ok_': {'value!': {'bool!': True}}}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.createStub_': {'count!': 2, 'stub': {'fn.test': {'value!': {'struct!': {'required': True}}}, '->': {'Ok_': {'value!': {'bool!': False}}}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.createStub_': {'stub': {'fn.example': {}, '->': {'Ok_': {}}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.test': {}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'struct!': {'required': False}}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'struct!': {'optional!': False, 'required': False}}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'struct!': {'optional!': True, 'required': True}}}}], [{}, {'Ok_': {'value!': {'bool!': False}}}]],
        [[{}, {'fn.test': {'value!': {'struct!': {'optional!': True, 'required': False}}}}], [{}, {'Ok_': {'value!': {'bool!': True}}}]],
        [[{}, {'fn.test': {'value!': {'struct!': {'required': True}}}}], [{}, {'Ok_': {'value!': {'bool!': False}}}]],
        [[{}, {'fn.test': {'value!': {'struct!': {'optional!': False, 'required': True}}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'struct!': {'optional!': True, 'required': False}, 'str!': 'b'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
    ],    
    'multipleReallyNestedPartialMatchStub': [
        [[{}, {'fn.clearStubs_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.clearCalls_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1, 'str!': 'a'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 0, 'str!': 'a'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1, 'str!': 'b'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'bool!': False, 'int!': 1, 'str!': 'a'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.createStub_': {'stub': {'fn.test': {'value!': {'arrStruct!': [{'optional!': True}]}}, '->': {'Ok_': {'value!': {'bool!': True}}}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.createStub_': {'stub': {'fn.test': {'value!': {'arrStruct!': [{'required': True}]}}, '->': {'Ok_': {'value!': {'bool!': False}}}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.createStub_': {'stub': {'fn.example': {}, '->': {'Ok_': {}}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.test': {}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'arrStruct!': [{'required': False}, {'optional!': False, 'required': False}]}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'arrStruct!': [{'required': False}, {'optional!': True, 'required': True}]}}}], [{}, {'Ok_': {'value!': {'bool!': False}}}]],
        [[{}, {'fn.test': {'value!': {'arrStruct!': [{'required': False}, {'optional!': True, 'required': False}]}}}], [{}, {'Ok_': {'value!': {'bool!': True}}}]],
        [[{}, {'fn.test': {'value!': {'arrStruct!': [{'required': False}, {'optional!': False, 'required': True}]}}}], [{}, {'Ok_': {'value!': {'bool!': False}}}]],
        [[{}, {'fn.test': {'value!': {'arrStruct!': [{'required': False}, {'optional!': True, 'required': False}], 'str!': 'b'}}}], [{}, {'Ok_': {'value!': {'bool!': True}}}]],
    ],
    'multipleReallyNestedPartialMatchStubCount': [
        [[{}, {'fn.clearStubs_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.clearCalls_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1, 'str!': 'a'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 0, 'str!': 'a'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1, 'str!': 'b'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'bool!': False, 'int!': 1, 'str!': 'a'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.createStub_': {'count!': 1, 'stub': {'fn.test': {'value!': {'arrStruct!': [{'optional!': True}]}}, '->': {'Ok_': {'value!': {'bool!': True}}}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.createStub_': {'count!': 1, 'stub': {'fn.test': {'value!': {'arrStruct!': [{'required': True}]}}, '->': {'Ok_': {'value!': {'bool!': False}}}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.createStub_': {'stub': {'fn.example': {}, '->': {'Ok_': {}}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.test': {}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'arrStruct!': [{'required': False}, {'optional!': False, 'required': False}]}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'arrStruct!': [{'required': False}, {'optional!': True, 'required': True}]}}}], [{}, {'Ok_': {'value!': {'bool!': False}}}]],
        [[{}, {'fn.test': {'value!': {'arrStruct!': [{'required': False}, {'optional!': True, 'required': False}]}}}], [{}, {'Ok_': {'value!': {'bool!': True}}}]],
        [[{}, {'fn.test': {'value!': {'arrStruct!': [{'required': False}, {'optional!': False, 'required': True}]}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'arrStruct!': [{'required': False}, {'optional!': True, 'required': False}], 'str!': 'b'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
    ],    
    'strictMatchStub': [
        [[{}, {'fn.clearStubs_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.clearCalls_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.createStub_': {'stub': {'fn.test': {'value!': {'int!': 1}}, '->': {'Ok_': {'value!': {'bool!': True}}}}, 'strictMatch!': True}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.test': {}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 0}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1}}}], [{}, {'Ok_': {'value!': {'bool!': True}}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1, 'str!': 'a'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
    ],
    'multipleStrictMatchStub': [
        [[{}, {'fn.clearStubs_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.clearCalls_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'str!': 'a'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.createStub_': {'stub': {'fn.test': {'value!': {'int!': 1}}, '->': {'Ok_': {'value!': {'bool!': True}}}}, 'strictMatch!': True}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.createStub_': {'stub': {'fn.test': {'value!': {'str!': 'a'}}, '->': {'Ok_': {'value!': {'bool!': False}}}}, 'strictMatch!': True}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.test': {}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 0}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1}}}], [{}, {'Ok_': {'value!': {'bool!': True}}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1, 'str!': 'a'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'str!': 'a'}}}], [{}, {'Ok_': {'value!': {'bool!': False}}}]],
        [[{}, {'fn.test': {'value!': {'int!': 0, 'str!': 'a'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1, 'str!': 'b'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'bool!': False, 'int!': 1, 'str!': 'a'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
    ],
    'multipleStrictMatchStubCount': [
        [[{}, {'fn.clearStubs_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.clearCalls_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'str!': 'a'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.createStub_': {'count!': 1, 'stub': {'fn.test': {'value!': {'int!': 1}}, '->': {'Ok_': {'value!': {'bool!': True}}}}, 'strictMatch!': True}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.createStub_': {'count!': 1, 'stub': {'fn.test': {'value!': {'str!': 'a'}}, '->': {'Ok_': {'value!': {'bool!': False}}}}, 'strictMatch!': True}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.test': {}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 0}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1}}}], [{}, {'Ok_': {'value!': {'bool!': True}}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1, 'str!': 'a'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'str!': 'a'}}}], [{}, {'Ok_': {'value!': {'bool!': False}}}]],
        [[{}, {'fn.test': {'value!': {'str!': 'a'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 0, 'str!': 'a'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1, 'str!': 'b'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'bool!': False, 'int!': 1, 'str!': 'a'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
    ],    
    'mixedPartialStrictMatchStub': [
        [[{}, {'fn.clearStubs_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.clearCalls_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1, 'str!': 'a'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1, 'str!': 'b'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'bool!': False, 'int!': 1, 'str!': 'a'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.createStub_': {'stub': {'fn.test': {'value!': {'int!': 1}}, '->': {'Ok_': {'value!': {'bool!': True}}}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.createStub_': {'stub': {'fn.test': {'value!': {'int!': 1, 'str!': 'a'}}, '->': {'Ok_': {'value!': {'bool!': False}}}}, 'strictMatch!': True}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.test': {}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 0}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1}}}], [{}, {'Ok_': {'value!': {'bool!': True}}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1, 'str!': 'a'}}}], [{}, {'Ok_': {'value!': {'bool!': False}}}]],
        [[{}, {'fn.test': {'value!': {'int!': 0, 'str!': 'a'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1, 'str!': 'b'}}}], [{}, {'Ok_': {'value!': {'bool!': True}}}]],
        [[{}, {'fn.test': {'value!': {'bool!': False, 'int!': 1, 'str!': 'a'}}}], [{}, {'Ok_': {'value!': {'bool!': True}}}]],
    ],
    'mixedStrictPartialMatchStub': [
        [[{}, {'fn.clearStubs_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.clearCalls_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1, 'str!': 'a'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1, 'str!': 'b'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'bool!': False, 'int!': 1, 'str!': 'a'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.createStub_': {'stub': {'fn.test': {'value!': {'int!': 1, 'str!': 'a'}}, '->': {'Ok_': {'value!': {'bool!': False}}}}, 'strictMatch!': True}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.createStub_': {'stub': {'fn.test': {'value!': {'int!': 1}}, '->': {'Ok_': {'value!': {'bool!': True}}}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.test': {}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 0}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1}}}], [{}, {'Ok_': {'value!': {'bool!': True}}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1, 'str!': 'a'}}}], [{}, {'Ok_': {'value!': {'bool!': True}}}]],
        [[{}, {'fn.test': {'value!': {'int!': 0, 'str!': 'a'}}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1, 'str!': 'b'}}}], [{}, {'Ok_': {'value!': {'bool!': True}}}]],
        [[{}, {'fn.test': {'value!': {'bool!': False, 'int!': 1, 'str!': 'a'}}}], [{}, {'Ok_': {'value!': {'bool!': True}}}]],
    ],
    'clearStubs': [
        [[{}, {'fn.clearStubs_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.clearCalls_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.test': {}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.createStub_': {'stub': {'fn.test': {}, '->': {'Ok_': {}}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.test': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.clearStubs_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.test': {}}], [{}, {'ErrorNoMatchingStub_': {}}]],
    ],
    'generation': [
        [[{}, {'fn.setRandomSeed_': {'seed': 0}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.clearStubs_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.clearCalls_': {}}], [{}, {'Ok_': {}}]],
        [[{'_gen': True}, {'fn.test': {}}], [{}, {'Ok_': {'value!': {'any!': True, 'arrFn!': [], 'arrNullAny!': [225740852], 'arrNullArr!': [[591276622]], 'arrNullBool!': [False], 'arrNullFn!': [], 'arrNum!': [0.5445731252173768], 'arrObj!': [{'HzuD3g': False, 'B8oYiw': 2053581748}], 'bool!': True, 'fn!': {'fn.example': {'optional!': False, 'required': True}}, 'nullAny!': 1130665698, 'nullArr!': [True, 69226605], 'nullBool!': True, 'nullFn!': None, 'nullInt!': 127811480, 'nullNum!': 0.6339545788401526, 'nullStr!': 'M1jZEw', 'nullStruct!': {'optional2!': 1385279860, 'required': False}, 'objAny!': {'HNHEPg': False}, 'objArr!': {}, 'objInt!': {'PuKmug': 321788014, 'Y299zQ': 1251252674}, 'objNullAny!': {}, 'objNullFn!': {'QYFAxA': None}, 'objNullInt!': {'CkST/g': 1442683466}, 'objNum!': {'HwbrFw': 0.937081863608715, 'SYjTAw': 0.5906006514982324}, 'objObj!': {'DkXDhQ': {'WbEG3A': 'YWsTjA'}, 'L8Cirg': {}}, 'objUnion!': {}, 'str!': 'R3Oc8A', 'union!': {'One': {}}}}}]],
        [[{'_gen': True}, {'fn.test': {}}], [{}, {'Ok_': {}}]],
        [[{'_gen': True}, {'fn.test': {}}], [{}, {'Ok_': {'value!': {'arrArr!': [], 'arrInt!': [377357501], 'arrNullFn!': [{'fn.example': {'optional!': False, 'required': True}}], 'arrNullNum!': [], 'arrNullObj!': [{'MPLDSg': 1440701173}, {'VGtqBg': 'ICseQQ', 'c9ezQg': False}], 'arrNullStr!': ['aMjUQQ', 'LfU1Zg'], 'arrNullStruct!': [None], 'arrNullUnion!': [None], 'arrNum!': [0.3242700110768294, 0.9367848150137741], 'arrStruct!': [{'optional!': True, 'optional2!': 153783732, 'required': False}], 'arrUnion!': [], 'nullArr!': [True, 1964550942], 'nullBool!': None, 'nullFn!': None, 'nullNum!': None, 'nullObj!': {'H0I5vA': 1201727870}, 'nullStr!': 'aQoB6g', 'nullStruct!': None, 'objAny!': {'GmoULw': 1952800740, 'WvHWLw': True}, 'objArr!': {'fNftFQ': ['ZPtG5g', 'RYqrGw'], 'PRNc7g': [False]}, 'objFn!': {'XYNwog': {'fn.example': {'optional!': False, 'required': False}}, 'EwJctQ': {'fn.example': {'required': False}}}, 'objInt!': {'TLgnTQ': 352543945, 'SL/tJQ': 374706552}, 'objNullFn!': {'WawLvg': {'fn.example': {'required': False}}, 'X7Zf6w': {'fn.example': {'optional!': True, 'required': True}}}, 'objNullNum!': {'asXKjg': 0.008515477184446285}, 'objNullStr!': {}, 'objNullStruct!': {'bPw3Cg': {'optional2!': 1511866087, 'required': True}, 'HmPbsg': None}, 'objStruct!': {'IrLrtQ': {'required': False}}, 'objUnion!': {}, 'struct!': {'optional!': True, 'optional2!': 484036347, 'required': False}, 'union!': {'Two': {'required': True}}}}}]],
        [[{'_gen': True}, {'fn.test': {}}], [{}, {'Ok_': {'value!': {'arr!': ['Tx/xiA', False], 'arrAny!': [True, True], 'arrNullAny!': [], 'arrNullArr!': [None], 'arrNullFn!': [], 'arrNullInt!': [None, None], 'arrNullNum!': [None, 0.49942290619920143], 'arrNullObj!': [{'NyRopQ': 1946086041, 'NAwK5A': 2089482048}, {'DChKeQ': True, 'C2yU2Q': False}], 'arrNullStr!': [None, 'HQGqMA'], 'arrNullStruct!': [], 'arrNullUnion!': [None, {'One': {}}], 'arrNum!': [], 'arrObj!': [], 'arrStr!': [], 'arrStruct!': [{'optional2!': 1294988167, 'required': True}, {'optional!': False, 'optional2!': 762857662, 'required': False}], 'arrUnion!': [{'Two': {'optional!': True, 'required': True}}, {'Two': {'required': True}}], 'fn!': {'fn.example': {'required': False}}, 'int!': 1501791946, 'nullArr!': None, 'nullBool!': None, 'nullFn!': {'fn.example': {'optional!': False, 'required': False}}, 'nullInt!': 227625195, 'nullNum!': 0.014725233900698477, 'nullObj!': {'A8PKlA': 1501133872}, 'nullUnion!': {'Two': {'optional!': False, 'required': True}}, 'num!': 0.44684865951857, 'obj!': {'aFVARA': 'C+CcTQ'}, 'objAny!': {}, 'objArr!': {}, 'objNullArr!': {'OP+5Eg': None}, 'objNullInt!': {'QvKNRA': 485988116, 'd7+Hpg': 1292529908}, 'objNullStruct!': {}, 'objNullUnion!': {}, 'objStr!': {'PNpjDA': 'JZ6hwA'}, 'objUnion!': {}, 'str!': 'Dq3/Qw', 'struct!': {'required': True}, 'union!': {'Two': {'optional!': False, 'required': False}}}}}]],
        [[{'_gen': True}, {'fn.test': {}}], [{}, {'Ok_': {'value!': {'arrBool!': [], 'arrNullArr!': [], 'arrNullInt!': [], 'arrNullObj!': [None], 'arrNullStruct!': [None], 'arrStr!': [], 'arrStruct!': [{'required': True}], 'bool!': True, 'fn!': {'fn.example': {'required': False}}, 'nullArr!': [13029836, 'e+viCg'], 'nullBool!': True, 'nullFn!': None, 'nullInt!': None, 'nullNum!': None, 'nullObj!': None, 'nullStr!': None, 'num!': 0.6676469085121746, 'objFn!': {}, 'objInt!': {'Ki799g': 744676297, 'AvD48g': 977972493}, 'objNullAny!': {'FBHCLQ': 1068930392, 'd5LZyg': None}, 'objNullBool!': {}, 'objNullFn!': {}, 'objNullInt!': {'SvmJtw': None, 'HkKSWw': 1477415918}, 'objNullObj!': {'bDG0Xw': {'RQ/vJw': False}, 'WiJSCg': {'OSgElQ': 'DzKRTw'}}, 'objNullStr!': {}, 'objNullUnion!': {'P2WAfw': {'Two': {'optional!': True, 'required': False}}, 'R2lvWw': {'Two': {'required': False}}}, 'objNum!': {'RehRUg': 0.028320919735506607}, 'objStr!': {'Nv2Zng': 'Q6jITQ'}, 'objStruct!': {'JRL8ag': {'optional2!': 201805976, 'required': False}, 'BWuWBw': {'optional2!': 1223282610, 'required': True}}, 'union!': {'One': {}}}}}]],
        [[{'_gen': True}, {'fn.test': {}}], [{}, {'Ok_': {}}]],
        [[{'_gen': True}, {'fn.test': {}}], [{}, {'Ok_': {'value!': {'any!': True, 'arrFn!': [{'fn.example': {'optional!': False, 'required': True}}, {'fn.example': {'optional!': False, 'required': False}}], 'arrNullAny!': [None, None], 'arrNullFn!': [{'fn.example': {'required': False}}], 'arrNullNum!': [None], 'arrNullStr!': [None], 'arrNullStruct!': [None], 'arrNullUnion!': [{'One': {}}], 'arrNum!': [], 'arrObj!': [], 'arrUnion!': [], 'fn!': {'fn.example': {'required': False}}, 'int!': 1860770624, 'nullArr!': None, 'nullFn!': {'fn.example': {'optional!': True, 'required': False}}, 'nullNum!': 0.53908802687148, 'obj!': {}, 'objAny!': {'GBxgqA': True, 'XmGZww': False}, 'objBool!': {'U2aotA': False, 'ZbvmEA': False}, 'objInt!': {}, 'objNullArr!': {'Yd2zvw': [True], 'dQMU2w': None}, 'objNullBool!': {'b3Y1MQ': None, 'SsVsTw': None}, 'objNullInt!': {'XrBaWA': None}, 'objNullObj!': {}, 'objNullStr!': {}, 'objNullStruct!': {'LI7w2g': {'optional2!': 1918894816, 'required': False}, 'Wp7WSQ': {'optional2!': 816466795, 'required': False}}, 'objNum!': {'OrjcVg': 0.46344568462271507, 'ZLWmqw': 0.00959141506328779}, 'objUnion!': {'evy7sA': {'Two': {'optional!': True, 'required': False}}}, 'union!': {'Two': {'required': True}}}}}]],
    ],
    'emptyPartialMatchVerify': [
        [[{}, {'fn.clearStubs_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.clearCalls_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.createStub_': {'stub': {'fn.test': {}, '->': {'Ok_': {}}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {}}}}], [{}, {'ErrorVerificationFailure': {'reason': {'TooFewMatchingCalls': {'allCalls': [], 'found': 0, 'wanted': {'AtLeast': {'times': 1}}}}}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {}}, 'count!': {'Exact': {'times': 1}}}}], [{}, {'ErrorVerificationFailure': {'reason': {'TooFewMatchingCalls': {'allCalls': [], 'found': 0, 'wanted': {'Exact': {'times': 1}}}}}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {}}, 'count!': {'AtLeast': {'times': 1}}}}], [{}, {'ErrorVerificationFailure': {'reason': {'TooFewMatchingCalls': {'allCalls': [], 'wanted': {'AtLeast': {'times': 1}}, 'found': 0}}}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {}}, 'count!': {'AtMost': {'times': 0}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.test': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.verifyNoMoreInteractions_': {}}], [{}, {'ErrorVerificationFailure': {'additionalUnverifiedCalls': [{'fn.test': {}}]}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.verifyNoMoreInteractions_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {}}, 'count!': {'Exact': {'times': 1}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {}}, 'count!': {'AtLeast': {'times': 1}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {}}, 'count!': {'AtLeast': {'times': 2}}}}], [{}, {'ErrorVerificationFailure': {'reason': {'TooFewMatchingCalls': {'allCalls': [{'fn.test': {}}], 'found': 1, 'wanted': {'AtLeast': {'times': 2}}}}}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {}}, 'count!': {'AtMost': {'times': 1}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {}}, 'count!': {'AtMost': {'times': 0}}}}], [{}, {'ErrorVerificationFailure': {'reason': {'TooManyMatchingCalls': {'wanted': {'AtMost': {'times': 0}}, 'allCalls': [{'fn.test': {}}], 'found': 1}}}}]],
    ],
    'partialMatchVerify': [
        [[{}, {'fn.clearStubs_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.clearCalls_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.createStub_': {'stub': {'fn.test': {'value!': {'int!': 0}}, '->': {'Ok_': {'value!': {'bool!': True}}}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {'value!': {'int!': 0}}}}}], [{}, {'ErrorVerificationFailure': {'reason': {'TooFewMatchingCalls': {'found': 0, 'allCalls': [], 'wanted': {'AtLeast': {'times': 1}}}}}}]],
        [[{}, {'fn.test': {'value!': {'int!': 0, 'str!': 'a'}}}], [{}, {'Ok_': {'value!': {'bool!': True}}}]],
        [[{}, {'fn.verifyNoMoreInteractions_': {}}], [{}, {'ErrorVerificationFailure': {'additionalUnverifiedCalls': [{'fn.test': {'value!': {'int!': 0, 'str!': 'a'}}}]}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {'value!': {'int!': 0}}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.verifyNoMoreInteractions_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {'value!': {'int!': 0}}}, 'count!': {'Exact': {'times': 1}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {'value!': {'int!': 0}}}, 'count!': {'AtLeast': {'times': 1}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {'value!': {'int!': 0}}}, 'count!': {'AtMost': {'times': 0}}}}], [{}, {'ErrorVerificationFailure': {'reason': {'TooManyMatchingCalls': {'wanted': {'AtMost': {'times': 0}}, 'allCalls': [{'fn.test': {'value!': {'int!': 0, 'str!': 'a'}}}], 'found': 1}}}}]],
    ],
    'multiplePartialMatchVerify': [
        [[{}, {'fn.clearStubs_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.clearCalls_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.createStub_': {'stub': {'fn.test': {}, '->': {'Ok_': {}}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {'value!': {'int!': 0}}}}}], [{}, {'ErrorVerificationFailure': {'reason': {'TooFewMatchingCalls': {'found': 0, 'allCalls': [], 'wanted': {'AtLeast': {'times': 1}}}}}}]],
        [[{}, {'fn.test': {'value!': {'int!': 0, 'bool!': True}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 0, 'str!': 'a'}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 1}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.verifyNoMoreInteractions_': {}}], [{}, {'ErrorVerificationFailure': {'additionalUnverifiedCalls': [{'fn.test': {'value!': {'int!': 0, 'bool!': True}}}, {'fn.test': {'value!': {'int!': 0, 'str!': 'a'}}}, {'fn.test': {'value!': {'int!': 1}}}]}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {'value!': {'int!': 0}}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.verifyNoMoreInteractions_': {}}], [{}, {'ErrorVerificationFailure': {'additionalUnverifiedCalls': [{'fn.test': {'value!': {'int!': 1}}}]}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.verifyNoMoreInteractions_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {'value!': {'int!': 0}}}, 'count!': {'Exact': {'times': 1}}}}], [{}, {'ErrorVerificationFailure': {'reason': {'TooManyMatchingCalls': {'wanted': {'Exact': {'times': 1}}, 'allCalls': [{'fn.test': {'value!': {'int!': 0, 'bool!': True}}}, {'fn.test': {'value!': {'int!': 0, 'str!': 'a'}}}, {'fn.test': {'value!': {'int!': 1}}}], 'found': 2}}}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {'value!': {'int!': 0}}}, 'count!': {'Exact': {'times': 2}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {'value!': {'int!': 0}}}, 'count!': {'Exact': {'times': 3}}}}], [{}, {'ErrorVerificationFailure': {'reason': {'TooFewMatchingCalls': {'wanted': {'Exact': {'times': 3}}, 'allCalls': [{'fn.test': {'value!': {'int!': 0, 'bool!': True}}}, {'fn.test': {'value!': {'int!': 0, 'str!': 'a'}}}, {'fn.test': {'value!': {'int!': 1}}}], 'found': 2}}}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {'value!': {'int!': 0}}}, 'count!': {'AtLeast': {'times': 1}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {'value!': {'int!': 0}}}, 'count!': {'AtMost': {'times': 1}}}}], [{}, {'ErrorVerificationFailure': {'reason': {'TooManyMatchingCalls': {'wanted': {'AtMost': {'times': 1}}, 'allCalls': [{'fn.test': {'value!': {'int!': 0, 'bool!': True}}}, {'fn.test': {'value!': {'int!': 0, 'str!': 'a'}}}, {'fn.test': {'value!': {'int!': 1}}}], 'found': 2}}}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {'value!': {'int!': 0}}}, 'count!': {'AtMost': {'times': 2}}}}], [{}, {'Ok_': {}}]],
    ],
    'strictMatchVerify': [
        [[{}, {'fn.clearStubs_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.clearCalls_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.createStub_': {'stub': {'fn.test': {}, '->': {'Ok_': {}}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {'value!': {'int!': 0}}}, 'strictMatch!': True}}], [{}, {'ErrorVerificationFailure': {'reason': {'TooFewMatchingCalls': {'found': 0, 'allCalls': [], 'wanted': {'AtLeast': {'times': 1}}}}}}]],
        [[{}, {'fn.test': {'value!': {'int!': 0}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.verifyNoMoreInteractions_': {}}], [{}, {'ErrorVerificationFailure': {'additionalUnverifiedCalls': [{'fn.test': {'value!': {'int!': 0}}}]}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {'value!': {'int!': 0}}}, 'strictMatch!': True}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.verifyNoMoreInteractions_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {'value!': {'int!': 1}}}, 'strictMatch!': True}}], [{}, {'ErrorVerificationFailure': {'reason': {'TooFewMatchingCalls': {'found': 0, 'allCalls': [{'fn.test': {'value!': {'int!': 0}}}], 'wanted': {'AtLeast': {'times': 1}}}}}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {'value!': {'int!': 0, 'str!': 'a'}}}, 'strictMatch!': True}}], [{}, {'ErrorVerificationFailure': {'reason': {'TooFewMatchingCalls': {'found': 0, 'allCalls': [{'fn.test': {'value!': {'int!': 0}}}], 'wanted': {'AtLeast': {'times': 1}}}}}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {'value!': {'int!': 0}}}, 'strictMatch!': True, 'count!': {'Exact': {'times': 0}}}}], [{}, {'ErrorVerificationFailure': {'reason': {'TooManyMatchingCalls': {'wanted': {'Exact': {'times': 0}}, 'allCalls': [{'fn.test': {'value!': {'int!': 0}}}], 'found': 1}}}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {'value!': {'int!': 0}}}, 'strictMatch!': True, 'count!': {'Exact': {'times': 2}}}}], [{}, {'ErrorVerificationFailure': {'reason': {'TooFewMatchingCalls': {'wanted': {'Exact': {'times': 2}}, 'allCalls': [{'fn.test': {'value!': {'int!': 0}}}], 'found': 1}}}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {'value!': {'int!': 0}}}, 'strictMatch!': True, 'count!': {'Exact': {'times': 1}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {'value!': {'int!': 0}}}, 'strictMatch!': True, 'count!': {'AtLeast': {'times': 2}}}}], [{}, {'ErrorVerificationFailure': {'reason': {'TooFewMatchingCalls': {'wanted': {'AtLeast': {'times': 2}}, 'allCalls': [{'fn.test': {'value!': {'int!': 0}}}], 'found': 1}}}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {'value!': {'int!': 0}}}, 'strictMatch!': True, 'count!': {'AtLeast': {'times': 1}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {'value!': {'int!': 0}}}, 'strictMatch!': True, 'count!': {'AtMost': {'times': 1}}}}], [{}, {'Ok_': {}}]],
    ],
    'multipleStrictMatchVerify': [
        [[{}, {'fn.clearStubs_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.clearCalls_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.createStub_': {'stub': {'fn.test': {}, '->': {'Ok_': {}}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {'value!': {'int!': 0}}}, 'strictMatch!': True}}], [{}, {'ErrorVerificationFailure': {'reason': {'TooFewMatchingCalls': {'found': 0, 'allCalls': [], 'wanted': {'AtLeast': {'times': 1}}}}}}]],
        [[{}, {'fn.test': {'value!': {'int!': 0}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.test': {'value!': {'int!': 0, 'str!': 'a'}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.verifyNoMoreInteractions_': {}}], [{}, {'ErrorVerificationFailure': {'additionalUnverifiedCalls': [{'fn.test': {'value!': {'int!': 0}}}, {'fn.test': {'value!': {'int!': 0, 'str!': 'a'}}}]}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {'value!': {'int!': 0}}}, 'strictMatch!': True}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.verifyNoMoreInteractions_': {}}], [{}, {'ErrorVerificationFailure': {'additionalUnverifiedCalls': [{'fn.test': {'value!': {'int!': 0, 'str!': 'a'}}}]}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.verifyNoMoreInteractions_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {'value!': {'int!': 1}}}, 'strictMatch!': True}}], [{}, {'ErrorVerificationFailure': {'reason': {'TooFewMatchingCalls': {'found': 0, 'allCalls': [{'fn.test': {'value!': {'int!': 0}}}, {'fn.test': {'value!': {'int!': 0, 'str!': 'a'}}}], 'wanted': {'AtLeast': {'times': 1}}}}}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {'value!': {'int!': 0, 'str!': 'b'}}}, 'strictMatch!': True}}], [{}, {'ErrorVerificationFailure': {'reason': {'TooFewMatchingCalls': {'found': 0, 'allCalls': [{'fn.test': {'value!': {'int!': 0}}}, {'fn.test': {'value!': {'int!': 0, 'str!': 'a'}}}], 'wanted': {'AtLeast': {'times': 1}}}}}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {'value!': {'int!': 0}}}, 'strictMatch!': True, 'count!': {'Exact': {'times': 0}}}}], [{}, {'ErrorVerificationFailure': {'reason': {'TooManyMatchingCalls': {'wanted': {'Exact': {'times': 0}}, 'allCalls': [{'fn.test': {'value!': {'int!': 0}}}, {'fn.test': {'value!': {'int!': 0, 'str!': 'a'}}}], 'found': 1}}}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {'value!': {'int!': 0}}}, 'strictMatch!': True, 'count!': {'Exact': {'times': 2}}}}], [{}, {'ErrorVerificationFailure': {'reason': {'TooFewMatchingCalls': {'wanted': {'Exact': {'times': 2}}, 'allCalls': [{'fn.test': {'value!': {'int!': 0}}}, {'fn.test': {'value!': {'int!': 0, 'str!': 'a'}}}], 'found': 1}}}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {'value!': {'int!': 0}}}, 'strictMatch!': True, 'count!': {'Exact': {'times': 1}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {'value!': {'int!': 0}}}, 'strictMatch!': True, 'count!': {'AtLeast': {'times': 2}}}}], [{}, {'ErrorVerificationFailure': {'reason': {'TooFewMatchingCalls': {'wanted': {'AtLeast': {'times': 2}}, 'allCalls': [{'fn.test': {'value!': {'int!': 0}}}, {'fn.test': {'value!': {'int!': 0, 'str!': 'a'}}}], 'found': 1}}}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {'value!': {'int!': 0}}}, 'strictMatch!': True, 'count!': {'AtLeast': {'times': 1}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {'value!': {'int!': 0}}}, 'strictMatch!': True, 'count!': {'AtMost': {'times': 1}}}}], [{}, {'Ok_': {}}]],
    ],
    'multipleNestedPartialMatchVerify': [
        [[{}, {'fn.clearStubs_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.clearCalls_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.createStub_': {'stub': {'fn.test': {}, '->': {'Ok_': {}}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {'value!': {'int!': 0}}}}}], [{}, {'ErrorVerificationFailure': {'reason': {'TooFewMatchingCalls': {'found': 0, 'allCalls': [], 'wanted': {'AtLeast': {'times': 1}}}}}}]],
        [[{}, {'fn.test': {'value!': {'struct!': {'required': True}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.test': {'value!': {'struct!': {'required': True, 'optional!': True}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.verifyNoMoreInteractions_': {}}], [{}, {'ErrorVerificationFailure': {'additionalUnverifiedCalls': [{'fn.test': {'value!': {'struct!': {'required': True}}}}, {'fn.test': {'value!': {'struct!': {'required': True, 'optional!': True}}}}]}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {'value!': {'struct!': {'optional!': True}}}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.verifyNoMoreInteractions_': {}}], [{}, {'ErrorVerificationFailure': {'additionalUnverifiedCalls': [{'fn.test': {'value!': {'struct!': {'required': True}}}}]}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.verifyNoMoreInteractions_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {'value!': {'struct!': {'optional!': True}}}}, 'count!': {'Exact': {'times': 1}}}}], [{}, {'Ok_': {}}]],
    ],
    'multipleReallyNestedPartialMatchVerify': [
        [[{}, {'fn.clearStubs_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.clearCalls_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.createStub_': {'stub': {'fn.test': {}, '->': {'Ok_': {}}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {'value!': {'int!': 0}}}}}], [{}, {'ErrorVerificationFailure': {'reason': {'TooFewMatchingCalls': {'found': 0, 'allCalls': [], 'wanted': {'AtLeast': {'times': 1}}}}}}]],
        [[{}, {'fn.test': {'value!': {'arrStruct!': [{'required': False}, {'required': True}]}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.test': {'value!': {'arrStruct!': [{'required': False}, {'required': True, 'optional!': True}]}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {'value!': {'arrStruct!': [{'optional!': True}]}}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.verifyNoMoreInteractions_': {}}], [{}, {'ErrorVerificationFailure': {'additionalUnverifiedCalls': [{'fn.test': {'value!': {'arrStruct!': [{'required': False}, {'required': True}]}}}]}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.verifyNoMoreInteractions_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {'value!': {'arrStruct!': [{'optional!': True}]}}}, 'count!': {'Exact': {'times': 1}}}}], [{}, {'Ok_': {}}]],
    ],
    'clearCalls': [
        [[{}, {'fn.clearStubs_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.clearCalls_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.createStub_': {'stub': {'fn.test': {}, '->': {'Ok_': {}}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {}}}}], [{}, {'ErrorVerificationFailure': {'reason': {'TooFewMatchingCalls': {'found': 0, 'allCalls': [], 'wanted': {'AtLeast': {'times': 1}}}}}}]],
        [[{}, {'fn.test': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.clearCalls_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.verify_': {'call': {'fn.test': {}}}}], [{}, {'ErrorVerificationFailure': {'reason': {'TooFewMatchingCalls': {'found': 0, 'allCalls': [], 'wanted': {'AtLeast': {'times': 1}}}}}}]],
    ],
    'resultSuppliesMissingRequiredFields': [
        [[{}, {'fn.setRandomSeed_': {'seed': 0}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.clearStubs_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.clearCalls_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.test': {}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.createStub_': {'stub': {'fn.test': {}, '->': {'Ok_': {'value!': {'bool!': True, 'struct!': {'optional!': True}}}}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.test': {}}], [{}, {'Ok_': {'value!': {'bool!': True, 'struct!': {'optional!': True, 'required': False}}}}]],
    ],
    'resultWithStartingValue': [
        [[{}, {'fn.clearStubs_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.clearCalls_': {}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.test': {}}], [{}, {'ErrorNoMatchingStub_': {}}]],
        [[{}, {'fn.createStub_': {'stub': {'fn.test': {}, '->': {'Ok_': {'value!': {'bool!': False, 'int!': 0, 'num!': 0.1, 'str!': '', 'arrBool!': [False], 'objBool!': {'a': False}, 'struct!': {'required': False}, 'union!': {'Two': {'required': False}}, 'fn!': {'fn.example': {'required': False}}}}}}}}], [{}, {'Ok_': {}}]],
        [[{}, {'fn.test': {}}], [{}, {'Ok_': {'value!': {'bool!': False, 'int!': 0, 'num!': 0.1, 'str!': '', 'arrBool!': [False], 'objBool!': {'a': False}, 'struct!': {'required': False}, 'union!': {'Two': {'required': False}}, 'fn!': {'fn.example': {'required': False}}}}}]],
    ],
}
