name: telepact
description: A Dart library for wrapping the telepact npm package.
version: 1.0.0-alpha.35
repository: https://github.com/Telepact/telepact
environment:
  sdk: ^3.6.0

dependencies:
  node_interop: ^2.1.0

dev_dependencies:
  test: ^1.25.15
  web: ^1.1.1
