name: telepact
description: A Dart library for wrapping the telepact npm package.
version: 1.0.0-alpha.1.4
environment:
  sdk: ^3.6.0

dependencies:
  node_interop: ^2.1.0

dev_dependencies:
  test: ^1.25.15

license: Apache-2.0

include:
- LICENSE
- NOTICE
