name: msgpact
description: A Dart library for wrapping an npm package.
version: 0.0.1
environment:
  sdk: "^3.6.0"

dependencies:
  node_interop: ^2.1.0

dev_dependencies:
  test: ^1.25.15

license: Apache-2.0

include:
  - LICENSE
  - NOTICE
