#|
#|  Copyright The Telepact Authors
#|  SPDX-License-Identifier: Apache-2.0
#|

ARG TELEPACT_VERSION=latest

FROM telepact-console:${TELEPACT_VERSION}

COPY override.js /usr/share/nginx/html/override.js

