version: '3.8'

services:
  app:
    build: 
      context: ../..
      dockerfile: tool/docker-mock-msgpact/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ../../qa/test/schema/calculator:/app/schema
    environment:
      PYTHONUNBUFFERED: 1
      MSGPACT_DIRECTORY: /app/schema

  app2:
    build: 
      context: ../..
      dockerfile: tool/docker-mock-msgpact/Dockerfile
    ports:
      - "8081:8080"
    volumes:
      - ../../qa/test/schema/calculator:/app/schema
    environment:
      PYTHONUNBUFFERED: 1
      MSGPACT_URL: http://app:8080/api
      

