version: '3.8'

services:
  app:
    build: .
    ports:
      - "8081:8080"
    volumes:
      - ./schema:/app/schema
    environment:
      PYTHONUNBUFFERED: 1
      MSGPACT_DIRECTORY: /app/schema

  app2:
    build: .
    ports:
      - "8082:8080"
    environment:
      PYTHONUNBUFFERED: 1
      MSGPACT_HTTP_URL: http://app:8080/api
      

