name: CI

on:
  workflow_dispatch:

jobs:
  build-msgpact-ts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "16"

      - name: Build ts
        run: make ts

      - name: Upload ts build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-msgpact-ts
          path: lib/ts/dist
          retention-days: 1

  build-msgpact-java:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "corretto"

      - name: Build java
        run: make java

      - name: Upload java build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-msgpact-java
          path: lib/java/target
          retention-days: 1

  build-msgpact-py:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install pipx
        run: |
          python3 -m pip install --user pipx
          python3 -m pipx ensurepath

      - name: Install Poetry
        run: pipx install poetry

      - name: Install dependencies
        run: make py

      - name: Upload py build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-msgpact-py
          path: lib/py/dist
          retention-days: 1

  build-msgpact-cli:
    runs-on: ubuntu-latest
    needs: [build-msgpact-py]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install pipx
        run: |
          python3 -m pip install --user pipx
          python3 -m pipx ensurepath

      - name: Install Poetry
        run: pipx install poetry

      - name: Download py build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-msgpact-py
          path: lib/py/dist

      - name: Build cli
        run: make cli

      - name: Upload msgpact-cli build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-msgpact-cli
          path: tool/cli/dist
          retention-days: 1

  build-msgpact-dart:
    runs-on: ubuntu-latest
    needs: [build-msgpact-ts]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: 3.6

      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Download ts build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-msgpact-ts
          path: lib/ts/dist

      - name: Build dart
        run: make dart

      - name: Run tests
        run: make test-dart

  build-msgpact-prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: make prettier

      - name: Upload prettier build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-msgpact-prettier
          path: tool/prettier-plugin-msgpact/dist
          retention-days: 1

  build-msgpact-console:
    runs-on: ubuntu-latest
    needs: [build-msgpact-ts, build-msgpact-cli, build-msgpact-prettier]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download ts build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-msgpact-ts
          path: lib/ts/dist

      - name: Download msgpact-cli build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-msgpact-cli
          path: tool/cli/dist

      - name: Download prettier build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-msgpact-prettier
          path: tool/prettier-plugin-msgpact/dist
      
      - name: Install CLI
        run: make install-cli

      - name: Build console
        run: make console
      
      - name: Install Playwright Browsers
        run: npx playwright install --force
      
      - name: Run tests
        run: make test-console


  run-tests:
    runs-on: ubuntu-latest
    needs: [build-msgpact-ts, build-msgpact-java, build-msgpact-py, build-msgpact-cli]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install pipx
        run: |
          python3 -m pip install --user pipx
          python3 -m pipx ensurepath

      - name: Install Poetry
        run: pipx install poetry

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "corretto"

      - name: Install nats-server
        run: |
          sudo apt-get update
          sudo apt-get install -y nats-server

      - name: Download ts build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-msgpact-ts
          path: lib/ts/dist

      - name: Download java build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-msgpact-java
          path: lib/java/target

      - name: Download py build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-msgpact-py
          path: lib/py/dist

      - name: Download msgpact-cli build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-msgpact-cli
          path: tool/cli/dist

      - name: Install CLI
        run: make install-cli

      - name: Run tests
        run: |
          make test
