#|
#|  Copyright The Telepact Authors
#|  SPDX-License-Identifier: Apache-2.0
#|

name: Merge Queue

on:
  merge_group:
    types:
      - checks_requested

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yml
