#|
#|  Copyright The Telepact Authors
#|  SPDX-License-Identifier: Apache-2.0
#|

name: PR Report

on:
  pull_request:
    types:
      - opened
      - reopened
    branches:
      - main

jobs:

  save-pr-details:
    name: Save PR Details
    runs-on: ubuntu-latest
    steps:
      - name: Define PR details
        run: |
          mkdir -p pr
          echo "{
            \"pr_number\": \"${{ github.event.pull_request.number }}\",
            \"pr_author\": \"${{ github.event.pull_request.user.login }}\"
          }" > pr/details.json

      - name: Upload PR details
        uses: actions/upload-artifact@v4
        with:
          name: pr-details
          path: pr
