package io.github.brenbar.japi.server;

enum InvalidFieldTypeError {
    NULL_INVALID_FOR_NON_NULL_TYPE,

    NUMBER_INVALID_FOR_BOOLEAN_TYPE,
    STRING_INVALID_FOR_BOOLEAN_TYPE,
    ARRAY_INVALID_FOR_BOOLEAN_TYPE,
    OBJECT_INVALID_FOR_BOOLEAN_TYPE,
    VALUE_INVALID_FOR_BOOLEAN_TYPE,

    BOOLEAN_INVALID_FOR_INTEGER_TYPE,
    NUMBER_INVALID_FOR_INTEGER_TYPE,
    STRING_INVALID_FOR_INTEGER_TYPE,
    ARRAY_INVALID_FOR_INTEGER_TYPE,
    OBJECT_INVALID_FOR_INTEGER_TYPE,
    VALUE_INVALID_FOR_INTEGER_TYPE,

    BOOLEAN_INVALID_FOR_NUMBER_TYPE,
    STRING_INVALID_FOR_NUMBER_TYPE,
    ARRAY_INVALID_FOR_NUMBER_TYPE,
    OBJECT_INVALID_FOR_NUMBER_TYPE,
    VALUE_INVALID_FOR_NUMBER_TYPE,

    BOOLEAN_INVALID_FOR_STRING_TYPE,
    NUMBER_INVALID_FOR_STRING_TYPE,
    ARRAY_INVALID_FOR_STRING_TYPE,
    OBJECT_INVALID_FOR_STRING_TYPE,
    VALUE_INVALID_FOR_STRING_TYPE,

    BOOLEAN_INVALID_FOR_ARRAY_TYPE,
    NUMBER_INVALID_FOR_ARRAY_TYPE,
    STRING_INVALID_FOR_ARRAY_TYPE,
    OBJECT_INVALID_FOR_ARRAY_TYPE,
    VALUE_INVALID_FOR_ARRAY_TYPE,

    BOOLEAN_INVALID_FOR_OBJECT_TYPE,
    NUMBER_INVALID_FOR_OBJECT_TYPE,
    STRING_INVALID_FOR_OBJECT_TYPE,
    ARRAY_INVALID_FOR_OBJECT_TYPE,
    VALUE_INVALID_FOR_OBJECT_TYPE,

    BOOLEAN_INVALID_FOR_STRUCT_TYPE,
    NUMBER_INVALID_FOR_STRUCT_TYPE,
    STRING_INVALID_FOR_STRUCT_TYPE,
    ARRAY_INVALID_FOR_STRUCT_TYPE,
    VALUE_INVALID_FOR_STRUCT_TYPE,

    BOOLEAN_INVALID_FOR_ENUM_TYPE,
    NUMBER_INVALID_FOR_ENUM_TYPE,
    STRING_INVALID_FOR_ENUM_TYPE,
    ARRAY_INVALID_FOR_ENUM_TYPE,
    VALUE_INVALID_FOR_ENUM_TYPE,

    BOOLEAN_INVALID_FOR_ENUM_STRUCT_TYPE,
    NUMBER_INVALID_FOR_ENUM_STRUCT_TYPE,
    STRING_INVALID_FOR_ENUM_STRUCT_TYPE,
    ARRAY_INVALID_FOR_ENUM_STRUCT_TYPE,
    VALUE_INVALID_FOR_ENUM_STRUCT_TYPE,

    INVALID_ENUM_VALUE,
    INVALID_TYPE
}
